import { NextRequest, NextResponse } from "next/server";
import { getPortalSessionAccess } from "@/lib/auth/portal-session";
// 8c-2: KYC gate — mirror top-level marketplace POST route. Without this,
// a portal client whose KYC is `rejected` / `suspended` could still create
// shipments / sign trade documents / post community content — binding
// commitments that affect counterparty's downstream flows.
import { requireKycApproved } from "@/lib/portal/kyc-gate";
import { createDocument } from "@/lib/data/marketplace-trade-documents-store";
import { autoGenerateDocument, AUTO_GENERATABLE_TYPES } from "@/lib/marketplace/document-generators";
import type {
  AutoGenerateContext,
  MarketplaceTradeDocumentType,
  TradeDocumentParty,
  TradeDocumentLineItem,
} from "@/lib/marketplace/document-generators";
import { getSupabase } from "@/lib/supabase/client";
import { getStore } from "@/lib/data/store";
import { audit } from "@/lib/api/helpers";
// 8c-9: per-portal-access rate limit — auto-generate is the most
// expensive write path in the platform (renders a PDF, computes a
// SHA-256 fingerprint, inserts into document_register + marketplace_
// trade_documents). Without a rate limit, a malicious partner can
// saturate the render pipeline + DB insert path with thousands of
// calls per minute. 10/min is well above any legit operator pattern.
import { checkRateLimit } from "@/lib/security/rate-limiter";
import { withApm } from "@/lib/monitoring/apm";
import type { Partner } from "@/lib/supabase/types";
import type {
  MarketplacePost,
  MarketplaceNegotiation,
  MarketplaceOfferTerms,
} from "@/lib/supabase/marketplace-types";
import type { Shipment } from "@/lib/supabase/marketplace-logistics-types";

export const runtime = "nodejs";

// POST /api/marketplace/documents/auto-generate — auto-generate a trade
// document (commercial invoice / packing list / certificate of origin /
// bill of lading / proforma) from a settled negotiation + post + shipment.
//
// Body:
//   {
//     document_type: "commercial_invoice" | "packing_list" | "certificate_of_origin" | "bill_of_lading" | "proforma_invoice",
//     post_id?: string,                  // must belong to caller's tenant
//     negotiation_id?: string,           // caller must be a party
//     shipment_id?: string,              // caller must be the booking partner (for BoL)
//     // Optional overrides — when not supplied, the route reads them from
//     // the post / negotiation / shipment context:
//     incoterm?: string,
//     paymentTerms?: string,
//     currency?: string,
//     originCountry?: string,
//     goodsDescription?: string,
//   }
//
// At least one of post_id / negotiation_id / shipment_id must be supplied.
// The route assembles the AutoGenerateContext (seller + buyer + items +
// currency + incoterm + payment terms + container / vessel / ports /
// weight) from the marketplace context and calls autoGenerateDocument().

async function _post(req: NextRequest) {
  const access = await getPortalSessionAccess();
  if (!access) {
    return NextResponse.json({ error: "Not authenticated." }, { status: 401 });
  }
  // 8c-2: KYC gate — defence-in-depth, mirror top-level marketplace POST.
  const _kycBlock = await requireKycApproved(access);
  if (_kycBlock) return _kycBlock;
  // 8c-9: per-portal-access rate limit (10/min). See import comment.
  const rl = await checkRateLimit(`mkt-auto-doc:${access.id}`, 10, 60_000);
  if (!rl.allowed) {
    return NextResponse.json({ error: "Too many document renders. Please slow down." }, { status: 429 });
  }

  let body;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  // Validate the document_type.
  const docType = body?.document_type as string;
  if (!docType || !(AUTO_GENERATABLE_TYPES as string[]).includes(docType)) {
    return NextResponse.json({
      error: `Invalid document_type. Auto-generatable types: ${(AUTO_GENERATABLE_TYPES as string[]).join(", ")}.`,
    }, { status: 400 });
  }
  const documentType = docType as MarketplaceTradeDocumentType;

  // At least one marketplace entity must be supplied.
  const postId = typeof body.post_id === "string" ? body.post_id : null;
  const negotiationId = typeof body.negotiation_id === "string" ? body.negotiation_id : null;
  const shipmentId = typeof body.shipment_id === "string" ? body.shipment_id : null;
  if (!postId && !negotiationId && !shipmentId) {
    return NextResponse.json(
      { error: "At least one of post_id / negotiation_id / shipment_id is required." },
      { status: 400 },
    );
  }

  const sb = getSupabase();
  const store = await getStore();

  try {
    // ── Resolve the marketplace context ──────────────────────────────────
    // Each FK is resolved independently — the context is the union of
    // whatever the caller supplies. So a caller passing only a
    // negotiation_id gets seller / buyer from the negotiation pair; a
    // caller passing post_id + shipment_id gets the product + the
    // container / vessel info.

    let post: MarketplacePost | null = null;
    let negotiation: MarketplaceNegotiation | null = null;
    let shipment: Shipment | null = null;

    if (postId) {
      const { data, error } = await sb
        .from("marketplace_posts")
        .select("*")
        .eq("id", postId)
        .eq("tenant_id", access.tenant_id)
        .maybeSingle();
      if (error) throw error;
      if (!data) return NextResponse.json({ error: "Post not found." }, { status: 404 });
      post = data as MarketplacePost;
    }

    if (negotiationId) {
      const { data, error } = await sb
        .from("marketplace_negotiations")
        .select("*")
        .eq("id", negotiationId)
        .maybeSingle();
      if (error) throw error;
      if (!data) return NextResponse.json({ error: "Negotiation not found." }, { status: 404 });
      const n = data as MarketplaceNegotiation;
      // Caller must be a party to the negotiation.
      if (n.tenant_id_a !== access.tenant_id && n.tenant_id_b !== access.tenant_id) {
        return NextResponse.json({ error: "Negotiation not found." }, { status: 404 });
      }
      if (n.partner_id_a !== access.partner_id && n.partner_id_b !== access.partner_id) {
        return NextResponse.json({ error: "Negotiation not found." }, { status: 404 });
      }
      // 8c-8: cross-FK consistency — when the caller supplies BOTH a
      // post_id and a negotiation_id, the negotiation's own post_id MUST
      // equal the supplied post_id. Without this check, a partner could
      // pair a real negotiation with an UNRELATED post_id (one they
      // own or have read access to but that the negotiation was never
      // opened on) and the auto-generate path below would build a
      // document using the negotiation's agreed_terms (price, currency,
      // incoterm, payment_terms) combined with the unrelated post's
      // product_name / origin_country / packaging — a commercial
      // forgery vector that would have looked legitimate to the
      // counterparty receiving the generated PDF. The check fires
      // after the party-membership check above so cross-tenant probes
      // still 404 (not 400) — this 400 only fires for callers that
      // legitimately resolved both rows but supplied a mismatched pair.
      if (postId && n.post_id && n.post_id !== postId) {
        return NextResponse.json(
          { error: "negotiation_id does not belong to the supplied post_id." },
          { status: 400 },
        );
      }
      negotiation = n;
      // If the caller didn't pass a post_id, follow the negotiation's FK.
      if (!post && n.post_id) {
        const { data: pRow, error: pErr } = await sb
          .from("marketplace_posts")
          .select("*")
          .eq("id", n.post_id)
          .eq("tenant_id", access.tenant_id)
          .maybeSingle();
        if (!pErr && pRow) post = pRow as MarketplacePost;
      }
    }

    if (shipmentId) {
      const { data, error } = await sb
        .from("marketplace_shipments")
        .select("*")
        .eq("id", shipmentId)
        .eq("tenant_id", access.tenant_id)
        .maybeSingle();
      if (error) throw error;
      if (!data) return NextResponse.json({ error: "Shipment not found." }, { status: 404 });
      shipment = data as Shipment;
      // For a BoL the caller must be the booking partner — the shipment's
      // partner_id is the issuer of the B/L.
      if (documentType === "bill_of_lading" && shipment.partner_id !== access.partner_id) {
        return NextResponse.json(
          { error: "Only the booking partner can generate a Bill of Lading." },
          { status: 403 },
        );
      }
    }

    // ── Resolve seller / buyer partner rows ───────────────────────────────
    // For a "sell" post: seller = post.partner_id, buyer = the OTHER
    // party in the negotiation (or the caller when they are the buyer).
    // For a "buy" post:  buyer  = post.partner_id, seller = the other
    // party.
    // For a "contract" / "auction" post: same as "sell".
    //
    // When there's no negotiation (caller passed only post_id + shipment_id),
    // the seller is the post owner and the buyer is the caller (when the
    // caller is not the owner) — i.e. the "issuer" is the seller and the
    // "counterparty" is whoever is calling.
    const postType = post?.post_type ?? "sell";
    const isSellSide = postType !== "buy";

    const sellerPartnerId =
      negotiation
        ? (isSellSide
            ? negotiation.partner_id_a
            : negotiation.partner_id_b)
        : post
          ? (isSellSide ? post.partner_id : access.partner_id)
          : access.partner_id;
    const buyerPartnerId =
      negotiation
        ? (isSellSide
            ? negotiation.partner_id_b
            : negotiation.partner_id_a)
        : post
          ? (isSellSide ? access.partner_id : post.partner_id)
          : null;

    // The issuer (creator of the document) is the caller — they may be the
    // seller OR the buyer depending on their role. The auto-generate
    // dispatch below uses seller / buyer semantics; the issuer partner_id
    // stamped by createDocument() is the caller.

    let sellerPartner: Partner | null = null;
    let buyerPartner: Partner | null = null;
    if (sellerPartnerId) {
      try { sellerPartner = await store.getPartner(sellerPartnerId); } catch { sellerPartner = null; }
    }
    if (buyerPartnerId) {
      try { buyerPartner = await store.getPartner(buyerPartnerId); } catch { buyerPartner = null; }
    }

    // ── Build the line-item array ─────────────────────────────────────────
    // The single line item is derived from the post's product / quantity /
    // unit_price (from the post's target_price OR the negotiation's
    // agreed_terms).
    //
    // MARKET-H22 (forge fix): the caller-supplied body.currency /
    // body.incoterm / body.paymentTerms are IGNORED for these three fields
    // — a partner that auto-generates a document from a settled
    // negotiation must not be able to forge the agreed price's currency or
    // the agreed incoterm / payment terms. When a negotiation_id is
    // supplied AND the negotiation carries `agreed_terms`, the agreed
    // terms are the SOLE source of truth. When there is no negotiation
    // (or the negotiation has no agreed_terms yet), the post's own
    // currency / incoterm / payment_terms are used. body.* is no longer
    // honoured on this path — callers that need to override must edit
    // the post / re-negotiate.
    const agreedTerms = (negotiation?.agreed_terms ?? null) as MarketplaceOfferTerms | null;
    // 2g-F26 fix: track whether we fell back to post.target_price (the buyer's
    // MAX willingness to pay — a ceiling, NOT the agreed sale price). When this
    // is true, the generated document carries an unconfirmed price that may
    // overstate the actual deal. The PDF template renders a "PRICE NOT
    // CONFIRMED" warning watermark when priceUnconfirmed is set.
    const usingTargetPriceFallback = agreedTerms?.unit_price == null && agreedTerms?.price == null && post?.target_price != null;
    const unitPrice = agreedTerms?.unit_price ?? agreedTerms?.price ?? post?.target_price ?? null;
    if (usingTargetPriceFallback) {
      console.warn(`[marketplace.documents.auto-generate] docType=${documentType} postId=${post?.id} — no agreed_terms; falling back to post.target_price=${post?.target_price} (buyer's ceiling, NOT the sale price). Document will carry a PRICE NOT CONFIRMED warning.`);
    }
    const quantity = agreedTerms?.quantity ?? post?.quantity ?? null;
    const unit = agreedTerms?.unit ?? post?.unit ?? null;
    const currency =
      (agreedTerms?.currency ?? post?.currency ?? "USD") as string;

    const lineItem: TradeDocumentLineItem = {
      description: post?.product_name ?? "Goods",
      hs_code: extractHsCode(post?.specifications),
      quantity: typeof quantity === "number" ? quantity : null,
      unit: unit ?? null,
      unit_price: typeof unitPrice === "number" ? unitPrice : null,
      currency,
      country_of_origin: post?.origin_country ?? null,
      gross_weight_kg: shipment?.gross_weight ?? null,
      net_weight_kg: shipment?.net_weight ?? null,
      packages: shipment?.packages_count ?? null,
      package_type: post?.packaging ?? null,
    };

    // ── Build the AutoGenerateContext ───────────────────────────────────
    // incoterm + paymentTerms resolution: agreedTerms take precedence
    // over the post, and the body's incoterm / paymentTerms are IGNORED
    // (see MARKET-H22 note above). goodsDescription / originCountry remain
    // caller-overridable — those are descriptive metadata, not commercial
    // terms, so the caller may set them freely (e.g. BoL notes).
    const ctx: AutoGenerateContext = {
      tenantId: access.tenant_id,
      priceUnconfirmed: usingTargetPriceFallback, // 2g-F26: surfaces a "PRICE NOT CONFIRMED" warning on the PDF
      seller: partnerToParty(sellerPartner, isSellSide ? "seller" : "buyer"),
      buyer: partnerToParty(buyerPartner, isSellSide ? "buyer" : "seller"),
      shipper: shipment ? partnerToParty(sellerPartner, "shipper") : undefined,
      consignee: shipment ? partnerToParty(buyerPartner, "consignee") : undefined,
      notifyParty: shipment ? partnerToParty(buyerPartner, "notify") : undefined,
      exporter: partnerToParty(sellerPartner, "exporter"),
      importer: partnerToParty(buyerPartner, "importer"),
      items: [lineItem],
      products: [lineItem],
      currency,
      incoterm: agreedTerms?.incoterm ?? post?.incoterm ?? undefined,
      paymentTerms: agreedTerms?.payment_terms ?? post?.payment_terms ?? undefined,
      containerNumber: shipment?.container_number ?? undefined,
      totalPackages: shipment?.packages_count ?? undefined,
      totalGrossWeight: shipment?.gross_weight ?? undefined,
      totalNetWeight: shipment?.net_weight ?? undefined,
      vesselName: shipment?.vessel_name ?? undefined,
      portOfLoading: shipment?.loading_port ?? undefined,
      portOfDischarge: shipment?.discharge_port ?? undefined,
      goodsDescription: body?.goodsDescription ?? post?.product_name ?? undefined,
      weight: shipment?.net_weight ?? shipment?.gross_weight ?? 0,
      originCountry: body?.originCountry ?? post?.origin_country ?? undefined,
    };

    // ── Dispatch ──────────────────────────────────────────────────────────
    const { referenceNumber, documentData } = autoGenerateDocument(documentType, ctx);

    // 2g-F26: merge the price-unconfirmed flag into the persisted document_data
    // so the PDF template can render a "PRICE NOT CONFIRMED" warning watermark
    // when the unit_price was derived from post.target_price (buyer's ceiling)
    // instead of agreed_terms.unit_price.
    const documentDataWithFlag = usingTargetPriceFallback
      ? { ...documentData, priceUnconfirmed: true }
      : documentData;

    // ── Persist ──────────────────────────────────────────────────────────
    const created = await createDocument(access.tenant_id, access.partner_id, {
      document_type: documentType,
      status: "generated",          // PDF can be rendered immediately
      document_data: documentDataWithFlag,
      post_id: post?.id ?? null,
      negotiation_id: negotiation?.id ?? null,
      shipment_id: shipment?.id ?? null,
      reference_number: referenceNumber,
    });

    try {
      await audit(
        store,
        { id: undefined, username: access.portal_email || `portal:${access.id}`, tenant_id: access.tenant_id },
        req,
        "marketplace.document_auto_generated",
        "marketplace_trade_documents",
        created.id,
        {
          document_type: created.document_type,
          reference_number: created.reference_number,
          post_id: created.post_id,
          negotiation_id: created.negotiation_id,
          shipment_id: created.shipment_id,
        },
      );
    } catch (e) {
      console.error("[marketplace.documents.auto-generate] audit failed:", e);
    }

    return NextResponse.json(created, { status: 201 });
  } catch (e: any) {
    console.error("[marketplace.documents.auto-generate]", e);
    const msg = e?.message || "Failed to auto-generate document.";
    const status = /not found/i.test(msg) ? 404 : 500;
    return NextResponse.json({ error: msg }, { status });
  }
}

export const POST = withApm(_post, "POST /api/marketplace/documents/auto-generate");

// ─── Helpers ────────────────────────────────────────────────────────────────

/**
 * Extract an HS code from a post's `specifications` JSONB field. The
 * field may be in any of these shapes:
 *   • { hs_code: "1006.30.10.00", ... }
 *   • { "HS Code": "1006.30.10.00", ... }
 *   • { hs: "1006.30.10.00", ... }
 *   • { } (no hs code)
 *
 * Returns the string or null when not found.
 */
function extractHsCode(specs: unknown): string | null {
  if (!specs || typeof specs !== "object") return null;
  const s = specs as Record<string, unknown>;
  const v =
    s.hs_code ?? s.hsCode ?? s.HSCode ?? s.hs ?? s["HS Code"] ?? s["HS code"];
  return typeof v === "string" && v.length > 0 ? v : null;
}

/**
 * Convert a Partner row to the TradeDocumentParty shape used by the
 * document generators. The `role` argument is only used as a label when
 * the partner is null (so the PDF shows "Seller not set" instead of "—").
 */
function partnerToParty(
  partner: Partner | null,
  _role: "seller" | "buyer" | "shipper" | "consignee" | "notify" | "exporter" | "importer",
): TradeDocumentParty {
  if (!partner) return {};
  return {
    name: partner.name,
    address_line: partner.address_line,
    city: partner.city,
    postal_code: partner.postal_code,
    country: partner.country,
    country_code: partner.country,
    phone: partner.phone,
    email: partner.email,
    tax_id: partner.tax_id ?? partner.vat_number ?? partner.registration_number ?? null,
    contact_name: partner.contact_name,
  };
}
