// Aspidus DMCC — Construction catalog (40 products)
// Category: "construction"
// SKU format: CON-TYPE-NN-NNN (CEM/CLK/GYP/LIM/AGG/SCT/BRK/TIL/GLS/INS)

export interface CoaParam { name: string; value: string; }
export interface Logistics { cap20: number | null; cap40: number | null; }
export interface SeedProduct {
  sku: string; name: string; category: string; unit: string;
  price: number; currency: string; cost: number;
  stock: number; reorder_level: number; active: boolean;
  description: string; hs_code: string;
  brand: null; shelf_life: string | null; image_url: null;
  logistics: Logistics; coa_params: CoaParam[];
  detailed_spec: string; tags: string[];
}

function p(o: {
  sku: string; name: string; category: string;
  hs: string; price: number; unit?: string;
  coa: [string, string][]; spec: string;
  cap20?: number | null; cap40?: number | null;
  tags?: string[]; shelfLife?: string | null;
  desc?: string; stock?: number;
}): SeedProduct {
  const unit = o.unit ?? "MT";
  const stock = o.stock ?? 20000;
  return {
    sku: o.sku, name: o.name, category: o.category, unit,
    price: o.price, currency: "USD", cost: o.price, stock,
    reorder_level: Math.max(1, Math.floor(stock / 20)),
    active: true, description: o.desc ?? o.name,
    hs_code: o.hs, brand: null,
    shelf_life: o.shelfLife ?? null, image_url: null,
    logistics: { cap20: o.cap20 ?? null, cap40: o.cap40 ?? null },
    coa_params: o.coa.map(([name, value]) => ({ name, value })),
    detailed_spec: o.spec, tags: o.tags ?? [],
  };
}

const CEMENT_SHELF = "3 months from production in original packaging";
const GYP_SHELF = "12 months under dry storage";
const LIME_SHELF = "6 months under dry storage";
const INS_SHELF = "24 months in original packaging";

// Logistics defaults
const CAP_CEMENT_20 = 24000, CAP_CEMENT_40 = 27000;
const CAP_BULK_20 = 25000, CAP_BULK_40 = 27000;
const CAP_GYP_20 = 24000, CAP_GYP_40 = 27000;
const CAP_AGG_20 = 24000, CAP_AGG_40 = 27000;
const CAP_STEEL_20 = 20000, CAP_STEEL_40 = 26000;
const CAP_BRICK_20 = 20000, CAP_BRICK_40 = 26000;
const CAP_TILE_20 = 20000, CAP_TILE_40 = 25000;
const CAP_GLASS_20 = 18000, CAP_GLASS_40 = 24000;

export const constructionProducts: SeedProduct[] = [
  // ============ CEM — Cement (10) ============
  p({
    sku: "CON-CEM-01-001",
    name: "OPC 42.5R Cement",
    category: "construction",
    hs: "2523290000",
    price: 75,
    coa: [
      ["Standard", "EN 197-1 / ASTM C150"],
      ["Type", "CEM I 42.5R"],
      ["Blaine Fineness", "320-380 m2/kg"],
      ["Initial Setting Time", "90 min Min"],
      ["Final Setting Time", "600 min Max"],
      ["Compressive Strength 3d", "22 MPa Min"],
      ["Compressive Strength 28d", "42.5 MPa Min"],
      ["SO3 Content", "3.5% Max"],
      ["Chloride (Cl-)", "0.10% Max"],
      ["Loss on Ignition", "5.0% Max"],
      ["Insoluble Residue", "5.0% Max"],
      ["Bulk Density", "1.0-1.2 g/cm3"],
    ],
    spec: "ORIGIN: Vietnam/China/Turkey. PACKAGING: 50kg PP bags with PE inner liner on pallets (1MT pallet), 1.5MT jumbo bags (FIBC), or bulk in tank containers/vessels. CERTIFICATIONS: EN 197-1 / ASTM C150 conformance, CE marking, ISO 9001, Certificate of Analysis (COA), Factory test report (FTR). QUALITY: Per buyer specification or national standard. HANDLING: Store in dry, covered warehouse; keep off ground on pallets; seal broken bags immediately. Hygroscopic — cement hardens if exposed to moisture. Shelf life 3 months from production in original unopened packaging. Stack max 8 bags high.",
    shelfLife: CEMENT_SHELF,
    cap20: CAP_CEMENT_20, cap40: CAP_CEMENT_40,
    tags: ["cement", "opc", "42.5r", "cem-i"],
  }),
  p({
    sku: "CON-CEM-02-002",
    name: "OPC 52.5N Cement",
    category: "construction",
    hs: "2523290000",
    price: 90,
    coa: [
      ["Standard", "EN 197-1 / ASTM C150"],
      ["Type", "CEM I 52.5N"],
      ["Blaine Fineness", "350-420 m2/kg"],
      ["Initial Setting Time", "75 min Min"],
      ["Final Setting Time", "600 min Max"],
      ["Compressive Strength 3d", "30 MPa Min"],
      ["Compressive Strength 28d", "52.5 MPa Min"],
      ["SO3 Content", "4.0% Max"],
      ["Chloride (Cl-)", "0.10% Max"],
      ["Loss on Ignition", "5.0% Max"],
      ["Insoluble Residue", "5.0% Max"],
    ],
    spec: "ORIGIN: Vietnam / China / Turkey. PACKAGING: 50kg PP bags with PE inner liner on pallets (1MT pallet), 1.5MT jumbo bags (FIBC), or bulk in tank containers. CERTIFICATIONS: EN 197-1 conformance, CE marking, ISO 9001, COA, Factory Test Report. QUALITY: High-early-strength cement for precast and high-strength concrete. HANDLING: Store dry, covered, off ground on pallets; seal broken bags immediately. Hygroscopic. Shelf life 3 months from production in original unopened packaging. Stack max 8 bags high.",
    shelfLife: CEMENT_SHELF,
    cap20: CAP_CEMENT_20, cap40: CAP_CEMENT_40,
    tags: ["cement", "opc", "52.5n", "high-strength"],
  }),
  p({
    sku: "CON-CEM-03-003",
    name: "SRC (Sulfate Resisting) Cement",
    category: "construction",
    hs: "2523290000",
    price: 85,
    coa: [
      ["Standard", "EN 197-1 / ASTM C150 Type V"],
      ["Type", "CEM I 42.5N-SR"],
      ["C3A Content", "5.0% Max"],
      ["Blaine Fineness", "320-380 m2/kg"],
      ["Initial Setting Time", "90 min Min"],
      ["Final Setting Time", "600 min Max"],
      ["Compressive Strength 28d", "42.5 MPa Min"],
      ["SO3 Content", "2.5% Max"],
      ["Chloride (Cl-)", "0.10% Max"],
      ["Loss on Ignition", "5.0% Max"],
    ],
    spec: "ORIGIN: Saudi Arabia / UAE / China. PACKAGING: 50kg PP bags with PE inner liner on pallets, 1.5MT jumbo bags (FIBC), or bulk. CERTIFICATIONS: EN 197-1 SR conformance, ASTM C150 Type V, CE marking, ISO 9001, COA, FTR. QUALITY: Sulfate-resisting cement for marine, foundation, and aggressive-soil environments. HANDLING: Store dry, covered, off ground; seal broken bags. Hygroscopic. Shelf life 3 months from production in original packaging. Stack max 8 bags high.",
    shelfLife: CEMENT_SHELF,
    cap20: CAP_CEMENT_20, cap40: CAP_CEMENT_40,
    tags: ["cement", "src", "sulfate-resisting", "marine"],
  }),
  p({
    sku: "CON-CEM-04-004",
    name: "PPC (Pozzolana) Cement",
    category: "construction",
    hs: "2523290000",
    price: 68,
    coa: [
      ["Standard", "EN 197-1 / IS 1489"],
      ["Type", "CEM II/B-P 32.5N"],
      ["Pozzolana Content", "21-35%"],
      ["Clinker Content", "65-79%"],
      ["Blaine Fineness", "340-400 m2/kg"],
      ["Initial Setting Time", "90 min Min"],
      ["Final Setting Time", "600 min Max"],
      ["Compressive Strength 28d", "32.5 MPa Min"],
      ["SO3 Content", "3.5% Max"],
      ["Chloride (Cl-)", "0.10% Max"],
    ],
    spec: "ORIGIN: India / Indonesia / Vietnam. PACKAGING: 50kg PP bags with PE inner liner on pallets, 1.5MT jumbo bags, or bulk. CERTIFICATIONS: EN 197-1 / IS 1489 Part 1, CE marking, ISO 9001, COA, FTR. QUALITY: Portland Pozzolana Cement for mass concrete, dams, and hydraulic structures. HANDLING: Store dry, covered, off ground; seal broken bags. Hygroscopic. Shelf life 3 months from production in original packaging. Stack max 8 bags high.",
    shelfLife: CEMENT_SHELF,
    cap20: CAP_CEMENT_20, cap40: CAP_CEMENT_40,
    tags: ["cement", "ppc", "pozzolana", "mass-concrete"],
  }),
  p({
    sku: "CON-CEM-05-005",
    name: "PSC (Slag Cement)",
    category: "construction",
    hs: "2523290000",
    price: 72,
    coa: [
      ["Standard", "EN 197-1 / IS 455"],
      ["Type", "CEM III/B 32.5N"],
      ["Granulated Slag Content", "66-80%"],
      ["Clinker Content", "20-34%"],
      ["Blaine Fineness", "360-440 m2/kg"],
      ["Initial Setting Time", "90 min Min"],
      ["Final Setting Time", "600 min Max"],
      ["Compressive Strength 28d", "32.5 MPa Min"],
      ["SO3 Content", "4.0% Max"],
      ["Chloride (Cl-)", "0.10% Max"],
    ],
    spec: "ORIGIN: India / Japan / Korea. PACKAGING: 50kg PP bags with PE inner liner on pallets, 1.5MT jumbo bags, or bulk. CERTIFICATIONS: EN 197-1 / IS 455, CE marking, ISO 9001, COA, FTR. QUALITY: Portland Slag Cement — high chloride & sulfate resistance for marine and aggressive environments. HANDLING: Store dry, covered, off ground; seal broken bags. Hygroscopic. Shelf life 3 months from production. Stack max 8 bags high.",
    shelfLife: CEMENT_SHELF,
    cap20: CAP_CEMENT_20, cap40: CAP_CEMENT_40,
    tags: ["cement", "psc", "slag", "marine"],
  }),
  p({
    sku: "CON-CEM-06-006",
    name: "White Cement",
    category: "construction",
    hs: "2523210000",
    price: 240,
    coa: [
      ["Standard", "EN 197-1 / ASTM C150"],
      ["Type", "CEM I 52.5R White"],
      ["Whiteness (L*)", "88 Min"],
      ["Fe2O3 Content", "0.4% Max"],
      ["Mn2O3 Content", "0.03% Max"],
      ["Blaine Fineness", "380-450 m2/kg"],
      ["Compressive Strength 28d", "52.5 MPa Min"],
      ["Initial Setting Time", "75 min Min"],
      ["Final Setting Time", "600 min Max"],
      ["SO3 Content", "3.5% Max"],
    ],
    spec: "ORIGIN: Turkey / UAE / Spain / Denmark. PACKAGING: 40kg PP bags with PE inner liner on pallets (1.6MT pallet) or 1.5MT jumbo bags; specialty 25kg moisture-proof bags. CERTIFICATIONS: EN 197-1, ASTM C150, CE marking, ISO 9001, COA, FTR, whiteness index report. QUALITY: High-whiteness architectural cement for terrazzo, decorative concrete, and tile adhesives. HANDLING: Store dry, covered, off ground; protect from dust & moisture to preserve whiteness. Shelf life 3 months from production in original packaging. Stack max 6 bags high.",
    shelfLife: CEMENT_SHELF,
    cap20: CAP_CEMENT_20, cap40: CAP_CEMENT_40,
    tags: ["cement", "white", "architectural", "decorative"],
  }),
  p({
    sku: "CON-CEM-07-007",
    name: "Oil Well Cement Class G",
    category: "construction",
    hs: "2523290000",
    price: 175,
    coa: [
      ["Standard", "API Spec 10A"],
      ["Class", "Class G (HSR)"],
      ["C3A Content", "3.0% Max (HSR)"],
      ["Free Water", "3.5 ml Max"],
      ["Thickening Time", "90-120 min at BHCT"],
      ["Compressive Strength 8h @ 38C", "2.1 MPa Min"],
      ["Compressive Strength 8h @ 60C", "10.3 MPa Min"],
      ["Blaine Fineness", "270-350 m2/kg"],
      ["MgO Content", "6.0% Max"],
      ["SO3 Content", "3.0% Max"],
    ],
    spec: "ORIGIN: USA / Canada / Saudi Arabia / China. PACKAGING: 1.5MT jumbo bags (FIBC) or 50kg specialized PP bags on pallets; bulk in tank containers. CERTIFICATIONS: API Spec 10A monogram license, ISO 9001, API Q1, COA, FTR. QUALITY: Class G High Sulfate Resistant (HSR) oil well cement for primary well cementing. HANDLING: Store dry, covered, off ground; strictly protect from moisture. Shelf life 3 months from production in original packaging. Stack max 6 bags high.",
    shelfLife: CEMENT_SHELF,
    cap20: CAP_CEMENT_20, cap40: CAP_CEMENT_40,
    tags: ["cement", "oil-well", "api-10a", "class-g", "hsr"],
  }),
  p({
    sku: "CON-CEM-08-008",
    name: "Masonry Cement",
    category: "construction",
    hs: "2523290000",
    price: 60,
    coa: [
      ["Standard", "ASTM C91 / EN 413-1"],
      ["Type", "MC 22.5X"],
      ["Clinker Content", "40-60%"],
      ["Limestone/Inert Filler", "20-40%"],
      ["Air Content", "8-18%"],
      ["Compressive Strength 28d", "22.5 MPa Min"],
      ["Initial Setting Time", "90 min Min"],
      ["Final Setting Time", "720 min Max"],
      ["SO3 Content", "3.5% Max"],
      ["Water Retention", "70% Min"],
    ],
    spec: "ORIGIN: India / Turkey / Egypt. PACKAGING: 40kg or 50kg PP bags with PE inner liner on pallets, or 1.2MT jumbo bags. CERTIFICATIONS: ASTM C91 / EN 413-1, CE marking, ISO 9001, COA, FTR. QUALITY: Masonry cement for bricklaying, plastering, and rendering mortars with enhanced workability. HANDLING: Store dry, covered, off ground; seal broken bags. Hygroscopic. Shelf life 3 months from production in original packaging. Stack max 8 bags high.",
    shelfLife: CEMENT_SHELF,
    cap20: CAP_CEMENT_20, cap40: CAP_CEMENT_40,
    tags: ["cement", "masonry", "mortar", "plastering"],
  }),
  p({
    sku: "CON-CEM-09-009",
    name: "Quick-Set Cement",
    category: "construction",
    hs: "2523290000",
    price: 95,
    coa: [
      ["Standard", "EN 197-1 / ASTM C150 (modified)"],
      ["Type", "Rapid Hardening CEM I 52.5R"],
      ["Blaine Fineness", "400-500 m2/kg"],
      ["Initial Setting Time", "45 min Min"],
      ["Final Setting Time", "300 min Max"],
      ["Compressive Strength 1d", "20 MPa Min"],
      ["Compressive Strength 28d", "52.5 MPa Min"],
      ["C3S Content", "60% Min"],
      ["SO3 Content", "4.0% Max"],
      ["Chloride (Cl-)", "0.10% Max"],
    ],
    spec: "ORIGIN: China / Turkey / India. PACKAGING: 25kg or 50kg PP bags with PE inner liner on pallets, 1MT jumbo bags. CERTIFICATIONS: EN 197-1 / ASTM C150, CE marking, ISO 9001, COA, FTR. QUALITY: Rapid-hardening cement for emergency repairs, precast, cold-weather concreting, and shotcrete. HANDLING: Store dry, covered, off ground; rapid setting — work quickly. Shelf life 3 months from production in original packaging. Stack max 6 bags high.",
    shelfLife: CEMENT_SHELF,
    cap20: CAP_CEMENT_20, cap40: CAP_CEMENT_40,
    tags: ["cement", "quick-set", "rapid-hardening", "repair"],
  }),
  p({
    sku: "CON-CEM-10-010",
    name: "Low-Alkali Cement",
    category: "construction",
    hs: "2523290000",
    price: 82,
    coa: [
      ["Standard", "EN 197-1 / ASTM C150 (LA)"],
      ["Type", "CEM I 42.5N-LA"],
      ["Equivalent Alkali (Na2O+0.658K2O)", "0.60% Max"],
      ["Blaine Fineness", "320-380 m2/kg"],
      ["Initial Setting Time", "90 min Min"],
      ["Final Setting Time", "600 min Max"],
      ["Compressive Strength 28d", "42.5 MPa Min"],
      ["SO3 Content", "3.5% Max"],
      ["Chloride (Cl-)", "0.10% Max"],
      ["Loss on Ignition", "5.0% Max"],
    ],
    spec: "ORIGIN: USA / Canada / Turkey / China. PACKAGING: 50kg PP bags with PE inner liner on pallets, 1.5MT jumbo bags, or bulk. CERTIFICATIONS: EN 197-1 / ASTM C150 with low-alkali option, CE marking, ISO 9001, COA, FTR, alkali content report. QUALITY: Low-alkali cement to mitigate alkali-silica reaction (ASR) with reactive aggregates. HANDLING: Store dry, covered, off ground; seal broken bags. Hygroscopic. Shelf life 3 months from production. Stack max 8 bags high.",
    shelfLife: CEMENT_SHELF,
    cap20: CAP_CEMENT_20, cap40: CAP_CEMENT_40,
    tags: ["cement", "low-alkali", "asr-resistant"],
  }),

  // ============ CLK — Clinker (3) ============
  p({
    sku: "CON-CLK-11-011",
    name: "Portland Clinker 65% CaO",
    category: "construction",
    hs: "2523100000",
    price: 52,
    coa: [
      ["CaO Content", "65% Min"],
      ["SiO2", "22% Typical"],
      ["Al2O3", "5% Typical"],
      ["Fe2O3", "3.5% Typical"],
      ["MgO", "2.0% Max"],
      ["SO3", "1.0% Max"],
      ["Free CaO", "1.5% Max"],
      ["Na2O+K2O", "1.0% Max"],
      ["Chloride (Cl-)", "0.01% Max"],
      ["Litre Weight", "1300-1400 g/l"],
      ["CS (C3S)", "55% Typical"],
      ["Size", "0-25 mm"],
    ],
    spec: "ORIGIN: Vietnam / China / Turkey / Iran. PACKAGING: Bulk in vessel holds or 1MT jumbo bags (FIBC); some shipments in 50kg PP bags. CERTIFICATIONS: EN 197-1 clinker spec, ASTM C150, ISO 9001, COA, FTR. QUALITY: High-quality Portland clinker for cement grinding. HANDLING: Store in covered dry silo or bulk warehouse; avoid moisture. Clinker does not have a defined shelf life but should be kept dry to prevent degradation. Fumigation per ISPM-15.",
    shelfLife: null,
    cap20: CAP_BULK_20, cap40: CAP_BULK_40,
    tags: ["clinker", "portland", "65-cao", "cement-grinding"],
  }),
  p({
    sku: "CON-CLK-12-012",
    name: "White Clinker",
    category: "construction",
    hs: "2523100000",
    price: 105,
    coa: [
      ["CaO Content", "68% Min"],
      ["Fe2O3", "0.4% Max"],
      ["Mn2O3", "0.03% Max"],
      ["SiO2", "24% Typical"],
      ["Al2O3", "5% Typical"],
      ["MgO", "2.0% Max"],
      ["Free CaO", "1.5% Max"],
      ["Whiteness (L*)", "85 Min"],
      ["Litre Weight", "1300-1400 g/l"],
      ["Size", "0-25 mm"],
    ],
    spec: "ORIGIN: Turkey / Spain / UAE. PACKAGING: 1MT jumbo bags (FIBC) on pallets or 50kg specialized PP bags; bulk in tank containers. CERTIFICATIONS: EN 197-1, ASTM C150, ISO 9001, COA, FTR, whiteness report. QUALITY: Low-iron white clinker for producing white cement. HANDLING: Store in covered dry warehouse; strictly protect from dust & moisture to preserve whiteness. No defined shelf life but keep dry.",
    shelfLife: null,
    cap20: CAP_BULK_20, cap40: CAP_BULK_40,
    tags: ["clinker", "white", "low-iron"],
  }),
  p({
    sku: "CON-CLK-13-013",
    name: "Sulfate-Resisting Clinker",
    category: "construction",
    hs: "2523100000",
    price: 58,
    coa: [
      ["CaO Content", "64% Min"],
      ["C3A Content", "5.0% Max"],
      ["C4AF Content", "20% Typical"],
      ["SiO2", "22% Typical"],
      ["Al2O3", "4% Typical"],
      ["Fe2O3", "5% Typical"],
      ["MgO", "2.0% Max"],
      ["Free CaO", "1.5% Max"],
      ["Litre Weight", "1300-1400 g/l"],
      ["Size", "0-25 mm"],
    ],
    spec: "ORIGIN: Saudi Arabia / China / Turkey. PACKAGING: Bulk in vessel holds or 1MT jumbo bags (FIBC). CERTIFICATIONS: EN 197-1 SR clinker spec, ASTM C150 Type V, ISO 9001, COA, FTR. QUALITY: Sulfate-resisting clinker with low C3A for marine & aggressive-environment cements. HANDLING: Store in covered dry silo or bulk warehouse; avoid moisture. No defined shelf life but keep dry.",
    shelfLife: null,
    cap20: CAP_BULK_20, cap40: CAP_BULK_40,
    tags: ["clinker", "sulfate-resisting", "low-c3a", "marine"],
  }),

  // ============ GYP — Gypsum (4) ============
  p({
    sku: "CON-GYP-14-014",
    name: "Natural Gypsum 90% Purity",
    category: "construction",
    hs: "2520100000",
    price: 32,
    coa: [
      ["CaSO4·2H2O", "90% Min"],
      ["Free Moisture", "3.0% Max"],
      ["SiO2", "3.0% Max"],
      ["Al2O3", "1.5% Max"],
      ["Fe2O3", "0.5% Max"],
      ["MgO", "1.0% Max"],
      ["Na2O", "0.3% Max"],
      ["K2O", "0.3% Max"],
      ["Purity (as CaSO4)", "85% Min"],
      ["Size", "0-50 mm"],
    ],
    spec: "ORIGIN: Thailand / Oman / Iran / Spain / Mexico. PACKAGING: 1MT or 1.5MT jumbo bags (FIBC), 50kg PP bags on pallets, or bulk in vessel. CERTIFICATIONS: ISO 9001, COA, FTR, Origin certificate. QUALITY: High-purity natural gypsum for cement retarder and plaster production. HANDLING: Store in covered dry warehouse; protect from moisture. Hygroscopic. Shelf life 12 months under dry storage. Stack max 6 bags high.",
    shelfLife: GYP_SHELF,
    cap20: CAP_GYP_20, cap40: CAP_GYP_40,
    tags: ["gypsum", "natural", "90-purity", "cement-retarder"],
  }),
  p({
    sku: "CON-GYP-15-015",
    name: "FGD Gypsum (Flue Gas Desulfurization)",
    category: "construction",
    hs: "2520100000",
    price: 25,
    coa: [
      ["CaSO4·2H2O", "95% Min"],
      ["Free Moisture", "10.0% Max"],
      ["Free Water", "10-15% Typical"],
      ["CaSO3·1/2H2O", "0.5% Max"],
      ["SiO2", "1.5% Max"],
      ["Al2O3", "0.5% Max"],
      ["Fe2O3", "0.2% Max"],
      ["MgO", "0.5% Max"],
      ["Chloride (Cl-)", "100 ppm Max"],
      ["Color", "White to off-white"],
    ],
    spec: "ORIGIN: China / India / Germany / USA (coal power plant byproduct). PACKAGING: 1MT jumbo bags (FIBC), bulk in vessel or silo truck. CERTIFICATIONS: ISO 9001, COA, FTR, heavy metals analysis. QUALITY: Synthetic gypsum from flue gas desulfurization; suitable for cement retarder, plasterboard, and wallboard. HANDLING: Store in covered dry warehouse; protect from moisture. Higher free moisture than natural gypsum. Shelf life 12 months under dry storage.",
    shelfLife: GYP_SHELF,
    cap20: CAP_GYP_20, cap40: CAP_GYP_40,
    tags: ["gypsum", "fgd", "synthetic", "byproduct"],
  }),
  p({
    sku: "CON-GYP-16-016",
    name: "Alpha Hemihydrate",
    category: "construction",
    hs: "2520200000",
    price: 240,
    coa: [
      ["Form", "Alpha Calcium Sulfate Hemihydrate"],
      ["CaSO4·1/2H2O", "95% Min"],
      ["Free Water", "2.0% Max"],
      ["Initial Setting Time", "15-25 min"],
      ["Final Setting Time", "30-45 min"],
      ["Compressive Strength 2h", "20 MPa Min"],
      ["Compressive Strength 24h", "35 MPa Min"],
      ["Particle Size (d50)", "15-30 μm"],
      ["pH", "7.0-9.0"],
      ["Bulk Density", "0.7-0.9 g/cm3"],
    ],
    spec: "ORIGIN: Germany / Japan / China / Thailand. PACKAGING: 25kg moisture-proof PP bags with PE inner liner on pallets (1.2MT pallet) or 1MT jumbo bags with PE liner. CERTIFICATIONS: ISO 9001, COA, FTR, dental/medical grade available. QUALITY: High-strength alpha hemihydrate for dental, precision casting (DCP), and self-leveling floor compounds. HANDLING: Store in original sealed packaging, dry (<50% RH), 10-25C. Highly hygroscopic. Shelf life 12 months under dry storage.",
    shelfLife: GYP_SHELF,
    cap20: CAP_GYP_20, cap40: CAP_GYP_40,
    tags: ["gypsum", "alpha", "hemihydrate", "high-strength", "dental"],
  }),
  p({
    sku: "CON-GYP-17-017",
    name: "Beta Plaster",
    category: "construction",
    hs: "2520200000",
    price: 100,
    coa: [
      ["Form", "Beta Calcium Sulfate Hemihydrate"],
      ["CaSO4·1/2H2O", "85% Min"],
      ["Free Water", "3.0% Max"],
      ["Initial Setting Time", "8-15 min"],
      ["Final Setting Time", "20-30 min"],
      ["Compressive Strength 2h", "8 MPa Min"],
      ["Water Plaster Ratio", "60-70%"],
      ["Particle Size (d50)", "20-50 μm"],
      ["Bulk Density", "0.6-0.8 g/cm3"],
      ["pH", "7.0-9.0"],
    ],
    spec: "ORIGIN: Turkey / Spain / Egypt / Thailand / China. PACKAGING: 25kg moisture-proof PP bags with PE inner liner on pallets, or 1MT jumbo bags with PE liner. CERTIFICATIONS: ISO 9001, COA, FTR. QUALITY: Beta plaster (stucco) for wall plaster, moulding plaster, and plasterboard production. HANDLING: Store in original sealed packaging, dry (<60% RH), 10-25C. Hygroscopic. Shelf life 12 months under dry storage.",
    shelfLife: GYP_SHELF,
    cap20: CAP_GYP_20, cap40: CAP_GYP_40,
    tags: ["gypsum", "beta", "plaster", "stucco"],
  }),

  // ============ LIM — Lime (3) ============
  p({
    sku: "CON-LIM-18-018",
    name: "Quicklime CaO 90%",
    category: "construction",
    hs: "2522100000",
    price: 95,
    coa: [
      ["Active CaO", "90% Min"],
      ["CO2 Content", "2.0% Max"],
      ["SiO2", "2.0% Max"],
      ["Al2O3", "1.0% Max"],
      ["Fe2O3", "0.5% Max"],
      ["MgO", "2.0% Max"],
      ["Sulfur (S)", "0.05% Max"],
      ["Lump Size", "10-50 mm"],
      ["Reactivity (T60)", "2-5 min"],
      ["Loss on Ignition", "5.0% Max"],
    ],
    spec: "ORIGIN: Vietnam / Oman / UAE / Malaysia. PACKAGING: 1MT or 1.5MT jumbo bags (FIBC) with PE liner, 50kg PP bags on pallets, or bulk in silo truck. CERTIFICATIONS: ISO 9001, COA, FTR, EN 459-1. QUALITY: High-calcium quicklime for steel, construction, water treatment, and soil stabilization. HANDLING: Highly reactive — store in sealed dry silo or original packaging; reacts violently with water releasing heat. Shelf life 6 months under dry storage. Stack max 5 bags high. Avoid skin/eye contact.",
    shelfLife: LIME_SHELF,
    cap20: CAP_GYP_20, cap40: CAP_GYP_40,
    tags: ["lime", "quicklime", "cao-90", "steel", "water-treatment"],
  }),
  p({
    sku: "CON-LIM-19-019",
    name: "Hydrated Lime 95%",
    category: "construction",
    hs: "2522200000",
    price: 110,
    coa: [
      ["Active Ca(OH)2", "95% Min"],
      ["Free Moisture", "1.5% Max"],
      ["CO2 Content", "1.5% Max"],
      ["SiO2", "1.5% Max"],
      ["Al2O3", "0.8% Max"],
      ["Fe2O3", "0.4% Max"],
      ["MgO", "2.0% Max"],
      ["Particle Size", "90% passing 75 μm"],
      ["Bulk Density", "0.4-0.6 g/cm3"],
      ["Residue on 75μm sieve", "10% Max"],
    ],
    spec: "ORIGIN: Vietnam / Oman / UAE / Egypt / China. PACKAGING: 25kg PP bags with PE inner liner on pallets (1MT pallet), 1MT jumbo bags with PE liner, or bulk in silo truck. CERTIFICATIONS: ISO 9001, COA, FTR, EN 459-1. QUALITY: High-purity hydrated lime for construction (mortar), water treatment, FGD, and chemical applications. HANDLING: Store in original sealed packaging, dry (<60% RH). Hygroscopic — slowly absorbs CO2. Shelf life 6 months under dry storage. Avoid inhalation.",
    shelfLife: LIME_SHELF,
    cap20: CAP_GYP_20, cap40: CAP_GYP_40,
    tags: ["lime", "hydrated", "caoh2-95", "fgd", "water-treatment"],
  }),
  p({
    sku: "CON-LIM-20-020",
    name: "Dolomitic Lime",
    category: "construction",
    hs: "2528300000",
    price: 120,
    coa: [
      ["CaO Content", "50-55%"],
      ["MgO Content", "30-35%"],
      ["SiO2", "1.5% Max"],
      ["Al2O3", "0.8% Max"],
      ["Fe2O3", "0.5% Max"],
      ["Sulfur (S)", "0.05% Max"],
      ["CO2 Content", "2.0% Max"],
      ["Loss on Ignition", "5.0% Max"],
      ["Lump Size", "10-50 mm"],
      ["Reactivity (T60)", "3-8 min"],
    ],
    spec: "ORIGIN: China / Turkey / Spain / Mexico. PACKAGING: 1MT or 1.5MT jumbo bags (FIBC) with PE liner, 50kg PP bags on pallets, or bulk. CERTIFICATIONS: ISO 9001, COA, FTR, EN 459-1. QUALITY: Dolomitic (high-magnesium) quicklime for steel fluxing, refractories, and specialty construction. HANDLING: Highly reactive — store sealed and dry; reacts with water releasing heat. Shelf life 6 months under dry storage. Stack max 5 bags high.",
    shelfLife: LIME_SHELF,
    cap20: CAP_GYP_20, cap40: CAP_GYP_40,
    tags: ["lime", "dolomitic", "high-magnesium", "steel-flux"],
  }),

  // ============ AGG — Aggregates (5) ============
  p({
    sku: "CON-AGG-21-021",
    name: "Washed River Sand",
    category: "construction",
    hs: "2505000000",
    price: 12,
    coa: [
      ["Source", "Natural river sand"],
      ["Fineness Modulus", "2.3-3.1"],
      ["Silt & Clay Content", "3.0% Max"],
      ["Clay Lumps & Friable Particles", "3.0% Max"],
      ["Material <75 μm (P200)", "5.0% Max"],
      ["Organic Impurities", "Colorimetric OK"],
      ["Specific Gravity", "2.55-2.65"],
      ["Bulk Density", "1.45-1.55 t/m3"],
      ["Chloride Content", "0.03% Max"],
      ["Grading Zone", "ASTM C33 Zone II"],
    ],
    spec: "ORIGIN: Malaysia (Sarawak) / Vietnam / Philippines / India. PACKAGING: Bulk in vessel, 1MT jumbo bags, or 50kg PP bags. CERTIFICATIONS: ISO 9001, COA, EN 12620 / ASTM C33 conformance, sieve analysis report. QUALITY: Washed river sand for concrete, plastering, and asphalt; chloride-compliant. HANDLING: Store on hard standing covered with tarpaulin; prevent contamination. No defined shelf life. Per ISPM-15 exemption (raw mineral).",
    shelfLife: null,
    cap20: CAP_AGG_20, cap40: CAP_AGG_40,
    tags: ["aggregate", "sand", "river", "concrete"],
  }),
  p({
    sku: "CON-AGG-22-022",
    name: "Crushed Stone Aggregate 20mm",
    category: "construction",
    hs: "2517490000",
    price: 16,
    coa: [
      ["Source", "Crushed limestone / granite"],
      ["Nominal Size", "20 mm"],
      ["Los Angeles Abrasion", "30% Max"],
      ["Aggregate Impact Value (AIV)", "25% Max"],
      ["Aggregate Crushing Value (ACV)", "25% Max"],
      ["Flakiness Index", "35% Max"],
      ["Elongation Index", "35% Max"],
      ["Material <75 μm (P200)", "3.0% Max"],
      ["Specific Gravity", "2.60-2.75"],
      ["Water Absorption", "2.0% Max"],
    ],
    spec: "ORIGIN: Oman / UAE / India / Vietnam / China. PACKAGING: Bulk in vessel, 1MT jumbo bags, or 50kg PP bags. CERTIFICATIONS: ISO 9001, COA, EN 12620 / ASTM C33 conformance, sieve analysis & mechanical test report. QUALITY: Coarse aggregate 20mm for structural concrete. HANDLING: Store on hard standing; segregate by size to prevent contamination. No defined shelf life.",
    shelfLife: null,
    cap20: CAP_AGG_20, cap40: CAP_AGG_40,
    tags: ["aggregate", "crushed-stone", "20mm", "concrete"],
  }),
  p({
    sku: "CON-AGG-23-023",
    name: "Crushed Stone 10mm",
    category: "construction",
    hs: "2517490000",
    price: 18,
    coa: [
      ["Source", "Crushed limestone / granite"],
      ["Nominal Size", "10 mm"],
      ["Los Angeles Abrasion", "30% Max"],
      ["Aggregate Impact Value (AIV)", "25% Max"],
      ["Aggregate Crushing Value (ACV)", "25% Max"],
      ["Flakiness Index", "35% Max"],
      ["Material <75 μm (P200)", "3.0% Max"],
      ["Specific Gravity", "2.60-2.75"],
      ["Water Absorption", "2.0% Max"],
      ["Grading", "ASTM C33 #7"],
    ],
    spec: "ORIGIN: Oman / UAE / India / Vietnam. PACKAGING: Bulk in vessel, 1MT jumbo bags, or 50kg PP bags. CERTIFICATIONS: ISO 9001, COA, EN 12620 / ASTM C33 conformance, sieve analysis & mechanical test report. QUALITY: 10mm single-size coarse aggregate for concrete, asphalt, and drainage. HANDLING: Store on hard standing; segregate by size. No defined shelf life.",
    shelfLife: null,
    cap20: CAP_AGG_20, cap40: CAP_AGG_40,
    tags: ["aggregate", "crushed-stone", "10mm", "drainage"],
  }),
  p({
    sku: "CON-AGG-24-024",
    name: "Marine Sand",
    category: "construction",
    hs: "2505000000",
    price: 10,
    coa: [
      ["Source", "Marine dredged sand"],
      ["Fineness Modulus", "2.3-3.0"],
      ["Chloride Content", "0.06% Max (washed)"],
      ["Shell Content", "5.0% Max"],
      ["Silt & Clay Content", "3.0% Max"],
      ["Material <75 μm (P200)", "5.0% Max"],
      ["Specific Gravity", "2.55-2.65"],
      ["Bulk Density", "1.40-1.55 t/m3"],
      ["Organic Impurities", "Colorimetric OK"],
      ["Process", "Washed & desalinated"],
    ],
    spec: "ORIGIN: Philippines / Malaysia / Vietnam / UAE. PACKAGING: Bulk in vessel or 1MT jumbo bags. CERTIFICATIONS: ISO 9001, COA, EN 12620 / ASTM C33 conformance, chloride analysis report. QUALITY: Washed and desalinated marine sand for concrete and reclamation. HANDLING: Store on hard standing covered with tarpaulin; chloride-tested for rebar safety. No defined shelf life.",
    shelfLife: null,
    cap20: CAP_AGG_20, cap40: CAP_AGG_40,
    tags: ["aggregate", "marine-sand", "washed", "reclamation"],
  }),
  p({
    sku: "CON-AGG-25-025",
    name: "Gabbro Aggregate",
    category: "construction",
    hs: "2517490000",
    price: 20,
    coa: [
      ["Source", "Crushed Gabbro igneous rock"],
      ["Nominal Size", "5-20 mm"],
      ["Los Angeles Abrasion", "22% Max"],
      ["Aggregate Impact Value (AIV)", "20% Max"],
      ["Aggregate Crushing Value (ACV)", "22% Max"],
      ["Polished Stone Value (PSV)", "50 Min"],
      ["Flakiness Index", "30% Max"],
      ["Specific Gravity", "2.90-3.05"],
      ["Water Absorption", "1.0% Max"],
      ["Material <75 μm (P200)", "2.0% Max"],
    ],
    spec: "ORIGIN: Oman (Rustaq) / UAE (Fujairah) / India. PACKAGING: Bulk in vessel, 1MT jumbo bags, or 50kg PP bags. CERTIFICATIONS: ISO 9001, COA, EN 12620 / BS 882 conformance, full mechanical & chemical test report. QUALITY: Premium high-density gabbro aggregate for asphalt, road base, and high-strength concrete. HANDLING: Store on hard standing; segregate by size. No defined shelf life.",
    shelfLife: null,
    cap20: CAP_AGG_20, cap40: CAP_AGG_40,
    tags: ["aggregate", "gabbro", "high-density", "asphalt"],
  }),

  // ============ SCT — Steel construction (5) ============
  p({
    sku: "CON-SCT-26-026",
    name: "Rebar 12mm Grade 60",
    category: "construction",
    hs: "7214200000",
    price: 580,
    coa: [
      ["Diameter", "12 mm"],
      ["Grade", "ASTM A615 Grade 60 / B500B"],
      ["Yield Strength", "420 MPa Min (60 ksi)"],
      ["Ultimate Tensile", "620 MPa Min"],
      ["Elongation", "9% Min (8d)"],
      ["Bend Test", "180 deg, 5d mandrel"],
      ["Carbon (C)", "0.44% Max"],
      ["Manganese (Mn)", "1.15% Max"],
      ["Phosphorus (P)", "0.06% Max"],
      ["Sulfur (S)", "0.06% Max"],
      ["Length", "12 m standard"],
    ],
    spec: "ORIGIN: Turkey / China / India / UAE. PACKAGING: Bundles of approx 2-3MT tied with steel wire, tagged with heat number, on wooden skids; bulk vessel possible. CERTIFICATIONS: ASTM A615 / BS 4449 / EN 10080, ISO 9001, mill test certificate (EN 10204 3.1/3.2), CE marking. QUALITY: Deformed carbon steel rebar for reinforced concrete. HANDLING: Store on hard standing off ground; protect from excessive moisture to prevent rust. No defined shelf life. Tag bundle heat number for traceability.",
    shelfLife: null,
    cap20: CAP_STEEL_20, cap40: CAP_STEEL_40,
    tags: ["steel", "rebar", "12mm", "grade-60", "reinforcement"],
  }),
  p({
    sku: "CON-SCT-27-027",
    name: "Wire Mesh 6mm 6x6m",
    category: "construction",
    hs: "7314120000",
    price: 650,
    coa: [
      ["Wire Diameter", "6 mm"],
      ["Panel Size", "6m x 6m"],
      ["Mesh Opening", "150 mm x 150 mm"],
      ["Wire Grade", "B500A / ASTM A1064"],
      ["Yield Strength", "500 MPa Min"],
      ["Tensile Strength", "550 MPa Min"],
      ["Elongation", "8% Min"],
      ["Zinc Coating", "0 (black) or 60-120 g/m2 galvanized"],
      ["Panel Weight", "approx 25 kg"],
      ["Surface", "Black or hot-dip galvanized"],
    ],
    spec: "ORIGIN: Turkey / China / India. PACKAGING: Bundles of 20-50 panels tied with steel wire, on wooden pallets (1.2-2.5MT). CERTIFICATIONS: EN 10080 / ASTM A1064, ISO 9001, mill test certificate (EN 10204 3.1). QUALITY: Welded wire reinforcement mesh for slabs, walls, and pavement. HANDLING: Store on hard standing off ground; protect galvanized mesh from moisture to prevent white rust. No defined shelf life.",
    shelfLife: null,
    cap20: CAP_STEEL_20, cap40: CAP_STEEL_40,
    tags: ["steel", "wire-mesh", "6mm", "reinforcement", "welded"],
  }),
  p({
    sku: "CON-SCT-28-028",
    name: "Binding Wire BWG20",
    category: "construction",
    hs: "7217100000",
    price: 780,
    coa: [
      ["Wire Gauge", "BWG 20 (0.9 mm)"],
      ["Diameter", "0.9 mm"],
      ["Tensile Strength", "550-750 MPa"],
      ["Elongation", "10% Min"],
      ["Material", "Low carbon steel wire"],
      ["Carbon (C)", "0.10-0.20%"],
      ["Surface", "Black annealed"],
      ["Annealing", "Bright annealed (soft)"],
      ["Coil Weight", "20-25 kg"],
      ["Coils per Bundle", "40-50 coils (1MT)"],
    ],
    spec: "ORIGIN: Turkey / China / India. PACKAGING: 20-25kg coils bundled into 1MT bales wrapped with PP sheet on pallets. CERTIFICATIONS: EN 10218 / ASTM A641, ISO 9001, mill test certificate (EN 10204 3.1). QUALITY: Soft annealed binding wire for tying rebar and baling. HANDLING: Store dry; annealed wire rusts readily — keep covered. No defined shelf life. Use within 12 months for best surface quality.",
    shelfLife: null,
    cap20: CAP_STEEL_20, cap40: CAP_STEEL_40,
    tags: ["steel", "binding-wire", "bwg20", "annealed"],
  }),
  p({
    sku: "CON-SCT-29-029",
    name: "Steel Beam IPE200",
    category: "construction",
    hs: "7216210000",
    price: 650,
    coa: [
      ["Profile", "IPE 200"],
      ["Height (h)", "200 mm"],
      ["Flange Width (b)", "100 mm"],
      ["Web Thickness (tw)", "5.6 mm"],
      ["Flange Thickness (tf)", "8.5 mm"],
      ["Weight per Meter", "22.4 kg/m"],
      ["Length", "12 m standard"],
      ["Grade", "S235JR / A36"],
      ["Yield Strength", "235 MPa Min"],
      ["Tensile Strength", "360-510 MPa"],
    ],
    spec: "ORIGIN: Turkey / China / India / UAE. PACKAGING: Bundles of 4-6 beams (1-2MT) tied with steel wire on wooden skids; bulk vessel possible. CERTIFICATIONS: EN 10025-2 / ASTM A36, ISO 9001, mill test certificate (EN 10204 3.1/3.2), CE marking. QUALITY: Hot-rolled IPE 200 beam for structural steelwork. HANDLING: Store on hard standing off ground; protect from excessive moisture to prevent surface rust. No defined shelf life. Tag bundle with heat number.",
    shelfLife: null,
    cap20: CAP_STEEL_20, cap40: CAP_STEEL_40,
    tags: ["steel", "beam", "ipe200", "structural"],
  }),
  p({
    sku: "CON-SCT-30-030",
    name: "Steel Channel UPN200",
    category: "construction",
    hs: "7216210000",
    price: 670,
    coa: [
      ["Profile", "UPN 200"],
      ["Height (h)", "200 mm"],
      ["Flange Width (b)", "75 mm"],
      ["Web Thickness (tw)", "8.0 mm"],
      ["Flange Thickness (tf)", "11.0 mm"],
      ["Weight per Meter", "25.3 kg/m"],
      ["Length", "12 m standard"],
      ["Grade", "S235JR / A36"],
      ["Yield Strength", "235 MPa Min"],
      ["Tensile Strength", "360-510 MPa"],
    ],
    spec: "ORIGIN: Turkey / China / India / UAE. PACKAGING: Bundles of 4-6 channels (1-2MT) tied with steel wire on wooden skids; bulk vessel possible. CERTIFICATIONS: EN 10025-2 / ASTM A36, ISO 9001, mill test certificate (EN 10204 3.1/3.2), CE marking. QUALITY: Hot-rolled UPN 200 channel for structural steelwork. HANDLING: Store on hard standing off ground; protect from excessive moisture. No defined shelf life. Tag bundle with heat number.",
    shelfLife: null,
    cap20: CAP_STEEL_20, cap40: CAP_STEEL_40,
    tags: ["steel", "channel", "upn200", "structural"],
  }),

  // ============ BRK — Bricks/blocks (4) ============
  p({
    sku: "CON-BRK-31-031",
    name: "Clay Bricks Solid 230x110x75",
    category: "construction",
    hs: "6904100000",
    price: 0.25,
    unit: "piece",
    stock: 200000,
    coa: [
      ["Dimensions", "230 x 110 x 75 mm"],
      ["Type", "Solid clay brick"],
      ["Compressive Strength", "10-20 MPa"],
      ["Water Absorption", "15-20%"],
      ["Density", "1.6-1.9 t/m3"],
      ["Firing Temperature", "900-1100C"],
      ["Cold Crushing Strength", "10 MPa Min"],
      ["Efflorescence", "Slight / Nil"],
      ["Color", "Red"],
      ["Pieces per m2 (single wall)", "55"],
    ],
    spec: "ORIGIN: India / Vietnam / Bangladesh / Egypt. PACKAGING: Wooden pallets of 500 pieces wrapped with stretch film and strapped (approx 1.5MT/pallet); bulk vessel possible. CERTIFICATIONS: IS 1077 / EN 771-1, ISO 9001, test certificate. QUALITY: Solid fired clay bricks for masonry walls. HANDLING: Store on level ground covered with tarpaulin; protect from heavy rain. No defined shelf life. Stack max 5 pallets high.",
    shelfLife: null,
    cap20: CAP_BRICK_20, cap40: CAP_BRICK_40,
    tags: ["brick", "clay", "solid", "masonry"],
  }),
  p({
    sku: "CON-BRK-32-032",
    name: "Fly Ash Bricks",
    category: "construction",
    hs: "6905100000",
    price: 0.20,
    unit: "piece",
    stock: 200000,
    coa: [
      ["Dimensions", "230 x 110 x 75 mm"],
      ["Type", "Fly ash brick (cement-flyash-lime)"],
      ["Compressive Strength", "7.5-12.5 MPa"],
      ["Water Absorption", "12-18%"],
      ["Density", "1.5-1.7 t/m3"],
      ["Fly Ash Content", "30-50%"],
      ["Cold Crushing Strength", "7.5 MPa Min"],
      ["Efflorescence", "Nil"],
      ["Color", "Grey"],
      ["Pieces per m2 (single wall)", "55"],
    ],
    spec: "ORIGIN: India / China / Indonesia. PACKAGING: Wooden pallets of 500 pieces wrapped with stretch film and strapped (approx 1.2MT/pallet). CERTIFICATIONS: IS 12894 / EN 771-3, ISO 9001, test certificate. QUALITY: Eco-friendly fly ash bricks — uniform size and low water absorption. HANDLING: Store on level ground covered with tarpaulin. No defined shelf life. Stack max 5 pallets high.",
    shelfLife: null,
    cap20: CAP_BRICK_20, cap40: CAP_BRICK_40,
    tags: ["brick", "fly-ash", "eco", "masonry"],
  }),
  p({
    sku: "CON-BRK-33-033",
    name: "AAC Blocks 600x200x200",
    category: "construction",
    hs: "6810910000",
    price: 175,
    unit: "m3",
    stock: 5000,
    coa: [
      ["Dimensions", "600 x 200 x 200 mm"],
      ["Type", "Autoclaved Aerated Concrete (AAC)"],
      ["Compressive Strength", "3.0-5.0 MPa"],
      ["Dry Density", "500-700 kg/m3"],
      ["Thermal Conductivity", "0.15-0.20 W/mK"],
      ["Drying Shrinkage", "0.5 mm/m Max"],
      ["Sound Insulation", "40-45 dB"],
      ["Fire Rating", "2-6 hours"],
      ["Yield", "67 pieces/m3"],
      ["Tolerance", "+/- 2 mm"],
    ],
    spec: "ORIGIN: India / China / Turkey / UAE. PACKAGING: Strapped bundles of 30-40 blocks on wooden pallets wrapped with stretch film (approx 1.5-2MT/bundle). CERTIFICATIONS: EN 771-4 / IS 2185 Part 3, ISO 9001, test certificate, fire rating cert. QUALITY: Lightweight AAC blocks for non-load-bearing walls — excellent thermal & sound insulation. HANDLING: Store on level ground, protect from rain; handle carefully (brittle). No defined shelf life. Stack max 3 bundles high.",
    shelfLife: null,
    cap20: CAP_BRICK_20, cap40: CAP_BRICK_40,
    tags: ["aac", "block", "lightweight", "thermal-insulation"],
  }),
  p({
    sku: "CON-BRK-34-034",
    name: "Concrete Hollow Blocks",
    category: "construction",
    hs: "6810910000",
    price: 0.40,
    unit: "piece",
    stock: 100000,
    coa: [
      ["Dimensions", "400 x 200 x 200 mm"],
      ["Type", "Hollow concrete block"],
      ["Compressive Strength", "5-10 MPa"],
      ["Dry Density", "1.2-1.6 t/m3"],
      ["Hollow Ratio", "50-55%"],
      ["Water Absorption", "10% Max"],
      ["Cement Content", "10-15%"],
      ["Aggregate", "Sand + 10mm crushed"],
      ["Pieces per m2 (single wall)", "12.5"],
      ["Curing", "7 days water cure"],
    ],
    spec: "ORIGIN: India / Vietnam / Saudi Arabia / UAE. PACKAGING: Strapped bundles of 100-150 blocks on wooden pallets (approx 1.5-2MT/pallet). CERTIFICATIONS: IS 2185 Part 1 / EN 771-3 / ASTM C90, ISO 9001, test certificate. QUALITY: Concrete hollow blocks for load-bearing and non-load-bearing masonry walls. HANDLING: Store on level ground, protect from heavy rain. No defined shelf life. Stack max 4 pallets high.",
    shelfLife: null,
    cap20: CAP_BRICK_20, cap40: CAP_BRICK_40,
    tags: ["concrete", "block", "hollow", "masonry"],
  }),

  // ============ TIL — Tiles (3) ============
  p({
    sku: "CON-TIL-35-035",
    name: "Ceramic Floor Tiles 600x600",
    category: "construction",
    hs: "6907210000",
    price: 4.5,
    unit: "m2",
    stock: 50000,
    coa: [
      ["Size", "600 x 600 mm"],
      ["Type", "Glazed ceramic floor tile"],
      ["Thickness", "9-10 mm"],
      ["Water Absorption", "0.5-3.0%"],
      ["PEI Rating", "Class III-IV"],
      ["Breaking Strength", "1000 N Min"],
      ["Mohs Hardness", "5-6"],
      ["Slip Rating", "R9-R10"],
      ["Pieces per m2", "2.78"],
      ["Pieces per Carton", "4"],
      ["Shade Variation", "V2"],
    ],
    spec: "ORIGIN: China / India / Spain / Vietnam. PACKAGING: Cartons of 4 tiles (1.44 m2) strapped on wooden pallets (approx 1.2MT/pallet, ~50 cartons). CERTIFICATIONS: ISO 13006 / EN 14411 Group BIIa, ISO 9001, CE marking, test report. QUALITY: Glazed ceramic floor tiles for residential & light commercial flooring. HANDLING: Store in original cartons on flat ground, protect from impact and moisture. No defined shelf life. Stack max 3 pallets high.",
    shelfLife: null,
    cap20: CAP_TILE_20, cap40: CAP_TILE_40,
    tags: ["tile", "ceramic", "floor", "glazed"],
  }),
  p({
    sku: "CON-TIL-36-036",
    name: "Porcelain Tiles 600x600 Polished",
    category: "construction",
    hs: "6907210000",
    price: 7.0,
    unit: "m2",
    stock: 50000,
    coa: [
      ["Size", "600 x 600 mm"],
      ["Type", "Polished porcelain tile"],
      ["Thickness", "9-10 mm"],
      ["Water Absorption", "<0.5%"],
      ["PEI Rating", "Class IV-V"],
      ["Breaking Strength", "1300 N Min"],
      ["Mohs Hardness", "6-7"],
      ["Slip Rating", "R9"],
      ["Pieces per m2", "2.78"],
      ["Pieces per Carton", "4"],
      ["Surface", "Polished (mirror)"],
    ],
    spec: "ORIGIN: China / India / Italy / Spain. PACKAGING: Cartons of 4 tiles (1.44 m2) strapped on wooden pallets (approx 1.3MT/pallet, ~50 cartons). CERTIFICATIONS: ISO 13006 / EN 14411 Group BIa, ISO 9001, CE marking, test report. QUALITY: Polished porcelain tiles for high-traffic commercial & residential flooring. HANDLING: Store in original cartons on flat ground, protect from impact. No defined shelf life. Stack max 3 pallets high.",
    shelfLife: null,
    cap20: CAP_TILE_20, cap40: CAP_TILE_40,
    tags: ["tile", "porcelain", "polished", "floor"],
  }),
  p({
    sku: "CON-TIL-37-037",
    name: "Vitrified Tiles 600x600 Double Charge",
    category: "construction",
    hs: "6907230000",
    price: 8.5,
    unit: "m2",
    stock: 50000,
    coa: [
      ["Size", "600 x 600 mm"],
      ["Type", "Double charged vitrified tile"],
      ["Thickness", "10-12 mm"],
      ["Water Absorption", "<0.05%"],
      ["PEI Rating", "Class V"],
      ["Breaking Strength", "1500 N Min"],
      ["Mohs Hardness", "7-8"],
      ["Slip Rating", "R9"],
      ["Pieces per m2", "2.78"],
      ["Pieces per Carton", "4"],
      ["Surface", "Polished"],
    ],
    spec: "ORIGIN: India (Morbi) / China. PACKAGING: Cartons of 4 tiles (1.44 m2) strapped on wooden pallets (approx 1.4MT/pallet, ~50 cartons). CERTIFICATIONS: ISO 13006 / EN 14411 Group BIa, ISO 9001, CE marking, test report. QUALITY: Double-charged vitrified tiles — through-body color, very high durability for commercial floors. HANDLING: Store in original cartons on flat ground. No defined shelf life. Stack max 3 pallets high.",
    shelfLife: null,
    cap20: CAP_TILE_20, cap40: CAP_TILE_40,
    tags: ["tile", "vitrified", "double-charge", "commercial"],
  }),

  // ============ GLS — Glass (3) ============
  p({
    sku: "CON-GLS-38-038",
    name: "Clear Float Glass 4mm",
    category: "construction",
    hs: "7005210000",
    price: 3.0,
    unit: "m2",
    stock: 30000,
    coa: [
      ["Thickness", "4 mm"],
      ["Type", "Clear float glass"],
      ["Light Transmission", "89% Min"],
      ["Visible Light Reflectance", "8%"],
      ["Edge Quality", "Smooth ground"],
      ["Thickness Tolerance", "+/- 0.2 mm"],
      ["Size Tolerance", "+/- 1.5 mm"],
      ["Color", "Clear"],
      ["Standard", "EN 572-2 / ASTM C1036"],
      ["Edge Work", "Polished (optional)"],
    ],
    spec: "ORIGIN: China / UAE / Egypt / India. PACKAGING: Wooden crates of 25-50 m2 strapped with steel bands on pallets (approx 0.6-1.2MT/crate); loose sheets in A-frame stillage. CERTIFICATIONS: EN 572-2 / ASTM C1036, ISO 9001, CE marking. QUALITY: Clear float glass for windows, mirrors, and further processing (tempering, laminating). HANDLING: Store in dry covered area, vertical on A-frame; protect edges from impact. No defined shelf life. Stack max 2 crates high.",
    shelfLife: null,
    cap20: CAP_GLASS_20, cap40: CAP_GLASS_40,
    tags: ["glass", "float", "clear", "4mm"],
  }),
  p({
    sku: "CON-GLS-39-039",
    name: "Clear Float Glass 6mm",
    category: "construction",
    hs: "7005210000",
    price: 4.0,
    unit: "m2",
    stock: 30000,
    coa: [
      ["Thickness", "6 mm"],
      ["Type", "Clear float glass"],
      ["Light Transmission", "88% Min"],
      ["Visible Light Reflectance", "8%"],
      ["Edge Quality", "Smooth ground"],
      ["Thickness Tolerance", "+/- 0.2 mm"],
      ["Size Tolerance", "+/- 1.5 mm"],
      ["Color", "Clear"],
      ["Standard", "EN 572-2 / ASTM C1036"],
      ["Edge Work", "Polished (optional)"],
    ],
    spec: "ORIGIN: China / UAE / Egypt / India. PACKAGING: Wooden crates of 20-40 m2 strapped with steel bands on pallets (approx 0.8-1.2MT/crate); loose sheets in A-frame stillage. CERTIFICATIONS: EN 572-2 / ASTM C1036, ISO 9001, CE marking. QUALITY: Clear float glass 6mm for windows, doors, and further processing (tempering, laminating). HANDLING: Store in dry covered area, vertical on A-frame; protect edges from impact. No defined shelf life. Stack max 2 crates high.",
    shelfLife: null,
    cap20: CAP_GLASS_20, cap40: CAP_GLASS_40,
    tags: ["glass", "float", "clear", "6mm"],
  }),
  p({
    sku: "CON-GLS-40-040",
    name: "Reflective Glass 6mm",
    category: "construction",
    hs: "7005290000",
    price: 6.5,
    unit: "m2",
    stock: 30000,
    coa: [
      ["Thickness", "6 mm"],
      ["Type", "Pyrolytic reflective (online coated)"],
      ["Light Transmission", "8-20%"],
      ["Visible Light Reflectance", "30-40%"],
      ["Solar Heat Gain Coefficient (SHGC)", "0.30-0.50"],
      ["Shading Coefficient (SC)", "0.35-0.55"],
      ["U-Value", "5.6 W/m2K"],
      ["Edge Quality", "Smooth ground"],
      ["Color", "Silver / Bronze / Blue"],
      ["Standard", "EN 1096 / ASTM C1376"],
    ],
    spec: "ORIGIN: China / UAE / Egypt / France (Saint-Gobain). PACKAGING: Wooden crates of 20-30 m2 strapped with steel bands on pallets (approx 0.9-1.2MT/crate). CERTIFICATIONS: EN 1096 / ASTM C1376, ISO 9001, CE marking. QUALITY: Pyrolytic online-coated reflective glass for solar control & facade aesthetics. HANDLING: Store in dry covered area, vertical on A-frame; protect coated surface & edges. No defined shelf life. Stack max 2 crates high.",
    shelfLife: null,
    cap20: CAP_GLASS_20, cap40: CAP_GLASS_40,
    tags: ["glass", "reflective", "solar-control", "facade"],
  }),

  // ============ INS — Insulation (3) ============
  p({
    sku: "CON-INS-41-041",
    name: "Glass Wool Rolls 50mm",
    category: "construction",
    hs: "7019900000",
    price: 2.2,
    unit: "m2",
    stock: 40000,
    coa: [
      ["Material", "Glass wool (borosilicate)"],
      ["Thickness", "50 mm"],
      ["Density", "12-16 kg/m3"],
      ["Thermal Conductivity (λ)", "0.040 W/mK Max"],
      ["Roll Width", "1200 mm"],
      ["Roll Length", "10-20 m"],
      ["Service Temperature", "-30C to +230C"],
      ["Fire Rating", "A1 (non-combustible)"],
      ["Sound Absorption (NRC)", "0.85-0.95"],
      ["Facing", "Unfaced / FSK / Black"],
    ],
    spec: "ORIGIN: China / India / Turkey / UAE. PACKAGING: Compressed rolls in polythene bags, 12-24 rolls per pallet (approx 0.8-1.2MT/pallet). CERTIFICATIONS: EN 13162 / ASTM C665, ISO 9001, CE marking, fire classification report, low-VOC. QUALITY: Glass wool rolls for thermal & acoustic insulation of roofs, ceilings, and HVAC ducts. HANDLING: Store in original sealed packaging, dry; protect from moisture. Shelf life 24 months in original packaging. Stack max 3 pallets high.",
    shelfLife: INS_SHELF,
    cap20: CAP_TILE_20, cap40: CAP_TILE_40,
    tags: ["insulation", "glass-wool", "thermal", "acoustic"],
  }),
  p({
    sku: "CON-INS-42-042",
    name: "XPS Foam Boards 50mm",
    category: "construction",
    hs: "3921900000",
    price: 4.5,
    unit: "m2",
    stock: 40000,
    coa: [
      ["Material", "Extruded Polystyrene (XPS)"],
      ["Thickness", "50 mm"],
      ["Density", "30-35 kg/m3"],
      ["Thermal Conductivity (λ)", "0.034 W/mK Max"],
      ["Compressive Strength", "200-300 kPa"],
      ["Water Absorption (long-term)", "1.5% Max"],
      ["Board Size", "1200 x 600 mm"],
      ["Service Temperature", "-50C to +75C"],
      ["Fire Rating", "B2 / Class E"],
      ["Edge", "Shiplap / Square"],
    ],
    spec: "ORIGIN: China / Turkey / UAE / India. PACKAGING: Stacked boards strapped on pallets wrapped with shrink film (approx 0.6-1MT/pallet, ~50 boards). CERTIFICATIONS: EN 13164 / ASTM C578, ISO 9001, CE marking, fire classification report. QUALITY: XPS foam boards for inverted roofs, floors, and below-grade insulation. HANDLING: Store in original packaging, dry; protect from UV and fire. Shelf life 24 months in original packaging. Stack max 4 pallets high.",
    shelfLife: INS_SHELF,
    cap20: CAP_TILE_20, cap40: CAP_TILE_40,
    tags: ["insulation", "xps", "foam", "thermal", "compressive"],
  }),
  p({
    sku: "CON-INS-43-043",
    name: "Rockwool Panels 50mm",
    category: "construction",
    hs: "6806100000",
    price: 4.0,
    unit: "m2",
    stock: 40000,
    coa: [
      ["Material", "Stone wool (rockwool)"],
      ["Thickness", "50 mm"],
      ["Density", "60-100 kg/m3"],
      ["Thermal Conductivity (λ)", "0.040 W/mK Max"],
      ["Maximum Service Temperature", "750C"],
      ["Fire Rating", "A1 (non-combustible)"],
      ["Water Repellency", ">98%"],
      ["Sound Absorption (NRC)", "0.90-1.00"],
      ["Panel Size", "1200 x 600 mm"],
      ["Facing", "Unfaced / FSK / Wire mesh"],
    ],
    spec: "ORIGIN: China / Turkey / UAE / India. PACKAGING: Stacked panels in cartons or shrink-wrapped on pallets (approx 0.8-1.2MT/pallet, ~40 panels). CERTIFICATIONS: EN 13162 / ASTM C612, ISO 9001, CE marking, fire classification A1 report. QUALITY: Rockwool panels for high-temperature insulation, fire protection, and acoustic walls. HANDLING: Store in original packaging, dry; protect from moisture. Shelf life 24 months in original packaging. Stack max 3 pallets high.",
    shelfLife: INS_SHELF,
    cap20: CAP_TILE_20, cap40: CAP_TILE_40,
    tags: ["insulation", "rockwool", "fire-rated", "acoustic"],
  }),
];
