// Aspidus DMCC — Spices catalog (30 products)
// Category: "spices"
// SKU format: SPI-TYPE-NN-NNN (PEP/CIN/CRD/CLV/NUT/GIN/TUR/CUM/COR/XSP)

export interface CoaParam { name: string; value: string; }
export interface Logistics { cap20: number | null; cap40: number | null; }
export interface SeedProduct {
  sku: string; name: string; category: string; unit: string;
  price: number; currency: string; cost: number;
  stock: number; reorder_level: number; active: boolean;
  description: string; hs_code: string;
  brand: null; shelf_life: string | null; image_url: null;
  logistics: Logistics; coa_params: CoaParam[];
  detailed_spec: string; tags: string[];
}

function p(o: {
  sku: string; name: string; category: string;
  hs: string; price: number; unit?: string;
  coa: [string, string][]; spec: string;
  cap20?: number | null; cap40?: number | null;
  tags?: string[]; shelfLife?: string | null;
  desc?: string; stock?: number;
}): SeedProduct {
  const unit = o.unit ?? "MT";
  const stock = o.stock ?? 20000;
  return {
    sku: o.sku, name: o.name, category: o.category, unit,
    price: o.price, currency: "USD", cost: o.price, stock,
    reorder_level: Math.max(1, Math.floor(stock / 20)),
    active: true, description: o.desc ?? o.name,
    hs_code: o.hs, brand: null,
    shelf_life: o.shelfLife ?? null, image_url: null,
    logistics: { cap20: o.cap20 ?? null, cap40: o.cap40 ?? null },
    coa_params: o.coa.map(([name, value]) => ({ name, value })),
    detailed_spec: o.spec, tags: o.tags ?? [],
  };
}

const SPEC_SHELF = "24 months from harvest under proper storage";
const MT_BAGS_CAP20 = 19000;
const MT_BAGS_CAP40 = 26000;

export const spiceProducts: SeedProduct[] = [
  // ============ PEP — Pepper (4) ============
  p({
    sku: "SPI-PEP-01-001",
    name: "Black Pepper MG1",
    category: "spices",
    hs: "0904110000",
    price: 6800,
    coa: [
      ["Density (Test Weight)", "570-600 g/l Min"],
      ["Moisture", "11.0% Max"],
      ["Light Berries", "2.0% Max"],
      ["Pinheads", "1.0% Max"],
      ["Broken", "2.0% Max"],
      ["Foreign Matter", "0.5% Max"],
      ["Black & Slightly Black", "3.0% Max"],
      ["Mold", "0.5% Max"],
      ["Insect Damage", "1.0% Max"],
      ["Piperine Content", "5.0% Min"],
      ["Volatile Oil", "2.0% Min"],
    ],
    spec: "ORIGIN: Vietnam (Lam Dong / Dak Lak). PACKAGING: 25kg multi-wall paper bags with PE inner liner or 50kg PP bags; vacuum packs available for premium grades. CERTIFICATIONS: Phytosanitary Certificate (Vietnam PPD), Certificate of Origin (VCCI), HACCP/ISO 22000, FDA registration, SGS/Intertek inspection, Pesticide residue report. QUALITY: Per ASTA cleanliness specifications. HANDLING: Store in cool (15-20C), dry (<65% RH), dark conditions; avoid moisture absorption and pest infestation. Shelf life 24 months from harvest under proper storage. Fumigation per ISPM-15.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["pepper", "mg1", "vietnam", "astA-clean"],
  }),
  p({
    sku: "SPI-PEP-02-002",
    name: "Black Pepper TGSEB (Trieur Garbled Special Extra Bold)",
    category: "spices",
    hs: "0904110000",
    price: 7800,
    coa: [
      ["Density (Test Weight)", "600-630 g/l Min"],
      ["Moisture", "11.0% Max"],
      ["Light Berries", "1.0% Max"],
      ["Pinheads", "0.5% Max"],
      ["Broken", "1.5% Max"],
      ["Foreign Matter", "0.3% Max"],
      ["Black & Slightly Black", "2.0% Max"],
      ["Mold", "0.3% Max"],
      ["Insect Damage", "0.5% Max"],
      ["Piperine Content", "5.5% Min"],
      ["Volatile Oil", "2.5% Min"],
      ["Grade", "TGSEB (Bold)"],
    ],
    spec: "ORIGIN: Vietnam (Dak Lak / Chu Se). PACKAGING: 25kg multi-wall paper bags with PE inner liner, vacuum-sealed cartons available for premium buyers. CERTIFICATIONS: Phytosanitary Certificate (Vietnam PPD), Certificate of Origin (VCCI), HACCP/ISO 22000, FDA registration, SGS/Intertek inspection. QUALITY: TGSEB = Trieur Garbled Special Extra Bold — the premium bold grade for food industry and spice blending. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest under proper storage. Fumigation per ISPM-15.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["pepper", "tgseb", "bold", "vietnam", "premium"],
  }),
  p({
    sku: "SPI-PEP-03-003",
    name: "White Pepper ASTA",
    category: "spices",
    hs: "0904110000",
    price: 8800,
    coa: [
      ["Color", "Off-white to light grey"],
      ["Density (Test Weight)", "600-640 g/l Min"],
      ["Moisture", "12.0% Max"],
      ["Broken", "2.0% Max"],
      ["Foreign Matter", "0.3% Max"],
      ["Black Specks", "1.0% Max"],
      ["Mold", "0.5% Max"],
      ["Insect Damage", "0.5% Max"],
      ["Piperine Content", "5.0% Min"],
      ["Volatile Oil", "1.8% Min"],
      ["Process", "Water-retted, mechanically decorticated"],
    ],
    spec: "ORIGIN: Vietnam (Binh Phuoc / Dak Lak). PACKAGING: 25kg multi-wall paper bags with PE inner liner or 50kg PP bags. CERTIFICATIONS: Phytosanitary Certificate (Vietnam PPD), Certificate of Origin (VCCI), HACCP/ISO 22000, FDA registration, SGS/Intertek inspection. QUALITY: Water-retted and mechanically decorticated; ASTA cleanliness compliance. HANDLING: Store cool (15-20C), dry (<65% RH), dark; protect from sunlight to prevent discoloration. Shelf life 24 months from harvest. Fumigation per ISPM-15.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["pepper", "white", "asta", "vietnam"],
  }),
  p({
    sku: "SPI-PEP-04-004",
    name: "Black Pepper 500 g/l",
    category: "spices",
    hs: "0904110000",
    price: 5500,
    coa: [
      ["Density (Test Weight)", "500-530 g/l"],
      ["Moisture", "12.0% Max"],
      ["Light Berries", "4.0% Max"],
      ["Pinheads", "2.0% Max"],
      ["Broken", "3.0% Max"],
      ["Foreign Matter", "1.0% Max"],
      ["Black & Slightly Black", "5.0% Max"],
      ["Mold", "1.0% Max"],
      ["Insect Damage", "1.5% Max"],
      ["Piperine Content", "4.5% Min"],
      ["Volatile Oil", "1.5% Min"],
      ["Grade", "Standard 500 g/l (FAQ)"],
    ],
    spec: "ORIGIN: Vietnam / Indonesia / Brazil. PACKAGING: 50kg PP woven bags or 25kg multi-wall paper bags with PE liner. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection. QUALITY: Standard FAQ grade suitable for grinding, extraction, and industrial blending. HANDLING: Store in cool, dry (<65% RH), dark conditions; avoid moisture and pest infestation. Shelf life 24 months from harvest under proper storage. Fumigation per ISPM-15.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["pepper", "500gl", "faq", "industrial"],
  }),

  // ============ CIN — Cinnamon (3) ============
  p({
    sku: "SPI-CIN-05-005",
    name: "Ceylon Cinnamon Quills Grade Alba",
    category: "spices",
    hs: "0906110000",
    price: 16500,
    coa: [
      ["Diameter", "6-10 mm"],
      ["Quill Length", "1067 mm (42 inch)"],
      ["Moisture", "12.0% Max"],
      ["Volatile Oil", "1.5% Min"],
      ["Coumarin Content", "0.005% Max (true Ceylon)"],
      ["Foreign Matter", "0.5% Max"],
      ["Extraneous Bark", "1.0% Max"],
      ["Appearance", "Pale yellow-brown"],
      ["Grade", "Alba (finest)"],
    ],
    spec: "ORIGIN: Sri Lanka (Southern Province / Mathara / Galle). PACKAGING: 25kg multi-wall paper bags with PE inner liner or 20kg compact cartons for premium quills. CERTIFICATIONS: Phytosanitary Certificate (Sri Lanka DAP), Certificate of Origin (CCSL), HACCP/ISO 22000, FDA registration, SGS/Intertek inspection, Coumarin analysis report (<0.005%). QUALITY: True Cinnamomum verum — Alba is the finest quill grade (6-10mm diameter). HANDLING: Store cool (15-20C), dry (<65% RH); protect from breakage. Shelf life 24 months from harvest.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["cinnamon", "ceylon", "alba", "premium", "low-coumarin"],
  }),
  p({
    sku: "SPI-CIN-06-006",
    name: "Cassia Hark (Broken)",
    category: "spices",
    hs: "0906190000",
    price: 3000,
    coa: [
      ["Type", "Cassia (Cinnamomum cassia) Broken"],
      ["Length", "2-8 cm pieces"],
      ["Thickness", "1-3 mm"],
      ["Moisture", "13.0% Max"],
      ["Volatile Oil", "1.5% Min"],
      ["Coumarin Content", "1.0-3.0% (typical cassia)"],
      ["Foreign Matter", "1.0% Max"],
      ["Mold", "1.0% Max"],
      ["Insect Damage", "1.0% Max"],
      ["Color", "Reddish-brown"],
    ],
    spec: "ORIGIN: Indonesia (Kerinci / Sumatra) / Vietnam (Yen Bai). PACKAGING: 25kg multi-wall paper bags with PE inner liner or 50kg PP woven bags. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection. QUALITY: Broken cassia bark pieces, ideal for grinding and oleoresin extraction. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest. Fumigation per ISPM-15.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["cassia", "broken", "indonesia", "grinding-grade"],
  }),
  p({
    sku: "SPI-CIN-07-007",
    name: "Cassia Whole Sticks 5-10cm",
    category: "spices",
    hs: "0906190000",
    price: 3500,
    coa: [
      ["Type", "Cassia (Cinnamomum cassia) Whole"],
      ["Length", "5-10 cm"],
      ["Diameter", "10-25 mm"],
      ["Thickness", "1.5-3 mm"],
      ["Moisture", "13.0% Max"],
      ["Volatile Oil", "1.5% Min"],
      ["Coumarin Content", "1.0-3.0% (typical cassia)"],
      ["Foreign Matter", "1.0% Max"],
      ["Mold", "1.0% Max"],
      ["Color", "Reddish-brown"],
    ],
    spec: "ORIGIN: Indonesia (Kerinci / Sumatra) / Vietnam. PACKAGING: 25kg multi-wall paper bags with PE inner liner or 20kg compact cartons. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection. QUALITY: Whole cassia sticks 5-10cm, cut to uniform length for retail packing and foodservice. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest. Fumigation per ISPM-15.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["cassia", "whole-sticks", "indonesia", "retail-grade"],
  }),

  // ============ CRD — Cardamom (3) ============
  p({
    sku: "SPI-CRD-08-008",
    name: "Green Cardamom AGS-1 (8mm Bold)",
    category: "spices",
    hs: "0908310000",
    price: 11500,
    coa: [
      ["Size", "8mm+ Bold"],
      ["Color", "Bright Green"],
      ["Moisture", "12.0% Max"],
      ["Volatile Oil", "7.0% Min"],
      ["Split/Mouth-open", "3.0% Max"],
      ["Immature/Empty", "2.0% Max"],
      ["Foreign Matter", "0.5% Max"],
      ["Insect Damage", "0.5% Max"],
      ["1,8-Cineole", "30-40%"],
      ["Alpha-Terpinyl Acetate", "35-45%"],
    ],
    spec: "ORIGIN: Guatemala (Alta Verapaz) / India (Idukki, Kerala). PACKAGING: 25kg multi-wall paper bags with PE inner liner or 10kg vacuum-sealed cartons for premium grade. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection, Pesticide residue report. QUALITY: AGS-1 (All Grade Special-1) — 8mm+ bold bright green, premium export grade. HANDLING: Store cool (15-20C), dry (<60% RH), dark; protect from sunlight to preserve color. Shelf life 24 months from harvest.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["cardamom", "ags-1", "bold", "premium", "guatemala"],
  }),
  p({
    sku: "SPI-CRD-09-009",
    name: "Green Cardamom AGS-2 (7mm)",
    category: "spices",
    hs: "0908310000",
    price: 9000,
    coa: [
      ["Size", "7mm+"],
      ["Color", "Bright Green"],
      ["Moisture", "12.0% Max"],
      ["Volatile Oil", "6.0% Min"],
      ["Split/Mouth-open", "5.0% Max"],
      ["Immature/Empty", "3.0% Max"],
      ["Foreign Matter", "0.5% Max"],
      ["Insect Damage", "0.5% Max"],
      ["1,8-Cineole", "28-38%"],
      ["Alpha-Terpinyl Acetate", "32-42%"],
    ],
    spec: "ORIGIN: Guatemala (Alta Verapaz) / India. PACKAGING: 25kg multi-wall paper bags with PE inner liner. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection. QUALITY: AGS-2 grade — 7mm bright green, suitable for grinding and blending. HANDLING: Store cool (15-20C), dry (<60% RH), dark; protect from sunlight to preserve color. Shelf life 24 months from harvest.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["cardamom", "ags-2", "guatemala", "industrial"],
  }),
  p({
    sku: "SPI-CRD-10-010",
    name: "Bleached Cardamom",
    category: "spices",
    hs: "0908310000",
    price: 8000,
    coa: [
      ["Size", "6-8mm"],
      ["Color", "Pale straw / cream (bleached)"],
      ["Moisture", "12.0% Max"],
      ["Volatile Oil", "5.0% Min"],
      ["Split/Mouth-open", "5.0% Max"],
      ["Immature/Empty", "3.0% Max"],
      ["Foreign Matter", "0.5% Max"],
      ["Insect Damage", "0.5% Max"],
      ["Sulfur Dioxide (SO2)", "50 mg/kg Max"],
      ["Process", "Sulfite-free bleaching available on request"],
    ],
    spec: "ORIGIN: India (Kerala / Karnataka) / Sri Lanka. PACKAGING: 25kg multi-wall paper bags with PE inner liner or 10kg cartons. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection, SO2 residue report. QUALITY: Bleached (pale color) cardamom for white-food applications and specific Middle East markets. HANDLING: Store cool (15-20C), dry (<60% RH), dark. Shelf life 24 months from harvest.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["cardamom", "bleached", "india", "white-food"],
  }),

  // ============ CLV — Cloves (2) ============
  p({
    sku: "SPI-CLV-11-011",
    name: "Cloves Grade 1 Handpicked",
    category: "spices",
    hs: "0907010000",
    price: 8000,
    coa: [
      ["Grade", "Handpicked (HP)"],
      ["Size", "14-16 mm"],
      ["Moisture", "12.0% Max"],
      ["Volatile Oil", "15.0% Min"],
      ["Eugenol Content", "70-85%"],
      ["Stems/Heads", "2.0% Max"],
      ["Foreign Matter", "0.5% Max"],
      ["Mold", "1.0% Max"],
      ["Insect Damage", "0.5% Max"],
      ["Color", "Reddish-brown, plump"],
    ],
    spec: "ORIGIN: Indonesia (Sulawesi / Moluccas) / Madagascar / Sri Lanka. PACKAGING: 25kg multi-wall paper bags with PE inner liner or 50kg PP woven bags. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection. QUALITY: Handpicked Grade 1 — plump, full-head cloves with high volatile oil. HANDLING: Store cool (15-20C), dry (<65% RH), dark; cloves are highly hygroscopic. Shelf life 24 months from harvest.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["cloves", "grade-1", "handpicked", "indonesia"],
  }),
  p({
    sku: "SPI-CLV-12-012",
    name: "Cloves Grade 2 (Stem Cloves)",
    category: "spices",
    hs: "0907010000",
    price: 4800,
    coa: [
      ["Grade", "Grade 2 / Stems"],
      ["Moisture", "12.0% Max"],
      ["Volatile Oil", "8.0% Min"],
      ["Eugenol Content", "60-70%"],
      ["Stems/Heads", "20-40%"],
      ["Foreign Matter", "2.0% Max"],
      ["Mold", "1.0% Max"],
      ["Insect Damage", "1.0% Max"],
      ["Color", "Brown"],
      ["Use", "Distillation / Extraction"],
    ],
    spec: "ORIGIN: Indonesia / Madagascar. PACKAGING: 50kg PP woven bags or 25kg multi-wall paper bags with PE inner liner. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection. QUALITY: Grade 2 / stem cloves for distillation of clove oil and eugenol extraction. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest. Suitable for industrial extraction only.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["cloves", "grade-2", "stem", "extraction"],
  }),

  // ============ NUT — Nutmeg (2) ============
  p({
    sku: "SPI-NUT-13-013",
    name: "Nutmeg With Shell BWP (Broken Without Pieces)",
    category: "spices",
    hs: "0908110000",
    price: 10000,
    coa: [
      ["Grade", "BWP (Broken Without Pieces)"],
      ["Size", "60-90 pieces/kg"],
      ["Moisture", "10.0% Max"],
      ["Volatile Oil", "8.0% Min"],
      ["Foreign Matter", "0.5% Max"],
      ["Mold", "1.0% Max"],
      ["Insect Damage", "1.0% Max"],
      ["Shrivel/Defective", "5.0% Max"],
      ["Color", "Dark brown (with shell)"],
      ["Process", "Sun-dried with shell intact"],
    ],
    spec: "ORIGIN: Indonesia (Maluku / North Sulawesi) / Sri Lanka. PACKAGING: 50kg PP woven bags or 25kg multi-wall paper bags with PE inner liner. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection. QUALITY: BWP — Broken Without Pieces with shell, ideal for distillation and grinding. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest. Aflatoxin tested on request.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["nutmeg", "bwp", "indonesia", "with-shell"],
  }),
  p({
    sku: "SPI-NUT-14-014",
    name: "Nutmeg Shelled Indonesian 80-85%",
    category: "spices",
    hs: "0908110000",
    price: 9000,
    coa: [
      ["Grade", "Shelled 80-85% Whole Sound"],
      ["Size", "110-130 pieces/kg"],
      ["Moisture", "10.0% Max"],
      ["Volatile Oil", "8.0% Min"],
      ["Whole Sound Nuts", "80-85% Min"],
      ["Broken", "5.0% Max"],
      ["Foreign Matter", "0.5% Max"],
      ["Mold", "1.0% Max"],
      ["Insect Damage", "1.0% Max"],
      ["Color", "Light brown (shelled)"],
    ],
    spec: "ORIGIN: Indonesia (Maluku / Sulawesi). PACKAGING: 25kg multi-wall paper bags with PE inner liner or 50kg PP woven bags. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection, Aflatoxin report. QUALITY: Shelled nutmeg 80-85% whole sound — premium food grade for retail grinding. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["nutmeg", "shelled", "indonesia", "premium"],
  }),

  // ============ GIN — Ginger (3) ============
  p({
    sku: "SPI-GIN-15-015",
    name: "Dried Ginger Whole",
    category: "spices",
    hs: "0910110000",
    price: 2900,
    coa: [
      ["Form", "Whole Rhizome (Sun-dried)"],
      ["Moisture", "12.0% Max"],
      ["Volatile Oil", "1.5% Min"],
      ["Oleoresin Yield", "6.0% Min"],
      ["Gingerol Content", "2.0% Min"],
      ["Foreign Matter", "1.0% Max"],
      ["Mold", "1.0% Max"],
      ["Insect Damage", "1.0% Max"],
      ["Total Ash", "8.0% Max"],
      ["Acid Insoluble Ash", "2.0% Max"],
    ],
    spec: "ORIGIN: Nigeria / India (Kerala / Karnataka) / China. PACKAGING: 50kg PP woven bags or 25kg multi-wall paper bags with PE inner liner. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection, Aflatoxin & Pesticide residue report. QUALITY: Fully sun-dried whole rhizomes, suitable for grinding and extraction. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest. Fumigation per ISPM-15.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["ginger", "whole", "dried", "nigeria"],
  }),
  p({
    sku: "SPI-GIN-16-016",
    name: "Ground Ginger",
    category: "spices",
    hs: "0910120000",
    price: 5000,
    coa: [
      ["Form", "Ground Powder"],
      ["Mesh Size", "60-80 mesh"],
      ["Moisture", "10.0% Max"],
      ["Volatile Oil", "1.2% Min"],
      ["Gingerol Content", "1.8% Min"],
      ["Total Ash", "8.0% Max"],
      ["Acid Insoluble Ash", "2.0% Max"],
      ["Foreign Matter", "0.5% Max"],
      ["Color", "Pale yellow-brown"],
      ["Bulk Density", "0.40-0.50 g/cm3"],
      ["Microbiology", "TPC <100000 cfu/g, Salmonella absent"],
    ],
    spec: "ORIGIN: India / Nigeria / China. PACKAGING: 25kg multi-wall paper bags with PE inner liner, or 20kg vacuum-sealed foil bags. CERTIFICATIONS: HACCP/ISO 22000, FDA registration, BRC, SGS/Intertek inspection, Aflatoxin & Pesticide residue report, Microbiology COA. QUALITY: Steam-sterilized ground ginger for direct food use. HANDLING: Store cool (15-20C), dry (<60% RH), dark. Shelf life 24 months from grinding. Avoid moisture and oxygen exposure.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["ginger", "ground", "powder", "steam-sterilized"],
  }),
  p({
    sku: "SPI-GIN-17-017",
    name: "Ginger Oleoresin",
    category: "spices",
    hs: "3301900000",
    price: 30000,
    coa: [
      ["Form", "Viscous dark brown oleoresin"],
      ["Solvent Residue", "Ethanol <50 ppm (or Hexane <25 ppm)"],
      ["Gingerol Content", "20.0-30.0%"],
      ["Shogaol Content", "5.0-10.0%"],
      ["Volatile Oil Content", "25-35 ml/100g"],
      ["Refractive Index", "1.510-1.530"],
      ["Heavy Metals (Pb)", "2 mg/kg Max"],
      ["Arsenic (As)", "1 mg/kg Max"],
      ["Microbiology", "TPC <10000 cfu/g, Salmonella absent"],
      ["Carrier", "None (100% pure)"],
    ],
    spec: "ORIGIN: India (Kerala). PACKAGING: 25kg HDPE jerry cans or 200kg steel drums with food-grade inner lining. CERTIFICATIONS: HACCP/ISO 22000, FDA registration, BRC, Kosher/Halal, SGS/Intertek inspection, Solvent residue report. QUALITY: Solvent-extracted ginger oleoresin standardized to 20-30% gingerols; suitable for flavor, beverage, and nutraceutical applications. HANDLING: Store cool (10-20C), dry, dark in sealed containers; avoid light and oxygen. Shelf life 36 months.",
    shelfLife: "36 months in original sealed packaging",
    cap20: 5000, cap40: 8000,
    tags: ["ginger", "oleoresin", "extract", "india"],
  }),

  // ============ TUR — Turmeric (3) ============
  p({
    sku: "SPI-TUR-18-018",
    name: "Turmeric Fingers Erode",
    category: "spices",
    hs: "0910300000",
    price: 2900,
    coa: [
      ["Grade", "Erode Finger (FAQ)"],
      ["Curcumin Content", "3.0-3.5%"],
      ["Moisture", "12.0% Max"],
      ["Volatile Oil", "2.0% Min"],
      ["Foreign Matter", "1.0% Max"],
      ["Mold", "1.0% Max"],
      ["Insect Damage", "1.0% Max"],
      ["Total Ash", "8.0% Max"],
      ["Acid Insoluble Ash", "1.5% Max"],
      ["Color", "Bright orange-yellow"],
    ],
    spec: "ORIGIN: India (Erode, Tamil Nadu). PACKAGING: 50kg PP woven bags or 25kg multi-wall paper bags with PE inner liner. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin (Erode GI), HACCP/ISO 22000, FDA registration, SGS/Intertek inspection, Aflatoxin & Pesticide residue report. QUALITY: Erode Finger — known for bright color and GI-tagged origin. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest. Fumigation per ISPM-15.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["turmeric", "erode", "fingers", "india", "gi"],
  }),
  p({
    sku: "SPI-TUR-19-019",
    name: "Turmeric Polished Nizamabad",
    category: "spices",
    hs: "0910300000",
    price: 2700,
    coa: [
      ["Grade", "Nizamabad Polished"],
      ["Curcumin Content", "2.5-3.0%"],
      ["Moisture", "12.0% Max"],
      ["Volatile Oil", "1.8% Min"],
      ["Foreign Matter", "1.0% Max"],
      ["Mold", "1.0% Max"],
      ["Insect Damage", "1.0% Max"],
      ["Total Ash", "8.0% Max"],
      ["Acid Insoluble Ash", "1.5% Max"],
      ["Color", "Deep yellow-orange"],
      ["Process", "Polished (mechanically cleaned)"],
    ],
    spec: "ORIGIN: India (Nizamabad, Telangana). PACKAGING: 50kg PP woven bags or 25kg multi-wall paper bags with PE inner liner. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection, Aflatoxin & Pesticide residue report. QUALITY: Polished Nizamabad turmeric fingers — the largest turmeric trading hub in Asia. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["turmeric", "nizamabad", "polished", "india"],
  }),
  p({
    sku: "SPI-TUR-20-020",
    name: "Ground Turmeric Curcumin 3%",
    category: "spices",
    hs: "0910300000",
    price: 5000,
    coa: [
      ["Form", "Ground Powder"],
      ["Mesh Size", "60-80 mesh"],
      ["Curcumin Content", "3.0% Min (spectrophotometric)"],
      ["Moisture", "10.0% Max"],
      ["Volatile Oil", "1.5% Min"],
      ["Total Ash", "8.0% Max"],
      ["Acid Insoluble Ash", "1.5% Max"],
      ["Foreign Matter", "0.5% Max"],
      ["Color", "Bright golden-yellow"],
      ["Bulk Density", "0.45-0.55 g/cm3"],
      ["Microbiology", "TPC <100000 cfu/g, Salmonella absent"],
      ["Lead (Pb)", "2 mg/kg Max"],
    ],
    spec: "ORIGIN: India (Erode / Nizamabad). PACKAGING: 25kg multi-wall paper bags with PE inner liner, or 20kg vacuum-sealed foil bags. CERTIFICATIONS: HACCP/ISO 22000, FDA registration, BRC, Kosher/Halal, SGS/Intertek inspection, Aflatoxin & Pesticide residue report, Microbiology COA. QUALITY: Steam-sterilized ground turmeric, standardized to 3% curcumin (UV-spectrophotometric). HANDLING: Store cool (15-20C), dry (<60% RH), dark. Shelf life 24 months from grinding.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["turmeric", "ground", "powder", "curcumin-3", "steam-sterilized"],
  }),

  // ============ CUM — Cumin (3) ============
  p({
    sku: "SPI-CUM-21-021",
    name: "Cumin Seeds Europe Quality 99% Pure",
    category: "spices",
    hs: "0909310000",
    price: 4000,
    coa: [
      ["Purity", "99.0% Min"],
      ["Moisture", "9.0% Max"],
      ["Volatile Oil", "2.5% Min"],
      ["Foreign Matter", "0.5% Max"],
      ["Other Seeds", "0.5% Max"],
      ["Mold", "1.0% Max"],
      ["Insect Damage", "0.5% Max"],
      ["Total Ash", "8.0% Max"],
      ["Acid Insoluble Ash", "1.5% Max"],
      ["Salmonella", "Absent in 25g"],
      ["Aflatoxin (B1+B2+G1+G2)", "10 ug/kg Max"],
    ],
    spec: "ORIGIN: India (Gujarat / Rajasthan) / Syria / Turkey. PACKAGING: 25kg multi-wall paper bags with PE inner liner or 50kg PP woven bags. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, BRC, SGS/Intertek inspection, Pesticide residue & Aflatoxin report. QUALITY: Europe Quality — 99% pure, steam-sterilized available. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest. Fumigation per ISPM-15.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["cumin", "europe-quality", "99-pure", "india"],
  }),
  p({
    sku: "SPI-CUM-22-022",
    name: "Cumin Seeds Singapore 98%",
    category: "spices",
    hs: "0909310000",
    price: 3100,
    coa: [
      ["Purity", "98.0% Min"],
      ["Moisture", "10.0% Max"],
      ["Volatile Oil", "2.0% Min"],
      ["Foreign Matter", "1.5% Max"],
      ["Other Seeds", "1.0% Max"],
      ["Mold", "1.0% Max"],
      ["Insect Damage", "1.0% Max"],
      ["Total Ash", "9.0% Max"],
      ["Acid Insoluble Ash", "2.0% Max"],
      ["Color", "Yellow-brown"],
    ],
    spec: "ORIGIN: India (Gujarat / Rajasthan). PACKAGING: 50kg PP woven bags or 25kg multi-wall paper bags with PE inner liner. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection. QUALITY: Singapore 98% grade — standard export quality for Asian and Middle East markets. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest. Fumigation per ISPM-15.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["cumin", "singapore", "98-pure", "india"],
  }),
  p({
    sku: "SPI-CUM-23-023",
    name: "Ground Cumin",
    category: "spices",
    hs: "0909310000",
    price: 6000,
    coa: [
      ["Form", "Ground Powder"],
      ["Mesh Size", "40-60 mesh"],
      ["Purity", "100% Cumin"],
      ["Volatile Oil", "1.8% Min"],
      ["Moisture", "10.0% Max"],
      ["Total Ash", "9.0% Max"],
      ["Acid Insoluble Ash", "1.5% Max"],
      ["Foreign Matter", "0.5% Max"],
      ["Bulk Density", "0.40-0.50 g/cm3"],
      ["Microbiology", "TPC <100000 cfu/g, Salmonella absent"],
    ],
    spec: "ORIGIN: India (Gujarat). PACKAGING: 25kg multi-wall paper bags with PE inner liner or 20kg vacuum-sealed foil bags. CERTIFICATIONS: HACCP/ISO 22000, FDA registration, BRC, Kosher/Halal, SGS/Intertek inspection, Pesticide residue & Microbiology COA. QUALITY: Steam-sterilized ground cumin powder. HANDLING: Store cool (15-20C), dry (<60% RH), dark; protect from oxidation. Shelf life 24 months from grinding.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["cumin", "ground", "powder", "steam-sterilized"],
  }),

  // ============ COR — Coriander (2) ============
  p({
    sku: "SPI-COR-24-024",
    name: "Coriander Seeds Eagle Type",
    category: "spices",
    hs: "0909210000",
    price: 950,
    coa: [
      ["Grade", "Eagle Type"],
      ["Purity", "99.0% Min"],
      ["Moisture", "9.0% Max"],
      ["Volatile Oil", "0.3% Min"],
      ["Foreign Matter", "0.5% Max"],
      ["Split/Broken", "5.0% Max"],
      ["Insect Damage", "0.5% Max"],
      ["Color", "Yellowish-brown"],
      ["Size", "3-5 mm"],
      ["Total Ash", "7.0% Max"],
    ],
    spec: "ORIGIN: India (Rajasthan / Madhya Pradesh) / Russia / Bulgaria. PACKAGING: 25kg multi-wall paper bags with PE inner liner or 50kg PP woven bags. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection, Pesticide residue report. QUALITY: Eagle Type — large, plump seeds with uniform golden-brown color. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest. Fumigation per ISPM-15.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["coriander", "eagle", "seeds", "india"],
  }),
  p({
    sku: "SPI-COR-25-025",
    name: "Split Coriander",
    category: "spices",
    hs: "0909210000",
    price: 820,
    coa: [
      ["Form", "Split / Broken halves"],
      ["Purity", "98.0% Min"],
      ["Moisture", "9.0% Max"],
      ["Volatile Oil", "0.3% Min"],
      ["Foreign Matter", "1.0% Max"],
      ["Insect Damage", "0.5% Max"],
      ["Color", "Yellowish-brown"],
      ["Size", "1-3 mm split"],
      ["Total Ash", "7.0% Max"],
      ["Process", "Mechanically split"],
    ],
    spec: "ORIGIN: India (Rajasthan / Madhya Pradesh). PACKAGING: 25kg multi-wall paper bags with PE inner liner or 50kg PP woven bags. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection. QUALITY: Mechanically split coriander halves — ideal for grinding and curry powder blending. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["coriander", "split", "india", "grinding-grade"],
  }),

  // ============ XSP — Other spices (5) ============
  p({
    sku: "SPI-XSP-26-026",
    name: "Saffron Grade 1 All-Red",
    category: "spices",
    hs: "0910200000",
    price: 18000,
    unit: "kg",
    stock: 1500,
    coa: [
      ["Category", "All-Red (Sargol)"],
      ["Coloring Strength (Crocin)", "230 Min"],
      ["Flavor (Picrocrocin)", "70 Min"],
      ["Aroma (Safranal)", "30 Min"],
      ["Moisture", "10.0% Max"],
      ["Foreign Matter", "0.1% Max"],
      ["Style/White Part", "None"],
      ["Length", "20-25 mm"],
      ["ISO 3632 Category", "Category I"],
      ["Origin", "Iran (Khorasan)"],
    ],
    spec: "ORIGIN: Iran (Khorasan Province). PACKAGING: 1g, 2g, 5g, 10g vacuum-sealed food-grade PET/foil sachets packed in 1kg master cartons; 100g/250g/500g tins available on request. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin (Iran Chamber), HACCP/ISO 22000, ISO 3632 Category I, FDA registration, SGS/Intertek inspection, lab analysis with crocin/picrocrocin/safranal values. QUALITY: Sargol (All-Red) — premium ISO 3632 Category I. HANDLING: Store cool (10-15C), dry (<40% RH), dark in sealed container. Shelf life 36 months.",
    shelfLife: "36 months in sealed packaging",
    cap20: 5000, cap40: 8000,
    tags: ["saffron", "sargol", "iran", "premium", "iso-3632"],
  }),
  p({
    sku: "SPI-XSP-27-027",
    name: "Vanilla Beans Grade A Bourbon (Madagascar)",
    category: "spices",
    hs: "0905000000",
    price: 500,
    unit: "kg",
    stock: 2000,
    coa: [
      ["Grade", "Grade A (Gourmet)"],
      ["Origin", "Madagascar (SAVA region)"],
      ["Length", "17-20 cm"],
      ["Moisture", "30-35%"],
      ["Vanillin Content", "1.8-2.5%"],
      ["Color", "Dark brown, oily"],
      ["Aroma", "Rich, sweet, classic bourbon"],
      ["Split", "5-10% Max"],
      ["Vanillin (HPLC)", "1.5% Min"],
      ["Curing", "Traditional 9-12 month Bourbon cure"],
    ],
    spec: "ORIGIN: Madagascar (SAVA region — Sambava, Antalaha, Vohemar, Andapa). PACKAGING: 1kg vacuum-sealed food-grade PVC/foil pouches packed in 10kg master cartons; 5kg tin bundles available. CERTIFICATIONS: Phytosanitary Certificate (MCC Madagascar), Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection, Vanillin HPLC report. QUALITY: Grade A gourmet beans — 17cm+, supple, oily, classic Bourbon aroma. HANDLING: Store cool (15-20C), dry (<60% RH), dark in vacuum-sealed packaging. Shelf life 36 months in vacuum. Do not freeze.",
    shelfLife: "36 months in vacuum packaging",
    cap20: 5000, cap40: 8000,
    tags: ["vanilla", "bourbon", "madagascar", "grade-a", "premium"],
  }),
  p({
    sku: "SPI-XSP-28-028",
    name: "Paprika Sweet ASTA 100",
    category: "spices",
    hs: "0904220000",
    price: 3000,
    coa: [
      ["Form", "Ground Powder"],
      ["ASTA Color Value", "100 Min"],
      ["Mesh Size", "60-80 mesh"],
      ["Moisture", "10.0% Max"],
      ["Scoville Heat (SHU)", "<100"],
      ["Total Ash", "8.0% Max"],
      ["Acid Insoluble Ash", "1.5% Max"],
      ["Foreign Matter", "0.5% Max"],
      ["Aflatoxin (Total)", "10 ug/kg Max"],
      ["Color", "Bright deep red"],
      ["Bulk Density", "0.45-0.55 g/cm3"],
    ],
    spec: "ORIGIN: Spain (Murcia / La Vera) / Peru / China. PACKAGING: 25kg multi-wall paper bags with PE inner liner or 20kg vacuum-sealed foil bags. CERTIFICATIONS: HACCP/ISO 22000, FDA registration, BRC, Kosher/Halal, SGS/Intertek inspection, Aflatoxin & Pesticide residue report, Microbiology COA. QUALITY: Sweet paprika standardized to ASTA 100 color value — sweet (non-pungent) for food coloring. HANDLING: Store cool (15-20C), dry (<60% RH), dark; protect from light to preserve color. Shelf life 24 months from grinding.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["paprika", "sweet", "asta-100", "coloring"],
  }),
  p({
    sku: "SPI-XSP-29-029",
    name: "Chili Crushed 50K SHU",
    category: "spices",
    hs: "0904210000",
    price: 2000,
    coa: [
      ["Form", "Crushed / Flakes"],
      ["Scoville Heat (SHU)", "45,000-55,000"],
      ["Capsaicin Content", "0.30-0.36%"],
      ["Mesh Size", "5-10 mm flakes"],
      ["Moisture", "10.0% Max"],
      ["Total Ash", "8.0% Max"],
      ["Acid Insoluble Ash", "1.5% Max"],
      ["Foreign Matter", "0.5% Max"],
      ["Color", "Deep red"],
      ["Aflatoxin (Total)", "10 ug/kg Max"],
    ],
    spec: "ORIGIN: India (Andhra Pradesh / Guntur) / China / Mexico. PACKAGING: 25kg multi-wall paper bags with PE inner liner or 20kg vacuum-sealed foil bags. CERTIFICATIONS: HACCP/ISO 22000, FDA registration, BRC, Kosher/Halal, SGS/Intertek inspection, Aflatoxin & Pesticide residue report, Microbiology COA. QUALITY: Crushed red chili flakes standardized to 50,000 SHU. HANDLING: Store cool (15-20C), dry (<60% RH), dark; avoid cross-contamination. Shelf life 24 months.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["chili", "crushed", "flakes", "50k-shu", "india"],
  }),
  p({
    sku: "SPI-XSP-30-030",
    name: "Fennel Seeds",
    category: "spices",
    hs: "0909500000",
    price: 1500,
    coa: [
      ["Purity", "99.0% Min"],
      ["Moisture", "9.0% Max"],
      ["Volatile Oil", "1.5% Min"],
      ["Anethole Content", "60-80%"],
      ["Foreign Matter", "0.5% Max"],
      ["Other Seeds", "0.5% Max"],
      ["Insect Damage", "0.5% Max"],
      ["Total Ash", "9.0% Max"],
      ["Acid Insoluble Ash", "1.5% Max"],
      ["Color", "Yellowish-green"],
      ["Length", "6-8 mm"],
    ],
    spec: "ORIGIN: India (Gujarat / Rajasthan) / Egypt / China. PACKAGING: 25kg multi-wall paper bags with PE inner liner or 50kg PP woven bags. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, HACCP/ISO 22000, FDA registration, SGS/Intertek inspection, Pesticide residue report. QUALITY: Greenish-yellow fennel seeds with characteristic sweet anise aroma. HANDLING: Store cool (15-20C), dry (<65% RH), dark. Shelf life 24 months from harvest. Fumigation per ISPM-15.",
    shelfLife: SPEC_SHELF,
    cap20: MT_BAGS_CAP20, cap40: MT_BAGS_CAP40,
    tags: ["fennel", "seeds", "india", "anise"],
  }),
];
