// Aspidus DMCC — Chemicals catalog (20 products)
// Categories: IND (Industrial) 6, PET (Petrochemicals) 6, AGC (Agro-chemicals) 4, WAT (Water treatment) 4
// Prices in USD per MT FOB; HS codes are 10-digit.

export interface CoaParam { name: string; value: string; }
export interface Logistics { cap20: number | null; cap40: number | null; }
export interface SeedProduct {
  sku: string; name: string; category: string; unit: string;
  price: number; currency: string; cost: number;
  stock: number; reorder_level: number; active: boolean;
  description: string; hs_code: string;
  brand: null; shelf_life: string | null; image_url: null;
  logistics: Logistics; coa_params: CoaParam[];
  detailed_spec: string; tags: string[];
}

function p(o: {
  sku: string; name: string; category: string;
  hs: string; price: number; unit?: string;
  coa: [string, string][]; spec: string;
  cap20?: number | null; cap40?: number | null;
  tags?: string[]; shelfLife?: string | null;
  desc?: string; stock?: number;
}): SeedProduct {
  const unit = o.unit ?? "MT";
  const stock = o.stock ?? 50000;
  return {
    sku: o.sku, name: o.name, category: o.category, unit,
    price: o.price, currency: "USD", cost: o.price, stock,
    reorder_level: Math.max(1, Math.floor(stock / 20)),
    active: true, description: o.desc ?? o.name,
    hs_code: o.hs, brand: null,
    shelf_life: o.shelfLife ?? null, image_url: null,
    logistics: { cap20: o.cap20 ?? null, cap40: o.cap40 ?? null },
    coa_params: o.coa.map(([name, value]) => ({ name, value })),
    detailed_spec: o.spec, tags: o.tags ?? [],
  };
}

const SHELF = "24 months under proper storage";
const BAG20 = 20000;   // 25kg bagged chemicals
const BAG40 = 24000;
const IBC20 = 14400;   // 1000L IBC liquid
const IBC40 = 19200;

export const chemicalProducts: SeedProduct[] = [
  // ============ IND (Industrial) — 6 ============
  p({
    sku: "CHE-IND-01-001",
    name: "Caustic Soda Flakes 99%",
    category: "chemicals",
    hs: "2815120000",
    price: 480,
    cap20: BAG20, cap40: BAG40,
    tags: ["industrial", "caustic-soda", "alkali"],
    shelfLife: SHELF,
    desc: "Caustic Soda Flakes 99% NaOH — chlor-alkali product for pulp, soap, and alumina.",
    coa: [
      ["NaOH Content", "99.0% Min"],
      ["Na2CO3", "0.5% Max"],
      ["NaCl", "0.02% Max"],
      ["Fe2O3", "0.002% Max"],
      ["Appearance", "White flakes"],
      ["Solubility", "109 g/100ml (20C)"],
      ["Density", "2.13 g/cm3"],
      ["Melting Point", "318C"],
      ["Pack Size", "25kg PP bags"],
      ["Moisture", "0.5% Max"],
    ],
    spec: "ORIGIN: China/India. PACKAGING: 25kg PP bags with PE inner liner on pallets (1MT) or 1000kg FIBCs. CERTIFICATIONS: ISO 9001, REACH, SDS/MSDS, COA. QUALITY: GB 209-2018 membrane grade. HANDLING: Corrosive UN 1823 class 8. Store dry, ventilated, away from acids and oxidizers. Use PPE (gloves, goggles, respirator). Hygroscopic — keep sealed. Shelf life 24 months.",
  }),
  p({
    sku: "CHE-IND-01-002",
    name: "Soda Ash Dense 99.5%",
    category: "chemicals",
    hs: "2836200000",
    price: 310,
    cap20: BAG20, cap40: BAG40,
    tags: ["industrial", "soda-ash", "alkali", "glass"],
    shelfLife: SHELF,
    desc: "Soda Ash Dense 99.5% Na2CO3 — sodium carbonate for glass, detergents, and chemicals.",
    coa: [
      ["Na2CO3 Content", "99.5% Min"],
      ["NaCl", "0.4% Max"],
      ["Fe2O3", "0.004% Max"],
      ["Insolubles in Water", "0.04% Max"],
      ["Bulk Density", "0.95-1.05 g/ml"],
      ["Particle Size (0.1-0.85mm)", "90% Min"],
      ["Appearance", "White granular"],
      ["Moisture", "0.1% Max"],
      ["Sulfate (SO4)", "0.03% Max"],
      ["Loss on Heating", "0.5% Max"],
    ],
    spec: "ORIGIN: China/Turkey. PACKAGING: 25kg/50kg PP bags with PE inner liner on pallets or 1000kg FIBCs. CERTIFICATIONS: ISO 9001, REACH registration, SDS, COA. QUALITY: GB 210-2018 dense grade. HANDLING: Non-hazardous but mild irritant. Store dry under cover; hygroscopic. Avoid acids (releases CO2). Use dust mask in confined spaces. Shelf life 24 months sealed.",
  }),
  p({
    sku: "CHE-IND-01-003",
    name: "Sulfuric Acid 98%",
    category: "chemicals",
    hs: "2807000000",
    price: 100,
    cap20: IBC20, cap40: IBC40,
    tags: ["industrial", "acid", "inorganic"],
    shelfLife: SHELF,
    desc: "Sulfuric Acid 98% H2SO4 — king of chemicals for fertilizer, refinery, and battery use.",
    coa: [
      ["H2SO4 Content", "98.0% Min"],
      ["Free SO3", "0.2% Max"],
      ["Iron (Fe)", "30 ppm Max"],
      ["Arsenic (As)", "1 ppm Max"],
      ["Lead (Pb)", "5 ppm Max"],
      ["Chloride (Cl)", "10 ppm Max"],
      ["Nitrogen (N)", "10 ppm Max"],
      ["Color", "Colorless to slight yellow"],
      ["Density (20C)", "1.84 g/cm3"],
      ["Boiling Point", "337C"],
    ],
    spec: "ORIGIN: China/India. PACKAGING: 1000L IBC totes (HDPE), 250L HDPE drums, or ISO tanks. CERTIFICATIONS: ISO 9001, REACH, SDS, COA. QUALITY: GB/T 534-2014. HANDLING: Corrosive UN 1830 class 8. Store in acid-resistant tanks (lead-lined, HDPE, FRP). Always add acid to water — never reverse. Use full PPE incl. acid suit and face shield. Shelf life 24 months sealed.",
  }),
  p({
    sku: "CHE-IND-01-004",
    name: "Hydrochloric Acid 33%",
    category: "chemicals",
    hs: "2806100000",
    price: 150,
    cap20: IBC20, cap40: IBC40,
    tags: ["industrial", "acid", "inorganic"],
    shelfLife: SHELF,
    desc: "Hydrochloric Acid 33% HCl — muriatic acid for steel pickling, food, and water treatment.",
    coa: [
      ["HCl Content", "33.0% Min"],
      ["Free Chlorine (Cl2)", "0.003% Max"],
      ["Iron (Fe)", "10 ppm Max"],
      ["Sulfate (SO4)", "0.01% Max"],
      ["Arsenic (As)", "1 ppm Max"],
      ["Lead (Pb)", "5 ppm Max"],
      ["Residue on Ignition", "0.05% Max"],
      ["Color", "Colorless to pale yellow"],
      ["Density (20C)", "1.16 g/cm3"],
      ["Boiling Point", "85C"],
    ],
    spec: "ORIGIN: China/India. PACKAGING: 1000L IBC totes (HDPE), 250L HDPE drums, or rubber-lined ISO tanks. CERTIFICATIONS: ISO 9001, REACH, SDS, COA, food grade available. QUALITY: GB 320-2006. HANDLING: Corrosive UN 1789 class 8. Fumes toxic — ventilate. Store in HDPE/glass-lined tanks. Use full PPE incl. acid respirator. Shelf life 24 months sealed.",
  }),
  p({
    sku: "CHE-IND-01-005",
    name: "Nitric Acid 65%",
    category: "chemicals",
    hs: "2808000000",
    price: 285,
    cap20: IBC20, cap40: IBC40,
    tags: ["industrial", "acid", "oxidizer"],
    shelfLife: SHELF,
    desc: "Nitric Acid 65% HNO3 — strong oxidizing acid for fertilizers, explosives, and dyes.",
    coa: [
      ["HNO3 Content", "65.0% Min"],
      ["Nitrous Acid (HNO2)", "0.1% Max"],
      ["Sulfate (SO4)", "0.02% Max"],
      ["Chloride (Cl)", "5 ppm Max"],
      ["Iron (Fe)", "10 ppm Max"],
      ["Arsenic (As)", "1 ppm Max"],
      ["Heavy Metals (as Pb)", "5 ppm Max"],
      ["Residue on Ignition", "0.01% Max"],
      ["Color", "Colorless to slight yellow"],
      ["Density (20C)", "1.39 g/cm3"],
    ],
    spec: "ORIGIN: China/Germany. PACKAGING: 1000L IBC totes (HDPE with vented cap), 250L HDPE drums, or glass-lined ISO tanks. CERTIFICATIONS: ISO 9001, REACH, SDS, COA. QUALITY: GB/T 337-2011. HANDLING: Corrosive UN 2031 class 8; strong oxidizer. Releases NO2 fumes (red-brown, toxic). Store cool, ventilated, away from organics. Use full PPE. Shelf life 12 months sealed.",
  }),
  p({
    sku: "CHE-IND-01-006",
    name: "Calcium Carbide",
    category: "chemicals",
    hs: "2848100000",
    price: 700,
    cap20: BAG20, cap40: BAG40,
    tags: ["industrial", "carbide", "acetylene"],
    shelfLife: SHELF,
    desc: "Calcium Carbide 80% — acetylene gas generation and desulfurization reagent.",
    coa: [
      ["CaC2 Content", "80.0% Min"],
      ["Gas Yield (L/kg)", "300 Min"],
      ["Particle Size (50-80mm)", "85% Min"],
      ["Phosphide (PH3)", "0.06% Max"],
      ["Sulfide (H2S)", "0.15% Max"],
      ["Moisture", "1.0% Max"],
      ["Free CaO", "10.0% Max"],
      ["MgO", "0.5% Max"],
      ["Appearance", "Grey/Brown solid"],
      ["Density", "2.22 g/cm3"],
    ],
    spec: "ORIGIN: China/Kazakhstan. PACKAGING: 50kg/100kg steel drums (UN-approved) with sealed gasket, or 1000kg steel bins. CERTIFICATIONS: ISO 9001, REACH, SDS, COA, UN 1402 packing group II. QUALITY: GB 10665-2004. HANDLING: Dangerous when wet — class 4.3, UN 1402. Releases acetylene + heat on water contact. Store dry, sealed, away from moisture and oxidizers. Use full PPE. Shelf life 12 months sealed.",
  }),

  // ============ PET (Petrochemicals) — 6 ============
  p({
    sku: "CHE-PET-01-001",
    name: "LDPE Film Grade",
    category: "chemicals",
    hs: "3901100000",
    price: 1200,
    cap20: BAG20, cap40: BAG40,
    tags: ["petrochemical", "polymer", "ldpe", "film"],
    shelfLife: SHELF,
    desc: "LDPE Film Grade 2420H — low-density polyethylene for packaging films.",
    coa: [
      ["Melt Flow Index (190C/2.16kg)", "1.7-2.3 g/10min"],
      ["Density", "0.922-0.924 g/cm3"],
      ["Tensile Strength (MD)", "20 MPa Min"],
      ["Elongation at Break (MD)", "300% Min"],
      ["Dart Drop Impact (F50)", "80 g Min"],
      ["Haze", "15% Max"],
      ["Gloss (45)", "50 Min"],
      ["Color", "Natural/translucent"],
      ["Volatile Matter", "0.2% Max"],
      ["Appearance", "Pellets"],
    ],
    spec: "ORIGIN: Saudi Arabia/Qatar. PACKAGING: 25kg PP bags on pallets, 750kg/1000kg FIBCs, or bulk silo truck. CERTIFICATIONS: ISO 9001, REACH, FDA 21 CFR 177.1520 food-contact, SDS, COA. QUALITY: ASTM D4976 LDPE film grade. HANDLING: Store in dry, ventilated warehouse away from sunlight, heat, and ignition sources. Avoid contamination. Process at 160-220C. Shelf life 24 months sealed.",
  }),
  p({
    sku: "CHE-PET-01-002",
    name: "HDPE Blow Moulding BM50100",
    category: "chemicals",
    hs: "3901200000",
    price: 1100,
    cap20: BAG20, cap40: BAG40,
    tags: ["petrochemical", "polymer", "hdpe", "blow-moulding"],
    shelfLife: SHELF,
    desc: "HDPE BM50100 — high-density polyethylene for blow-moulded bottles and drums.",
    coa: [
      ["Melt Flow Index (190C/21.6kg)", "6.0-9.0 g/10min"],
      ["Density", "0.958-0.960 g/cm3"],
      ["Tensile Strength (Yield)", "26 MPa Min"],
      ["ESCR (F50, 10% Igepal)", "30 hrs Min"],
      ["Notched Izod Impact", "8 kJ/m2 Min"],
      ["Flexural Modulus", "1200 MPa Min"],
      ["Color", "Natural/White"],
      ["Volatile Matter", "0.2% Max"],
      ["Ash Content", "0.04% Max"],
      ["Appearance", "Pellets"],
    ],
    spec: "ORIGIN: Saudi Arabia (SABIC)/South Korea. PACKAGING: 25kg PP bags on pallets, 1000kg FIBCs, or bulk. CERTIFICATIONS: ISO 9001, REACH, FDA 21 CFR 177.1520 food-contact, UN-certified for HMW-HDPE drums, SDS, COA. QUALITY: ASTM D4976 BM grade. HANDLING: Store dry under cover. Process at 180-230C. Avoid contamination. Shelf life 24 months sealed.",
  }),
  p({
    sku: "CHE-PET-01-003",
    name: "LLDPE Film Grade",
    category: "chemicals",
    hs: "3901200000",
    price: 1200,
    cap20: BAG20, cap40: BAG40,
    tags: ["petrochemical", "polymer", "lldpe", "film"],
    shelfLife: SHELF,
    desc: "LLDPE Film Grade 218W — linear low-density polyethylene for stretch and lamination films.",
    coa: [
      ["Melt Flow Index (190C/2.16kg)", "1.9-2.5 g/10min"],
      ["Density", "0.918-0.922 g/cm3"],
      ["Tensile Strength (MD)", "25 MPa Min"],
      ["Elongation at Break (MD)", "600% Min"],
      ["Dart Drop Impact (F50)", "100 g Min"],
      ["Elmendorf Tear (MD)", "80 g Min"],
      ["Haze", "15% Max"],
      ["Color", "Natural/translucent"],
      ["Volatile Matter", "0.2% Max"],
      ["Appearance", "Pellets"],
    ],
    spec: "ORIGIN: Saudi Arabia/Qatar. PACKAGING: 25kg PP bags on pallets, 1000kg FIBCs, or bulk. CERTIFICATIONS: ISO 9001, REACH, FDA 21 CFR 177.1520 food-contact, SDS, COA. QUALITY: ASTM D4976 LLDPE butene/octene film grade. HANDLING: Store dry under cover. Process at 180-220C. Often blended with LDPE for stretch films. Avoid contamination. Shelf life 24 months sealed.",
  }),
  p({
    sku: "CHE-PET-01-004",
    name: "PP Raffia Grade",
    category: "chemicals",
    hs: "3902100000",
    price: 1050,
    cap20: BAG20, cap40: BAG40,
    tags: ["petrochemical", "polymer", "pp", "raffia"],
    shelfLife: SHELF,
    desc: "PP Raffia Grade T30S — polypropylene homopolymer for woven sacks, tapes, and yarns.",
    coa: [
      ["Melt Flow Index (230C/2.16kg)", "2.5-3.5 g/10min"],
      ["Density", "0.90-0.91 g/cm3"],
      ["Tensile Strength at Yield", "35 MPa Min"],
      ["Elongation at Yield", "10% Min"],
      ["Flexural Modulus", "1500 MPa Min"],
      ["Notched Izod Impact (23C)", "4 kJ/m2 Min"],
      ["Volatile Matter", "0.2% Max"],
      ["Ash Content", "0.02% Max"],
      ["Color", "Natural/White"],
      ["Appearance", "Pellets"],
    ],
    spec: "ORIGIN: Saudi Arabia/India. PACKAGING: 25kg PP bags on pallets, 1000kg FIBCs, or bulk. CERTIFICATIONS: ISO 9001, REACH, FDA 21 CFR 177.1520, SDS, COA. QUALITY: ASTM D4100 PP raffia grade. HANDLING: Store dry under cover. Process at 200-260C. Suitable for woven sacks, FIBCs, ropes, carpet yarns. Avoid contamination. Shelf life 24 months sealed.",
  }),
  p({
    sku: "CHE-PET-01-005",
    name: "PVC Suspension SG-5",
    category: "chemicals",
    hs: "3904100000",
    price: 880,
    cap20: BAG20, cap40: BAG40,
    tags: ["petrochemical", "polymer", "pvc", "suspension"],
    shelfLife: SHELF,
    desc: "PVC Suspension SG-5 (K67) — polyvinyl chloride resin for pipes, profiles, and fittings.",
    coa: [
      ["K Value", "66-68"],
      ["Apparent Density", "0.48-0.55 g/ml"],
      ["Volatile Matter", "0.3% Max"],
      ["Particle Size (250um pass)", "98% Min"],
      ["Plasticizer Absorption", "22 g/100g Min"],
      ["Fish Eye", "10/100 cm2 Max"],
      ["VCM Residual", "1 ppm Max"],
      ["Color", "White powder"],
      ["Bulk Density", "0.50 g/ml"],
      ["Grade", "Suspension SG-5 K67"],
    ],
    spec: "ORIGIN: China/Taiwan. PACKAGING: 25kg PP bags with PE inner liner on pallets (1MT), 1000kg FIBCs, or bulk silo. CERTIFICATIONS: ISO 9001, REACH, FDA 21 CFR 178.3740, SDS, COA. QUALITY: GB/T 5761-2018 SG-5 grade. HANDLING: Store dry under cover; powder dust hazard — ventilate and use dust mask. Process with stabilizers and plasticizers at 160-200C. Avoid VCM exposure. Shelf life 24 months sealed.",
  }),
  p({
    sku: "CHE-PET-01-006",
    name: "PET Resin Bottle Grade",
    category: "chemicals",
    hs: "3907610000",
    price: 1000,
    cap20: BAG20, cap40: BAG40,
    tags: ["petrochemical", "polymer", "pet", "bottle-grade"],
    shelfLife: SHELF,
    desc: "PET Resin Bottle Grade BG801 — polyethylene terephthalate for beverage bottles.",
    coa: [
      ["Intrinsic Viscosity (IV)", "0.78-0.82 dl/g"],
      ["Acetaldehyde (AA)", "1.0 ppm Max"],
      ["Color (L)", "80 Min"],
      ["Color (b)", "1.0 Max"],
      ["Melting Point", "245-252C"],
      ["Moisture", "0.2% Max"],
      ["Carboxyl End Groups", "35 mmol/kg Max"],
      ["Diethylene Glycol (DEG)", "1.3% Max"],
      ["Particle Size", "3-5mm chips"],
      ["Crystallinity", "50% Min"],
    ],
    spec: "ORIGIN: China/India. PACKAGING: 25kg PP bags with PE inner liner on pallets (1MT) or 1000kg FIBCs. CERTIFICATIONS: ISO 9001, REACH, FDA 21 CFR 177.1630 food-contact, EU 10/2011, SDS, COA. QUALITY: GB/T 17931-2018 bottle grade. HANDLING: Store dry under cover; hygroscopic — dry at 170C/6hr before processing. Process at 270-290C. Recyclable. Shelf life 12 months sealed.",
  }),

  // ============ AGC (Agro-chemicals) — 4 ============
  p({
    sku: "CHE-AGC-01-001",
    name: "Glyphosate Technical 95%",
    category: "chemicals",
    hs: "2931490000",
    price: 3200,
    cap20: BAG20, cap40: BAG40,
    tags: ["agro-chemical", "herbicide", "glyphosate", "technical"],
    shelfLife: SHELF,
    desc: "Glyphosate Technical 95% — non-selective systemic herbicide active ingredient.",
    coa: [
      ["Glyphosate Purity", "95.0% Min"],
      ["N-Nitroso Glyphosate", "1.0 ppm Max"],
      ["Formaldehyde", "0.5 g/kg Max"],
      ["Aminomethylphosphonic Acid", "2.0 g/kg Max"],
      ["Moisture", "0.5% Max"],
      ["pH (1% water)", "3.5-5.0"],
      ["Sodium Chloride", "1.0% Max"],
      ["Appearance", "White to off-white powder"],
      ["Melting Point", "189-190C"],
      ["Solubility in Water", "12 g/L (25C)"],
    ],
    spec: "ORIGIN: China. PACKAGING: 25kg PP bags with PE inner liner on pallets (1MT) or 1000kg FIBCs. CERTIFICATIONS: ISO 9001, REACH, FAO/WHO spec, GMP, SDS, COA. QUALITY: FAO Spec 1.324/TC/S/F (2016). HANDLING: Toxic — store in original sealed containers in dry, ventilated area. Use full PPE. Avoid inhalation and skin contact. Formulate to 41% SL or 62% IPA salt for end-use. Shelf life 24 months sealed.",
  }),
  p({
    sku: "CHE-AGC-01-002",
    name: "Atrazine Technical 95%",
    category: "chemicals",
    hs: "2933690000",
    price: 3500,
    cap20: BAG20, cap40: BAG40,
    tags: ["agro-chemical", "herbicide", "atrazine", "technical"],
    shelfLife: SHELF,
    desc: "Atrazine Technical 95% — selective triazine herbicide for maize and sugarcane.",
    coa: [
      ["Atrazine Purity", "95.0% Min"],
      ["Simazine Content", "1.5% Max"],
      ["Propazine Content", "0.5% Max"],
      ["Hydroxyatrazine", "0.5% Max"],
      ["Free Chlorine", "0.05% Max"],
      ["Moisture", "0.5% Max"],
      ["pH (1% water)", "6.0-8.0"],
      ["Appearance", "White to off-white powder"],
      ["Melting Point", "173-175C"],
      ["Solubility in Water", "33 mg/L (25C)"],
    ],
    spec: "ORIGIN: China/Israel. PACKAGING: 25kg PP bags with PE inner liner on pallets (1MT) or 1000kg FIBCs. CERTIFICATIONS: ISO 9001, REACH, FAO/WHO spec, SDS, COA. QUALITY: FAO Spec 1.185/TC/S/F (1999). HANDLING: Toxic to aquatic life — store sealed in dry, ventilated area away from waterways. Use full PPE. Formulate to 50% WP or 500 g/L SC for end-use. Shelf life 24 months sealed.",
  }),
  p({
    sku: "CHE-AGC-01-003",
    name: "Mancozeb Technical 90%",
    category: "chemicals",
    hs: "3808930000",
    price: 2800,
    cap20: BAG20, cap40: BAG40,
    tags: ["agro-chemical", "fungicide", "mancozeb", "technical"],
    shelfLife: SHELF,
    desc: "Mancozeb Technical 90% — contact fungicide for foliar disease control.",
    coa: [
      ["Mancozeb Purity", "90.0% Min"],
      ["Maneb Content", "0.5% Max"],
      ["Zinc Content", "2.5-2.8%"],
      ["Manganese Content", "19.0-21.0%"],
      ["Ethylene Thiourea (ETU)", "0.5% Max"],
      ["Moisture", "2.0% Max"],
      ["pH (1% suspension)", "6.0-8.0"],
      ["Fineness (45um pass)", "98% Min"],
      ["Appearance", "Greyish-yellow powder"],
      ["Decomposition Temp", "190-205C"],
    ],
    spec: "ORIGIN: China/India. PACKAGING: 25kg PP bags with PE inner liner on pallets (1MT) or 1000kg FIBCs. CERTIFICATIONS: ISO 9001, REACH, FAO/WHO spec, GMP, SDS, COA. QUALITY: FAO Spec 2.024/TC/S/P (1993). HANDLING: Toxic and mild sensitizer — store sealed in dry, ventilated area. Use full PPE incl. respirator. Decomposes above 190C. Formulate to 75% WP or 80% WDG. Shelf life 24 months sealed.",
  }),
  p({
    sku: "CHE-AGC-01-004",
    name: "Urea Formaldehyde",
    category: "chemicals",
    hs: "3909100000",
    price: 1050,
    cap20: BAG20, cap40: BAG40,
    tags: ["agro-chemical", "resin", "slow-release", "uf"],
    shelfLife: SHELF,
    desc: "Urea Formaldehyde Resin Powder — slow-release nitrogen source and wood adhesive.",
    coa: [
      ["Nitrogen (N) Content", "38.0% Min"],
      ["Urea-Formaldehyde", "98.0% Min"],
      ["Slow-Release N (Cold Water Insoluble)", "65.0% Min"],
      ["Activity Index", "40-55%"],
      ["Free Urea", "5.0% Max"],
      ["Free Formaldehyde", "0.5% Max"],
      ["Moisture", "2.0% Max"],
      ["pH (1% suspension)", "7.0-9.0"],
      ["Particle Size (250um)", "95% Min"],
      ["Appearance", "White powder"],
    ],
    spec: "ORIGIN: China/Germany. PACKAGING: 25kg PP bags with PE inner liner on pallets (1MT) or 1000kg FIBCs. CERTIFICATIONS: ISO 9001, REACH, ECHA compliant, SDS, COA. QUALITY: EN 12022 / Reg EU 2019/1009 slow-release; also wood adhesive (CAS 9011-05-6). HANDLING: Store dry under cover; dust hazard — ventilate. Use dust mask. Avoid formaldehyde inhalation. Shelf life 24 months sealed.",
  }),

  // ============ WAT (Water treatment) — 4 ============
  p({
    sku: "CHE-WAT-01-001",
    name: "PAC (Poly Aluminium Chloride)",
    category: "chemicals",
    hs: "2827320000",
    price: 580,
    cap20: BAG20, cap40: BAG40,
    tags: ["water-treatment", "coagulant", "pac", "flocculant"],
    shelfLife: SHELF,
    desc: "PAC Poly Aluminium Chloride — inorganic coagulant for drinking water and wastewater.",
    coa: [
      ["Al2O3 Content", "30.0% Min"],
      ["Basicity", "70-85%"],
      ["pH (1% water)", "3.5-5.0"],
      ["Insolubles in Water", "0.2% Max"],
      ["Iron (Fe)", "0.05% Max"],
      ["Arsenic (As)", "2 ppm Max"],
      ["Lead (Pb)", "5 ppm Max"],
      ["Cadmium (Cd)", "1 ppm Max"],
      ["Mercury (Hg)", "0.1 ppm Max"],
      ["Appearance", "Yellow/light brown powder"],
    ],
    spec: "ORIGIN: China/India. PACKAGING: 25kg PP bags with PE inner liner on pallets (1MT), 1000kg FIBCs, or bulk tank. CERTIFICATIONS: ISO 9001, REACH, NSF/ANSI 60 drinking-water certified, SDS, COA. QUALITY: GB 15892-2020. HANDLING: Corrosive — store in dry, ventilated area away from acids and oxidizers. Use PPE (gloves, goggles). Dose 5-100 mg/L depending on turbidity. Shelf life 12 months sealed.",
  }),
  p({
    sku: "CHE-WAT-01-002",
    name: "Ferric Chloride 39%",
    category: "chemicals",
    hs: "2827390000",
    price: 310,
    cap20: IBC20, cap40: IBC40,
    tags: ["water-treatment", "coagulant", "iron", "flocculant"],
    shelfLife: SHELF,
    desc: "Ferric Chloride 39% Solution — FeCl3 coagulant for water and wastewater treatment.",
    coa: [
      ["FeCl3 Content", "39.0% Min"],
      ["FeCl2 Content", "0.3% Max"],
      ["Free Acid (HCl)", "0.5% Max"],
      ["Insolubles", "0.3% Max"],
      ["Specific Gravity (20C)", "1.40-1.45"],
      ["pH (1% solution)", "1.5-2.5"],
      ["Free Chlorine (Cl2)", "0.01% Max"],
      ["Copper (Cu)", "50 ppm Max"],
      ["Color", "Dark brown liquid"],
      ["Boiling Point", "105C"],
    ],
    spec: "ORIGIN: China/India. PACKAGING: 1000L IBC totes (HDPE), 250L HDPE drums, or rubber-lined ISO tanks. CERTIFICATIONS: ISO 9001, REACH, NSF/ANSI 60, SDS, COA. QUALITY: GB 4482-2018. HANDLING: Corrosive UN 2582 class 8. Store in HDPE/rubber-lined tanks. Stains surfaces — use full PPE incl. acid suit. Effective at pH 4-11. Dose 10-100 mg/L. Shelf life 12 months sealed.",
  }),
  p({
    sku: "CHE-WAT-01-003",
    name: "Polyacrylamide Anionic",
    category: "chemicals",
    hs: "3906900000",
    price: 2000,
    cap20: BAG20, cap40: BAG40,
    tags: ["water-treatment", "flocculant", "polymer", "pam"],
    shelfLife: SHELF,
    desc: "Polyacrylamide Anionic — synthetic polymer flocculant for sludge dewatering and clarification.",
    coa: [
      ["Active Content", "90.0% Min"],
      ["Molecular Weight (million)", "12-18"],
      ["Degree of Hydrolysis", "20-30%"],
      ["Residual Acrylamide", "0.05% Max"],
      ["Bulk Density", "0.65-0.75 g/ml"],
      ["Dissolution Time", "60 min Max"],
      ["pH Range (effective)", "4.0-10.0"],
      ["Moisture", "10.0% Max"],
      ["Particle Size (1-2mm)", "90% Min"],
      ["Appearance", "White granular powder"],
    ],
    spec: "ORIGIN: China/France. PACKAGING: 25kg PP bags with PE inner liner on pallets (1MT) or 750kg/1000kg FIBCs. CERTIFICATIONS: ISO 9001, REACH, NSF/ANSI 60, SDS, COA. QUALITY: GB 17514-2017. HANDLING: Store dry under cover; highly hygroscopic and slippery when wet. Use dust mask. Dilute to 0.1-0.3% before dosing. Dose 0.5-5 mg/L (water) or 2-5 kg/T dry solids. Shelf life 12 months sealed.",
  }),
  p({
    sku: "CHE-WAT-01-004",
    name: "Sodium Hypochlorite 12%",
    category: "chemicals",
    hs: "2828900000",
    price: 280,
    cap20: IBC20, cap40: IBC40,
    tags: ["water-treatment", "disinfectant", "bleach", "chlorine"],
    shelfLife: "6 months under proper storage",
    desc: "Sodium Hypochlorite 12% Solution — NaOCl disinfectant for water and surface sanitization.",
    coa: [
      ["Available Chlorine (Cl2)", "12.0% Min"],
      ["Free Alkali (as NaOH)", "0.5-1.5%"],
      ["Sodium Chloride (NaCl)", "10.0% Max"],
      ["Iron (Fe)", "10 ppm Max"],
      ["Heavy Metals (as Pb)", "5 ppm Max"],
      ["Free Chlorine (Cl2)", "0.05% Max"],
      ["Specific Gravity (20C)", "1.20-1.25"],
      ["pH", "11.0-13.0"],
      ["Color", "Pale yellow/greenish"],
      ["Decomposition Rate", "5%/month at 25C"],
    ],
    spec: "ORIGIN: China/India. PACKAGING: 1000L IBC totes (HDPE vented), 25L/30L HDPE carboys, or rubber-lined road tankers. CERTIFICATIONS: ISO 9001, REACH, NSF/ANSI 60, SDS, COA. QUALITY: GB 19106-2013. HANDLING: Corrosive UN 1791 class 8; strong oxidizer. Releases Cl2 on contact with acids. Store cool (<25C), shaded, vented. Use full PPE. Shelf life 6 months.",
  }),
];
