// Aspidus DMCC — Ores Product Catalog (40 SKUs)
// Generated for tenant c889572d-d35b-43ec-bca1-a5359d95603d
// Sub-categories: IRO, CUO, BAU, MAN, CHR, ZNO, PBO, TNO, NIO, XRO

export interface CoaParam { name: string; value: string; }
export interface Logistics { cap20: number | null; cap40: number | null; }
export interface SeedProduct {
  sku: string; name: string; category: string; unit: string;
  price: number; currency: string; cost: number;
  stock: number; reorder_level: number; active: boolean;
  description: string; hs_code: string;
  brand: null; shelf_life: string | null; image_url: null;
  logistics: Logistics; coa_params: CoaParam[];
  detailed_spec: string; tags: string[];
}

function p(o: {
  sku: string; name: string; category: string;
  hs: string; price: number; unit?: string;
  coa: [string, string][]; spec: string;
  cap20?: number | null; cap40?: number | null;
  tags?: string[]; shelfLife?: string | null;
  desc?: string; stock?: number;
}): SeedProduct {
  const unit = o.unit ?? "MT";
  const stock = o.stock ?? 5000;
  return {
    sku: o.sku, name: o.name, category: o.category, unit,
    price: o.price, currency: "USD", cost: o.price, stock,
    reorder_level: Math.max(1, Math.floor(stock / 20)),
    active: true, description: o.desc ?? o.name,
    hs_code: o.hs, brand: null,
    shelf_life: o.shelfLife ?? null, image_url: null,
    logistics: { cap20: o.cap20 ?? null, cap40: o.cap40 ?? null },
    coa_params: o.coa.map(([name, value]) => ({ name, value })),
    detailed_spec: o.spec, tags: o.tags ?? [],
  };
}

export const oreProducts: SeedProduct[] = [
  // ───────────────────────── IRO — Iron ore (8) ─────────────────────────
  p({
    sku: "ORE-IRO-01-001",
    name: "Hematite Lump 62% Fe",
    category: "ores",
    hs: "2601110000",
    price: 120,
    cap20: 25000, cap40: 27000,
    tags: ["iron-ore", "hematite", "lump", "62%"],
    desc: "Hematite iron ore lump 62% Fe for blast furnace feed",
    coa: [
      ["Fe Content", "62.0% Min"],
      ["SiO2", "4.0% Max"],
      ["Al2O3", "2.5% Max"],
      ["Phosphorus (P)", "0.06% Max"],
      ["Sulfur (S)", "0.04% Max"],
      ["Moisture", "5.0% Max"],
      ["Size (10-40mm)", "90% Min"],
      ["Size <10mm", "5% Max"],
      ["Size >40mm", "5% Max"],
      ["Physical", "Lump"],
      ["TI (Tumble Index)", "85% Min"],
    ],
    spec: "ORIGIN: Brazil/Australia/South Africa. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek/BV inspection at load/discharge, Certificate of Origin, Weight Certificate (draft survey or shore scale). QUALITY: Per IODEX/MBIO index pricing. HANDLING: Store under cover or with tarpaulin; keep dry. No shelf life. Moisture above spec subject to claim.",
  }),
  p({
    sku: "ORE-IRO-02-002",
    name: "Hematite Fines 60% Fe",
    category: "ores",
    hs: "2601110000",
    price: 105,
    cap20: 24000, cap40: 27000,
    tags: ["iron-ore", "hematite", "fines", "60%"],
    desc: "Hematite iron ore fines 60% Fe for sintering/pelletizing",
    coa: [
      ["Fe Content", "60.0% Min"],
      ["SiO2", "5.5% Max"],
      ["Al2O3", "3.0% Max"],
      ["Phosphorus (P)", "0.07% Max"],
      ["Sulfur (S)", "0.05% Max"],
      ["Moisture", "8.0% Max"],
      ["Size <10mm", "90% Min"],
      ["Size <0.15mm", "25% Max"],
      ["AI (Abrasion Index)", "5.0% Max"],
      ["Physical", "Fines"],
      ["Pricing Index", "IODEX 60%"],
    ],
    spec: "ORIGIN: Brazil/India/Australia. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek/Bureau Veritas inspection at load/discharge port, Certificate of Origin, Weight Certificate. QUALITY: Per IODEX 60% Fe index. HANDLING: Store under cover; keep dry to maintain moisture spec. No shelf life. Moisture above spec subject to claim.",
  }),
  p({
    sku: "ORE-IRO-03-003",
    name: "Magnetite Concentrate 65% Fe",
    category: "ores",
    hs: "2601110000",
    price: 100,
    cap20: 24000, cap40: 27000,
    tags: ["iron-ore", "magnetite", "concentrate", "65%"],
    desc: "Magnetite concentrate 65% Fe for pelletizing",
    coa: [
      ["Fe Content", "65.0% Min"],
      ["SiO2", "6.0% Max"],
      ["Al2O3", "1.0% Max"],
      ["Phosphorus (P)", "0.03% Max"],
      ["Sulfur (S)", "0.10% Max"],
      ["Moisture", "9.0% Max"],
      ["Magnetite Content", "95% Min"],
      ["Size <75μm", "80% Min"],
      ["Blaine Surface", "1800 cm²/g Min"],
      ["Form", "Filter cake"],
      ["Use", "Pellet feed"],
    ],
    spec: "ORIGIN: Australia/Chile/Sweden. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: Per pellet feed spec, magnetite concentrate. HANDLING: Store under cover; keep dry. No shelf life. Moisture above 9% subject to claim.",
  }),
  p({
    sku: "ORE-IRO-04-004",
    name: "Iron Ore Pellets 65% Fe",
    category: "ores",
    hs: "2601120000",
    price: 140,
    cap20: 25000, cap40: 27000,
    tags: ["iron-ore", "pellets", "65%", "DR-grade"],
    desc: "Iron ore pellets 65% Fe (DR grade) for direct reduction",
    coa: [
      ["Fe Content", "65.0% Min"],
      ["SiO2", "3.0% Max"],
      ["Al2O3", "1.0% Max"],
      ["CaO", "0.5-1.5%"],
      ["MgO", "0.5-1.5%"],
      ["Phosphorus (P)", "0.03% Max"],
      ["Sulfur (S)", "0.01% Max"],
      ["Size (9-16mm)", "92% Min"],
      ["CCS (Cold Crushing)", "200 kg/pellet Min"],
      ["TI (Tumble Index)", "94% Min"],
      ["Form", "Pellets (DR grade)"],
    ],
    spec: "ORIGIN: Brazil/Canada/Sweden. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: DR-grade pellets per ISO 4700 / ASTM E1072. HANDLING: Store under cover; protect from moisture. No shelf life. Loading per vessel laycan terms.",
  }),
  p({
    sku: "ORE-IRO-05-005",
    name: "Iron Ore Lump 58% Fe",
    category: "ores",
    hs: "2601110000",
    price: 90,
    cap20: 25000, cap40: 27000,
    tags: ["iron-ore", "lump", "58%"],
    desc: "Iron ore lump 58% Fe (lower-grade lump) for BF feed",
    coa: [
      ["Fe Content", "58.0% Min"],
      ["SiO2", "7.0% Max"],
      ["Al2O3", "3.5% Max"],
      ["Phosphorus (P)", "0.08% Max"],
      ["Sulfur (S)", "0.06% Max"],
      ["Moisture", "5.0% Max"],
      ["Size (10-40mm)", "85% Min"],
      ["Size <10mm", "8% Max"],
      ["Size >40mm", "7% Max"],
      ["Physical", "Lump"],
      ["TI (Tumble Index)", "80% Min"],
    ],
    spec: "ORIGIN: India/South Africa/Mexico. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek inspection at load/discharge port, Certificate of Origin, Weight Certificate. QUALITY: Per index pricing (58% Fe basis). HANDLING: Store under cover or with tarpaulin; keep dry. No shelf life. Moisture above spec subject to claim.",
  }),
  p({
    sku: "ORE-IRO-06-006",
    name: "Iron Ore Fines 56% Fe",
    category: "ores",
    hs: "2601110000",
    price: 80,
    cap20: 24000, cap40: 27000,
    tags: ["iron-ore", "fines", "56%", "low-grade"],
    desc: "Iron ore fines 56% Fe for sintering/blending",
    coa: [
      ["Fe Content", "56.0% Min"],
      ["SiO2", "9.0% Max"],
      ["Al2O3", "4.5% Max"],
      ["Phosphorus (P)", "0.09% Max"],
      ["Sulfur (S)", "0.07% Max"],
      ["Moisture", "9.0% Max"],
      ["Size <10mm", "90% Min"],
      ["Size <0.15mm", "25% Max"],
      ["AI (Abrasion Index)", "6.0% Max"],
      ["Physical", "Fines"],
      ["Pricing Index", "IODEX 58% discounted"],
    ],
    spec: "ORIGIN: India/Indonesia/Malaysia. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: Per index pricing (58% Fe basis with discount). HANDLING: Store under cover; keep dry. No shelf life. Moisture above 9% subject to claim.",
  }),
  p({
    sku: "ORE-IRO-07-007",
    name: "Sinter Feed 60% Fe",
    category: "ores",
    hs: "2601110000",
    price: 110,
    cap20: 24000, cap40: 27000,
    tags: ["iron-ore", "sinter-feed", "60%", "BF"],
    desc: "Iron ore sinter feed 60% Fe (natural fines for sintering)",
    coa: [
      ["Fe Content", "60.0% Min"],
      ["SiO2", "5.0% Max"],
      ["Al2O3", "2.5% Max"],
      ["Phosphorus (P)", "0.06% Max"],
      ["Sulfur (S)", "0.05% Max"],
      ["Moisture", "7.0% Max"],
      ["Size <6mm", "85% Min"],
      ["Size >10mm", "5% Max"],
      ["Size <0.15mm", "20% Max"],
      ["Physical", "Natural fines"],
      ["Use", "Sinter plant feed"],
    ],
    spec: "ORIGIN: Brazil/Australia/South Africa. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: Per IODEX 60% Fe index, sinter feed spec. HANDLING: Store under cover; keep dry. No shelf life. Moisture above 7% subject to claim.",
  }),
  p({
    sku: "ORE-IRO-08-008",
    name: "DSO Lump 60% Fe",
    category: "ores",
    hs: "2601110000",
    price: 115,
    cap20: 25000, cap40: 27000,
    tags: ["iron-ore", "DSO", "lump", "60%"],
    desc: "Direct Shipping Ore (DSO) lump 60% Fe for BF feed",
    coa: [
      ["Fe Content", "60.0% Min"],
      ["SiO2", "5.5% Max"],
      ["Al2O3", "3.0% Max"],
      ["Phosphorus (P)", "0.07% Max"],
      ["Sulfur (S)", "0.05% Max"],
      ["Moisture", "5.0% Max"],
      ["Size (10-40mm)", "88% Min"],
      ["Size <10mm", "7% Max"],
      ["Size >40mm", "5% Max"],
      ["Physical", "DSO Lump"],
      ["TI (Tumble Index)", "82% Min"],
    ],
    spec: "ORIGIN: Mauritania/Canada/Sierra Leone. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: DSO lump per index pricing (60% Fe basis). HANDLING: Store under cover; keep dry. No shelf life. Moisture above spec subject to claim.",
  }),

  // ───────────────────────── CUO — Copper ore (5) ─────────────────────────
  p({
    sku: "ORE-CUO-01-009",
    name: "Copper Concentrate 25% Cu",
    category: "ores",
    hs: "2603000000",
    price: 1700,
    cap20: 24000, cap40: 27000,
    tags: ["copper", "concentrate", "25%"],
    desc: "Copper concentrate 25% Cu with precious metal credits",
    coa: [
      ["Cu Content", "25.0% Min"],
      ["Gold (Au)", "8 g/MT Min"],
      ["Silver (Ag)", "80 g/MT Min"],
      ["Sulfur (S)", "30% Typical"],
      ["Iron (Fe)", "25% Typical"],
      ["Arsenic (As)", "0.3% Max"],
      ["Lead (Pb)", "2.0% Max"],
      ["Zinc (Zn)", "2.0% Max"],
      ["Bismuth (Bi)", "0.05% Max"],
      ["Antimony (Sb)", "0.2% Max"],
      ["Moisture", "8.0% Max"],
    ],
    spec: "ORIGIN: Chile/Peru/Indonesia. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek assay at load/discharge, Certificate of Origin, Weight Certificate. QUALITY: Priced via TC/RC + QP + precious metal credits. HANDLING: Store under cover; keep dry. No shelf life. Moisture above 8% subject to claim. Penalty elements per contract.",
  }),
  p({
    sku: "ORE-CUO-02-010",
    name: "Copper Concentrate 30% Cu",
    category: "ores",
    hs: "2603000000",
    price: 2100,
    cap20: 24000, cap40: 27000,
    tags: ["copper", "concentrate", "30%", "high-grade"],
    desc: "Copper concentrate 30% Cu (high grade) with precious metal credits",
    coa: [
      ["Cu Content", "30.0% Min"],
      ["Gold (Au)", "12 g/MT Min"],
      ["Silver (Ag)", "120 g/MT Min"],
      ["Sulfur (S)", "28% Typical"],
      ["Iron (Fe)", "22% Typical"],
      ["Arsenic (As)", "0.2% Max"],
      ["Lead (Pb)", "1.5% Max"],
      ["Zinc (Zn)", "1.5% Max"],
      ["Bismuth (Bi)", "0.03% Max"],
      ["Antimony (Sb)", "0.15% Max"],
      ["Moisture", "8.0% Max"],
    ],
    spec: "ORIGIN: Chile/Peru/Mongolia. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek assay at load/discharge, Certificate of Origin, Weight Certificate. QUALITY: Priced via TC/RC + QP + precious metal credits. HANDLING: Store under cover; keep dry. No shelf life. Penalty elements per contract.",
  }),
  p({
    sku: "ORE-CUO-03-011",
    name: "ROM Copper Ore 2% Cu",
    category: "ores",
    hs: "2603000000",
    price: 120,
    cap20: 25000, cap40: 27000,
    tags: ["copper", "ROM", "ore", "2%"],
    desc: "Run-of-Mine copper ore 2% Cu (sulfide) for direct smelting/leaching",
    coa: [
      ["Cu Content", "2.0% Min"],
      ["Sulfur (S)", "5-10% Typical"],
      ["Iron (Fe)", "15-25% Typical"],
      ["Silica (SiO2)", "40-55% Typical"],
      ["Al2O3", "5-10% Typical"],
      ["Gold (Au)", "0.5-2 g/MT typical"],
      ["Silver (Ag)", "5-20 g/MT typical"],
      ["Arsenic (As)", "0.05% Max"],
      ["Moisture", "5.0% Max"],
      ["Size", "0-200 mm ROM"],
      ["Inspection", "SGS/Intertek"],
    ],
    spec: "ORIGIN: Zambia/DRC/Chile. PACKAGING: Bulk in containers or vessel hold (loose). CERTIFICATIONS: SGS/Intertek inspection at load/discharge port, Certificate of Origin, Weight Certificate. QUALITY: ROM sulfide ore, amenable to flotation or leaching. HANDLING: Store on hard standing; protect from excessive moisture. No shelf life.",
  }),
  p({
    sku: "ORE-CUO-04-012",
    name: "Copper Oxide Ore 1.5% Cu",
    category: "ores",
    hs: "2603000000",
    price: 90,
    cap20: 25000, cap40: 27000,
    tags: ["copper", "oxide-ore", "1.5%", "SX-EW"],
    desc: "Copper oxide ore 1.5% Cu for heap leach / SX-EW processing",
    coa: [
      ["Cu Total", "1.5% Min"],
      ["Cu Oxide (acid soluble)", "1.0% Min"],
      ["Cu Sulfide", "0.5% Typical"],
      ["Iron (Fe)", "10-20% Typical"],
      ["Silica (SiO2)", "45-60% Typical"],
      ["Al2O3", "5-10% Typical"],
      ["Calcium (CaO)", "2-6% Typical"],
      ["Sulfur (S)", "0.5% Max"],
      ["Acid Consumption", "10-25 kg H2SO4/MT"],
      ["Moisture", "5.0% Max"],
      ["Size", "0-50 mm crushed"],
    ],
    spec: "ORIGIN: Chile/Peru/DRC. PACKAGING: Bulk in containers or vessel hold (loose). CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: Oxide ore for SX-EW processing. HANDLING: Store on hard standing; protect from excessive moisture. No shelf life.",
  }),
  p({
    sku: "ORE-CUO-05-013",
    name: "Copper Matte 70% Cu",
    category: "ores",
    hs: "2825500000",
    price: 6000,
    cap20: 24000, cap40: 27000,
    tags: ["copper", "matte", "70%", "intermediate"],
    desc: "Copper matte 70% Cu (intermediate smelter product)",
    coa: [
      ["Cu Content", "70.0% Min"],
      ["Iron (Fe)", "5.0% Max"],
      ["Sulfur (S)", "20-22%"],
      ["Oxygen (O)", "1.0% Max"],
      ["Lead (Pb)", "0.5% Max"],
      ["Arsenic (As)", "0.10% Max"],
      ["Antimony (Sb)", "0.10% Max"],
      ["Bismuth (Bi)", "0.05% Max"],
      ["Gold (Au)", "10-50 g/MT typical"],
      ["Silver (Ag)", "500-2000 g/MT typical"],
      ["Form", "Granulated/pig"],
    ],
    spec: "ORIGIN: Chile/Peru/Indonesia. PACKAGING: In 1MT bulk bags or steel drums, granulated/pig form. CERTIFICATIONS: SGS/Intertek assay, Certificate of Origin, Weight Certificate. QUALITY: Priced LME Cu less refining charges + precious metal credits. HANDLING: Store in dry covered area. No shelf life. Stack max 2 pallets high.",
  }),

  // ───────────────────────── BAU — Bauxite (4) ─────────────────────────
  p({
    sku: "ORE-BAU-01-014",
    name: "Metallurgical Bauxite 45% Al2O3",
    category: "ores",
    hs: "2606000000",
    price: 65,
    cap20: 25000, cap40: 27000,
    tags: ["bauxite", "metallurgical", "gibbsitic", "Bayer-process"],
    desc: "Metallurgical-grade gibbsitic bauxite 45% Al2O3 for alumina refining",
    coa: [
      ["Al2O3", "45.0% Min"],
      ["SiO2", "4.0% Max"],
      ["Fe2O3", "25% Typical"],
      ["TiO2", "2.5% Typical"],
      ["LOI", "27% Typical"],
      ["Moisture", "5.0% Max"],
      ["Available Alumina", "38% Min"],
      ["Reactive Silica", "1.5% Max"],
      ["Size", "0-100 mm"],
      ["Mineralogy", "Gibbsitic"],
      ["Use", "Bayer process"],
    ],
    spec: "ORIGIN: Guinea/Brazil/Australia. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek/Bureau Veritas inspection, Certificate of Origin, Weight Certificate. QUALITY: Per metal Bulletin Bauxite Index. HANDLING: Store under cover or with tarpaulin; keep dry. No shelf life. Moisture above spec subject to claim.",
  }),
  p({
    sku: "ORE-BAU-02-015",
    name: "Refractory Bauxite 80% Al2O3",
    category: "ores",
    hs: "2606000000",
    price: 150,
    cap20: 24000, cap40: 27000,
    tags: ["bauxite", "refractory", "80%", "calcined"],
    desc: "Refractory-grade bauxite 80% Al2O3 (RASC type)",
    coa: [
      ["Al2O3", "80.0% Min"],
      ["SiO2", "6.0% Max"],
      ["Fe2O3", "2.5% Max"],
      ["TiO2", "4.0% Max"],
      ["CaO", "0.4% Max"],
      ["LOI", "0.5% Max"],
      ["Bulk Density", "3.0 g/cm³ Min"],
      ["Refractoriness", "1790°C Min"],
      ["Size", "0-1 / 1-3 / 3-5 mm"],
      ["Type", "RASC"],
      ["Use", "Refractory bricks"],
    ],
    spec: "ORIGIN: China/Guyana/India. PACKAGING: In 1MT bulk bags on wooden pallets, strapped. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin. QUALITY: RASC (Refractory A-Grade Super Calcined) per industry spec. HANDLING: Store in dry covered area; protect from moisture. No shelf life. Stack max 2 pallets high.",
  }),
  p({
    sku: "ORE-BAU-03-016",
    name: "Bauxite Cement Grade",
    category: "ores",
    hs: "2606000000",
    price: 95,
    cap20: 25000, cap40: 27000,
    tags: ["bauxite", "cement", "CAC", "aluminous"],
    desc: "Calcium aluminate cement grade bauxite (high Al2O3, low SiO2)",
    coa: [
      ["Al2O3", "55.0% Min"],
      ["SiO2", "8.0% Max"],
      ["Fe2O3", "20% Typical"],
      ["TiO2", "4.0% Max"],
      ["CaO", "0.5% Max"],
      ["MgO", "0.3% Max"],
      ["Alkalies (Na2O+K2O)", "0.3% Max"],
      ["LOI", "12% Typical"],
      ["Moisture", "5.0% Max"],
      ["Size", "0-50 mm"],
      ["Use", "CAC production"],
    ],
    spec: "ORIGIN: Guinea/China/Turkey. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin. QUALITY: Per CAC (Calcium Aluminate Cement) production spec. HANDLING: Store under cover; keep dry. No shelf life. Stack max 2 pallets high.",
  }),
  p({
    sku: "ORE-BAU-04-017",
    name: "Calcined Bauxite 88%",
    category: "ores",
    hs: "2508400000",
    price: 280,
    cap20: 24000, cap40: 27000,
    tags: ["bauxite", "calcined", "88%", "abrasive"],
    desc: "Calcined bauxite 88% Al2O3 for abrasives/friction/proppants",
    coa: [
      ["Al2O3", "88.0% Min"],
      ["SiO2", "5.0% Max"],
      ["Fe2O3", "2.0% Max"],
      ["TiO2", "4.0% Max"],
      ["CaO", "0.3% Max"],
      ["MgO", "0.2% Max"],
      ["LOI", "0.5% Max"],
      ["Bulk Density", "3.2 g/cm³ Min"],
      ["Mohs Hardness", "9 Min"],
      ["Size", "0-1 / 1-3 / 3-5 mm"],
      ["Use", "Abrasives / Proppants"],
    ],
    spec: "ORIGIN: China/Guyana/Brazil. PACKAGING: In 1MT bulk bags on wooden pallets, strapped. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin. QUALITY: Rotary kiln calcined per industry spec. HANDLING: Store in dry covered area; protect from moisture. No shelf life. Stack max 2 pallets high.",
  }),

  // ───────────────────────── MAN — Manganese (4) ─────────────────────────
  p({
    sku: "ORE-MAN-01-018",
    name: "Manganese Lump 44% Mn",
    category: "ores",
    hs: "2602000000",
    price: 200,
    cap20: 25000, cap40: 27000,
    tags: ["manganese", "lump", "44%", "metallurgical"],
    desc: "Metallurgical-grade manganese lump ore 44% Mn for ferroalloy production",
    coa: [
      ["Mn Content", "44.0% Min"],
      ["Fe Content", "8.0% Max"],
      ["SiO2", "10.0% Max"],
      ["Al2O3", "5.0% Max"],
      ["Phosphorus (P)", "0.12% Max"],
      ["Sulfur (S)", "0.05% Max"],
      ["Moisture", "5.0% Max"],
      ["Size (10-75mm)", "85% Min"],
      ["Size <10mm", "5% Max"],
      ["Mn/Fe Ratio", "5.0 Min"],
      ["Physical", "Lump"],
    ],
    spec: "ORIGIN: South Africa/Gabon/Australia. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek inspection at load/discharge port, Certificate of Origin, Weight Certificate. QUALITY: Priced per dmtu (44% Mn basis). HANDLING: Store under cover; keep dry. No shelf life.",
  }),
  p({
    sku: "ORE-MAN-02-019",
    name: "Manganese Fines 38% Mn",
    category: "ores",
    hs: "2602000000",
    price: 140,
    cap20: 24000, cap40: 27000,
    tags: ["manganese", "fines", "38%", "sinter-feed"],
    desc: "Manganese fines 38% Mn for sintering / agglomeration",
    coa: [
      ["Mn Content", "38.0% Min"],
      ["Fe Content", "12.0% Max"],
      ["SiO2", "12.0% Max"],
      ["Al2O3", "6.0% Max"],
      ["Phosphorus (P)", "0.15% Max"],
      ["Sulfur (S)", "0.05% Max"],
      ["Moisture", "8.0% Max"],
      ["Size <10mm", "85% Min"],
      ["Size <0.15mm", "20% Max"],
      ["Mn/Fe Ratio", "3.0 Min"],
      ["Physical", "Fines"],
    ],
    spec: "ORIGIN: South Africa/Ghana/Indonesia. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: Priced per dmtu (38% Mn basis). HANDLING: Store under cover; keep dry. No shelf life.",
  }),
  p({
    sku: "ORE-MAN-03-020",
    name: "Sintered Manganese 48% Mn",
    category: "ores",
    hs: "2602000000",
    price: 230,
    cap20: 25000, cap40: 27000,
    tags: ["manganese", "sintered", "48%", "BF-grade"],
    desc: "Sintered manganese ore 48% Mn for blast furnace / ferromanganese",
    coa: [
      ["Mn Content", "48.0% Min"],
      ["Fe Content", "6.0% Max"],
      ["SiO2", "8.0% Max"],
      ["Al2O3", "4.0% Max"],
      ["Phosphorus (P)", "0.10% Max"],
      ["Sulfur (S)", "0.03% Max"],
      ["Moisture", "3.0% Max"],
      ["Size (5-40mm)", "90% Min"],
      ["Size <5mm", "5% Max"],
      ["Mn/Fe Ratio", "7.0 Min"],
      ["Form", "Sintered"],
    ],
    spec: "ORIGIN: South Africa/India. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: Sintered product per spec for ferromanganese. HANDLING: Store under cover; keep dry. No shelf life.",
  }),
  p({
    sku: "ORE-MAN-04-021",
    name: "Battery Grade Manganese 42% Mn",
    category: "ores",
    hs: "2602000000",
    price: 350,
    cap20: 24000, cap40: 27000,
    tags: ["manganese", "battery-grade", "42%", "EMD"],
    desc: "Battery-grade manganese ore 42% Mn (low impurities) for EMD/CAM",
    coa: [
      ["Mn Content", "42.0% Min"],
      ["Fe Content", "3.0% Max"],
      ["SiO2", "5.0% Max"],
      ["Al2O3", "3.0% Max"],
      ["Phosphorus (P)", "0.05% Max"],
      ["Sulfur (S)", "0.02% Max"],
      ["Heavy Metals (Pb/Cd/As)", "0.005% each Max"],
      ["Copper (Cu)", "0.005% Max"],
      ["Nickel (Ni)", "0.005% Max"],
      ["Cobalt (Co)", "0.005% Max"],
      ["Use", "EMD / CAM precursor"],
    ],
    spec: "ORIGIN: Gabon/Australia/Brazil. PACKAGING: In 1MT bulk bags on wooden pallets, strapped. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, battery material spec sheet. QUALITY: Low-impurity grade for battery precursors. HANDLING: Store in dry covered area; protect from contamination. No shelf life. Stack max 2 pallets high.",
  }),

  // ───────────────────────── CHR — Chromite (4) ─────────────────────────
  p({
    sku: "ORE-CHR-01-022",
    name: "Chromite Metallurgical Lump 48% Cr2O3",
    category: "ores",
    hs: "2610000000",
    price: 220,
    cap20: 25000, cap40: 27000,
    tags: ["chromite", "metallurgical", "48%", "ferrochrome"],
    desc: "Metallurgical-grade chromite lump 48% Cr2O3 for ferrochrome production",
    coa: [
      ["Cr2O3", "48.0% Min"],
      ["Cr/Fe Ratio", "2.5 Min"],
      ["FeO", "14-22% Typical"],
      ["SiO2", "4.0% Max"],
      ["Al2O3", "12% Typical"],
      ["MgO", "12-18% Typical"],
      ["CaO", "1.0% Max"],
      ["Phosphorus (P)", "0.005% Max"],
      ["Sulfur (S)", "0.02% Max"],
      ["Size (10-100mm)", "85% Min"],
      ["Physical", "Lump"],
    ],
    spec: "ORIGIN: South Africa/Zimbabwe/Kazakhstan. PACKAGING: Bulk vessel shipment or in 1MT bulk bags for container loads. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: Per UG2/Metallurgical spec. HANDLING: Store under cover; keep dry. No shelf life.",
  }),
  p({
    sku: "ORE-CHR-02-023",
    name: "Chromite Foundry Sand 46% Cr2O3",
    category: "ores",
    hs: "2610000000",
    price: 270,
    cap20: 24000, cap40: 27000,
    tags: ["chromite", "foundry-sand", "46%", "AFS"],
    desc: "Chromite foundry sand 46% Cr2O3 for steel casting molds/cores",
    coa: [
      ["Cr2O3", "46.0% Min"],
      ["SiO2", "1.0% Max"],
      ["Fe2O3", "26% Typical"],
      ["Al2O3", "16% Typical"],
      ["MgO", "10% Typical"],
      ["CaO", "0.5% Max"],
      ["AFS Grain Fineness", "45-55"],
      ["Moisture", "0.2% Max"],
      ["Acid Demand", "5 ml Max"],
      ["Size Distribution", "Tight (95% in spec)"],
      ["Use", "Foundry molding sand"],
    ],
    spec: "ORIGIN: South Africa/Philippines. PACKAGING: In 1MT or 1.5MT bulk bags on wooden pallets, strapped. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, foundry sand spec sheet. QUALITY: AFS-grade foundry sand per ISO 13545. HANDLING: Store in dry covered area; protect from moisture. No shelf life.",
  }),
  p({
    sku: "ORE-CHR-03-024",
    name: "Chromite Refractory 45% Cr2O3",
    category: "ores",
    hs: "2610000000",
    price: 200,
    cap20: 25000, cap40: 27000,
    tags: ["chromite", "refractory", "45%", "brick"],
    desc: "Refractory-grade chromite ore 45% Cr2O3 for refractory bricks",
    coa: [
      ["Cr2O3", "45.0% Min"],
      ["SiO2", "5.0% Max"],
      ["Fe2O3", "22% Typical"],
      ["Al2O3", "15% Typical"],
      ["MgO", "14% Typical"],
      ["CaO", "1.0% Max"],
      ["TiO2", "1.0% Max"],
      ["LOI", "1.0% Max"],
      ["Refractoriness", "1700°C Min"],
      ["Size", "0-5 mm / lump"],
      ["Use", "Refractory bricks"],
    ],
    spec: "ORIGIN: South Africa/Turkey/Philippines. PACKAGING: Bulk vessel shipment or in 1MT bulk bags. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin. QUALITY: Refractory grade per industry spec. HANDLING: Store under cover; keep dry. No shelf life.",
  }),
  p({
    sku: "ORE-CHR-04-025",
    name: "Chromite Concentrate 42% Cr2O3",
    category: "ores",
    hs: "2610000000",
    price: 175,
    cap20: 24000, cap40: 27000,
    tags: ["chromite", "concentrate", "42%"],
    desc: "Chromite concentrate 42% Cr2O3 (gravity concentrate, fines)",
    coa: [
      ["Cr2O3", "42.0% Min"],
      ["Cr/Fe Ratio", "1.6 Min"],
      ["Fe Total", "20% Typical"],
      ["SiO2", "8.0% Max"],
      ["Al2O3", "12% Typical"],
      ["MgO", "14% Typical"],
      ["CaO", "1.0% Max"],
      ["Phosphorus (P)", "0.01% Max"],
      ["Moisture", "8.0% Max"],
      ["Size <0.5mm", "80% Min"],
      ["Form", "Concentrate fines"],
    ],
    spec: "ORIGIN: South Africa/Philippines/Turkey. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin. QUALITY: Gravity concentrate for sintering/pelletizing. HANDLING: Store under cover; keep dry. No shelf life.",
  }),

  // ───────────────────────── ZNO — Zinc ore (3) ─────────────────────────
  p({
    sku: "ORE-ZNO-01-026",
    name: "Sphalerite Concentrate 50% Zn",
    category: "ores",
    hs: "2608000000",
    price: 1150,
    cap20: 24000, cap40: 27000,
    tags: ["zinc", "concentrate", "sphalerite", "50%"],
    desc: "Sphalerite zinc concentrate 50% Zn for smelting",
    coa: [
      ["Zn Content", "50.0% Min"],
      ["Pb Content", "2.0% Max"],
      ["Fe Content", "10.0% Max"],
      ["Cu Content", "0.5% Max"],
      ["Cd Content", "0.3% Max"],
      ["As Content", "0.3% Max"],
      ["Sb Content", "0.05% Max"],
      ["SiO2", "4.0% Max"],
      ["Sulfur (S)", "30% Typical"],
      ["Moisture", "8.0% Max"],
      ["Inspection", "SGS/Intertek"],
    ],
    spec: "ORIGIN: Peru/Australia/Bolivia. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek assay at load/discharge, Certificate of Origin, Weight Certificate. QUALITY: Priced via TC + QP. HANDLING: Store under cover; keep dry. No shelf life. Penalty elements per contract.",
  }),
  p({
    sku: "ORE-ZNO-02-027",
    name: "Marmatite Concentrate 45% Zn",
    category: "ores",
    hs: "2608000000",
    price: 950,
    cap20: 24000, cap40: 27000,
    tags: ["zinc", "concentrate", "marmatite", "high-Fe"],
    desc: "Marmatite zinc concentrate 45% Zn (high-iron variety)",
    coa: [
      ["Zn Content", "45.0% Min"],
      ["Pb Content", "2.5% Max"],
      ["Fe Content", "14.0% Max"],
      ["Cu Content", "0.5% Max"],
      ["Cd Content", "0.3% Max"],
      ["As Content", "0.3% Max"],
      ["Sb Content", "0.05% Max"],
      ["SiO2", "4.0% Max"],
      ["Sulfur (S)", "29% Typical"],
      ["Moisture", "8.0% Max"],
      ["Mineralogy", "Marmatite (Fe-rich)"],
    ],
    spec: "ORIGIN: Peru/China/Namibia. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek assay, Certificate of Origin, Weight Certificate. QUALITY: Priced via TC + QP, higher Fe penalty typical. HANDLING: Store under cover; keep dry. No shelf life. Penalty elements per contract.",
  }),
  p({
    sku: "ORE-ZNO-03-028",
    name: "ROM Zinc Ore 8% Zn",
    category: "ores",
    hs: "2608000000",
    price: 80,
    cap20: 25000, cap40: 27000,
    tags: ["zinc", "ROM", "ore", "8%"],
    desc: "Run-of-Mine zinc ore 8% Zn (sphalerite) for direct milling",
    coa: [
      ["Zn Content", "8.0% Min"],
      ["Pb Content", "1.5% Max"],
      ["Fe Content", "12% Typical"],
      ["Cu Content", "0.2% Max"],
      ["Cd Content", "0.05% Max"],
      ["As Content", "0.10% Max"],
      ["SiO2", "40-55% Typical"],
      ["Al2O3", "5-10% Typical"],
      ["Sulfur (S)", "5-10% Typical"],
      ["Moisture", "5.0% Max"],
      ["Size", "0-200 mm ROM"],
    ],
    spec: "ORIGIN: Peru/Ireland/Bolivia. PACKAGING: Bulk in containers or vessel hold (loose). CERTIFICATIONS: SGS/Intertek inspection at load/discharge port, Certificate of Origin, Weight Certificate. QUALITY: ROM sulfide ore for flotation. HANDLING: Store on hard standing; protect from excessive moisture. No shelf life.",
  }),

  // ───────────────────────── PBO — Lead ore (3) ─────────────────────────
  p({
    sku: "ORE-PBO-01-029",
    name: "Galena Concentrate 65% Pb",
    category: "ores",
    hs: "2607000000",
    price: 1450,
    cap20: 24000, cap40: 27000,
    tags: ["lead", "concentrate", "galena", "65%"],
    desc: "Galena lead concentrate 65% Pb for smelting",
    coa: [
      ["Pb Content", "65.0% Min"],
      ["Zn Content", "3.0% Max"],
      ["Fe Content", "5.0% Max"],
      ["Cu Content", "1.0% Max"],
      ["As Content", "0.3% Max"],
      ["Sb Content", "0.3% Max"],
      ["Bi Content", "0.05% Max"],
      ["Ag Content", "500-2000 g/MT typical"],
      ["Sulfur (S)", "16% Typical"],
      ["Moisture", "8.0% Max"],
      ["Inspection", "SGS/Intertek"],
    ],
    spec: "ORIGIN: Peru/Australia/Bolivia. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek assay at load/discharge, Certificate of Origin, Weight Certificate. QUALITY: Priced via TC + QP + Ag credits. HANDLING: Store under cover; keep dry. No shelf life. Penalty elements per contract.",
  }),
  p({
    sku: "ORE-PBO-02-030",
    name: "Mixed Pb-Zn Concentrate",
    category: "ores",
    hs: "2607000000",
    price: 1100,
    cap20: 24000, cap40: 27000,
    tags: ["lead", "zinc", "mixed-concentrate", "polymetallic"],
    desc: "Mixed lead-zinc concentrate (Pb 35%, Zn 25%) for smelting",
    coa: [
      ["Pb Content", "35.0% Min"],
      ["Zn Content", "25.0% Min"],
      ["Fe Content", "8.0% Max"],
      ["Cu Content", "1.5% Max"],
      ["As Content", "0.4% Max"],
      ["Sb Content", "0.3% Max"],
      ["Bi Content", "0.05% Max"],
      ["Ag Content", "800-1500 g/MT typical"],
      ["Au Content", "1-5 g/MT typical"],
      ["Sulfur (S)", "22% Typical"],
      ["Moisture", "8.0% Max"],
    ],
    spec: "ORIGIN: Peru/Mexico/Iran. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek assay, Certificate of Origin, Weight Certificate. QUALITY: Polymetallic concentrate, priced via TC + QP + credits. HANDLING: Store under cover; keep dry. No shelf life. Penalty elements per contract.",
  }),
  p({
    sku: "ORE-PBO-03-031",
    name: "ROM Lead Ore 5% Pb",
    category: "ores",
    hs: "2607000000",
    price: 75,
    cap20: 25000, cap40: 27000,
    tags: ["lead", "ROM", "ore", "5%"],
    desc: "Run-of-Mine lead ore 5% Pb (galena) for direct milling",
    coa: [
      ["Pb Content", "5.0% Min"],
      ["Zn Content", "1.5% Max"],
      ["Fe Content", "10% Typical"],
      ["Cu Content", "0.3% Max"],
      ["As Content", "0.10% Max"],
      ["Sb Content", "0.10% Max"],
      ["SiO2", "45-60% Typical"],
      ["Al2O3", "5-10% Typical"],
      ["Sulfur (S)", "3-8% Typical"],
      ["Moisture", "5.0% Max"],
      ["Size", "0-200 mm ROM"],
    ],
    spec: "ORIGIN: Peru/Mexico/Bolivia. PACKAGING: Bulk in containers or vessel hold (loose). CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: ROM sulfide ore for flotation. HANDLING: Store on hard standing; protect from excessive moisture. No shelf life.",
  }),

  // ───────────────────────── TNO — Tin ore (3) ─────────────────────────
  p({
    sku: "ORE-TNO-01-032",
    name: "Cassiterite Concentrate 70% Sn",
    category: "ores",
    hs: "2609000000",
    price: 22000,
    cap20: 24000, cap40: 27000,
    tags: ["tin", "concentrate", "cassiterite", "70%"],
    desc: "Cassiterite tin concentrate 70% Sn for smelting",
    coa: [
      ["Sn Content", "70.0% Min"],
      ["Pb Content", "0.5% Max"],
      ["As Content", "0.3% Max"],
      ["Sb Content", "0.2% Max"],
      ["Bi Content", "0.05% Max"],
      ["Fe Content", "2.0% Max"],
      ["Sulfur (S)", "0.5% Max"],
      ["WO3 Content", "0.5% Max"],
      ["SiO2", "5.0% Max"],
      ["Moisture", "5.0% Max"],
      ["Form", "Concentrate"],
    ],
    spec: "ORIGIN: Indonesia/Myanmar/Bolivia. PACKAGING: In 1MT bulk bags or steel drums on pallets, strapped. CERTIFICATIONS: SGS/Intertek assay, Certificate of Origin, Weight Certificate. QUALITY: Priced via LME Sn less smelting/refining charges. HANDLING: Store in dry covered area. No shelf life. Tin conflict-mineral due diligence (OECD).",
  }),
  p({
    sku: "ORE-TNO-02-033",
    name: "Tin Concentrate 60% Sn",
    category: "ores",
    hs: "2609000000",
    price: 16000,
    cap20: 24000, cap40: 27000,
    tags: ["tin", "concentrate", "60%", "cassiterite"],
    desc: "Tin concentrate 60% Sn (medium grade) for smelting",
    coa: [
      ["Sn Content", "60.0% Min"],
      ["Pb Content", "1.0% Max"],
      ["As Content", "0.5% Max"],
      ["Sb Content", "0.3% Max"],
      ["Bi Content", "0.10% Max"],
      ["Fe Content", "4.0% Max"],
      ["Sulfur (S)", "1.0% Max"],
      ["WO3 Content", "1.0% Max"],
      ["SiO2", "8.0% Max"],
      ["Moisture", "8.0% Max"],
      ["Form", "Concentrate"],
    ],
    spec: "ORIGIN: Indonesia/Nigeria/Bolivia. PACKAGING: In 1MT bulk bags or steel drums on pallets, strapped. CERTIFICATIONS: SGS/Intertek assay, Certificate of Origin, Weight Certificate. QUALITY: Priced via LME Sn less smelting/refining charges. HANDLING: Store in dry covered area. No shelf life. Tin conflict-mineral due diligence (OECD).",
  }),
  p({
    sku: "ORE-TNO-03-034",
    name: "Alluvial Tin Ore",
    category: "ores",
    hs: "2609000000",
    price: 1800,
    cap20: 25000, cap40: 27000,
    tags: ["tin", "alluvial", "ore", "placer"],
    desc: "Alluvial tin ore (placer cassiterite) 3-5% Sn for concentration",
    coa: [
      ["Sn Content", "3.0-5.0%"],
      ["Sn Mineralogy", "Cassiterite"],
      ["Pb Content", "0.5% Max"],
      ["As Content", "0.2% Max"],
      ["Fe Content", "10% Typical"],
      ["WO3 Content", "0.5% Max"],
      ["SiO2", "55-70% Typical"],
      ["Bulk Density", "1.6-1.8 t/m³"],
      ["Size", "0-10 mm alluvial"],
      ["Moisture", "10.0% Max"],
      ["Form", "Alluvial sand/gravel"],
    ],
    spec: "ORIGIN: Indonesia/Nigeria/Myanmar. PACKAGING: Bulk in containers or vessel hold (loose). CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: Alluvial placer ore for gravity concentration. HANDLING: Store on hard standing; protect from excessive moisture. No shelf life. Tin conflict-mineral due diligence (OECD).",
  }),

  // ───────────────────────── NIO — Nickel ore (3) ─────────────────────────
  p({
    sku: "ORE-NIO-01-035",
    name: "Nickel Laterite 1.8% Ni",
    category: "ores",
    hs: "2604000000",
    price: 35,
    cap20: 25000, cap40: 27000,
    tags: ["nickel", "laterite", "1.8%", "NPI"],
    desc: "Nickel laterite ore 1.8% Ni (limonitic) for NPI / ferro-nickel",
    coa: [
      ["Ni Content", "1.80% Min"],
      ["Co Content", "0.05% Min"],
      ["Fe Content", "40-50% Typical"],
      ["MgO", "5-15% Typical"],
      ["SiO2", "10-25% Typical"],
      ["Al2O3", "5-10% Typical"],
      ["Cr2O3", "1-3% Typical"],
      ["Moisture", "30-35% Typical"],
      ["Size", "0-100 mm ROM"],
      ["Type", "Limonitic laterite"],
      ["Use", "NPI / FeNi feed"],
    ],
    spec: "ORIGIN: Indonesia/Philippines/New Caledonia. PACKAGING: Bulk vessel shipment (geared/handysize), or bulk in containers (max 25 wmt). CERTIFICATIONS: SGS/Intertek inspection at load/discharge, Certificate of Origin, Weight Certificate (wet/dry). QUALITY: Priced per wmt + Ni premium. HANDLING: Liquefaction risk (IMSBC Code Group A) — moisture limits critical. No shelf life.",
  }),
  p({
    sku: "ORE-NIO-02-036",
    name: "Nickel Laterite 2.0% Ni",
    category: "ores",
    hs: "2604000000",
    price: 45,
    cap20: 25000, cap40: 27000,
    tags: ["nickel", "laterite", "2.0%", "HPAL"],
    desc: "Nickel laterite ore 2.0% Ni (saprolite) for ferronickel / HPAL",
    coa: [
      ["Ni Content", "2.00% Min"],
      ["Co Content", "0.05% Min"],
      ["Fe Content", "12-20% Typical"],
      ["MgO", "20-30% Typical"],
      ["SiO2", "35-45% Typical"],
      ["Al2O3", "3-8% Typical"],
      ["Cr2O3", "0.5-2% Typical"],
      ["Moisture", "25-30% Typical"],
      ["Size", "0-100 mm ROM"],
      ["Type", "Saprolitic laterite"],
      ["Use", "FeNi / HPAL"],
    ],
    spec: "ORIGIN: Indonesia/Philippines/New Caledonia. PACKAGING: Bulk vessel shipment (geared/handysize), or bulk in containers (max 25 wmt). CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: Priced per wmt + Ni premium. HANDLING: Liquefaction risk (IMSBC Code Group A) — moisture limits critical. No shelf life.",
  }),
  p({
    sku: "ORE-NIO-03-037",
    name: "Nickel Sulfide Concentrate 12% Ni",
    category: "ores",
    hs: "2604000000",
    price: 3500,
    cap20: 24000, cap40: 27000,
    tags: ["nickel", "sulfide", "concentrate", "12%"],
    desc: "Nickel sulfide concentrate 12% Ni (pentlandite) for smelting",
    coa: [
      ["Ni Content", "12.0% Min"],
      ["Cu Content", "1.5-3.0%"],
      ["Co Content", "0.3-0.6%"],
      ["Fe Content", "30-38%"],
      ["Sulfur (S)", "28-34%"],
      ["MgO Content", "5.0% Max"],
      ["SiO2", "8.0% Max"],
      ["As Content", "0.1% Max"],
      ["Pb Content", "0.05% Max"],
      ["Moisture", "8.0% Max"],
      ["Inspection", "SGS/Intertek"],
    ],
    spec: "ORIGIN: Canada/Russia/Australia. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek assay at load/discharge, Certificate of Origin, Weight Certificate. QUALITY: Priced via TC + QP + Co/PGE credits. HANDLING: Store under cover; keep dry. No shelf life. Penalty elements per contract.",
  }),

  // ───────────────────────── XRO — Other ores (3) ─────────────────────────
  p({
    sku: "ORE-XRO-01-038",
    name: "Ilmenite 50% TiO2",
    category: "ores",
    hs: "2614000000",
    price: 240,
    cap20: 25000, cap40: 27000,
    tags: ["ilmenite", "titanium", "TiO2", "concentrate"],
    desc: "Ilmenite concentrate 50% TiO2 for TiO2 pigment / titanium metal",
    coa: [
      ["TiO2", "50.0% Min"],
      ["Fe Total", "35% Typical"],
      ["Fe2O3", "20% Typical"],
      ["FeO", "30% Typical"],
      ["SiO2", "2.0% Max"],
      ["Al2O3", "1.5% Max"],
      ["MgO", "1.5% Max"],
      ["CaO", "0.3% Max"],
      ["MnO", "1.0% Max"],
      ["Size", "0.1-0.5 mm typical"],
      ["Use", "TiO2 pigment / slag"],
    ],
    spec: "ORIGIN: Australia/South Africa/India. PACKAGING: Bulk in containers or vessel hold; or in 1MT bulk bags on pallets. CERTIFICATIONS: SGS/Intertek inspection, Certificate of Origin, Weight Certificate. QUALITY: Per chloride/sulfate process pigment spec. HANDLING: Store under cover; keep dry. No shelf life.",
  }),
  p({
    sku: "ORE-XRO-02-039",
    name: "Tungsten Concentrate 65% WO3",
    category: "ores",
    hs: "2611000000",
    price: 28000,
    cap20: 24000, cap40: 27000,
    tags: ["tungsten", "concentrate", "WO3", "65%"],
    desc: "Tungsten concentrate 65% WO3 (scheelite/wolframite) for APT production",
    coa: [
      ["WO3 Content", "65.0% Min"],
      ["Sn Content", "0.5% Max"],
      ["As Content", "0.2% Max"],
      ["P Content", "0.05% Max"],
      ["S Content", "0.7% Max"],
      ["Mo Content", "0.05% Max"],
      ["Cu Content", "0.10% Max"],
      ["Pb Content", "0.10% Max"],
      ["SiO2", "5.0% Max"],
      ["Moisture", "5.0% Max"],
      ["Mineralogy", "Scheelite / Wolframite"],
    ],
    spec: "ORIGIN: China/Russia/Bolivia/Rwanda. PACKAGING: In steel drums (200-250 kg) on pallets, strapped. CERTIFICATIONS: SGS/Intertek assay, Certificate of Origin, Weight Certificate. QUALITY: Priced per MTU (10 kg WO3). HANDLING: Store in dry covered area. No shelf life. Conflict-mineral due diligence (OECD) for 3T.",
  }),
  p({
    sku: "ORE-XRO-03-040",
    name: "Molybdenum Concentrate 50% Mo",
    category: "ores",
    hs: "2613100000",
    price: 12000,
    cap20: 24000, cap40: 27000,
    tags: ["molybdenum", "concentrate", "Mo", "50%"],
    desc: "Molybdenum concentrate 50% Mo (molybdenite) for roasting to MoO3",
    coa: [
      ["Mo Content", "50.0% Min"],
      ["Sulfur (S)", "30-35% Typical"],
      ["Cu Content", "0.3% Max"],
      ["Pb Content", "0.1% Max"],
      ["Sn Content", "0.05% Max"],
      ["P Content", "0.05% Max"],
      ["As Content", "0.05% Max"],
      ["SiO2", "5.0% Max"],
      ["CaO", "1.0% Max"],
      ["Moisture", "5.0% Max"],
      ["Mineralogy", "Molybdenite (MoS2)"],
    ],
    spec: "ORIGIN: Chile/USA/China/Peru. PACKAGING: In 1MT bulk bags or steel drums on pallets, strapped. CERTIFICATIONS: SGS/Intertek assay, Certificate of Origin, Weight Certificate. QUALITY: Priced via LME Mo or per Platts. HANDLING: Store in dry covered area. No shelf life. Roast to technical MoO3 for downstream alloying.",
  }),
];

export default oreProducts;
