// Aspidus DMCC — Fertilizer catalog (40 products)
// Categories: NIT (Nitrogen) 10, PHO (Phosphate) 8, POT (Potash) 6, NPK (Blends) 10, SPE (Specialty) 6
// Prices in USD per MT FOB; HS codes are 10-digit.

export interface CoaParam { name: string; value: string; }
export interface Logistics { cap20: number | null; cap40: number | null; }
export interface SeedProduct {
  sku: string; name: string; category: string; unit: string;
  price: number; currency: string; cost: number;
  stock: number; reorder_level: number; active: boolean;
  description: string; hs_code: string;
  brand: null; shelf_life: string | null; image_url: null;
  logistics: Logistics; coa_params: CoaParam[];
  detailed_spec: string; tags: string[];
}

function p(o: {
  sku: string; name: string; category: string;
  hs: string; price: number; unit?: string;
  coa: [string, string][]; spec: string;
  cap20?: number | null; cap40?: number | null;
  tags?: string[]; shelfLife?: string | null;
  desc?: string; stock?: number;
}): SeedProduct {
  const unit = o.unit ?? "MT";
  const stock = o.stock ?? 50000;
  return {
    sku: o.sku, name: o.name, category: o.category, unit,
    price: o.price, currency: "USD", cost: o.price, stock,
    reorder_level: Math.max(1, Math.floor(stock / 20)),
    active: true, description: o.desc ?? o.name,
    hs_code: o.hs, brand: null,
    shelf_life: o.shelfLife ?? null, image_url: null,
    logistics: { cap20: o.cap20 ?? null, cap40: o.cap40 ?? null },
    coa_params: o.coa.map(([name, value]) => ({ name, value })),
    detailed_spec: o.spec, tags: o.tags ?? [],
  };
}

const SHELF = "12 months from production under proper storage";
const BAG20 = 24000;
const BAG40 = 27000;
const BULK20 = 24000;
const BULK40 = 27000;
const LIQ20 = 20000;
const LIQ40 = 24000;

export const fertilizerProducts: SeedProduct[] = [
  // ============ NIT (Nitrogen) — 10 ============
  p({
    sku: "FER-NIT-01-001",
    name: "Urea 46% N Granular",
    category: "fertilizers",
    hs: "3102100000",
    price: 360,
    cap20: BAG20, cap40: BAG40,
    tags: ["nitrogen", "urea", "granular"],
    shelfLife: SHELF,
    desc: "Urea 46% N Granular — premium nitrogen fertilizer, granular form.",
    coa: [
      ["Nitrogen (N) Content", "46.0% Min"],
      ["Biuret", "1.0% Max"],
      ["Moisture", "0.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Free Ammonia", "160 ppm Max"],
      ["Formaldehyde", "0.4% Max"],
      ["Color", "White/Off-white"],
      ["Bulk Density", "0.72-0.77 kg/l"],
      ["Crushing Strength", "2-3 kg/cm2"],
      ["Coating", "Anti-caking treated"],
    ],
    spec: "ORIGIN: Russia/Ukraine. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk vessel. CERTIFICATIONS: SGS/Intertek inspection, COO, COQ. QUALITY: GOST 2081-2010 / ISO 22241. HANDLING: Store in dry, covered warehouse; keep away from moisture, heat, and oxidizers. Hygroscopic — seal broken bags immediately. Hazard class 5.1 for prilled; handle per IMDG.",
  }),
  p({
    sku: "FER-NIT-01-002",
    name: "Urea 46% N Prilled",
    category: "fertilizers",
    hs: "3102100000",
    price: 370,
    cap20: BAG20, cap40: BAG40,
    tags: ["nitrogen", "urea", "prilled"],
    shelfLife: SHELF,
    desc: "Urea 46% N Prilled — small prills for foliar and solution applications.",
    coa: [
      ["Nitrogen (N) Content", "46.0% Min"],
      ["Biuret", "0.9% Max"],
      ["Moisture", "0.5% Max"],
      ["Particle Size (1-2mm)", "90% Min"],
      ["Free Ammonia", "150 ppm Max"],
      ["Formaldehyde", "0.4% Max"],
      ["Color", "White"],
      ["Bulk Density", "0.72-0.76 kg/l"],
      ["Softening Point", "130C"],
      ["Coating", "Anti-caking treated"],
    ],
    spec: "ORIGIN: Qatar/Oman. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk vessel. CERTIFICATIONS: SGS/Intertek inspection, COO, COQ. QUALITY: ISO 22241-1 prilled urea, GOST 2081-2010. HANDLING: Store dry under cover; avoid moisture. Hazard class 5.1 (oxidizing) per IMDG. Seal bags after opening. Shelf life 12 months.",
  }),
  p({
    sku: "FER-NIT-01-003",
    name: "Ammonium Nitrate 33.5% N",
    category: "fertilizers",
    hs: "3102300000",
    price: 400,
    cap20: BAG20, cap40: BAG40,
    tags: ["nitrogen", "ammonium-nitrate", "high-n"],
    shelfLife: SHELF,
    desc: "Ammonium Nitrate 33.5% N — high-nitrogen fertilizer for cereal crops.",
    coa: [
      ["Total Nitrogen (N)", "33.5% Min"],
      ["Ammoniacal N", "16.7%"],
      ["Nitrate N", "16.8%"],
      ["Moisture", "0.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Oil Retention", "4.0-5.0%"],
      ["Bulk Density", "0.85-0.95 kg/l"],
      ["Color", "Off-white/Yellowish"],
      ["Caking", "Anti-caking treated"],
      ["Free Acid", "0.02% Max"],
    ],
    spec: "ORIGIN: Russia/Egypt. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs. CERTIFICATIONS: SGS/Intertek, COO, COQ, AN-FO Security Certificate. QUALITY: GOST 2-85 / EU Reg 2003/2003. HANDLING: Strong oxidizer, hazard class 5.1. Store separately from combustibles, organics, acids. Keep dry and cool. UN 1942. Shelf life 6-9 months under proper storage.",
  }),
  p({
    sku: "FER-NIT-01-004",
    name: "Ammonium Sulfate 21% N",
    category: "fertilizers",
    hs: "3102210000",
    price: 260,
    cap20: BAG20, cap40: BAG40,
    tags: ["nitrogen", "sulfate", "sulfur"],
    shelfLife: SHELF,
    desc: "Ammonium Sulfate 21% N + 24% S — dual nutrient source for alkaline soils.",
    coa: [
      ["Nitrogen (N) Content", "21.0% Min"],
      ["Sulfur (S) Content", "24.0% Min"],
      ["Free Acid (H2SO4)", "0.05% Max"],
      ["Moisture", "0.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Color", "White/Cream"],
      ["Bulk Density", "0.85-1.05 kg/l"],
      ["Heavy Metals (as Pb)", "5 ppm Max"],
      ["Arsenic (As)", "2 ppm Max"],
      ["Free Flowing", "Yes"],
    ],
    spec: "ORIGIN: China/Turkmenistan. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: GB 535-1995 / ISO 22241. HANDLING: Store in dry, covered warehouse; non-hazardous. Hygroscopic — seal broken bags. Avoid strong alkalis. Shelf life 12 months under proper storage.",
  }),
  p({
    sku: "FER-NIT-01-005",
    name: "UAN 32% Solution",
    category: "fertilizers",
    hs: "3102800000",
    price: 310,
    unit: "MT",
    cap20: LIQ20, cap40: LIQ40,
    tags: ["nitrogen", "uan", "liquid", "solution"],
    shelfLife: SHELF,
    desc: "UAN 32% Solution — liquid nitrogen blend for direct application and fertigation.",
    coa: [
      ["Total Nitrogen (N)", "32.0% Min"],
      ["Ammoniacal N", "8.0%"],
      ["Nitrate N", "8.0%"],
      ["Urea N", "16.0%"],
      ["Specific Gravity (15C)", "1.32-1.33"],
      ["pH", "6.5-7.5"],
      ["Free Ammonia", "0.1% Max"],
      ["Biuret", "0.5% Max"],
      ["Color", "Clear to pale yellow"],
      ["Salt-Out Temp", "-18C"],
    ],
    spec: "ORIGIN: USA/Russia. PACKAGING: Bulk in ISO tanks, road tankers, or 1000L IBC totes. CERTIFICATIONS: SGS/Intertek, COO, COQ, REACH registration. QUALITY: ISO 18643. HANDLING: Mildly corrosive; store in stainless steel or coated tanks. Avoid contact with galvanized metals and strong oxidizers. pH neutral to slightly alkaline. Shelf life 12 months in sealed containers.",
  }),
  p({
    sku: "FER-NIT-01-006",
    name: "UAN 28% Solution",
    category: "fertilizers",
    hs: "3102800000",
    price: 290,
    cap20: LIQ20, cap40: LIQ40,
    tags: ["nitrogen", "uan", "liquid", "solution"],
    shelfLife: SHELF,
    desc: "UAN 28% Solution — cold-weather liquid nitrogen fertilizer.",
    coa: [
      ["Total Nitrogen (N)", "28.0% Min"],
      ["Ammoniacal N", "7.0%"],
      ["Nitrate N", "7.0%"],
      ["Urea N", "14.0%"],
      ["Specific Gravity (15C)", "1.28-1.29"],
      ["pH", "6.5-7.5"],
      ["Free Ammonia", "0.1% Max"],
      ["Biuret", "0.4% Max"],
      ["Color", "Clear to pale yellow"],
      ["Salt-Out Temp", "-22C"],
    ],
    spec: "ORIGIN: USA/Netherlands. PACKAGING: Bulk ISO tanks, road tankers, 1000L IBC totes. CERTIFICATIONS: SGS/Intertek, COO, COQ, REACH. QUALITY: ISO 18643. HANDLING: Mildly corrosive; store in stainless steel, HDPE, or coated tanks. Avoid galvanized metals and strong oxidizers. Low salt-out temperature suits cold climates. Shelf life 12 months sealed.",
  }),
  p({
    sku: "FER-NIT-01-007",
    name: "CAN (Calcium Ammonium Nitrate) 27% N",
    category: "fertilizers",
    hs: "3102400000",
    price: 330,
    cap20: BAG20, cap40: BAG40,
    tags: ["nitrogen", "can", "calcium"],
    shelfLife: SHELF,
    desc: "CAN 27% N + 8% Ca — safer alternative to ammonium nitrate, ideal for acidic soils.",
    coa: [
      ["Total Nitrogen (N)", "27.0% Min"],
      ["Ammoniacal N", "13.5%"],
      ["Nitrate N", "13.5%"],
      ["Calcium Carbonate (CaCO3)", "20.0% Min"],
      ["Calcium (Ca)", "8.0% Min"],
      ["Magnesium (MgO)", "2.0% Min"],
      ["Moisture", "0.5% Max"],
      ["Particle Size (2-5mm)", "90% Min"],
      ["Color", "Grey/Off-white"],
      ["Bulk Density", "0.95-1.05 kg/l"],
    ],
    spec: "ORIGIN: Lithuania/Norway. PACKAGING: 50kg PP bags with PE inner liner, 500kg/1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Oxidizer class 5.1, UN 2067. Store dry under cover away from combustibles. Neutralizes acidic soils. Shelf life 12 months.",
  }),
  p({
    sku: "FER-NIT-01-008",
    name: "Aqua Ammonia 20% N",
    category: "fertilizers",
    hs: "2814100000",
    price: 250,
    cap20: LIQ20, cap40: LIQ40,
    tags: ["nitrogen", "ammonia", "liquid"],
    shelfLife: SHELF,
    desc: "Aqua Ammonia 20% N — aqueous ammonia solution for direct soil injection.",
    coa: [
      ["Ammonia (NH3) Content", "20.0% Min"],
      ["Nitrogen (N)", "16.5% Min"],
      ["Specific Gravity (15C)", "0.92"],
      ["pH", "11.5-12.0"],
      ["Free Ammonia Vapor", "Controlled"],
      ["Iron (Fe)", "5 ppm Max"],
      ["Carbon Dioxide (CO2)", "0.05% Max"],
      ["Color", "Colorless"],
      ["Chloride (Cl)", "5 ppm Max"],
      ["Storage Temp", "Avoid >30C"],
    ],
    spec: "ORIGIN: India/China. PACKAGING: Bulk ISO tanks (insulated), road tankers, or 1000L IBC totes. CERTIFICATIONS: SGS/Intertek, COO, COQ, REACH. QUALITY: IS 7986-1976 / ASTM E299. HANDLING: Corrosive, UN 2672 (8). Pressurized/vented tanks required. Use PPE; ammonia vapor is toxic. Store cool (<30C), away from acids and oxidizers. Shelf life 12 months.",
  }),
  p({
    sku: "FER-NIT-01-009",
    name: "Ammonium Chloride 25% N",
    category: "fertilizers",
    hs: "2827100000",
    price: 220,
    cap20: BAG20, cap40: BAG40,
    tags: ["nitrogen", "chloride", "rice"],
    shelfLife: SHELF,
    desc: "Ammonium Chloride 25% N — chloride-based nitrogen for rice and palm crops.",
    coa: [
      ["Nitrogen (N) Content", "25.0% Min"],
      ["Ammonium Chloride (NH4Cl)", "99.0% Min"],
      ["Moisture", "1.0% Max"],
      ["Sodium (Na)", "0.5% Max"],
      ["Iron (Fe)", "0.01% Max"],
      ["Heavy Metals (as Pb)", "5 ppm Max"],
      ["Sulfate (SO4)", "0.02% Max"],
      ["Particle Size", "Powder/Granular"],
      ["Color", "White"],
      ["Bulk Density", "0.55-0.60 kg/l"],
    ],
    spec: "ORIGIN: China/Japan. PACKAGING: 25kg/50kg PP bags with PE inner liner, 1000kg FIBCs. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: GB 2946-2018 / JIS K1442. HANDLING: Store dry under cover; non-hazardous but hygroscopic. Avoid strong alkalis (releases NH3) and oxidizers. Suitable for chloride-tolerant crops. Shelf life 12 months.",
  }),
  p({
    sku: "FER-NIT-01-010",
    name: "Sulfur-Coated Urea 40% N",
    category: "fertilizers",
    hs: "3102900000",
    price: 480,
    cap20: BAG20, cap40: BAG40,
    tags: ["nitrogen", "sulfur", "slow-release"],
    shelfLife: SHELF,
    desc: "Sulfur-Coated Urea 40% N — controlled-release nitrogen with added sulfur.",
    coa: [
      ["Total Nitrogen (N)", "40.0% Min"],
      ["Urea N", "37.0%"],
      ["Sulfur (S) Content", "10.0% Min"],
      ["Slow-Release N (7-day)", "30% Min"],
      ["Slow-Release N (28-day)", "70% Min"],
      ["Moisture", "0.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Coating Uniformity", "95% Min"],
      ["Color", "Yellow/Golden"],
      ["Bulk Density", "0.75-0.80 kg/l"],
    ],
    spec: "ORIGIN: USA/Korea. PACKAGING: 25kg/50kg PP bags with PE inner liner, 1000kg FIBCs. CERTIFICATIONS: SGS/Intertek, COO, COQ, APEP. QUALITY: ISO 18643 controlled-release. HANDLING: Store dry under cover; non-hazardous. Sulfur coating buffers release — ideal for turf, horticulture, and long-cycle crops. Shelf life 24 months sealed.",
  }),

  // ============ PHO (Phosphate) — 8 ============
  p({
    sku: "FER-PHO-01-001",
    name: "DAP 18-46-0",
    category: "fertilizers",
    hs: "3105300000",
    price: 620,
    cap20: BAG20, cap40: BAG40,
    tags: ["phosphate", "dap", "npk-base"],
    shelfLife: SHELF,
    desc: "Diammonium Phosphate 18-46-0 — high-phosphorus fertilizer for root development.",
    coa: [
      ["Total Nitrogen (N)", "18.0% Min"],
      ["Available P2O5", "46.0% Min"],
      ["Moisture", "1.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Free Acid", "0.1% Max"],
      ["Cadmium (Cd)", "10 mg/kg Max"],
      ["Lead (Pb)", "5 mg/kg Max"],
      ["Arsenic (As)", "5 mg/kg Max"],
      ["Color", "Brown/Dark brown"],
      ["Bulk Density", "0.95-1.05 kg/l"],
    ],
    spec: "ORIGIN: Morocco/Saudi Arabia. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; mildly acidic. Hygroscopic — seal broken bags. Heavy metals compliant with EU Fertilizer Reg. Shelf life 12 months.",
  }),
  p({
    sku: "FER-PHO-01-002",
    name: "MAP 11-52-0",
    category: "fertilizers",
    hs: "3105300000",
    price: 640,
    cap20: BAG20, cap40: BAG40,
    tags: ["phosphate", "map", "high-p"],
    shelfLife: SHELF,
    desc: "Monoammonium Phosphate 11-52-0 — highest-phosphorus solid fertilizer.",
    coa: [
      ["Total Nitrogen (N)", "11.0% Min"],
      ["Available P2O5", "52.0% Min"],
      ["Moisture", "1.0% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["pH (1% solution)", "4.0-5.0"],
      ["Cadmium (Cd)", "10 mg/kg Max"],
      ["Lead (Pb)", "5 mg/kg Max"],
      ["Arsenic (As)", "5 mg/kg Max"],
      ["Color", "Brown/Grey"],
      ["Bulk Density", "0.90-1.00 kg/l"],
    ],
    spec: "ORIGIN: Morocco/USA. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; acidic pH aids P availability in alkaline soils. Hygroscopic — seal broken bags. Heavy metals compliant. Shelf life 12 months.",
  }),
  p({
    sku: "FER-PHO-01-003",
    name: "TSP 46% P2O5",
    category: "fertilizers",
    hs: "3103100000",
    price: 490,
    cap20: BAG20, cap40: BAG40,
    tags: ["phosphate", "tsp", "high-p"],
    shelfLife: SHELF,
    desc: "Triple Superphosphate 46% P2O5 — concentrated single-nutrient phosphate.",
    coa: [
      ["Available P2O5", "46.0% Min"],
      ["Water-Soluble P2O5", "42.0% Min"],
      ["Free Acid (as P2O5)", "2.0% Max"],
      ["Moisture", "3.0% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Cadmium (Cd)", "15 mg/kg Max"],
      ["Lead (Pb)", "10 mg/kg Max"],
      ["Arsenic (As)", "5 mg/kg Max"],
      ["Color", "Brown/Grey"],
      ["Bulk Density", "0.90-1.10 kg/l"],
    ],
    spec: "ORIGIN: Tunisia/Morocco. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; hygroscopic and slightly acidic. Seal broken bags. Avoid contact with alkaline materials. Shelf life 12 months.",
  }),
  p({
    sku: "FER-PHO-01-004",
    name: "SSP 16% P2O5",
    category: "fertilizers",
    hs: "3103100000",
    price: 230,
    cap20: BAG20, cap40: BAG40,
    tags: ["phosphate", "ssp", "low-cost"],
    shelfLife: SHELF,
    desc: "Single Superphosphate 16% P2O5 — economical phosphate with sulfur and calcium.",
    coa: [
      ["Available P2O5", "16.0% Min"],
      ["Water-Soluble P2O5", "14.0% Min"],
      ["Sulfur (S) Content", "11.0% Min"],
      ["Calcium (CaO)", "20.0% Min"],
      ["Free Acid (as P2O5)", "4.0% Max"],
      ["Moisture", "5.0% Max"],
      ["Particle Size (1-4mm)", "90% Min"],
      ["Cadmium (Cd)", "20 mg/kg Max"],
      ["Color", "Grey/Brown"],
      ["Bulk Density", "0.90-1.10 kg/l"],
    ],
    spec: "ORIGIN: India/Tunisia. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: IS 5796-2008 / EN 12022. HANDLING: Store dry under cover; hygroscopic and acidic. Seal broken bags. Suitable for acidic and sulfur-deficient soils. Shelf life 12 months.",
  }),
  p({
    sku: "FER-PHO-01-005",
    name: "Rock Phosphate 28% P2O5",
    category: "fertilizers",
    hs: "2510100000",
    price: 100,
    cap20: BULK20, cap40: BULK40,
    tags: ["phosphate", "rock", "mineral"],
    shelfLife: SHELF,
    desc: "Rock Phosphate 28% P2O5 — natural mineral for direct application or acidulation.",
    coa: [
      ["Total P2O5", "28.0% Min"],
      ["Available P2O5 (Citric)", "5.0% Min"],
      ["Calcium (CaO)", "45.0% Min"],
      ["Fluorine (F)", "3.5% Max"],
      ["Cadmium (Cd)", "20 mg/kg Max"],
      ["Lead (Pb)", "10 mg/kg Max"],
      ["Arsenic (As)", "10 mg/kg Max"],
      ["Chloride (Cl)", "0.1% Max"],
      ["Moisture", "2.0% Max"],
      ["Particle Size (<0.15mm)", "70% Min"],
    ],
    spec: "ORIGIN: Morocco/Algeria. PACKAGING: Bulk vessel, 1000kg FIBCs, or 50kg PP bags. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: ISO 22241 raw phosphate. HANDLING: Store dry under cover; dusty — use dust masks. Best applied to acidic soils (pH<6.5) or processed to SSP/TSP. Shelf life 24 months.",
  }),
  p({
    sku: "FER-PHO-01-006",
    name: "MKP 0-52-34",
    category: "fertilizers",
    hs: "2835240000",
    price: 1200,
    cap20: BAG20, cap40: BAG40,
    tags: ["phosphate", "mkp", "water-soluble", "fertigation"],
    shelfLife: SHELF,
    desc: "Monopotassium Phosphate 0-52-34 — fully water-soluble P+K for fertigation and foliar.",
    coa: [
      ["P2O5 Content", "52.0% Min"],
      ["K2O Content", "34.0% Min"],
      ["Water Solubility", "99.5% Min"],
      ["Moisture", "0.2% Max"],
      ["pH (1% solution)", "4.3-4.7"],
      ["Heavy Metals (as Pb)", "10 ppm Max"],
      ["Arsenic (As)", "3 ppm Max"],
      ["Fluoride (F)", "100 ppm Max"],
      ["Chloride (Cl)", "0.1% Max"],
      ["Appearance", "White powder/crystal"],
    ],
    spec: "ORIGIN: China/Israel. PACKAGING: 25kg PP bags with PE inner liner, 1000kg FIBCs. CERTIFICATIONS: SGS/Intertek, COO, COQ, REACH. QUALITY: ISO 18643 water-soluble grade. HANDLING: Store dry under cover; highly hygroscopic. Keep sealed. Use clean water for solution preparation (avoid Ca/Mg-rich water). Shelf life 24 months sealed.",
  }),
  p({
    sku: "FER-PHO-01-007",
    name: "NPS 19-38-7",
    category: "fertilizers",
    hs: "3105300000",
    price: 660,
    cap20: BAG20, cap40: BAG40,
    tags: ["phosphate", "nps", "npk-base", "sulfur"],
    shelfLife: SHELF,
    desc: "NPS 19-38-7 — N+P+S compound for sulfur-deficient soils.",
    coa: [
      ["Total Nitrogen (N)", "19.0% Min"],
      ["Available P2O5", "38.0% Min"],
      ["Sulfur (S) Content", "7.0% Min"],
      ["Moisture", "1.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Free Acid", "0.1% Max"],
      ["Cadmium (Cd)", "10 mg/kg Max"],
      ["Lead (Pb)", "5 mg/kg Max"],
      ["Color", "Brown/Grey"],
      ["Bulk Density", "0.95-1.05 kg/l"],
    ],
    spec: "ORIGIN: Morocco/Ethiopia. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; hygroscopic. Seal broken bags. Ideal for cereals and oilseeds in sulfur-deficient soils. Shelf life 12 months.",
  }),
  p({
    sku: "FER-PHO-01-008",
    name: "DAP Low Cadmium",
    category: "fertilizers",
    hs: "3105300000",
    price: 640,
    cap20: BAG20, cap40: BAG40,
    tags: ["phosphate", "dap", "low-cadmium", "premium"],
    shelfLife: SHELF,
    desc: "DAP Low Cadmium — premium DAP with <5 mg/kg Cd for organic and food-grade crops.",
    coa: [
      ["Total Nitrogen (N)", "18.0% Min"],
      ["Available P2O5", "46.0% Min"],
      ["Moisture", "1.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Free Acid", "0.1% Max"],
      ["Cadmium (Cd)", "5 mg/kg Max"],
      ["Lead (Pb)", "2 mg/kg Max"],
      ["Arsenic (As)", "2 mg/kg Max"],
      ["Mercury (Hg)", "0.5 mg/kg Max"],
      ["Color", "Brown/Dark brown"],
    ],
    spec: "ORIGIN: Saudi Arabia (Ma'aden). PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ, EU Organic compliant. QUALITY: EN 12022 / Reg EU 2019/1009 (PFC 1). HANDLING: Store dry under cover; hygroscopic. Premium low-Cd phosphate for food-grade and EU markets. Shelf life 12 months.",
  }),

  // ============ POT (Potash) — 6 ============
  p({
    sku: "FER-POT-01-001",
    name: "MOP 60% K2O White",
    category: "fertilizers",
    hs: "3104200000",
    price: 320,
    cap20: BAG20, cap40: BAG40,
    tags: ["potash", "mop", "white", "chloride"],
    shelfLife: SHELF,
    desc: "Muriate of Potash 60% K2O White — premium soluble potash for fertigation.",
    coa: [
      ["K2O Content", "60.0% Min"],
      ["Moisture", "0.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Sodium (Na)", "1.0% Max"],
      ["Magnesium (Mg)", "0.2% Max"],
      ["Calcium (Ca)", "0.5% Max"],
      ["Chloride Content", "47% Min"],
      ["Color", "White"],
      ["Bulk Density", "1.05-1.10 kg/l"],
      ["Insolubles", "0.5% Max"],
    ],
    spec: "ORIGIN: Canada/Belarus. PACKAGING: 25kg/50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; mildly hygroscopic. White grade preferred for fertigation, foliar, and chloride-tolerant crops. Shelf life 24 months.",
  }),
  p({
    sku: "FER-POT-01-002",
    name: "MOP 60% K2O Red/Pink",
    category: "fertilizers",
    hs: "3104200000",
    price: 300,
    cap20: BAG20, cap40: BAG40,
    tags: ["potash", "mop", "red", "standard"],
    shelfLife: SHELF,
    desc: "Muriate of Potash 60% K2O Red/Pink — standard granular potash for field crops.",
    coa: [
      ["K2O Content", "60.0% Min"],
      ["Moisture", "0.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Sodium (Na)", "1.5% Max"],
      ["Magnesium (Mg)", "0.3% Max"],
      ["Calcium (Ca)", "0.5% Max"],
      ["Chloride Content", "47% Min"],
      ["Color", "Red/Pink"],
      ["Bulk Density", "1.05-1.15 kg/l"],
      ["Insolubles", "0.5% Max"],
    ],
    spec: "ORIGIN: Russia/Canada. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; mildly hygroscopic. Iron oxide gives pink/red color — no impact on agronomic value. Shelf life 24 months.",
  }),
  p({
    sku: "FER-POT-01-003",
    name: "SOP 50% K2O",
    category: "fertilizers",
    hs: "3104300000",
    price: 600,
    cap20: BAG20, cap40: BAG40,
    tags: ["potash", "sop", "sulfate", "chloride-free"],
    shelfLife: SHELF,
    desc: "Sulfate of Potash 50% K2O — chloride-free potash for high-value and chloride-sensitive crops.",
    coa: [
      ["K2O Content", "50.0% Min"],
      ["Sulfur (S) Content", "18.0% Min"],
      ["Chloride (Cl)", "2.0% Max"],
      ["Moisture", "1.0% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Sodium (Na)", "1.0% Max"],
      ["Magnesium (Mg)", "0.5% Max"],
      ["Calcium (Ca)", "0.5% Max"],
      ["Color", "White/Off-white"],
      ["Bulk Density", "1.10-1.20 kg/l"],
    ],
    spec: "ORIGIN: USA/Belgium. PACKAGING: 25kg/50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; mildly hygroscopic. Ideal for tobacco, fruits, vegetables, and chloride-sensitive crops. Shelf life 24 months.",
  }),
  p({
    sku: "FER-POT-01-004",
    name: "Potassium Nitrate 13-0-46",
    category: "fertilizers",
    hs: "2834210000",
    price: 1000,
    cap20: BAG20, cap40: BAG40,
    tags: ["potash", "nitrate", "water-soluble", "fertigation"],
    shelfLife: SHELF,
    desc: "Potassium Nitrate 13-0-46 — fully water-soluble N+K for fertigation and greenhouse.",
    coa: [
      ["Nitrogen (N) Content", "13.0% Min"],
      ["K2O Content", "46.0% Min"],
      ["Water Solubility", "99.5% Min"],
      ["Moisture", "0.2% Max"],
      ["Chloride (Cl)", "0.2% Max"],
      ["Sodium (Na)", "0.5% Max"],
      ["Heavy Metals (as Pb)", "10 ppm Max"],
      ["Arsenic (As)", "3 ppm Max"],
      ["pH (1% solution)", "6.0-8.0"],
      ["Appearance", "White powder/crystal"],
    ],
    spec: "ORIGIN: Chile/Israel. PACKAGING: 25kg PP bags with PE inner liner, 1000kg FIBCs. CERTIFICATIONS: SGS/Intertek, COO, COQ, REACH. QUALITY: ISO 18643 water-soluble grade. HANDLING: Store dry under cover; highly hygroscopic and oxidizing. Hazard class 5.1, UN 1486. Keep away from combustibles. Shelf life 24 months sealed.",
  }),
  p({
    sku: "FER-POT-01-005",
    name: "KMS (Potassium Magnesium Sulfate)",
    category: "fertilizers",
    hs: "3104300000",
    price: 400,
    cap20: BAG20, cap40: BAG40,
    tags: ["potash", "kms", "magnesium", "sulfate"],
    shelfLife: SHELF,
    desc: "KMS — K+Mg+S three-nutrient potash for magnesium-deficient soils.",
    coa: [
      ["K2O Content", "22.0% Min"],
      ["Magnesium (MgO)", "11.0% Min"],
      ["Sulfur (S) Content", "22.0% Min"],
      ["Chloride (Cl)", "2.5% Max"],
      ["Moisture", "2.0% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Sodium (Na)", "1.5% Max"],
      ["Calcium (Ca)", "1.0% Max"],
      ["Color", "White/Grey"],
      ["Bulk Density", "1.05-1.15 kg/l"],
    ],
    spec: "ORIGIN: USA (New Mexico). PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; mildly hygroscopic. Langbeinite-based — chloride-free, ideal for citrus, grapes, vegetables. Shelf life 24 months.",
  }),
  p({
    sku: "FER-POT-01-006",
    name: "MOP Standard Granular",
    category: "fertilizers",
    hs: "3104200000",
    price: 310,
    cap20: BAG20, cap40: BAG40,
    tags: ["potash", "mop", "granular", "standard"],
    shelfLife: SHELF,
    desc: "MOP Standard Granular 60% K2O — bulk-grade potash for direct application and blends.",
    coa: [
      ["K2O Content", "60.0% Min"],
      ["Moisture", "0.5% Max"],
      ["Particle Size (2-4mm)", "85% Min"],
      ["Sodium (Na)", "1.5% Max"],
      ["Magnesium (Mg)", "0.3% Max"],
      ["Calcium (Ca)", "0.5% Max"],
      ["Chloride Content", "47% Min"],
      ["Color", "Pink/Brown"],
      ["Bulk Density", "1.05-1.15 kg/l"],
      ["Insolubles", "0.5% Max"],
    ],
    spec: "ORIGIN: Russia/Belarus. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk vessel. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; mildly hygroscopic. Standard granular for broadacre farming and NPK blending. Shelf life 24 months.",
  }),

  // ============ NPK (Blends) — 10 ============
  p({
    sku: "FER-NPK-01-001",
    name: "NPK 15-15-15",
    category: "fertilizers",
    hs: "3105200000",
    price: 440,
    cap20: BAG20, cap40: BAG40,
    tags: ["npk", "balanced", "all-purpose"],
    shelfLife: SHELF,
    desc: "NPK 15-15-15 — balanced compound fertilizer for general-purpose use.",
    coa: [
      ["Total Nitrogen (N)", "15.0% Min"],
      ["Ammoniacal N", "8.0%"],
      ["Nitrate N", "7.0%"],
      ["Available P2O5", "15.0% Min"],
      ["Water-Soluble P2O5", "10.0% Min"],
      ["K2O Content", "15.0% Min"],
      ["Moisture", "1.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Color", "Brown/Grey"],
      ["Bulk Density", "0.95-1.05 kg/l"],
    ],
    spec: "ORIGIN: Russia/Spain. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009 (PFC 1). HANDLING: Store dry under cover; hygroscopic. Balanced ratios suit pre-plant and side-dress applications across cereals, fruits, and vegetables. Shelf life 12 months.",
  }),
  p({
    sku: "FER-NPK-01-002",
    name: "NPK 20-20-20",
    category: "fertilizers",
    hs: "3105200000",
    price: 540,
    cap20: BAG20, cap40: BAG40,
    tags: ["npk", "balanced", "water-soluble", "fertigation"],
    shelfLife: SHELF,
    desc: "NPK 20-20-20 — fully water-soluble high-analysis blend for fertigation and foliar.",
    coa: [
      ["Total Nitrogen (N)", "20.0% Min"],
      ["Urea N", "10.0%"],
      ["Ammoniacal N", "5.0%"],
      ["Nitrate N", "5.0%"],
      ["P2O5 (Water-Soluble)", "20.0% Min"],
      ["K2O (Water-Soluble)", "20.0% Min"],
      ["Moisture", "0.5% Max"],
      ["Water Solubility", "99.5% Min"],
      ["pH (1% solution)", "5.5-6.5"],
      ["Heavy Metals (as Pb)", "10 ppm Max"],
    ],
    spec: "ORIGIN: Belgium/Spain. PACKAGING: 25kg PP bags with PE inner liner, 1000kg FIBCs. CERTIFICATIONS: SGS/Intertek, COO, COQ, REACH. QUALITY: ISO 18643 water-soluble grade. HANDLING: Store dry under cover; highly hygroscopic. Keep sealed. Use clean water for solution preparation. Ideal for greenhouse and drip irrigation. Shelf life 24 months sealed.",
  }),
  p({
    sku: "FER-NPK-01-003",
    name: "NPK 10-26-26",
    category: "fertilizers",
    hs: "3105200000",
    price: 480,
    cap20: BAG20, cap40: BAG40,
    tags: ["npk", "high-pk", "root"],
    shelfLife: SHELF,
    desc: "NPK 10-26-26 — high P+K starter fertilizer for root development and flowering.",
    coa: [
      ["Total Nitrogen (N)", "10.0% Min"],
      ["Ammoniacal N", "8.0%"],
      ["Nitrate N", "2.0%"],
      ["Available P2O5", "26.0% Min"],
      ["K2O Content", "26.0% Min"],
      ["Moisture", "1.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Sulfur (S)", "1.5% Min"],
      ["Color", "Grey/Brown"],
      ["Bulk Density", "0.95-1.05 kg/l"],
    ],
    spec: "ORIGIN: India/Bangladesh. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; hygroscopic. Recommended as basal dose for pulses, oilseeds, and tubers. Shelf life 12 months.",
  }),
  p({
    sku: "FER-NPK-01-004",
    name: "NPK 12-32-16",
    category: "fertilizers",
    hs: "3105200000",
    price: 500,
    cap20: BAG20, cap40: BAG40,
    tags: ["npk", "high-p", "starter"],
    shelfLife: SHELF,
    desc: "NPK 12-32-16 — high-phosphorus NPK for basal application in cereals.",
    coa: [
      ["Total Nitrogen (N)", "12.0% Min"],
      ["Ammoniacal N", "9.0%"],
      ["Nitrate N", "3.0%"],
      ["Available P2O5", "32.0% Min"],
      ["K2O Content", "16.0% Min"],
      ["Moisture", "1.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Sulfur (S)", "1.0% Min"],
      ["Color", "Grey/Brown"],
      ["Bulk Density", "0.95-1.05 kg/l"],
    ],
    spec: "ORIGIN: India/Iran. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; hygroscopic. High-P starter for wheat, maize, and rice basal dose. Shelf life 12 months.",
  }),
  p({
    sku: "FER-NPK-01-005",
    name: "NPK 17-17-17",
    category: "fertilizers",
    hs: "3105200000",
    price: 460,
    cap20: BAG20, cap40: BAG40,
    tags: ["npk", "balanced", "all-purpose"],
    shelfLife: SHELF,
    desc: "NPK 17-17-17 — balanced high-analysis compound for top-dressing.",
    coa: [
      ["Total Nitrogen (N)", "17.0% Min"],
      ["Ammoniacal N", "9.0%"],
      ["Nitrate N", "8.0%"],
      ["Available P2O5", "17.0% Min"],
      ["Water-Soluble P2O5", "12.0% Min"],
      ["K2O Content", "17.0% Min"],
      ["Moisture", "1.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Color", "Brown/Grey"],
      ["Bulk Density", "0.95-1.05 kg/l"],
    ],
    spec: "ORIGIN: Russia/Egypt. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; hygroscopic. Versatile balanced NPK for top-dressing cereals, oilseeds, and vegetables. Shelf life 12 months.",
  }),
  p({
    sku: "FER-NPK-01-006",
    name: "NPK 14-28-28",
    category: "fertilizers",
    hs: "3105200000",
    price: 520,
    cap20: BAG20, cap40: BAG40,
    tags: ["npk", "high-pk", "flowering"],
    shelfLife: SHELF,
    desc: "NPK 14-28-28 — high P+K compound for flowering and fruit-set stages.",
    coa: [
      ["Total Nitrogen (N)", "14.0% Min"],
      ["Ammoniacal N", "11.0%"],
      ["Nitrate N", "3.0%"],
      ["Available P2O5", "28.0% Min"],
      ["K2O Content", "28.0% Min"],
      ["Moisture", "1.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Sulfur (S)", "2.0% Min"],
      ["Color", "Grey/Brown"],
      ["Bulk Density", "0.95-1.05 kg/l"],
    ],
    spec: "ORIGIN: India/Belgium. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; hygroscopic. Excellent for fruits, vegetables, and flowering crops at pre-bloom stage. Shelf life 12 months.",
  }),
  p({
    sku: "FER-NPK-01-007",
    name: "NPK 19-19-19",
    category: "fertilizers",
    hs: "3105200000",
    price: 530,
    cap20: BAG20, cap40: BAG40,
    tags: ["npk", "balanced", "high-analysis"],
    shelfLife: SHELF,
    desc: "NPK 19-19-19 — high-analysis balanced compound for nutrient-demanding crops.",
    coa: [
      ["Total Nitrogen (N)", "19.0% Min"],
      ["Ammoniacal N", "10.0%"],
      ["Nitrate N", "9.0%"],
      ["Available P2O5", "19.0% Min"],
      ["Water-Soluble P2O5", "14.0% Min"],
      ["K2O Content", "19.0% Min"],
      ["Moisture", "1.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Color", "Brown/Grey"],
      ["Bulk Density", "0.95-1.05 kg/l"],
    ],
    spec: "ORIGIN: Russia/Iran. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; hygroscopic. High nutrient density reduces per-hectare volume. Ideal for cereals and sugarcane. Shelf life 12 months.",
  }),
  p({
    sku: "FER-NPK-01-008",
    name: "NPK 20-10-10",
    category: "fertilizers",
    hs: "3105200000",
    price: 430,
    cap20: BAG20, cap40: BAG40,
    tags: ["npk", "high-n", "top-dress"],
    shelfLife: SHELF,
    desc: "NPK 20-10-10 — high-nitrogen NPK for top-dressing leafy and cereal crops.",
    coa: [
      ["Total Nitrogen (N)", "20.0% Min"],
      ["Ammoniacal N", "12.0%"],
      ["Nitrate N", "8.0%"],
      ["Available P2O5", "10.0% Min"],
      ["K2O Content", "10.0% Min"],
      ["Moisture", "1.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Sulfur (S)", "1.5% Min"],
      ["Color", "Grey/Brown"],
      ["Bulk Density", "0.95-1.05 kg/l"],
    ],
    spec: "ORIGIN: India/Russia. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; hygroscopic. High N drives vegetative growth in maize, wheat, rice, and pasture. Shelf life 12 months.",
  }),
  p({
    sku: "FER-NPK-01-009",
    name: "NPK 16-16-8",
    category: "fertilizers",
    hs: "3105200000",
    price: 420,
    cap20: BAG20, cap40: BAG40,
    tags: ["npk", "low-k", "basal"],
    shelfLife: SHELF,
    desc: "NPK 16-16-8 — low-K basal blend for K-rich soils.",
    coa: [
      ["Total Nitrogen (N)", "16.0% Min"],
      ["Ammoniacal N", "10.0%"],
      ["Nitrate N", "6.0%"],
      ["Available P2O5", "16.0% Min"],
      ["K2O Content", "8.0% Min"],
      ["Moisture", "1.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Sulfur (S)", "1.0% Min"],
      ["Color", "Grey/Brown"],
      ["Bulk Density", "0.95-1.05 kg/l"],
    ],
    spec: "ORIGIN: India/Iran. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; hygroscopic. Suitable for basal application on soils with adequate K reserves. Shelf life 12 months.",
  }),
  p({
    sku: "FER-NPK-01-010",
    name: "NPK 8-24-24",
    category: "fertilizers",
    hs: "3105200000",
    price: 470,
    cap20: BAG20, cap40: BAG40,
    tags: ["npk", "high-pk", "low-n"],
    shelfLife: SHELF,
    desc: "NPK 8-24-24 — low-N high-PK blend for legumes and tubers.",
    coa: [
      ["Total Nitrogen (N)", "8.0% Min"],
      ["Ammoniacal N", "6.0%"],
      ["Nitrate N", "2.0%"],
      ["Available P2O5", "24.0% Min"],
      ["K2O Content", "24.0% Min"],
      ["Moisture", "1.5% Max"],
      ["Particle Size (2-4mm)", "90% Min"],
      ["Sulfur (S)", "1.5% Min"],
      ["Color", "Grey/Brown"],
      ["Bulk Density", "0.95-1.05 kg/l"],
    ],
    spec: "ORIGIN: India/Belgium. PACKAGING: 50kg PP bags with PE inner liner, 1000kg FIBCs, or bulk. CERTIFICATIONS: SGS/Intertek, COO, COQ. QUALITY: EN 12022 / Reg EU 2019/1009. HANDLING: Store dry under cover; hygroscopic. Low N suits N-fixing legumes; high PK supports tuber bulking and flowering. Shelf life 12 months.",
  }),

  // ============ SPE (Specialty) — 6 ============
  p({
    sku: "FER-SPE-01-001",
    name: "Zinc Sulfate 33% Zn",
    category: "fertilizers",
    hs: "2833290000",
    price: 900,
    cap20: BAG20, cap40: BAG40,
    tags: ["micronutrient", "zinc", "sulfate"],
    shelfLife: SHELF,
    desc: "Zinc Sulfate Monohydrate 33% Zn — zinc micronutrient for cereals and rice.",
    coa: [
      ["Zinc (Zn) Content", "33.0% Min"],
      ["Sulfur (S) Content", "16.0% Min"],
      ["Zinc Sulfate (ZnSO4·H2O)", "90.0% Min"],
      ["Moisture", "1.0% Max"],
      ["Heavy Metals (as Pb)", "20 ppm Max"],
      ["Cadmium (Cd)", "5 ppm Max"],
      ["Arsenic (As)", "5 ppm Max"],
      ["Iron (Fe)", "0.1% Max"],
      ["Water Solubility", "99.0% Min"],
      ["Appearance", "White powder/granular"],
    ],
    spec: "ORIGIN: China/India. PACKAGING: 25kg PP bags with PE inner liner, 1000kg FIBCs. CERTIFICATIONS: SGS/Intertek, COO, COQ, REACH. QUALITY: ISO 18643 micronutrient grade. HANDLING: Store dry under cover; mildly hygroscopic. Corrects Zn deficiency in rice, maize, wheat, and citrus. Apply 10-25 kg/ha. Shelf life 24 months sealed.",
  }),
  p({
    sku: "FER-SPE-01-002",
    name: "Borax 11% B",
    category: "fertilizers",
    hs: "2840110000",
    price: 1000,
    cap20: BAG20, cap40: BAG40,
    tags: ["micronutrient", "boron", "borax"],
    shelfLife: SHELF,
    desc: "Borax Decahydrate 11% B — boron micronutrient for flowering crops.",
    coa: [
      ["Boron (B) Content", "11.0% Min"],
      ["Borax (Na2B4O7·10H2O)", "99.5% Min"],
      ["Sodium (Na)", "10.0% Min"],
      ["Sulfate (SO4)", "0.1% Max"],
      ["Chloride (Cl)", "0.05% Max"],
      ["Iron (Fe)", "0.005% Max"],
      ["Heavy Metals (as Pb)", "10 ppm Max"],
      ["Water Solubility", "99.5% Min"],
      ["pH (1% solution)", "9.0-9.5"],
      ["Appearance", "White crystal/powder"],
    ],
    spec: "ORIGIN: Turkey/USA. PACKAGING: 25kg PP bags with PE inner liner, 1000kg FIBCs. CERTIFICATIONS: SGS/Intertek, COO, COQ, REACH. QUALITY: ISO 18643 micronutrient grade. HANDLING: Store dry under cover; mildly hygroscopic. Critical for pollen viability in oilseeds, fruits, and vegetables. Apply 5-15 kg/ha. Shelf life 24 months sealed.",
  }),
  p({
    sku: "FER-SPE-01-003",
    name: "Magnesium Sulfate 9.6% Mg",
    category: "fertilizers",
    hs: "2833210000",
    price: 350,
    cap20: BAG20, cap40: BAG40,
    tags: ["micronutrient", "magnesium", "epsom"],
    shelfLife: SHELF,
    desc: "Magnesium Sulfate Heptahydrate (Epsom) 9.6% Mg — Mg+S source for chlorophyll synthesis.",
    coa: [
      ["Magnesium (Mg) Content", "9.6% Min"],
      ["Magnesium Oxide (MgO)", "16.0% Min"],
      ["Sulfur (S) Content", "13.0% Min"],
      ["MgSO4·7H2O Purity", "99.5% Min"],
      ["Moisture", "1.0% Max"],
      ["Chloride (Cl)", "0.05% Max"],
      ["Heavy Metals (as Pb)", "10 ppm Max"],
      ["Iron (Fe)", "0.005% Max"],
      ["Water Solubility", "99.5% Min"],
      ["Appearance", "White crystal"],
    ],
    spec: "ORIGIN: China/Turkey. PACKAGING: 25kg PP bags with PE inner liner, 1000kg FIBCs. CERTIFICATIONS: SGS/Intertek, COO, COQ, REACH. QUALITY: ISO 18643 micronutrient grade. HANDLING: Store dry under cover; mildly hygroscopic. Corrects Mg deficiency in citrus, grapes, tomatoes, and chlorotic soils. Apply 50-100 kg/ha. Shelf life 24 months sealed.",
  }),
  p({
    sku: "FER-SPE-01-004",
    name: "Micronutrient Mix (Zn+B+Cu+Fe+Mn+Mo)",
    category: "fertilizers",
    hs: "3105900000",
    price: 1500,
    cap20: BAG20, cap40: BAG40,
    tags: ["micronutrient", "mix", "blend", "fortified"],
    shelfLife: SHELF,
    desc: "Micronutrient Mix — chelated blend of 6 micronutrients for balanced plant nutrition.",
    coa: [
      ["Zinc (Zn) EDTA", "4.0% Min"],
      ["Boron (B)", "1.5% Min"],
      ["Copper (Cu) EDTA", "1.0% Min"],
      ["Iron (Fe) EDTA", "5.0% Min"],
      ["Manganese (Mn) EDTA", "3.0% Min"],
      ["Molybdenum (Mo)", "0.1% Min"],
      ["Magnesium (MgO)", "2.0% Min"],
      ["Sulfur (S)", "1.0% Min"],
      ["Water Solubility", "99.0% Min"],
      ["Appearance", "Pink/Purple powder"],
    ],
    spec: "ORIGIN: Spain/Israel. PACKAGING: 25kg PP bags with PE inner liner, 1000kg FIBCs. CERTIFICATIONS: SGS/Intertek, COO, COQ, REACH. QUALITY: ISO 18643 chelated micronutrient grade. HANDLING: Store dry under cover; highly hygroscopic. Keep sealed. Chelated form ensures availability across pH 4-9. Apply foliar 1-2 g/L or soil 5-10 kg/ha. Shelf life 24 months sealed.",
  }),
  p({
    sku: "FER-SPE-01-005",
    name: "Humic Acid 60%",
    category: "fertilizers",
    hs: "3801900000",
    price: 1700,
    cap20: BAG20, cap40: BAG40,
    tags: ["organic", "humic", "soil-conditioner"],
    shelfLife: SHELF,
    desc: "Humic Acid 60% Potassium Humate — soil conditioner and bio-stimulant.",
    coa: [
      ["Humic Acid Content", "60.0% Min"],
      ["Fulvic Acid Content", "10.0% Min"],
      ["Potassium (K2O)", "10.0% Min"],
      ["Moisture", "15.0% Max"],
      ["Water Solubility", "95.0% Min"],
      ["pH (1% solution)", "9.0-10.0"],
      ["Organic Matter", "75.0% Min"],
      ["Heavy Metals (as Pb)", "20 ppm Max"],
      ["Cadmium (Cd)", "5 ppm Max"],
      ["Appearance", "Black powder/flakes"],
    ],
    spec: "ORIGIN: China/India. PACKAGING: 25kg PP bags with PE inner liner, 1000kg FIBCs. CERTIFICATIONS: SGS/Intertek, COO, COQ, OMRI organic. QUALITY: ISO 18643 bio-stimulant grade. HANDLING: Store dry under cover; hygroscopic. Improves soil structure, CEC, and nutrient uptake. Apply 5-15 kg/ha soil or 100-200 g/100L foliar. Shelf life 36 months sealed.",
  }),
  p({
    sku: "FER-SPE-01-006",
    name: "Seaweed Extract Bio-stimulant",
    category: "fertilizers",
    hs: "3101000000",
    price: 3000,
    cap20: LIQ20, cap40: LIQ40,
    tags: ["organic", "seaweed", "bio-stimulant", "ascophyllum"],
    shelfLife: SHELF,
    desc: "Seaweed Extract Bio-stimulant — Ascophyllum nodosum extract for stress tolerance.",
    coa: [
      ["Seaweed Extract (Ascophyllum)", "100% pure"],
      ["Alginic Acid", "12.0% Min"],
      ["Mannitol", "4.0% Min"],
      ["Organic Matter", "45.0% Min"],
      ["Total Nitrogen (N)", "1.0% Min"],
      ["K2O Content", "12.0% Min"],
      ["Plant Growth Hormones", "Cytokinin/Auxin trace"],
      ["Amino Acids", "5.0% Min"],
      ["pH (1% solution)", "9.0-10.5"],
      ["Appearance", "Dark brown liquid"],
    ],
    spec: "ORIGIN: Ireland/Canada. PACKAGING: 20L/200L drums, 1000L IBC totes. CERTIFICATIONS: SGS/Intertek, COO, COQ, OMRI organic. QUALITY: EU 2019/1009 bio-stimulant grade. HANDLING: Store in cool, dry place away from direct sunlight. Shake before use. Compatible with most agrochemicals — jar test recommended. Apply foliar 1-2 L/ha. Shelf life 24 months sealed.",
  }),
];
