-- 050_marketplace_documents.sql
-- ============================================================================
-- VELOS Marketplace — Phase 8: document automation (auto-generated trade
-- documents, customs forms, electronic Bill of Lading / eBL).
--
-- Adds one table:
--   • marketplace_trade_documents  — auto-generated commercial invoices,
--                                    packing lists, certificates of origin,
--                                    bills of lading (eBL), proformas,
--                                    shipping manifests, customs declarations,
--                                    weight certificates, etc.
--
-- DATA MODEL
--   A row is created whenever the seller (or buyer) generates a trade document
--   from a settled negotiation / post / shipment. The structured payload is
--   stored verbatim in `document_data` (JSONB); the PDF render is generated on
--   demand from this payload so a re-issue (after fixing a typo) just updates
--   the JSONB and re-renders — no separate "version" table needed.
--
--   `status` tracks the document lifecycle:
--     draft → generated → sent → signed → rejected
--   The "generated" state means the PDF has been rendered at least once; "sent"
--   means it has been forwarded to the counterparty; "signed" means the
--   `digital_signature` field has been set (a SHA-256 over the JSONB + the
--   signer's partner_id, computed at the API layer). "rejected" means the
--   counterparty refused to sign.
--
--   `digital_signature` is a SHA-256 hex digest. The signed_at / signed_by
--   columns record WHO signed and WHEN. A signed document is immutable —
--   the API layer rejects any PUT to a signed row.
--
-- SECURITY MODEL
--   • RLS is permissive (USING(true)) as defense-in-depth — service_role
--     bypasses RLS, and the API layer is the real participant check. Mirrors
--     044 / 046 / 047 marketplace migrations.
--   • Documents are tenant-scoped via the FK chain document →
--     marketplace_posts → tenant_id. The store filters by tenant_id +
--     partner_id at read time. partner_id is stamped from the auth context
--     at create time — never trust a body-supplied partner_id.
--
-- IDEMPOTENCY
--   CREATE TABLE IF NOT EXISTS + CREATE INDEX IF NOT EXISTS make this
--   safe to re-run. No data is ever deleted.
-- ============================================================================

-- ─── 1. marketplace_trade_documents ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS marketplace_trade_documents (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       TEXT NOT NULL,
  partner_id      TEXT NOT NULL,              -- → partners.id (issuing partner)

  -- Optional marketplace context (any / all may be NULL for a standalone doc)
  post_id         UUID REFERENCES marketplace_posts(id),
  negotiation_id UUID REFERENCES marketplace_negotiations(id),
  shipment_id     UUID REFERENCES marketplace_shipments(id),

  -- Document type — what kind of trade document this is.
  document_type   TEXT NOT NULL CHECK (document_type IN (
    'commercial_invoice', 'packing_list', 'certificate_of_origin',
    'bill_of_lading', 'shipping_manifest', 'inspection_certificate',
    'insurance_certificate', 'export_declaration', 'customs_declaration',
    'letter_of_credit_draft', 'proforma_invoice', 'weight_certificate'
  )),

  -- Lifecycle
  status          TEXT DEFAULT 'draft' CHECK (status IN (
    'draft', 'generated', 'sent', 'signed', 'rejected'
  )),

  -- Structured payload (invoice / packing-list / BoL fields). The PDF
  -- renderer reads this JSONB verbatim, so any field rename is a backwards-
  -- incompatible change. The auto-generate helpers in
  -- src/lib/marketplace/document-generators.ts are the canonical producers.
  document_data   JSONB NOT NULL DEFAULT '{}',

  -- Rendered PDF — the signed URL is written here once the PDF is rendered
  -- (or the inline data: URL when running in dev/mock mode). NULL until
  -- the first render succeeds.
  generated_pdf_url TEXT,

  -- Digital signature (SHA-256 hex over the JSONB + signer partner_id).
  -- Set once, at signing time. NULL until signed.
  digital_signature TEXT,
  signed_at          TIMESTAMPTZ,
  signed_by         TEXT,                      -- partner_id of the signer

  -- Human-readable reference (e.g. "INV-2025-00001", "BL-2025-00001").
  -- Generated by generateDocumentNumber() in document-generators.ts and
  -- stamped at create time. NOT UNIQUE — multiple revisions of the same
  -- logical document (e.g. after a counter-offer) may share a reference.
  reference_number  TEXT,

  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─── 2. Indexes ───────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_td_partner ON marketplace_trade_documents(partner_id);
CREATE INDEX IF NOT EXISTS idx_td_type   ON marketplace_trade_documents(document_type);
CREATE INDEX IF NOT EXISTS idx_td_post   ON marketplace_trade_documents(post_id);
CREATE INDEX IF NOT EXISTS idx_td_neg   ON marketplace_trade_documents(negotiation_id);
CREATE INDEX IF NOT EXISTS idx_td_ship  ON marketplace_trade_documents(shipment_id);
CREATE INDEX IF NOT EXISTS idx_td_status ON marketplace_trade_documents(status);

-- ─── 3. RLS — permissive (service_role writes; API layer enforces ownership) ─
ALTER TABLE marketplace_trade_documents ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  BEGIN
    EXECUTE format('CREATE POLICY %I ON %I USING (true) WITH CHECK (true)',
                   'marketplace_trade_documents_service_role_all',
                   'marketplace_trade_documents');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END $$;

-- ─── 4. updated_at trigger ─────────────────────────────────────────────────
-- Reuse the public.set_updated_at() function from 044_marketplace.sql — it
-- is CREATE OR REPLACE so this migration is safe even if 044 was applied
-- later.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_td_updated ON marketplace_trade_documents;
CREATE TRIGGER trg_td_updated BEFORE UPDATE ON marketplace_trade_documents
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
