// VELOS — Metals Product Catalog (60 SKUs)
// Generated for tenant c889572d-d35b-43ec-bca1-a5359d95603d
// Sub-categories: ALU, COP, ZIN, LEA, TIN, NIC, STL, PRE, OTH

export interface CoaParam { name: string; value: string; }
export interface Logistics { cap20: number | null; cap40: number | null; }
export interface SeedProduct {
  sku: string; name: string; category: string; unit: string;
  price: number; currency: string; cost: number;
  stock: number; reorder_level: number; active: boolean;
  description: string; hs_code: string;
  brand: null; shelf_life: string | null; image_url: null;
  logistics: Logistics; coa_params: CoaParam[];
  detailed_spec: string; tags: string[];
}

function p(o: {
  sku: string; name: string; category: string;
  hs: string; price: number; unit?: string;
  coa: [string, string][]; spec: string;
  cap20?: number | null; cap40?: number | null;
  tags?: string[]; shelfLife?: string | null;
  desc?: string; stock?: number;
}): SeedProduct {
  const unit = o.unit ?? "MT";
  const stock = o.stock ?? 5000;
  return {
    sku: o.sku, name: o.name, category: o.category, unit,
    price: o.price, currency: "USD", cost: o.price, stock,
    reorder_level: Math.max(1, Math.floor(stock / 20)),
    active: true, description: o.desc ?? o.name,
    hs_code: o.hs, brand: null,
    shelf_life: o.shelfLife ?? null, image_url: null,
    logistics: { cap20: o.cap20 ?? null, cap40: o.cap40 ?? null },
    coa_params: o.coa.map(([name, value]) => ({ name, value })),
    detailed_spec: o.spec, tags: o.tags ?? [],
  };
}

export const metalProducts: SeedProduct[] = [
  // ───────────────────────── ALU — Aluminium (12) ─────────────────────────
  p({
    sku: "MET-ALU-01-001",
    name: "Aluminium Ingots P1020A",
    category: "metals",
    hs: "7601100000",
    price: 2250,
    cap20: 20000, cap40: 26000,
    tags: ["aluminium", "ingots", "P1020A", "LME"],
    desc: "Primary aluminium ingots P1020A (99.70% Al), LME registered brand",
    coa: [
      ["Purity (Al)", "99.70% Min"],
      ["Iron (Fe)", "0.20% Max"],
      ["Silicon (Si)", "0.10% Max"],
      ["Copper (Cu)", "0.01% Max"],
      ["Manganese (Mn)", "0.03% Max"],
      ["Magnesium (Mg)", "0.02% Max"],
      ["Zinc (Zn)", "0.03% Max"],
      ["Titanium (Ti)", "0.03% Max"],
      ["Other Impurities (each)", "0.03% Max"],
      ["Total Others", "0.10% Max"],
    ],
    spec: "ORIGIN: Russia/Bahrain/UAE. PACKAGING: Ingots bundled on wooden pallets (approx. 1000kg/pallet), strapped with steel bands. CERTIFICATIONS: COA, Certificate of Origin, LME registered brands available. QUALITY: Per ASTM B230 / GOST 11069-2001. HANDLING: Store in dry, covered area; protect from moisture. No shelf life. Transport per IMDG/ADR. Stack max 3 pallets high.",
  }),
  p({
    sku: "MET-ALU-02-002",
    name: "Aluminium Ingots A7 (GOST)",
    category: "metals",
    hs: "7601100000",
    price: 2350,
    cap20: 20000, cap40: 26000,
    tags: ["aluminium", "ingots", "A7", "GOST"],
    desc: "Russian GOST A7 primary aluminium ingots (99.70% Al)",
    coa: [
      ["Purity (Al)", "99.70% Min"],
      ["Iron (Fe)", "0.16% Max"],
      ["Silicon (Si)", "0.15% Max"],
      ["Copper (Cu)", "0.01% Max"],
      ["Manganese (Mn)", "0.04% Max"],
      ["Magnesium (Mg)", "0.04% Max"],
      ["Zinc (Zn)", "0.02% Max"],
      ["Titanium (Ti)", "0.01% Max"],
      ["Standard", "GOST 11069-2001"],
      ["Form", "Ingots 15kg each"],
    ],
    spec: "ORIGIN: Russia (RUSAL brands). PACKAGING: Ingots stacked on wooden pallets (1000-1100kg/pallet), strapped with steel bands. CERTIFICATIONS: GOST 11069-2001 COA, Certificate of Origin. QUALITY: LME registered brands available. HANDLING: Store in dry, covered warehouse; protect from moisture. No shelf life. Stack max 3 pallets high. Transport per IMDG/ADR.",
  }),
  p({
    sku: "MET-ALU-03-003",
    name: "Aluminium Ingots A8 (GOST)",
    category: "metals",
    hs: "7601100000",
    price: 2450,
    cap20: 20000, cap40: 26000,
    tags: ["aluminium", "ingots", "A8", "GOST", "high-grade"],
    desc: "Russian GOST A8 high-purity primary aluminium ingots (99.80% Al)",
    coa: [
      ["Purity (Al)", "99.80% Min"],
      ["Iron (Fe)", "0.12% Max"],
      ["Silicon (Si)", "0.10% Max"],
      ["Copper (Cu)", "0.01% Max"],
      ["Manganese (Mn)", "0.02% Max"],
      ["Magnesium (Mg)", "0.02% Max"],
      ["Zinc (Zn)", "0.02% Max"],
      ["Titanium (Ti)", "0.01% Max"],
      ["Standard", "GOST 11069-2001"],
      ["Form", "Ingots 15kg each"],
    ],
    spec: "ORIGIN: Russia (RUSAL high purity brands). PACKAGING: Ingots stacked on wooden pallets (1000kg/pallet), strapped. CERTIFICATIONS: GOST 11069-2001 COA, Certificate of Origin, LME brand eligible. QUALITY: High-purity grade for electrical and aerospace applications. HANDLING: Store in dry covered warehouse; protect from moisture. No shelf life. Stack max 3 pallets high.",
  }),
  p({
    sku: "MET-ALU-04-004",
    name: "Aluminium Billets 6063",
    category: "metals",
    hs: "7604100000",
    price: 2550,
    cap20: 20000, cap40: 26000,
    tags: ["aluminium", "billets", "6063", "extrusion"],
    desc: "Aluminium extrusion billets 6063 alloy (Architectural grade)",
    coa: [
      ["Alloy", "AA 6063"],
      ["Magnesium (Mg)", "0.45-0.9%"],
      ["Silicon (Si)", "0.20-0.6%"],
      ["Iron (Fe)", "0.35% Max"],
      ["Copper (Cu)", "0.10% Max"],
      ["Manganese (Mn)", "0.10% Max"],
      ["Zinc (Zn)", "0.10% Max"],
      ["Chromium (Cr)", "0.10% Max"],
      ["Titanium (Ti)", "0.10% Max"],
      ["Diameter", "6 inch / 152.4 mm"],
      ["Length", "6000 mm typical"],
    ],
    spec: "ORIGIN: UAE/Bahrain/India. PACKAGING: Bundles of billets (6m length) on steel pallets, strapped with steel bands. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: AA 6063 per ASTM B221 / EN 573-3. HANDLING: Store under cover; separate by alloy to avoid cross-contamination. No shelf life. Stack max 2 bundles high.",
  }),
  p({
    sku: "MET-ALU-05-005",
    name: "Aluminium Billets 6061",
    category: "metals",
    hs: "7604100000",
    price: 2600,
    cap20: 20000, cap40: 26000,
    tags: ["aluminium", "billets", "6061", "extrusion", "structural"],
    desc: "Aluminium extrusion billets 6061 alloy (Structural grade)",
    coa: [
      ["Alloy", "AA 6061"],
      ["Magnesium (Mg)", "0.8-1.2%"],
      ["Silicon (Si)", "0.4-0.8%"],
      ["Iron (Fe)", "0.7% Max"],
      ["Copper (Cu)", "0.15-0.40%"],
      ["Manganese (Mn)", "0.15% Max"],
      ["Zinc (Zn)", "0.25% Max"],
      ["Chromium (Cr)", "0.04-0.35%"],
      ["Titanium (Ti)", "0.15% Max"],
      ["Diameter", "7 inch / 178 mm"],
      ["Length", "6000 mm typical"],
    ],
    spec: "ORIGIN: UAE/India/Bahrain. PACKAGING: Bundles of billets (6m length) on steel pallets, strapped. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: AA 6061 per ASTM B221 / EN 573-3, structural extrusion grade. HANDLING: Store under cover; separate by alloy. No shelf life. Stack max 2 bundles high.",
  }),
  p({
    sku: "MET-ALU-06-006",
    name: "Aluminium Slabs 3003",
    category: "metals",
    hs: "7606120000",
    price: 2480,
    cap20: 20000, cap40: 26000,
    tags: ["aluminium", "slabs", "3003", "rolling"],
    desc: "Aluminium rolling slabs 3003 alloy for sheet production",
    coa: [
      ["Alloy", "AA 3003"],
      ["Manganese (Mn)", "1.0-1.5%"],
      ["Copper (Cu)", "0.05-0.20%"],
      ["Iron (Fe)", "0.7% Max"],
      ["Silicon (Si)", "0.6% Max"],
      ["Magnesium (Mg)", "0.05% Max"],
      ["Zinc (Zn)", "0.10% Max"],
      ["Thickness", "300-600 mm"],
      ["Width", "1200-1800 mm"],
      ["Length", "2000-4000 mm"],
    ],
    spec: "ORIGIN: Bahrain/UAE. PACKAGING: Slabs strapped to wooden sleepers, steel bands, padded corners. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: AA 3003 per ASTM B209, suitable for cold rolling to sheet/foil. HANDLING: Store under cover; protect surface from scratches. No shelf life.",
  }),
  p({
    sku: "MET-ALU-07-007",
    name: "Aluminium Slabs 5052",
    category: "metals",
    hs: "7606120000",
    price: 2520,
    cap20: 20000, cap40: 26000,
    tags: ["aluminium", "slabs", "5052", "rolling", "marine"],
    desc: "Aluminium rolling slabs 5052 alloy (marine grade)",
    coa: [
      ["Alloy", "AA 5052"],
      ["Magnesium (Mg)", "2.2-2.8%"],
      ["Chromium (Cr)", "0.15-0.35%"],
      ["Manganese (Mn)", "0.10% Max"],
      ["Iron (Fe)", "0.40% Max"],
      ["Silicon (Si)", "0.25% Max"],
      ["Copper (Cu)", "0.10% Max"],
      ["Zinc (Zn)", "0.10% Max"],
      ["Thickness", "300-600 mm"],
      ["Width", "1200-1800 mm"],
    ],
    spec: "ORIGIN: Bahrain/UAE. PACKAGING: Slabs strapped to wooden sleepers with steel bands, padded corners. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: AA 5052 per ASTM B209, marine/saltwater grade. HANDLING: Store under cover; protect surface. No shelf life.",
  }),
  p({
    sku: "MET-ALU-08-008",
    name: "Primary Aluminium 99.7%",
    category: "metals",
    hs: "7601100000",
    price: 2200,
    cap20: 20000, cap40: 26000,
    tags: ["aluminium", "primary", "99.7", "LME"],
    desc: "Primary unalloyed aluminium 99.7% (LME Grade)",
    coa: [
      ["Purity (Al)", "99.70% Min"],
      ["Iron (Fe)", "0.20% Max"],
      ["Silicon (Si)", "0.10% Max"],
      ["Copper (Cu)", "0.01% Max"],
      ["Manganese (Mn)", "0.03% Max"],
      ["Magnesium (Mg)", "0.02% Max"],
      ["Zinc (Zn)", "0.03% Max"],
      ["Titanium (Ti)", "0.03% Max"],
      ["Total Impurities", "0.30% Max"],
      ["LME Grade", "P1020A compliant"],
    ],
    spec: "ORIGIN: Bahrain/UAE/India. PACKAGING: T-bars or ingots on wooden pallets (1000kg/pallet), strapped. CERTIFICATIONS: Certificate of Analysis, Certificate of Origin, LME registered. QUALITY: Per ASTM B230. HANDLING: Store in dry covered area; protect from moisture. No shelf life. Stack max 3 pallets high.",
  }),
  p({
    sku: "MET-ALU-09-009",
    name: "Primary Aluminium 99.8%",
    category: "metals",
    hs: "7601100000",
    price: 2400,
    cap20: 20000, cap40: 26000,
    tags: ["aluminium", "primary", "99.8", "high-purity"],
    desc: "Primary high-purity unalloyed aluminium 99.8%",
    coa: [
      ["Purity (Al)", "99.80% Min"],
      ["Iron (Fe)", "0.12% Max"],
      ["Silicon (Si)", "0.10% Max"],
      ["Copper (Cu)", "0.01% Max"],
      ["Manganese (Mn)", "0.02% Max"],
      ["Magnesium (Mg)", "0.02% Max"],
      ["Zinc (Zn)", "0.02% Max"],
      ["Titanium (Ti)", "0.01% Max"],
      ["Total Impurities", "0.20% Max"],
      ["LME Grade", "P1020 compliant"],
    ],
    spec: "ORIGIN: Bahrain/Russia/UAE. PACKAGING: T-bars or ingots on wooden pallets (1000kg/pallet), strapped. CERTIFICATIONS: COA, Certificate of Origin, LME registered. QUALITY: High-purity grade for electrical applications. HANDLING: Store in dry covered area. No shelf life. Stack max 3 pallets high.",
  }),
  p({
    sku: "MET-ALU-10-010",
    name: "ADC12 Aluminium Alloy Ingots",
    category: "metals",
    hs: "7601200000",
    price: 2050,
    cap20: 20000, cap40: 26000,
    tags: ["aluminium", "alloy", "ADC12", "die-casting"],
    desc: "ADC12 die-casting aluminium alloy ingots (JIS standard)",
    coa: [
      ["Alloy", "ADC12 / A383"],
      ["Silicon (Si)", "9.6-12.0%"],
      ["Copper (Cu)", "1.5-3.5%"],
      ["Magnesium (Mg)", "0.30% Max"],
      ["Iron (Fe)", "1.3% Max"],
      ["Manganese (Mn)", "0.50% Max"],
      ["Zinc (Zn)", "1.0% Max"],
      ["Nickel (Ni)", "0.50% Max"],
      ["Tin (Sn)", "0.30% Max"],
      ["Standard", "JIS H 2212-2006"],
      ["Form", "Ingots 10-15kg"],
    ],
    spec: "ORIGIN: Japan/China/Malaysia. PACKAGING: Ingots bundled on wooden pallets (1000kg/pallet), strapped. CERTIFICATIONS: JIS H 2212 Certificate of Analysis, Certificate of Origin. QUALITY: Die-casting alloy per JIS H 2212 / ASTM B179. HANDLING: Store in dry covered area; protect from moisture. No shelf life. Stack max 3 pallets high.",
  }),
  p({
    sku: "MET-ALU-11-011",
    name: "Aluminium Wire Rods 9.5mm",
    category: "metals",
    hs: "7605110000",
    price: 2480,
    cap20: 20000, cap40: 26000,
    tags: ["aluminium", "wire-rod", "EC-grade", "drawing"],
    desc: "Aluminium EC grade wire rods 9.5mm diameter for conductor drawing",
    coa: [
      ["Alloy", "AA 1350 (EC Grade)"],
      ["Purity (Al)", "99.50% Min"],
      ["Silicon (Si)", "0.10% Max"],
      ["Iron (Fe)", "0.40% Max"],
      ["Copper (Cu)", "0.05% Max"],
      ["Magnesium (Mg)", "0.01% Max"],
      ["Boron (B)", "0.05% Max"],
      ["Diameter", "9.5 mm ±0.3"],
      ["Conductivity", "61% IACS Min"],
      ["Tensile Strength", "80-120 MPa"],
    ],
    spec: "ORIGIN: Bahrain/UAE/India. PACKAGING: Coils (1000-1500kg) on wooden pallets, strapped with steel bands. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: AA 1350 EC grade per ASTM B233. HANDLING: Store in dry covered area; protect coil from damage. No shelf life. Stack max 2 coils high.",
  }),
  p({
    sku: "MET-ALU-12-012",
    name: "Aluminium T-Bars",
    category: "metals",
    hs: "7604100000",
    price: 2300,
    cap20: 20000, cap40: 26000,
    tags: ["aluminium", "T-bar", "primary", "LME"],
    desc: "Primary aluminium T-bars (99.7%) LME registered shape",
    coa: [
      ["Purity (Al)", "99.70% Min"],
      ["Iron (Fe)", "0.20% Max"],
      ["Silicon (Si)", "0.10% Max"],
      ["Copper (Cu)", "0.01% Max"],
      ["Manganese (Mn)", "0.03% Max"],
      ["Magnesium (Mg)", "0.02% Max"],
      ["Zinc (Zn)", "0.03% Max"],
      ["Titanium (Ti)", "0.03% Max"],
      ["Form", "T-bar"],
      ["Weight per piece", "approx. 700-800 kg"],
      ["LME Registered", "Yes"],
    ],
    spec: "ORIGIN: Bahrain/UAE. PACKAGING: T-bars in bundles on wooden pallets/sleepers, strapped with steel bands. CERTIFICATIONS: COA, Certificate of Origin, LME registered brand. QUALITY: Per ASTM B230 / LME P1020A. HANDLING: Store in dry covered area; protect from moisture. No shelf life. Stack max 2 layers high.",
  }),

  // ───────────────────────── COP — Copper (8) ─────────────────────────
  p({
    sku: "MET-COP-01-013",
    name: "Copper Cathode Grade A (LME)",
    category: "metals",
    hs: "7402000000",
    price: 8500,
    cap20: 20000, cap40: 26000,
    tags: ["copper", "cathode", "LME", "Grade-A"],
    desc: "Copper cathode Grade A LME registered (99.99% Cu+Ag)",
    coa: [
      ["Purity (Cu+Ag)", "99.99% Min"],
      ["Silver (Ag)", "0.0025% Max"],
      ["Oxygen (O)", "0.0200% Max"],
      ["Lead (Pb)", "0.0005% Max"],
      ["Sulfur (S)", "0.0015% Max"],
      ["Antimony (Sb)", "0.0004% Max"],
      ["Arsenic (As)", "0.0005% Max"],
      ["Bismuth (Bi)", "0.0003% Max"],
      ["Iron (Fe)", "0.0010% Max"],
      ["Nickel (Ni)", "0.0005% Max"],
    ],
    spec: "ORIGIN: Chile/Peru/DRC/Zambia. PACKAGING: Bundles of cathode plates strapped with steel bands (1-4 MT bundles). CERTIFICATIONS: Certificate of Analysis (ASTM B115), Certificate of Origin, LME registered brand. QUALITY: GRADE A per ASTM B115 / LME Cathode spec. HANDLING: Store in dry covered area; keep cathodes clean. No shelf life. Stack max 3 bundles high.",
  }),
  p({
    sku: "MET-COP-02-014",
    name: "Copper Wire Rods 8mm",
    category: "metals",
    hs: "7408110000",
    price: 8700,
    cap20: 20000, cap40: 26000,
    tags: ["copper", "wire-rod", "8mm", "drawing"],
    desc: "Copper wire rods 8mm diameter (Cu-ETP / C11000) for drawing",
    coa: [
      ["Alloy", "Cu-ETP / C11000"],
      ["Purity (Cu+Ag)", "99.95% Min"],
      ["Oxygen (O)", "0.0200-0.0400%"],
      ["Silver (Ag)", "0.0025% Max"],
      ["Lead (Pb)", "0.0005% Max"],
      ["Bismuth (Bi)", "0.0003% Max"],
      ["Diameter", "8.0 mm ±0.05"],
      ["Conductivity", "100-101% IACS"],
      ["Tensile Strength", "220-260 MPa"],
      ["Elongation", "30-40%"],
      ["Surface", "Oxide-free, bright"],
    ],
    spec: "ORIGIN: UAE/Spain/Germany. PACKAGING: Coils (3-5 MT) on wooden pallets, strapped, plastic wrapped. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: Cu-ETP per ASTM B49 / EN 1977. HANDLING: Store in dry covered area; protect from moisture. No shelf life. Stack max 2 coils high.",
  }),
  p({
    sku: "MET-COP-03-015",
    name: "Copper Scrap Birch/Cliff (No.1)",
    category: "metals",
    hs: "7404000000",
    price: 8000,
    cap20: 20000, cap40: 26000,
    tags: ["copper", "scrap", "Birch-Cliff", "No.1"],
    desc: "Copper scrap Birch/Cliff No.1 (clean mixed copper solids)",
    coa: [
      ["Grade", "Birch/Cliff (No.1)"],
      ["Cu Content", "94-96%"],
      ["ISRI Code", "Birch/Cliff"],
      ["Free of", "Brass, solder, insulation"],
      ["Maximum Size", "1/16 inch mesh"],
      ["Minimum Size", "Smaller acceptable"],
      ["Contamination", "Free of excessively oxidized material"],
      ["Moisture", "Free of moisture"],
      ["Hazardous Materials", "None"],
      ["Inspection", "SGS/Intertek"],
      ["Packing", "Bulk or pressed bales"],
    ],
    spec: "ORIGIN: Europe/USA/UAE. PACKAGING: Bulk in containers or pressed bales (500-1000kg). CERTIFICATIONS: ISRI classification, SGS/Intertek inspection certificate, Certificate of Origin. QUALITY: Per ISRI Birch/Cliff No.1 specification. HANDLING: Store in dry area; avoid moisture accumulation. No shelf life. Loading per ISRI guidelines.",
  }),
  p({
    sku: "MET-COP-04-016",
    name: "Copper Scrap Candy (No.2)",
    category: "metals",
    hs: "7404000000",
    price: 7800,
    cap20: 20000, cap40: 26000,
    tags: ["copper", "scrap", "Candy", "No.2"],
    desc: "Copper scrap Candy No.2 (heavy copper solids with solder)",
    coa: [
      ["Grade", "Candy (No.2)"],
      ["Cu Content", "92-94%"],
      ["ISRI Code", "Candy"],
      ["Solder content", "Permitted in moderation"],
      ["Brass content", "Max 1%"],
      ["Insulation", "Free"],
      ["Minimum Size", "1/16 inch mesh"],
      ["Maximum Size", "Permitted larger solids"],
      ["Moisture", "Free of moisture"],
      ["Inspection", "SGS/Intertek"],
    ],
    spec: "ORIGIN: Europe/USA/UAE. PACKAGING: Bulk in containers or pressed bales (500-1000kg). CERTIFICATIONS: ISRI classification, SGS/Intertek inspection, Certificate of Origin. QUALITY: Per ISRI Candy specification. HANDLING: Store in dry area; avoid moisture. No shelf life. Loading per ISRI guidelines.",
  }),
  p({
    sku: "MET-COP-05-017",
    name: "Copper Concentrate 25% Cu",
    category: "metals",
    hs: "2603000000",
    price: 1700,
    cap20: 24000, cap40: 27000,
    tags: ["copper", "concentrate", "25%"],
    desc: "Copper concentrate 25% Cu with precious metal credits",
    coa: [
      ["Cu Content", "25.0% Min"],
      ["Gold (Au)", "8 g/MT Min"],
      ["Silver (Ag)", "80 g/MT Min"],
      ["Sulfur (S)", "30% Typical"],
      ["Iron (Fe)", "25% Typical"],
      ["Arsenic (As)", "0.3% Max"],
      ["Lead (Pb)", "2.0% Max"],
      ["Zinc (Zn)", "2.0% Max"],
      ["Bismuth (Bi)", "0.05% Max"],
      ["Antimony (Sb)", "0.2% Max"],
      ["Moisture", "8.0% Max"],
    ],
    spec: "ORIGIN: Chile/Peru/Indonesia. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek assay at load/discharge, Certificate of Origin, Weight Certificate. QUALITY: Priced via TC/RC + QP. HANDLING: Store under cover; keep dry. Moisture above 8% subject to claim. Penalty elements per contract.",
  }),
  p({
    sku: "MET-COP-06-018",
    name: "Blister Copper 98%",
    category: "metals",
    hs: "7401000000",
    price: 8100,
    cap20: 20000, cap40: 26000,
    tags: ["copper", "blister", "98%"],
    desc: "Blister copper 98% Cu (intermediate smelter product)",
    coa: [
      ["Cu Content", "98.0-99.0%"],
      ["Silver (Ag)", "500-1500 g/MT"],
      ["Gold (Au)", "5-30 g/MT"],
      ["Sulfur (S)", "0.2-0.5%"],
      ["Oxygen (O)", "0.3-0.6%"],
      ["Lead (Pb)", "0.2% Max"],
      ["Arsenic (As)", "0.10% Max"],
      ["Antimony (Sb)", "0.10% Max"],
      ["Iron (Fe)", "0.05% Max"],
      ["Nickel (Ni)", "0.10% Max"],
      ["Form", "Slab/plate blister"],
    ],
    spec: "ORIGIN: Chile/Peru/Indonesia. PACKAGING: Slab/plate form on wooden pallets, strapped with steel bands (1-2 MT/pallet). CERTIFICATIONS: SGS/Intertek assay, Certificate of Origin, Weight Certificate. QUALITY: Intermediate smelter product, priced LME Cu less refining charges. HANDLING: Store in dry covered area. No shelf life. Stack max 2 pallets high.",
  }),
  p({
    sku: "MET-COP-07-019",
    name: "Brass Ingots",
    category: "metals",
    hs: "7405000000",
    price: 5800,
    cap20: 20000, cap40: 26000,
    tags: ["copper", "brass", "alloy", "ingots"],
    desc: "Brass ingots C26000 (Cartridge Brass 70/30) for casting",
    coa: [
      ["Alloy", "C26000 (70/30)"],
      ["Copper (Cu)", "68.5-71.5%"],
      ["Zinc (Zn)", "Remainder"],
      ["Lead (Pb)", "0.07% Max"],
      ["Iron (Fe)", "0.05% Max"],
      ["Aluminium (Al)", "0.05% Max"],
      ["Nickel (Ni)", "0.10% Max"],
      ["Tin (Sn)", "0.10% Max"],
      ["Form", "Ingots 8-15kg"],
      ["Standard", "ASTM B36"],
    ],
    spec: "ORIGIN: India/UAE/Germany. PACKAGING: Ingots bundled on wooden pallets (1000kg/pallet), strapped. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: C26000 per ASTM B36. HANDLING: Store in dry covered area. No shelf life. Stack max 3 pallets high.",
  }),
  p({
    sku: "MET-COP-08-020",
    name: "Bronze Ingots",
    category: "metals",
    hs: "7405000000",
    price: 6200,
    cap20: 20000, cap40: 26000,
    tags: ["copper", "bronze", "alloy", "ingots"],
    desc: "Bronze ingots C90300 (Tin Bronze) for bushings and bearings",
    coa: [
      ["Alloy", "C90300 (Tin Bronze)"],
      ["Copper (Cu)", "86-89%"],
      ["Tin (Sn)", "7.5-9.0%"],
      ["Zinc (Zn)", "3.0-5.0%"],
      ["Lead (Pb)", "0.30% Max"],
      ["Iron (Fe)", "0.20% Max"],
      ["Nickel (Ni)", "1.0% Max"],
      ["Antimony (Sb)", "0.20% Max"],
      ["Sulfur (S)", "0.05% Max"],
      ["Form", "Ingots 8-15kg"],
      ["Standard", "ASTM B505"],
    ],
    spec: "ORIGIN: India/UAE/Italy. PACKAGING: Ingots bundled on wooden pallets (1000kg/pallet), strapped. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: C90300 per ASTM B505, suitable for bushings and bearings. HANDLING: Store in dry covered area. No shelf life. Stack max 3 pallets high.",
  }),

  // ───────────────────────── ZIN — Zinc (6) ─────────────────────────
  p({
    sku: "MET-ZIN-01-021",
    name: "Zinc SHG 99.99% (LME)",
    category: "metals",
    hs: "7901110000",
    price: 2600,
    cap20: 20000, cap40: 26000,
    tags: ["zinc", "SHG", "LME", "99.99"],
    desc: "Special High Grade (SHG) zinc 99.995% LME registered",
    coa: [
      ["Purity (Zn)", "99.995% Min"],
      ["Lead (Pb)", "0.003% Max"],
      ["Cadmium (Cd)", "0.003% Max"],
      ["Iron (Fe)", "0.002% Max"],
      ["Copper (Cu)", "0.001% Max"],
      ["Tin (Sn)", "0.001% Max"],
      ["Aluminium (Al)", "0.001% Max"],
      ["Total Impurities", "0.005% Max"],
      ["Form", "Ingots 25kg each"],
      ["LME Registered", "Yes"],
    ],
    spec: "ORIGIN: Australia/China/Netherlands. PACKAGING: Ingots on wooden pallets (1000-1200kg/pallet), strapped with steel bands. CERTIFICATIONS: Certificate of Analysis (EN 1179), Certificate of Origin, LME registered. QUALITY: SHG per EN 1179 / ASTM B6. HANDLING: Store in dry covered area; protect from moisture. No shelf life. Stack max 3 pallets high.",
  }),
  p({
    sku: "MET-ZIN-02-022",
    name: "Zinc Prime Western 98%",
    category: "metals",
    hs: "7901120000",
    price: 2300,
    cap20: 20000, cap40: 26000,
    tags: ["zinc", "Prime-Western", "98%", "alloy"],
    desc: "Prime Western Grade (PWG) zinc 98% with Pb for galvanizing",
    coa: [
      ["Purity (Zn)", "98.0-99.0%"],
      ["Lead (Pb)", "0.5-1.5%"],
      ["Cadmium (Cd)", "0.05% Max"],
      ["Iron (Fe)", "0.05% Max"],
      ["Aluminium (Al)", "0.05% Max"],
      ["Copper (Cu)", "0.02% Max"],
      ["Tin (Sn)", "0.02% Max"],
      ["Form", "Ingots 25kg each"],
      ["Standard", "ASTM B6 PWG"],
      ["Use", "Hot-dip galvanizing"],
    ],
    spec: "ORIGIN: China/India/Spain. PACKAGING: Ingots on wooden pallets (1000kg/pallet), strapped. CERTIFICATIONS: Certificate of Analysis, Certificate of Origin. QUALITY: PWG per ASTM B6. HANDLING: Store in dry covered area; protect from moisture. No shelf life. Stack max 3 pallets high.",
  }),
  p({
    sku: "MET-ZIN-03-023",
    name: "Zinc Ingots 99.95%",
    category: "metals",
    hs: "7901110000",
    price: 2480,
    cap20: 20000, cap40: 26000,
    tags: ["zinc", "ingots", "99.95"],
    desc: "Refined zinc ingots 99.95% for general galvanizing",
    coa: [
      ["Purity (Zn)", "99.95% Min"],
      ["Lead (Pb)", "0.030% Max"],
      ["Cadmium (Cd)", "0.010% Max"],
      ["Iron (Fe)", "0.010% Max"],
      ["Copper (Cu)", "0.005% Max"],
      ["Tin (Sn)", "0.005% Max"],
      ["Aluminium (Al)", "0.005% Max"],
      ["Total Impurities", "0.050% Max"],
      ["Form", "Ingots 25kg"],
      ["Standard", "EN 1179 Z2"],
    ],
    spec: "ORIGIN: China/India/Bolivia. PACKAGING: Ingots on wooden pallets (1000kg/pallet), strapped. CERTIFICATIONS: Certificate of Analysis (EN 1179 Z2), Certificate of Origin. QUALITY: Per EN 1179 grade Z2 / ASTM B6. HANDLING: Store in dry covered area. No shelf life. Stack max 3 pallets high.",
  }),
  p({
    sku: "MET-ZIN-04-024",
    name: "Zinc Scrap (Clean Dross-Free)",
    category: "metals",
    hs: "7902000000",
    price: 2200,
    cap20: 20000, cap40: 26000,
    tags: ["zinc", "scrap", "recycled"],
    desc: "Zinc scrap clean dross-free (new die-cast scrap, ISRI Zorin)",
    coa: [
      ["Grade", "ISRI Zorin"],
      ["Zn Content", "92-96%"],
      ["Free of", "Dross, slag, oils, moisture"],
      ["Al Content", "4% Max (die-cast)"],
      ["Cu Content", "1% Max"],
      ["Mg Content", "0.5% Max"],
      ["Fe Content", "0.5% Max"],
      ["Pb Content", "1% Max"],
      ["Inspection", "SGS/Intertek"],
      ["Packing", "Bulk or bales"],
    ],
    spec: "ORIGIN: Europe/USA/UAE. PACKAGING: Bulk in containers or pressed bales (500-1000kg). CERTIFICATIONS: ISRI classification, SGS/Intertek inspection, Certificate of Origin. QUALITY: Per ISRI Zorin specification. HANDLING: Store in dry area; segregate from other metals. No shelf life.",
  }),
  p({
    sku: "MET-ZIN-05-025",
    name: "Zinc Oxide (Direct Process)",
    category: "metals",
    hs: "2817000000",
    price: 2500,
    cap20: 20000, cap40: 26000,
    tags: ["zinc", "oxide", "ZnO", "chemical"],
    desc: "Zinc oxide direct process (American process) for rubber/ceramics",
    coa: [
      ["ZnO Content", "99.5% Min"],
      ["Zinc Metal", "80.5% Min"],
      ["Lead (Pb)", "0.05% Max"],
      ["Cadmium (Cd)", "0.005% Max"],
      ["Iron (Fe)", "0.005% Max"],
      ["Copper (Cu)", "0.001% Max"],
      ["Manganese (Mn)", "0.001% Max"],
      ["Loss on Ignition", "0.3% Max"],
      ["Sieve Residue (45μm)", "0.10% Max"],
      ["Surface Area (BET)", "3-7 m²/g"],
      ["Form", "Powder"],
    ],
    spec: "ORIGIN: China/India. PACKAGING: 25kg or 1000kg FFS bags on wooden pallets, strapped. CERTIFICATIONS: Certificate of Analysis (ISO 9298), Certificate of Origin. QUALITY: Direct/American process per ISO 9298. HANDLING: Store in dry covered area; protect from moisture and contamination. Shelf life 24 months sealed. Stack max 2 pallets high.",
    shelfLife: "24 months sealed",
  }),
  p({
    sku: "MET-ZIN-06-026",
    name: "Zinc Concentrate 50% Zn",
    category: "metals",
    hs: "2608000000",
    price: 1100,
    cap20: 24000, cap40: 27000,
    tags: ["zinc", "concentrate", "sphalerite"],
    desc: "Zinc concentrate 50% Zn (sphalerite flotation concentrate)",
    coa: [
      ["Zn Content", "50.0% Min"],
      ["Pb Content", "2.0% Max"],
      ["Fe Content", "10.0% Max"],
      ["Cu Content", "0.5% Max"],
      ["Cd Content", "0.3% Max"],
      ["As Content", "0.3% Max"],
      ["Sb Content", "0.05% Max"],
      ["SiO2", "4.0% Max"],
      ["Sulfur (S)", "30% Typical"],
      ["Moisture", "8.0% Max"],
      ["Inspection", "SGS/Intertek"],
    ],
    spec: "ORIGIN: Peru/Australia/Bolivia. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek assay at load/discharge, Certificate of Origin, Weight Certificate. QUALITY: Priced via TC + QP. HANDLING: Store under cover; keep dry. Moisture above 8% subject to claim. Penalty elements per contract.",
  }),

  // ───────────────────────── LEA — Lead (5) ─────────────────────────
  p({
    sku: "MET-LEA-01-027",
    name: "Refined Lead 99.97%",
    category: "metals",
    hs: "7801100000",
    price: 2150,
    cap20: 20000, cap40: 26000,
    tags: ["lead", "refined", "99.97", "LME"],
    desc: "Refined lead 99.97% (LME Grade) for batteries and chemicals",
    coa: [
      ["Purity (Pb)", "99.97% Min"],
      ["Silver (Ag)", "0.005% Max"],
      ["Copper (Cu)", "0.001% Max"],
      ["Zinc (Zn)", "0.001% Max"],
      ["Bismuth (Bi)", "0.025% Max"],
      ["Antimony (Sb)", "0.001% Max"],
      ["Arsenic (As)", "0.001% Max"],
      ["Tin (Sn)", "0.001% Max"],
      ["Iron (Fe)", "0.001% Max"],
      ["Cadmium (Cd)", "0.001% Max"],
      ["Form", "Ingots 25kg"],
    ],
    spec: "ORIGIN: Australia/Canada/China. PACKAGING: Ingots strapped on wooden pallets (1000kg/pallet). CERTIFICATIONS: Certificate of Analysis (LME spec), Certificate of Origin, LME registered. QUALITY: LME Grade per EN 12659 / ASTM B29. HANDLING: Store in dry covered area; wash hands after handling. No shelf life. Stack max 3 pallets high.",
  }),
  p({
    sku: "MET-LEA-02-028",
    name: "Lead Ingots (Pure)",
    category: "metals",
    hs: "7801100000",
    price: 2100,
    cap20: 20000, cap40: 26000,
    tags: ["lead", "ingots", "pure"],
    desc: "Pure lead ingots 99.95% Pb for general industrial use",
    coa: [
      ["Purity (Pb)", "99.95% Min"],
      ["Silver (Ag)", "0.005% Max"],
      ["Copper (Cu)", "0.003% Max"],
      ["Zinc (Zn)", "0.002% Max"],
      ["Bismuth (Bi)", "0.030% Max"],
      ["Antimony (Sb)", "0.002% Max"],
      ["Arsenic (As)", "0.002% Max"],
      ["Tin (Sn)", "0.002% Max"],
      ["Iron (Fe)", "0.002% Max"],
      ["Form", "Ingots 25-40kg"],
    ],
    spec: "ORIGIN: India/China/UAE. PACKAGING: Ingots strapped on wooden pallets (1000-1200kg/pallet). CERTIFICATIONS: Certificate of Analysis, Certificate of Origin. QUALITY: Per ASTM B29. HANDLING: Store in dry covered area; wash hands after handling. No shelf life. Stack max 3 pallets high.",
  }),
  p({
    sku: "MET-LEA-03-029",
    name: "Lead Scrap (Racks)",
    category: "metals",
    hs: "7802000000",
    price: 1900,
    cap20: 20000, cap40: 26000,
    tags: ["lead", "scrap", "racks", "recycled"],
    desc: "Lead scrap battery racks/terminals clean (ISRI Radio/Relay)",
    coa: [
      ["Grade", "ISRI Radio/Relay"],
      ["Pb Content", "94-98%"],
      ["Sb Content", "1-3% (alloyed)"],
      ["Free of", "Acid, electrolyte, separators"],
      ["Moisture", "Free of moisture"],
      ["Contamination", "Free of foreign material"],
      ["Insulation", "None"],
      ["Inspection", "SGS/Intertek"],
      ["Packing", "Bulk or drums"],
      ["Origin", "End-of-life batteries"],
    ],
    spec: "ORIGIN: UAE/Europe/USA. PACKAGING: Bulk in containers or steel drums (200-250kg). CERTIFICATIONS: ISRI classification, SGS/Intertek inspection, Certificate of Origin. QUALITY: Per ISRI Radio/Relay specification, deacidified and dried. HANDLING: Store in dry area; handle with PPE. No shelf life. Basel Convention notice may apply for export.",
  }),
  p({
    sku: "MET-LEA-04-030",
    name: "Lead Concentrate 65% Pb",
    category: "metals",
    hs: "2607000000",
    price: 1400,
    cap20: 24000, cap40: 27000,
    tags: ["lead", "concentrate", "galena", "65%"],
    desc: "Lead concentrate 65% Pb (galena flotation concentrate)",
    coa: [
      ["Pb Content", "65.0% Min"],
      ["Zn Content", "3.0% Max"],
      ["Fe Content", "5.0% Max"],
      ["Cu Content", "1.0% Max"],
      ["As Content", "0.3% Max"],
      ["Sb Content", "0.3% Max"],
      ["Bi Content", "0.05% Max"],
      ["Ag Content", "500-2000 g/MT typical"],
      ["Sulfur (S)", "16% Typical"],
      ["Moisture", "8.0% Max"],
      ["Inspection", "SGS/Intertek"],
    ],
    spec: "ORIGIN: Peru/Australia/Bolivia. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek assay at load/discharge, Certificate of Origin, Weight Certificate. QUALITY: Priced via TC + QP + precious metal credits. HANDLING: Store under cover; keep dry. Penalty elements per contract.",
  }),
  p({
    sku: "MET-LEA-05-031",
    name: "Antimonial Lead (Hard Lead)",
    category: "metals",
    hs: "7801200000",
    price: 2200,
    cap20: 20000, cap40: 26000,
    tags: ["lead", "antimonial", "hard-lead", "alloy"],
    desc: "Antimonial lead alloy 3-4% Sb for battery grids and castings",
    coa: [
      ["Alloy", "Pb-Sb (Hard Lead)"],
      ["Pb Content", "95-96%"],
      ["Antimony (Sb)", "3.0-4.0%"],
      ["Tin (Sn)", "0.2-0.5%"],
      ["Arsenic (As)", "0.15-0.25%"],
      ["Silver (Ag)", "0.005% Max"],
      ["Copper (Cu)", "0.05% Max"],
      ["Bismuth (Bi)", "0.05% Max"],
      ["Iron (Fe)", "0.005% Max"],
      ["Zinc (Zn)", "0.002% Max"],
      ["Form", "Ingots 25-40kg"],
    ],
    spec: "ORIGIN: India/UAE/China. PACKAGING: Ingots strapped on wooden pallets (1000-1200kg/pallet). CERTIFICATIONS: Mill Test Certificate, Certificate of Origin. QUALITY: Per ASTM B29 alloy. HANDLING: Store in dry covered area; wash hands after handling. No shelf life. Stack max 3 pallets high.",
  }),

  // ───────────────────────── TIN — Tin (4) ─────────────────────────
  p({
    sku: "MET-TIN-01-032",
    name: "Tin Ingots 99.9% (LME)",
    category: "metals",
    hs: "8001100000",
    price: 30000,
    cap20: 20000, cap40: 26000,
    tags: ["tin", "ingots", "99.9", "LME"],
    desc: "Tin ingots 99.90% LME registered (Grade T)",
    coa: [
      ["Purity (Sn)", "99.90% Min"],
      ["Lead (Pb)", "0.020% Max"],
      ["Antimony (Sb)", "0.020% Max"],
      ["Copper (Cu)", "0.020% Max"],
      ["Bismuth (Bi)", "0.015% Max"],
      ["Iron (Fe)", "0.010% Max"],
      ["Arsenic (As)", "0.010% Max"],
      ["Aluminium (Al)", "0.001% Max"],
      ["Zinc (Zn)", "0.001% Max"],
      ["Cadmium (Cd)", "0.001% Max"],
      ["Form", "Ingots 25kg"],
    ],
    spec: "ORIGIN: Indonesia/Malaysia/Myanmar. PACKAGING: Ingots on wooden pallets (1000kg/pallet), strapped. CERTIFICATIONS: Certificate of Analysis (ASTM B339 Grade A), Certificate of Origin, LME registered. QUALITY: Per ASTM B339 / EN 610. HANDLING: Store in dry covered area; protect from moisture. No shelf life. Stack max 3 pallets high.",
  }),
  p({
    sku: "MET-TIN-02-033",
    name: "Tin Solder 60/40",
    category: "metals",
    hs: "8001200000",
    price: 22000,
    cap20: 20000, cap40: 26000,
    tags: ["tin", "solder", "60-40", "alloy"],
    desc: "Tin-lead solder 60/40 (60% Sn, 40% Pb) for electronics",
    coa: [
      ["Alloy", "Sn60Pb40"],
      ["Tin (Sn)", "59.5-60.5%"],
      ["Lead (Pb)", "Remainder"],
      ["Antimony (Sb)", "0.20% Max"],
      ["Copper (Cu)", "0.05% Max"],
      ["Bismuth (Bi)", "0.10% Max"],
      ["Iron (Fe)", "0.02% Max"],
      ["Zinc (Zn)", "0.003% Max"],
      ["Aluminium (Al)", "0.003% Max"],
      ["Arsenic (As)", "0.03% Max"],
      ["Form", "Bars 0.5-1kg"],
    ],
    spec: "ORIGIN: China/Malaysia/Singapore. PACKAGING: Bars in cartons on pallets (500-1000kg/pallet). CERTIFICATIONS: Certificate of Analysis (J-STD-006), Certificate of Origin. QUALITY: Per J-STD-006 Sn60Pb40. HANDLING: Store in dry covered area. No shelf life. Wash hands after handling (Pb content).",
  }),
  p({
    sku: "MET-TIN-03-034",
    name: "Tin Solder 63/37",
    category: "metals",
    hs: "8001200000",
    price: 23500,
    cap20: 20000, cap40: 26000,
    tags: ["tin", "solder", "63-37", "alloy", "eutectic"],
    desc: "Tin-lead solder 63/37 eutectic (63% Sn, 37% Pb) for precision electronics",
    coa: [
      ["Alloy", "Sn63Pb37 (Eutectic)"],
      ["Tin (Sn)", "62.5-63.5%"],
      ["Lead (Pb)", "Remainder"],
      ["Antimony (Sb)", "0.20% Max"],
      ["Copper (Cu)", "0.05% Max"],
      ["Bismuth (Bi)", "0.10% Max"],
      ["Iron (Fe)", "0.02% Max"],
      ["Zinc (Zn)", "0.003% Max"],
      ["Aluminium (Al)", "0.003% Max"],
      ["Arsenic (As)", "0.03% Max"],
      ["Form", "Bars 0.5-1kg"],
    ],
    spec: "ORIGIN: China/Malaysia/Singapore. PACKAGING: Bars in cartons on pallets (500-1000kg/pallet). CERTIFICATIONS: Certificate of Analysis (J-STD-006), Certificate of Origin. QUALITY: Eutectic per J-STD-006. HANDLING: Store in dry covered area. No shelf life. Wash hands after handling (Pb content).",
  }),
  p({
    sku: "MET-TIN-04-035",
    name: "Tin Anodes",
    category: "metals",
    hs: "8003000000",
    price: 31000,
    cap20: 20000, cap40: 26000,
    tags: ["tin", "anodes", "plating", "99.9"],
    desc: "Tin anodes 99.9% for electroplating (slab form)",
    coa: [
      ["Purity (Sn)", "99.90% Min"],
      ["Lead (Pb)", "0.020% Max"],
      ["Antimony (Sb)", "0.020% Max"],
      ["Copper (Cu)", "0.020% Max"],
      ["Bismuth (Bi)", "0.015% Max"],
      ["Iron (Fe)", "0.010% Max"],
      ["Arsenic (As)", "0.010% Max"],
      ["Aluminium (Al)", "0.001% Max"],
      ["Zinc (Zn)", "0.001% Max"],
      ["Form", "Slab anodes 5-25kg"],
      ["Standard", "ASTM B339 Grade A"],
    ],
    spec: "ORIGIN: Indonesia/Malaysia/China. PACKAGING: Anodes on wooden pallets (500-1000kg/pallet), strapped. CERTIFICATIONS: Certificate of Analysis (ASTM B339), Certificate of Origin. QUALITY: Plating grade per ASTM B339. HANDLING: Store in dry covered area. No shelf life. Stack max 3 pallets high.",
  }),

  // ───────────────────────── NIC — Nickel (5) ─────────────────────────
  p({
    sku: "MET-NIC-01-036",
    name: "Nickel Cathode 99.8%",
    category: "metals",
    hs: "7502100000",
    price: 17000,
    cap20: 20000, cap40: 26000,
    tags: ["nickel", "cathode", "99.8", "LME"],
    desc: "Nickel cathode 99.8% (LME registered) for stainless steel and alloys",
    coa: [
      ["Purity (Ni+Co)", "99.80% Min"],
      ["Cobalt (Co)", "0.15% Max"],
      ["Carbon (C)", "0.03% Max"],
      ["Sulfur (S)", "0.001% Max"],
      ["Iron (Fe)", "0.02% Max"],
      ["Copper (Cu)", "0.01% Max"],
      ["Silicon (Si)", "0.001% Max"],
      ["Zinc (Zn)", "0.001% Max"],
      ["Arsenic (As)", "0.001% Max"],
      ["Lead (Pb)", "0.001% Max"],
      ["Form", "Cathode plates / sheared"],
    ],
    spec: "ORIGIN: Russia/Canada/Australia. PACKAGING: Cathode bundles strapped (1-2 MT/bundle) or in drums (cut pieces). CERTIFICATIONS: Certificate of Analysis, Certificate of Origin, LME registered. QUALITY: Per ASTM B39 / LME primary nickel. HANDLING: Store in dry covered area. No shelf life. Stack max 2 bundles high.",
  }),
  p({
    sku: "MET-NIC-02-037",
    name: "Nickel Pig Iron (NPI) 10-12%",
    category: "metals",
    hs: "7202600000",
    price: 2400,
    cap20: 20000, cap40: 26000,
    tags: ["nickel", "NPI", "pig-iron", "ferronickel"],
    desc: "Nickel Pig Iron (NPI) 10-12% Ni for stainless steel production",
    coa: [
      ["Ni Content", "10.0-12.0%"],
      ["Fe Content", "82-86%"],
      ["Carbon (C)", "2.0-3.5%"],
      ["Silicon (Si)", "1.5% Max"],
      ["Sulfur (S)", "0.05% Max"],
      ["Phosphorus (P)", "0.03% Max"],
      ["Cobalt (Co)", "0.5% Typical"],
      ["Chromium (Cr)", "0.5% Max"],
      ["Form", "Pig ingots / shot"],
      ["Use", "Stainless steelmaking"],
    ],
    spec: "ORIGIN: Indonesia/China/Philippines. PACKAGING: Pigs/ingots in bundles strapped (1-2 MT) or in bulk bags. CERTIFICATIONS: Mill Test Certificate, Certificate of Origin. QUALITY: NPI per industry spec for stainless steelmaking. HANDLING: Store in dry covered area. No shelf life. Stack max 2 bundles high.",
  }),
  p({
    sku: "MET-NIC-03-038",
    name: "Ferronickel 20% Ni",
    category: "metals",
    hs: "7501200000",
    price: 4200,
    cap20: 20000, cap40: 26000,
    tags: ["nickel", "ferronickel", "20%", "alloy"],
    desc: "Ferronickel 20% Ni for stainless steel and alloy production",
    coa: [
      ["Ni Content", "20.0-22.0%"],
      ["Fe Content", "73-77%"],
      ["Carbon (C)", "1.5-2.5%"],
      ["Silicon (Si)", "2.0% Max"],
      ["Sulfur (S)", "0.05% Max"],
      ["Phosphorus (P)", "0.03% Max"],
      ["Cobalt (Co)", "0.5-1.0%"],
      ["Chromium (Cr)", "1.0% Max"],
      ["Form", "Briquettes / pigs"],
      ["Standard", "ISO 6501"],
    ],
    spec: "ORIGIN: New Caledonia/Greece/Colombia. PACKAGING: Briquettes or pigs in steel drums (250kg) or bulk bags (1 MT). CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: Per ISO 6501 / ASTM A651. HANDLING: Store in dry covered area. No shelf life. Stack max 2 layers high.",
  }),
  p({
    sku: "MET-NIC-04-039",
    name: "Nickel Scrap (Clean Solids)",
    category: "metals",
    hs: "7503000000",
    price: 14000,
    cap20: 20000, cap40: 26000,
    tags: ["nickel", "scrap", "recycled"],
    desc: "Nickel scrap clean solids (turnings/solids, ISRI Nickel type)",
    coa: [
      ["Grade", "ISRI Nickel (clean solids)"],
      ["Ni Content", "96-99%"],
      ["Co Content", "0.5% Max"],
      ["Cu Content", "0.5% Max"],
      ["Fe Content", "0.5% Max"],
      ["Free of", "Moisture, oils, foreign metals"],
      ["Contamination", "Free of plated/clad material"],
      ["Inspection", "SGS/Intertek"],
      ["Packing", "Drums or bulk bags"],
      ["Origin", "Process/Aerospace/Marine"],
    ],
    spec: "ORIGIN: Europe/USA/UAE. PACKAGING: Steel drums (200-250kg) or bulk bags (1 MT) on pallets. CERTIFICATIONS: ISRI classification, SGS/Intertek inspection, Certificate of Origin. QUALITY: Per ISRI Nickel specification. HANDLING: Store in dry area; segregate from other alloys. No shelf life.",
  }),
  p({
    sku: "MET-NIC-05-040",
    name: "Nickel Concentrate 12% Ni",
    category: "metals",
    hs: "7504000000",
    price: 3500,
    cap20: 24000, cap40: 27000,
    tags: ["nickel", "concentrate", "sulfide"],
    desc: "Nickel sulfide concentrate 12% Ni (pentlandite flotation)",
    coa: [
      ["Ni Content", "12.0% Min"],
      ["Cu Content", "1.5-3.0%"],
      ["Co Content", "0.3-0.6%"],
      ["Fe Content", "30-38%"],
      ["Sulfur (S)", "28-34%"],
      ["MgO Content", "5.0% Max"],
      ["SiO2", "8.0% Max"],
      ["As Content", "0.1% Max"],
      ["Pb Content", "0.05% Max"],
      ["Moisture", "8.0% Max"],
      ["Inspection", "SGS/Intertek"],
    ],
    spec: "ORIGIN: Canada/Russia/Australia. PACKAGING: In 1MT bulk bags or bulk container, filter cake form. CERTIFICATIONS: SGS/Intertek assay at load/discharge, Certificate of Origin, Weight Certificate. QUALITY: Priced via TC + QP + Co/PGE credits. HANDLING: Store under cover; keep dry. Penalty elements per contract.",
  }),

  // ───────────────────────── STL — Steel (12) ─────────────────────────
  p({
    sku: "MET-STL-01-041",
    name: "HRC (Hot Rolled Coil) 3mm",
    category: "metals",
    hs: "7208510000",
    price: 600,
    cap20: 20000, cap40: 25000,
    tags: ["steel", "HRC", "hot-rolled", "coil"],
    desc: "Hot Rolled Coil 3mm S235JR / SS400 structural grade",
    coa: [
      ["Thickness", "3.0 mm"],
      ["Width", "1250 mm or 1500 mm"],
      ["Grade", "S235JR / SS400"],
      ["Yield Strength", "235 MPa Min"],
      ["Tensile Strength", "360-510 MPa"],
      ["Elongation", "26% Min"],
      ["Carbon (C)", "0.20% Max"],
      ["Manganese (Mn)", "1.40% Max"],
      ["Phosphorus (P)", "0.045% Max"],
      ["Sulfur (S)", "0.045% Max"],
      ["Surface", "Hot rolled, pickled"],
      ["Coil Weight", "5-20 MT"],
    ],
    spec: "ORIGIN: India/China/Turkey/Russia. PACKAGING: Coils (5-20 MT) strapped with steel bands, eye-to-sky or eye-to-wall on wooden pallets/skids. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: S235JR per EN 10025-2 / SS400 per JIS G3101. HANDLING: Store in dry covered area; protect from rust with oil/VCI. No shelf life. Single coil per pallet.",
  }),
  p({
    sku: "MET-STL-02-042",
    name: "CRC (Cold Rolled Coil) 1mm",
    category: "metals",
    hs: "7209170000",
    price: 700,
    cap20: 20000, cap40: 25000,
    tags: ["steel", "CRC", "cold-rolled", "coil"],
    desc: "Cold Rolled Coil 1mm DC01 / SPCC deep drawing grade",
    coa: [
      ["Thickness", "1.0 mm"],
      ["Width", "1250 mm"],
      ["Grade", "DC01 / SPCC"],
      ["Yield Strength", "130-260 MPa"],
      ["Tensile Strength", "270-410 MPa"],
      ["Elongation", "28% Min"],
      ["Carbon (C)", "0.12% Max"],
      ["Manganese (Mn)", "0.60% Max"],
      ["Phosphorus (P)", "0.045% Max"],
      ["Sulfur (S)", "0.045% Max"],
      ["Surface", "Cold rolled, oiled"],
      ["Coil Weight", "5-15 MT"],
    ],
    spec: "ORIGIN: India/China/Turkey/Japan. PACKAGING: Coils (5-15 MT) strapped with steel bands, VCI paper wrap, on wooden pallets. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: DC01 per EN 10130 / SPCC per JIS G3141. HANDLING: Store in dry covered area; keep oiled to prevent rust. No shelf life.",
  }),
  p({
    sku: "MET-STL-03-043",
    name: "Rebar 12mm",
    category: "metals",
    hs: "7214200000",
    price: 580,
    cap20: 20000, cap40: 25000,
    tags: ["steel", "rebar", "12mm", "construction"],
    desc: "Deformed concrete reinforcement bar 12mm Grade 60 / B500B",
    coa: [
      ["Diameter", "12 mm"],
      ["Grade", "B500B / Grade 60"],
      ["Yield Strength", "500 MPa Min"],
      ["Tensile Strength", "540 MPa Min"],
      ["Elongation", "8% Min (Agt ≥ 1.05)"],
      ["Carbon (C)", "0.22% Max"],
      ["Manganese (Mn)", "1.0-1.6%"],
      ["Phosphorus (P)", "0.050% Max"],
      ["Sulfur (S)", "0.050% Max"],
      ["Length", "12000 mm"],
      ["Standard", "EN 10080 / ASTM A615"],
    ],
    spec: "ORIGIN: Turkey/UAE/India/Egypt. PACKAGING: Bundles (2-5 MT) of 12m bars, strapped with steel bands (4-6 bands per bundle). CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin, CE mark optional. QUALITY: B500B per EN 10080 / ASTM A615. HANDLING: Store on hard standing; protect from excessive rust. No shelf life. Stack max 4 bundles high.",
  }),
  p({
    sku: "MET-STL-04-044",
    name: "Wire Rod 5.5mm",
    category: "metals",
    hs: "7213910000",
    price: 600,
    cap20: 20000, cap40: 25000,
    tags: ["steel", "wire-rod", "5.5mm", "drawing"],
    desc: "Wire rod 5.5mm SAE 1008 / low carbon for drawing",
    coa: [
      ["Diameter", "5.5 mm"],
      ["Grade", "SAE 1008 / SAE 1018"],
      ["Carbon (C)", "0.08-0.10%"],
      ["Manganese (Mn)", "0.30-0.60%"],
      ["Silicon (Si)", "0.10-0.30%"],
      ["Phosphorus (P)", "0.035% Max"],
      ["Sulfur (S)", "0.035% Max"],
      ["Tensile Strength", "380-520 MPa"],
      ["Elongation", "20% Min"],
      ["Coil Weight", "1.0-2.5 MT"],
      ["Surface", "Pickled, coated"],
    ],
    spec: "ORIGIN: Turkey/India/China. PACKAGING: Coils (1-2.5 MT) strapped with steel bands, on wooden pallets. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: SAE 1008 per SAE J403. HANDLING: Store in dry covered area; keep oiled. No shelf life. Stack max 3 coils high.",
  }),
  p({
    sku: "MET-STL-05-045",
    name: "Steel Billets 125x125",
    category: "metals",
    hs: "7207120000",
    price: 550,
    cap20: 20000, cap40: 25000,
    tags: ["steel", "billets", "125", "semi-finished"],
    desc: "Steel billets 125x125mm for rebar/wire rod rolling",
    coa: [
      ["Section", "125 x 125 mm"],
      ["Length", "6000-12000 mm"],
      ["Grade", "3SP / S235JR / Q235"],
      ["Carbon (C)", "0.14-0.22%"],
      ["Manganese (Mn)", "0.40-0.65%"],
      ["Silicon (Si)", "0.05-0.17%"],
      ["Phosphorus (P)", "0.040% Max"],
      ["Sulfur (S)", "0.040% Max"],
      ["Yield Strength", "235 MPa Min"],
      ["Surface", "As-rolled, descaled"],
      ["Standard", "GOST 380 / EN 10025-2"],
    ],
    spec: "ORIGIN: Russia/Ukraine/India/Turkey. PACKAGING: Bundles (3-5 MT) of 6-12m billets, strapped with steel bands (4-6 bands). CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: Per GOST 380 / EN 10025-2. HANDLING: Store on hard standing; protect from excessive rust. No shelf life. Stack max 3 bundles high.",
  }),
  p({
    sku: "MET-STL-06-046",
    name: "Steel Slabs",
    category: "metals",
    hs: "7207110000",
    price: 560,
    cap20: 20000, cap40: 25000,
    tags: ["steel", "slabs", "semi-finished"],
    desc: "Steel slabs for hot rolling (semi-finished)",
    coa: [
      ["Thickness", "200-250 mm"],
      ["Width", "900-1800 mm"],
      ["Length", "4000-12000 mm"],
      ["Grade", "S235JR / Q235B"],
      ["Carbon (C)", "0.14-0.20%"],
      ["Manganese (Mn)", "0.40-0.80%"],
      ["Silicon (Si)", "0.10-0.30%"],
      ["Phosphorus (P)", "0.040% Max"],
      ["Sulfur (S)", "0.040% Max"],
      ["Surface", "As-cast, scarfled"],
      ["Standard", "EN 10025-2"],
    ],
    spec: "ORIGIN: Russia/India/Brazil. PACKAGING: Loose slabs on rail cars or stacked in vessel hold; for container, strapped bundles (max 20 MT). CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: Continuous cast slab per EN 10025-2. HANDLING: Store on hard standing; protect from rust. No shelf life.",
  }),
  p({
    sku: "MET-STL-07-047",
    name: "Galvanized Coil 0.5mm",
    category: "metals",
    hs: "7210490000",
    price: 760,
    cap20: 20000, cap40: 25000,
    tags: ["steel", "galvanized", "GI", "coil"],
    desc: "Hot-dip galvanized steel coil 0.5mm (Z100-Z275 coating)",
    coa: [
      ["Thickness", "0.5 mm"],
      ["Width", "1250 mm"],
      ["Grade", "DX51D+Z / SGCC"],
      ["Zinc Coating", "Z100-Z275 g/m²"],
      ["Spangle", "Regular / Minimized"],
      ["Yield Strength", "170-380 MPa"],
      ["Tensile Strength", "270-500 MPa"],
      ["Elongation", "22% Min"],
      ["Surface", "Chromated/passivated"],
      ["Coil Weight", "5-10 MT"],
      ["Standard", "EN 10346 / ASTM A653"],
    ],
    spec: "ORIGIN: India/China/Turkey/Korea. PACKAGING: Coils (5-10 MT) strapped with steel bands, VCI wrap, on wooden pallets. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: DX51D+Z per EN 10346 / SGCC per JIS G3302. HANDLING: Store in dry covered area; avoid white rust. No shelf life.",
  }),
  p({
    sku: "MET-STL-08-048",
    name: "PPGI 0.5mm",
    category: "metals",
    hs: "7210700000",
    price: 820,
    cap20: 20000, cap40: 25000,
    tags: ["steel", "PPGI", "prepainted", "coil"],
    desc: "Pre-painted galvanized steel coil 0.5mm (PE paint 15-25μm)",
    coa: [
      ["Thickness", "0.5 mm"],
      ["Width", "1000-1250 mm"],
      ["Grade", "DX51D+Z (PE 15/5)"],
      ["Zinc Coating", "Z120-Z275 g/m²"],
      ["Paint Topcoat", "PE 15-25 μm"],
      ["Paint Primer", "EP 5-8 μm"],
      ["Paint Backcoat", "PE 5-10 μm"],
      ["Coating Type", "Polyester (PE)"],
      ["Color", "RAL per order"],
      ["Coil Weight", "3-8 MT"],
      ["Standard", "EN 10169 / ASTM A755"],
    ],
    spec: "ORIGIN: India/China/Korea/Turkey. PACKAGING: Coils (3-8 MT) strapped with steel bands, protective wrap, on wooden pallets. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin, paint warranty certificate. QUALITY: Per EN 10169 / ASTM A755. HANDLING: Store in dry covered area; protect paint film. No shelf life. Stack max 2 coils high.",
  }),
  p({
    sku: "MET-STL-09-049",
    name: "Tinplate 0.2mm",
    category: "metals",
    hs: "7212100000",
    price: 1100,
    cap20: 20000, cap40: 25000,
    tags: ["steel", "tinplate", "0.2mm", "packaging"],
    desc: "Tinplate coil/sheet 0.2mm (ECCS/T3) for food cans",
    coa: [
      ["Thickness", "0.20 mm"],
      ["Width", "832-1000 mm"],
      ["Grade", "T3 / T4 CA"],
      ["Tin Coating", "2.8/2.8 g/m²"],
      ["Temper", "T3 (CA)"],
      ["Yield Strength", "330 MPa typical"],
      ["Tensile Strength", "380 MPa typical"],
      ["Elongation", "15-20%"],
      ["Surface", "Bright / Stone"],
      ["Coil Weight", "5-10 MT"],
      ["Standard", "EN 10202 / ASTM A623"],
    ],
    spec: "ORIGIN: Germany/Korea/India/China. PACKAGING: Coils or sheets (5-10 MT) on wooden pallets, strapped, VCI wrap. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin, food contact compliance. QUALITY: Per EN 10202 / ASTM A623. HANDLING: Store in dry covered area; protect coating. No shelf life. Stack max 2 coils high.",
  }),
  p({
    sku: "MET-STL-10-050",
    name: "Stainless 304 Coil",
    category: "metals",
    hs: "7219130000",
    price: 2400,
    cap20: 20000, cap40: 25000,
    tags: ["steel", "stainless", "304", "coil"],
    desc: "Stainless steel 304 hot rolled coil 3mm (austenitic)",
    coa: [
      ["Grade", "AISI 304 / 1.4301"],
      ["Thickness", "3.0 mm"],
      ["Width", "1250 / 1500 mm"],
      ["Chromium (Cr)", "18.0-20.0%"],
      ["Nickel (Ni)", "8.0-10.5%"],
      ["Carbon (C)", "0.07% Max"],
      ["Manganese (Mn)", "2.0% Max"],
      ["Silicon (Si)", "0.75% Max"],
      ["Phosphorus (P)", "0.045% Max"],
      ["Sulfur (S)", "0.015% Max"],
      ["Surface", "No.1 (annealed, pickled)"],
    ],
    spec: "ORIGIN: India/China/Korea/Japan. PACKAGING: Coils (5-15 MT) strapped with steel bands, on wooden pallets. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: AISI 304 per ASTM A240 / EN 10088-2. HANDLING: Store in dry covered area; avoid carbon steel contact. No shelf life. Stack max 2 coils high.",
  }),
  p({
    sku: "MET-STL-11-051",
    name: "Stainless 316 Coil",
    category: "metals",
    hs: "7219130000",
    price: 3400,
    cap20: 20000, cap40: 25000,
    tags: ["steel", "stainless", "316", "coil", "marine"],
    desc: "Stainless steel 316 hot rolled coil 3mm (marine grade)",
    coa: [
      ["Grade", "AISI 316 / 1.4401"],
      ["Thickness", "3.0 mm"],
      ["Width", "1250 / 1500 mm"],
      ["Chromium (Cr)", "16.0-18.0%"],
      ["Nickel (Ni)", "10.0-14.0%"],
      ["Molybdenum (Mo)", "2.0-3.0%"],
      ["Carbon (C)", "0.07% Max"],
      ["Manganese (Mn)", "2.0% Max"],
      ["Silicon (Si)", "0.75% Max"],
      ["Phosphorus (P)", "0.045% Max"],
      ["Surface", "No.1 (annealed, pickled)"],
    ],
    spec: "ORIGIN: India/China/Korea/Japan. PACKAGING: Coils (5-15 MT) strapped with steel bands, on wooden pallets. CERTIFICATIONS: Mill Test Certificate (EN 10204 3.1), Certificate of Origin. QUALITY: AISI 316 per ASTM A240 / EN 10088-2. HANDLING: Store in dry covered area; avoid carbon steel contact. No shelf life. Stack max 2 coils high.",
  }),
  p({
    sku: "MET-STL-12-052",
    name: "Steel Scrap HMS 1&2 (80:20)",
    category: "metals",
    hs: "7204490000",
    price: 380,
    cap20: 20000, cap40: 25000,
    tags: ["steel", "scrap", "HMS", "recycled"],
    desc: "Steel scrap Heavy Melting Scrap 1&2 (80:20 blend, ISRI 200-206)",
    coa: [
      ["Grade", "HMS 1&2 (80:20)"],
      ["ISRI Code", "200-206"],
      ["HMS 1 Content", "80% Min"],
      ["HMS 2 Content", "20% Max"],
      ["Free of", "Tin, lead, ex-armed forces material"],
      ["Maximum Dimensions", "1500 x 600 x 500 mm"],
      ["Maximum Thickness (HMS1)", "6 mm"],
      ["Minimum Thickness (HMS2)", "3 mm"],
      ["Residuals", "Per ISRI guidelines"],
      ["Sulfur (S)", "0.050% Max"],
      ["Inspection", "SGS/Intertek"],
    ],
    spec: "ORIGIN: Europe/USA/UAE. PACKAGING: Bulk in containers or loose in vessel hold. CERTIFICATIONS: ISRI classification, SGS/Intertek inspection, Certificate of Origin. QUALITY: Per ISRI HMS 1&2 (80:20). HANDLING: Store on hard standing; avoid moisture accumulation. No shelf life. Loading per ISRI guidelines.",
  }),

  // ───────────────────────── PRE — Precious (4) ─────────────────────────
  p({
    sku: "MET-PRE-01-053",
    name: "Gold Doré",
    category: "metals",
    hs: "7108120000",
    price: 67000,
    unit: "kg",
    stock: 200,
    cap20: 5000, cap40: 8000,
    tags: ["gold", "dore", "precious", "semi-refined"],
    desc: "Gold doré bars 80-90% Au, semi-refined mine product",
    coa: [
      ["Gold (Au)", "80-90%"],
      ["Silver (Ag)", "5-15%"],
      ["Copper (Cu)", "1-4%"],
      ["Iron (Fe)", "0.5% Max"],
      ["Lead (Pb)", "0.5% Max"],
      ["Zinc (Zn)", "0.2% Max"],
      ["Mercury (Hg)", "0.001% Max"],
      ["Form", "Bars 1-5 kg"],
      ["Refining", "Semi-refined (doré)"],
      ["Inspection", "LBMA refiner assay"],
    ],
    spec: "ORIGIN: West Africa/South America/Mongolia. PACKAGING: Sealed tamper-evident security bags inside steel lockboxes, escorted transport. CERTIFICATIONS: LBMA refiner assay, Certificate of Origin, export license, Kimberley/anti-conflict gold compliance. QUALITY: Doré 80-90% Au for downstream refining. HANDLING: Vault storage, max security. No shelf life. Ship per LBMA chain-of-custody protocols.",
  }),
  p({
    sku: "MET-PRE-02-054",
    name: "Silver Granules 99.9%",
    category: "metals",
    hs: "7106910000",
    price: 850,
    unit: "kg",
    stock: 500,
    cap20: 5000, cap40: 8000,
    tags: ["silver", "granules", "999", "precious"],
    desc: "Silver granules 99.9% (3-9 fine) LBMA refiner grade",
    coa: [
      ["Purity (Ag)", "99.90% Min"],
      ["Gold (Au)", "0.002% Max"],
      ["Copper (Cu)", "0.03% Max"],
      ["Iron (Fe)", "0.005% Max"],
      ["Lead (Pb)", "0.005% Max"],
      ["Bismuth (Bi)", "0.002% Max"],
      ["Zinc (Zn)", "0.005% Max"],
      ["Form", "Granules 1-3 mm"],
      ["Standard", "LBMA Good Delivery"],
      ["Refining", "Electrolytic"],
    ],
    spec: "ORIGIN: Switzerland/UK/UAE. PACKAGING: Sealed plastic jugs inside steel lockboxes (5-25 kg), tamper-evident. CERTIFICATIONS: LBMA refiner certificate, Certificate of Origin. QUALITY: 99.9% per LBMA Good Delivery. HANDLING: Vault storage, max security. No shelf life. Ship per LBMA chain-of-custody protocols.",
  }),
  p({
    sku: "MET-PRE-03-055",
    name: "Platinum Sponge",
    category: "metals",
    hs: "7110110000",
    price: 29000,
    unit: "kg",
    stock: 100,
    cap20: 5000, cap40: 8000,
    tags: ["platinum", "sponge", "precious", "PGM"],
    desc: "Platinum sponge 99.95% Pt (refined, catalytic grade)",
    coa: [
      ["Purity (Pt)", "99.95% Min"],
      ["Palladium (Pd)", "0.01% Max"],
      ["Rhodium (Rh)", "0.01% Max"],
      ["Iridium (Ir)", "0.01% Max"],
      ["Ruthenium (Ru)", "0.01% Max"],
      ["Gold (Au)", "0.001% Max"],
      ["Iron (Fe)", "0.005% Max"],
      ["Copper (Cu)", "0.005% Max"],
      ["Form", "Sponge (powder)"],
      ["Standard", "LBMA/IPMI Good Delivery"],
    ],
    spec: "ORIGIN: South Africa/Russia/Zimbabwe. PACKAGING: Sealed glass/plastic jars inside steel lockboxes (1-5 kg), tamper-evident. CERTIFICATIONS: LBMA refiner certificate, Certificate of Origin. QUALITY: 99.95% per LBMA/IPMI Good Delivery. HANDLING: Vault storage, max security. No shelf life. Ship per LBMA chain-of-custody protocols.",
  }),
  p({
    sku: "MET-PRE-04-056",
    name: "Palladium Sponge",
    category: "metals",
    hs: "7110210000",
    price: 950,
    unit: "kg",
    stock: 100,
    cap20: 5000, cap40: 8000,
    tags: ["palladium", "sponge", "precious", "PGM"],
    desc: "Palladium sponge 99.95% Pd (refined, catalytic grade)",
    coa: [
      ["Purity (Pd)", "99.95% Min"],
      ["Platinum (Pt)", "0.01% Max"],
      ["Rhodium (Rh)", "0.01% Max"],
      ["Iridium (Ir)", "0.01% Max"],
      ["Ruthenium (Ru)", "0.01% Max"],
      ["Gold (Au)", "0.001% Max"],
      ["Iron (Fe)", "0.005% Max"],
      ["Copper (Cu)", "0.005% Max"],
      ["Form", "Sponge (powder)"],
      ["Standard", "LBMA/IPMI Good Delivery"],
    ],
    spec: "ORIGIN: South Africa/Russia/Zimbabwe. PACKAGING: Sealed glass/plastic jars inside steel lockboxes (1-5 kg), tamper-evident. CERTIFICATIONS: LBMA refiner certificate, Certificate of Origin. QUALITY: 99.95% per LBMA/IPMI Good Delivery. HANDLING: Vault storage, max security. No shelf life. Ship per LBMA chain-of-custody protocols.",
  }),

  // ───────────────────────── OTH — Other metals (4) ─────────────────────────
  p({
    sku: "MET-OTH-01-057",
    name: "Cobalt Metal 99.8%",
    category: "metals",
    hs: "8105200000",
    price: 30000,
    cap20: 20000, cap40: 26000,
    tags: ["cobalt", "metal", "99.8", "battery"],
    desc: "Cobalt metal cathodes 99.8% Co (LME registered)",
    coa: [
      ["Purity (Co)", "99.80% Min"],
      ["Nickel (Ni)", "0.10% Max"],
      ["Copper (Cu)", "0.02% Max"],
      ["Iron (Fe)", "0.05% Max"],
      ["Carbon (C)", "0.03% Max"],
      ["Sulfur (S)", "0.01% Max"],
      ["Zinc (Zn)", "0.005% Max"],
      ["Lead (Pb)", "0.001% Max"],
      ["Arsenic (As)", "0.001% Max"],
      ["Form", "Cathode cut pieces"],
      ["Standard", "ASTM A106"],
    ],
    spec: "ORIGIN: DRC/Zambia/Russia. PACKAGING: Cut cathodes in steel drums (200-250 kg), palletized, strapped. CERTIFICATIONS: Certificate of Analysis, Certificate of Origin, LME registered. QUALITY: Per ASTM A106 / LME Cobalt spec. HANDLING: Store in dry covered area; CA-mineral supply chain due diligence (OECD). No shelf life.",
  }),
  p({
    sku: "MET-OTH-02-058",
    name: "Magnesium Ingots 99.9%",
    category: "metals",
    hs: "8104110000",
    price: 3100,
    cap20: 20000, cap40: 26000,
    tags: ["magnesium", "ingots", "99.9", "light-metal"],
    desc: "Magnesium ingots 99.9% Mg for alloying and desulfurization",
    coa: [
      ["Purity (Mg)", "99.90% Min"],
      ["Iron (Fe)", "0.030% Max"],
      ["Silicon (Si)", "0.010% Max"],
      ["Aluminium (Al)", "0.020% Max"],
      ["Copper (Cu)", "0.005% Max"],
      ["Nickel (Ni)", "0.001% Max"],
      ["Manganese (Mn)", "0.010% Max"],
      ["Zinc (Zn)", "0.010% Max"],
      ["Form", "Ingots 7-8 kg"],
      ["Standard", "ASTM B92"],
    ],
    spec: "ORIGIN: China/Israel/Turkey. PACKAGING: Ingots on wooden pallets (1000kg/pallet), strapped; sealed to prevent oxidation. CERTIFICATIONS: Certificate of Analysis (ASTM B92), Certificate of Origin. QUALITY: 99.9% per ASTM B92 grade 9980A. HANDLING: Store in dry covered area; flammable (Class 4.1/4.3) — per IMDG/ADR. No shelf life. Stack max 2 pallets high.",
  }),
  p({
    sku: "MET-OTH-03-059",
    name: "Silicon Metal 553",
    category: "metals",
    hs: "2804690000",
    price: 2000,
    cap20: 20000, cap40: 26000,
    tags: ["silicon", "metal", "553", "metallurgical"],
    desc: "Silicon metal 553 grade (Si 98.5%) for aluminium alloying",
    coa: [
      ["Si Content", "98.50% Min"],
      ["Iron (Fe)", "0.50% Max"],
      ["Aluminium (Al)", "0.50% Max"],
      ["Calcium (Ca)", "0.30% Max"],
      ["Grade", "553"],
      ["Form", "Lumps 10-100 mm"],
      ["Carbon (C)", "0.10% Max"],
      ["Phosphorus (P)", "0.005% Max"],
      ["Titanium (Ti)", "0.050% Max"],
      ["Standard", "ASTM A842"],
    ],
    spec: "ORIGIN: China/Brazil/Norway/Russia. PACKAGING: In 1MT bulk bags or wooden big-box (1000kg), strapped. CERTIFICATIONS: Certificate of Analysis (ASTM A842), Certificate of Origin. QUALITY: Grade 553 per ASTM A842. HANDLING: Store in dry covered area; protect from moisture. No shelf life. Stack max 2 bags high.",
  }),
  p({
    sku: "MET-OTH-04-060",
    name: "Silicon Metal 441",
    category: "metals",
    hs: "2804690000",
    price: 2200,
    cap20: 20000, cap40: 26000,
    tags: ["silicon", "metal", "441", "chemical"],
    desc: "Silicon metal 441 grade (Si 99.0%) for chemical/solar grade",
    coa: [
      ["Si Content", "99.00% Min"],
      ["Iron (Fe)", "0.40% Max"],
      ["Aluminium (Al)", "0.40% Max"],
      ["Calcium (Ca)", "0.10% Max"],
      ["Grade", "441"],
      ["Form", "Lumps 10-100 mm"],
      ["Carbon (C)", "0.05% Max"],
      ["Phosphorus (P)", "0.004% Max"],
      ["Titanium (Ti)", "0.030% Max"],
      ["Standard", "ASTM A842"],
    ],
    spec: "ORIGIN: China/Brazil/Norway. PACKAGING: In 1MT bulk bags or wooden big-box (1000kg), strapped. CERTIFICATIONS: Certificate of Analysis (ASTM A842), Certificate of Origin. QUALITY: Grade 441 per ASTM A842, suitable for chemical/solar applications. HANDLING: Store in dry covered area; protect from moisture. No shelf life. Stack max 2 bags high.",
  }),
];

export default metalProducts;
