// VELOS — Agriculture Product Catalog (80 products)
// Sub-categories: GRA (Grains) 20, OIL (Oilseeds) 15, PUL (Pulses) 15,
// NUT (Nuts) 10, FED (Animal Feed) 10, CRP (Other Crops) 10

export interface CoaParam { name: string; value: string; }
export interface Logistics { cap20: number | null; cap40: number | null; }
export interface SeedProduct {
  sku: string; name: string; category: string; unit: string;
  price: number; currency: string; cost: number;
  stock: number; reorder_level: number; active: boolean;
  description: string; hs_code: string;
  brand: null; shelf_life: string | null; image_url: null;
  logistics: Logistics; coa_params: CoaParam[];
  detailed_spec: string; tags: string[];
}

function p(o: {
  sku: string; name: string; category: string;
  hs: string; price: number; unit?: string;
  coa: [string, string][]; spec: string;
  cap20?: number | null; cap40?: number | null;
  tags?: string[]; shelfLife?: string | null;
  desc?: string; stock?: number;
}): SeedProduct {
  const unit = o.unit ?? "MT";
  const stock = o.stock ?? 50000;
  return {
    sku: o.sku, name: o.name, category: o.category, unit,
    price: o.price, currency: "USD", cost: o.price, stock,
    reorder_level: Math.max(1, Math.floor(stock / 20)),
    active: true, description: o.desc ?? o.name,
    hs_code: o.hs, brand: null,
    shelf_life: o.shelfLife ?? null, image_url: null,
    logistics: { cap20: o.cap20 ?? null, cap40: o.cap40 ?? null },
    coa_params: o.coa.map(([name, value]) => ({ name, value })),
    detailed_spec: o.spec, tags: o.tags ?? [],
  };
}

// Logistics presets
const BAG50 = { cap20: 22000, cap40: 26000 }; // 50kg PP bags
const BULK = { cap20: 24000, cap40: 27000 };  // Bulk container

export const agricultureProducts: SeedProduct[] = [
  // ============ GRA — GRAINS (20) ============
  p({
    sku: "AGR-GRA-01-001", name: "Wheat HRW 12.5%", category: "agriculture",
    hs: "1001990000", price: 285, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["wheat", "hrw", "grain", "milling"],
    coa: [
      ["Moisture", "13.0% Max"], ["Protein (12.5% mb)", "12.5% Min"],
      ["Test Weight", "76 kg/hl Min"], ["Falling Number", "300 sec Min"],
      ["Foreign Material", "2.0% Max"], ["Damaged Kernels", "2.0% Max"],
      ["Shrunken & Broken", "3.0% Max"], ["Aflatoxin", "20 ppb Max"],
      ["Vomitoxin (DON)", "2.0 ppm Max"], ["Wet Gluten", "26% Min"],
      ["Ash Content", "1.5% Max"],
    ],
    spec: "ORIGIN: Russia (Rostov region) / USA (Kansas). PACKAGING: 50kg PP bags with inner liner or 1MT FIBCs; bulk vessel loading available. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, GAFTA contract terms. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated; protect from moisture and pests. Fumigation: aluminum phosphide per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-02-001", name: "Wheat SRW 10.5%", category: "agriculture",
    hs: "1001990000", price: 265, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["wheat", "srw", "grain", "milling"],
    coa: [
      ["Moisture", "13.0% Max"], ["Protein (12% mb)", "10.5% Min"],
      ["Test Weight", "74 kg/hl Min"], ["Falling Number", "300 sec Min"],
      ["Foreign Material", "2.0% Max"], ["Damaged Kernels", "2.0% Max"],
      ["Shrunken & Broken", "3.0% Max"], ["Aflatoxin", "20 ppb Max"],
      ["Vomitoxin (DON)", "2.0 ppm Max"], ["Wet Gluten", "22% Min"],
    ],
    spec: "ORIGIN: USA (Ohio/Indiana) / Russia. PACKAGING: 50kg PP bags with inner liner or bulk vessel. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin (Chamber of Commerce), GAFTA contract terms. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated; protect from moisture and pests. Shelf life 12 months under proper storage. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-03-001", name: "Wheat DNS 14%", category: "agriculture",
    hs: "1001990000", price: 315, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["wheat", "dns", "high-protein", "grain"],
    coa: [
      ["Moisture", "13.0% Max"], ["Protein (14% mb)", "14.0% Min"],
      ["Test Weight", "78 kg/hl Min"], ["Falling Number", "300 sec Min"],
      ["Foreign Material", "1.0% Max"], ["Damaged Kernels", "2.0% Max"],
      ["Shrunken & Broken", "3.0% Max"], ["Aflatoxin", "20 ppb Max"],
      ["Vomitoxin (DON)", "2.0 ppm Max"], ["Wet Gluten", "30% Min"],
      ["Ash Content", "1.5% Max"],
    ],
    spec: "ORIGIN: USA (North Dakota) / Canada. PACKAGING: 50kg PP bags with inner liner or 1MT FIBCs; bulk vessel loading. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, GAFTA terms. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated; protect from moisture and pests. Shelf life 12 months. Fumigation: aluminum phosphide per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-04-001", name: "Wheat Soft White", category: "agriculture",
    hs: "1001990000", price: 270, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["wheat", "soft-white", "pastry", "grain"],
    coa: [
      ["Moisture", "13.0% Max"], ["Protein (12% mb)", "9.5-11.0%"],
      ["Test Weight", "76 kg/hl Min"], ["Falling Number", "300 sec Min"],
      ["Foreign Material", "2.0% Max"], ["Damaged Kernels", "2.0% Max"],
      ["Shrunken & Broken", "3.0% Max"], ["Aflatoxin", "20 ppb Max"],
      ["Wet Gluten", "20% Min"],
    ],
    spec: "ORIGIN: USA (Pacific Northwest) / Australia. PACKAGING: 50kg PP bags with inner liner or bulk vessel loading. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, GAFTA terms. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months under proper storage. Fumigation: aluminum phosphide per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-05-001", name: "Yellow Corn #2", category: "agriculture",
    hs: "1005900000", price: 205, cap20: BULK.cap20, cap40: BULK.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["corn", "maize", "yellow", "feed"],
    coa: [
      ["Moisture", "14.0% Max"], ["Test Weight", "54 lb/bu Min"],
      ["Broken Corn & Foreign Material", "3.0% Max"], ["Heat Damage", "0.5% Max"],
      ["Total Damage", "5.0% Max"], ["Aflatoxin", "20 ppb Max"],
      ["Vomitoxin (DON)", "5.0 ppm Max"], ["Fumonisin", "5.0 ppm Max"],
      ["GMO Status", "GMO"], ["Bulk Density", "720 kg/m3 Min"],
    ],
    spec: "ORIGIN: Brazil / Argentina / Ukraine / USA. PACKAGING: Bulk vessel loading or 50kg PP bags; bulk in 20'/40' containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration (if applicable), Certificate of Origin, GAFTA terms. QUALITY: USDA/FDA standards, GAFTA trading rules. HANDLING: Store cool, dry, ventilated; protect from moisture. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-06-001", name: "White Corn", category: "agriculture",
    hs: "1005900000", price: 215, cap20: BULK.cap20, cap40: BULK.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["corn", "maize", "white", "food-grade"],
    coa: [
      ["Moisture", "14.0% Max"], ["Test Weight", "54 lb/bu Min"],
      ["Broken Corn & Foreign Material", "2.0% Max"], ["Heat Damage", "0.5% Max"],
      ["Total Damage", "3.0% Max"], ["Aflatoxin", "20 ppb Max"],
      ["Vomitoxin (DON)", "5.0 ppm Max"], ["GMO Status", "Non-GMO"],
      ["Color", "White"], ["Bulk Density", "720 kg/m3 Min"],
    ],
    spec: "ORIGIN: South Africa / Mexico / Brazil. PACKAGING: Bulk vessel or 50kg PP bags; bulk in 20'/40' containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, GAFTA terms. QUALITY: USDA/FDA standards. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation: aluminum phosphide per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-07-001", name: "Long Grain White Rice 5%", category: "agriculture",
    hs: "1006300000", price: 550, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["rice", "long-grain", "white", "food"],
    coa: [
      ["Moisture", "14.0% Max"], ["Broken Grains", "5.0% Max"],
      ["Foreign Matter", "0.5% Max"], ["Discolored Kernels", "1.0% Max"],
      ["Paddy Kernels", "0.5% Max"], ["Red & Red Streaked", "0.5% Max"],
      ["Chalky Kernels", "3.0% Max"], ["Average Grain Length", "6.7 mm Min"],
      ["Milling Degree", "Well Milled"], ["Whiteness", "40 Min"],
    ],
    spec: "ORIGIN: Thailand / Vietnam / India / Pakistan. PACKAGING: 25kg or 50kg PP bags with inner liner; private-label retail packs available. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, SGS/Intertek inspection. QUALITY: ISO 7301. HANDLING: Store cool, dry, ventilated; protect from moisture and pests. Shelf life 24 months. Fumigation: aluminum phosphide per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-08-001", name: "Parboiled Rice 5%", category: "agriculture",
    hs: "1006300000", price: 580, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["rice", "parboiled", "long-grain", "food"],
    coa: [
      ["Moisture", "13.0% Max"], ["Broken Grains", "5.0% Max"],
      ["Foreign Matter", "0.5% Max"], ["Discolored Kernels", "1.0% Max"],
      ["Paddy Kernels", "0.5% Max"], ["Chalky Kernels", "2.0% Max"],
      ["Average Grain Length", "6.7 mm Min"], ["Milling Degree", "Well Milled"],
      ["Whiteness", "30 Min"], ["Color", "Light yellow"],
    ],
    spec: "ORIGIN: Thailand / India / USA. PACKAGING: 25kg or 50kg PP bags with inner liner; private-label retail packs available. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, SGS/Intertek inspection. QUALITY: ISO 7301. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation: aluminum phosphide per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-09-001", name: "Basmati Rice 1121", category: "agriculture",
    hs: "1006300000", price: 1050, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["rice", "basmati", "1121", "premium"],
    coa: [
      ["Moisture", "12.0% Max"], ["Broken Grains", "2.0% Max"],
      ["Foreign Matter", "0.1% Max"], ["Discolored Kernels", "0.5% Max"],
      ["Paddy Kernels", "0.2% Max"], ["Average Grain Length (cooked)", "8.4 mm Min"],
      ["Milling Degree", "Double Polished, Sortex"], ["Whiteness", "42 Min"],
      ["Elongation Ratio", "2.0x Min"], ["Aroma", "Strong characteristic"],
    ],
    spec: "ORIGIN: India (Punjab/Haryana) / Pakistan. PACKAGING: 5kg, 10kg, 25kg, 50kg PP/PE bags with inner liner; private-label retail packs available. CERTIFICATIONS: Phytosanitary Certificate, APEDA Certificate of Origin, GI-protected Basmati, SGS inspection. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-10-001", name: "Jasmine Rice 5%", category: "agriculture",
    hs: "1006300000", price: 680, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "18 months under proper storage",
    tags: ["rice", "jasmine", "aromatic", "food"],
    coa: [
      ["Moisture", "14.0% Max"], ["Broken Grains", "5.0% Max"],
      ["Foreign Matter", "0.5% Max"], ["Discolored Kernels", "1.0% Max"],
      ["Paddy Kernels", "0.5% Max"], ["Chalky Kernels", "3.0% Max"],
      ["Average Grain Length", "6.8 mm Min"], ["Milling Degree", "Well Milled"],
      ["Whiteness", "40 Min"], ["Aroma", "Characteristic jasmine"],
    ],
    spec: "ORIGIN: Thailand (Korat / Surin). PACKAGING: 25kg or 50kg PP bags with inner liner; private-label retail packs available. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, SGS/Intertek inspection. QUALITY: ISO 7301, Thai Hom Mali standard. HANDLING: Store cool, dry, ventilated. Shelf life 18 months. Fumigation: aluminum phosphide per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-11-001", name: "Broken Rice 100%", category: "agriculture",
    hs: "1006400000", price: 380, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["rice", "broken", "feed", "industrial"],
    coa: [
      ["Moisture", "14.0% Max"], ["Broken Grains (under 3/4)", "100%"],
      ["Foreign Matter", "1.0% Max"], ["Discolored Kernels", "2.0% Max"],
      ["Paddy Kernels", "1.0% Max"], ["Average Length", "under 5 mm"],
      ["Milling Degree", "Well Milled"], ["Color", "White"],
    ],
    spec: "ORIGIN: Thailand / Vietnam / India / Pakistan. PACKAGING: 50kg PP bags with inner liner; bulk vessel loading available. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, SGS inspection. QUALITY: ISO 7301. HANDLING: Store cool, dry, ventilated; protect from moisture and pests. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-12-001", name: "Barley Feed", category: "agriculture",
    hs: "1003009000", price: 235, cap20: BULK.cap20, cap40: BULK.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["barley", "feed", "grain"],
    coa: [
      ["Moisture", "14.0% Max"], ["Protein (dry basis)", "10.0% Min"],
      ["Test Weight", "60 kg/hl Min"], ["Foreign Material", "2.0% Max"],
      ["Broken Kernels", "4.0% Max"], ["Damaged Kernels", "2.0% Max"],
      ["Sprout Damage", "4.0% Max"], ["Aflatoxin", "20 ppb Max"],
      ["Bulk Density", "600 kg/m3 Min"],
    ],
    spec: "ORIGIN: Russia / Ukraine / Australia. PACKAGING: Bulk vessel loading or 50kg PP bags; bulk in 20'/40' containers. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, GAFTA terms. QUALITY: GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months under proper storage. Fumigation: aluminum phosphide per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-13-001", name: "Barley Malting", category: "agriculture",
    hs: "1003009000", price: 275, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["barley", "malting", "brewing", "premium"],
    coa: [
      ["Moisture", "13.5% Max"], ["Protein (dry basis)", "11.5% Max"],
      ["Test Weight", "64 kg/hl Min"], ["Foreign Material", "1.0% Max"],
      ["Broken Kernels", "2.0% Max"], ["Damaged Kernels", "1.0% Max"],
      ["Sprout Damage", "1.0% Max"], ["Germination (72h)", "95% Min"],
      ["Plump Kernels", "80% Min"], ["Thins", "5.0% Max"],
      ["Aflatoxin", "20 ppb Max"],
    ],
    spec: "ORIGIN: Australia / EU (France/Germany) / Canada. PACKAGING: 50kg PP bags with inner liner or bulk container. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, GAFTA terms, Malting Barley Analysis. QUALITY: EBC/ASBC standards. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-14-001", name: "Oats", category: "agriculture",
    hs: "1004900000", price: 275, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["oats", "grain", "food"],
    coa: [
      ["Moisture", "14.0% Max"], ["Test Weight", "50 kg/hl Min"],
      ["Foreign Material", "2.0% Max"], ["Broken Kernels", "3.0% Max"],
      ["Damaged Kernels", "2.0% Max"], ["Wild Oats", "2.0% Max"],
      ["Heat Damage", "0.5% Max"], ["Aflatoxin", "20 ppb Max"],
      ["Color", "Bright"], ["Odor", "Free from musty/ sour"],
    ],
    spec: "ORIGIN: Canada / Australia / Finland. PACKAGING: 50kg PP bags with inner liner or bulk container. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, GAFTA terms. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-15-001", name: "Sorghum Red", category: "agriculture",
    hs: "1007009000", price: 255, cap20: BULK.cap20, cap40: BULK.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["sorghum", "red", "grain", "feed"],
    coa: [
      ["Moisture", "14.0% Max"], ["Test Weight", "55 lb/bu Min"],
      ["Foreign Material", "2.0% Max"], ["Broken Kernels", "3.0% Max"],
      ["Damaged Kernels", "2.0% Max"], ["Heat Damage", "0.5% Max"],
      ["Aflatoxin", "20 ppb Max"], ["Color", "Red"], ["Tannin", "Low"],
    ],
    spec: "ORIGIN: Argentina / Sudan / USA. PACKAGING: Bulk vessel loading or 50kg PP bags; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, GAFTA terms. QUALITY: USDA/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-16-001", name: "Sorghum White", category: "agriculture",
    hs: "1007009000", price: 265, cap20: BULK.cap20, cap40: BULK.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["sorghum", "white", "food-grade", "grain"],
    coa: [
      ["Moisture", "14.0% Max"], ["Test Weight", "55 lb/bu Min"],
      ["Foreign Material", "1.5% Max"], ["Broken Kernels", "3.0% Max"],
      ["Damaged Kernels", "2.0% Max"], ["Heat Damage", "0.5% Max"],
      ["Aflatoxin", "20 ppb Max"], ["Color", "White"], ["Tannin", "None"],
    ],
    spec: "ORIGIN: Sudan / Nigeria / Argentina. PACKAGING: 50kg PP bags with inner liner or bulk container. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, GAFTA terms. QUALITY: USDA/GAFTA rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-17-001", name: "Millet Yellow", category: "agriculture",
    hs: "1008290000", price: 310, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["millet", "yellow", "gluten-free", "grain"],
    coa: [
      ["Moisture", "13.0% Max"], ["Foreign Matter", "1.0% Max"],
      ["Broken", "2.0% Max"], ["Damaged Kernels", "2.0% Max"],
      ["Discolored", "1.0% Max"], ["Color", "Bright yellow"],
      ["Aflatoxin", "20 ppb Max"], ["Purity", "98% Min"],
    ],
    spec: "ORIGIN: India / Nigeria / China. PACKAGING: 25kg or 50kg PP bags with inner liner. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, SGS inspection. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-18-001", name: "Rye", category: "agriculture",
    hs: "1002009000", price: 260, cap20: BULK.cap20, cap40: BULK.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["rye", "grain", "milling"],
    coa: [
      ["Moisture", "14.0% Max"], ["Test Weight", "64 kg/hl Min"],
      ["Foreign Material", "2.0% Max"], ["Broken Kernels", "3.0% Max"],
      ["Damaged Kernels", "2.0% Max"], ["Heat Damage", "0.5% Max"],
      ["Aflatoxin", "20 ppb Max"], ["Falling Number", "180 sec Min"],
      ["Ergot", "0.05% Max"],
    ],
    spec: "ORIGIN: Poland / Germany / Russia. PACKAGING: Bulk vessel loading or 50kg PP bags; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, GAFTA terms. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-19-001", name: "Triticale", category: "agriculture",
    hs: "1008900000", price: 245, cap20: BULK.cap20, cap40: BULK.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["triticale", "hybrid", "feed", "grain"],
    coa: [
      ["Moisture", "14.0% Max"], ["Test Weight", "60 kg/hl Min"],
      ["Foreign Material", "2.0% Max"], ["Broken Kernels", "3.0% Max"],
      ["Damaged Kernels", "2.0% Max"], ["Heat Damage", "0.5% Max"],
      ["Protein (dry basis)", "11.0% Min"], ["Aflatoxin", "20 ppb Max"],
    ],
    spec: "ORIGIN: Poland / Germany / Australia. PACKAGING: Bulk vessel loading or 50kg PP bags; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, GAFTA terms. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-GRA-20-001", name: "Canary Seed", category: "agriculture",
    hs: "1008300000", price: 425, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["canary-seed", "bird-seed", "grain"],
    coa: [
      ["Moisture", "13.0% Max"], ["Test Weight", "65 kg/hl Min"],
      ["Foreign Material", "1.0% Max"], ["Broken Kernels", "2.0% Max"],
      ["Damaged Kernels", "2.0% Max"], ["Hulled (Brown)", "98% Min"],
      ["Color", "Brown"], ["Purity", "99% Min"], ["Aflatoxin", "20 ppb Max"],
    ],
    spec: "ORIGIN: Canada / Argentina / Hungary. PACKAGING: 25kg or 50kg PP bags with inner liner. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, SGS inspection. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),

  // ============ OIL — OILSEEDS (15) ============
  p({
    sku: "AGR-OIL-01-001", name: "Soybeans Non-GMO", category: "agriculture",
    hs: "1201900000", price: 540, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["soybeans", "non-gmo", "oilseed", "food-grade"],
    coa: [
      ["Moisture", "13.0% Max"], ["Protein (13% mb)", "35% Min"],
      ["Oil Content", "18% Min"], ["Foreign Material", "1.0% Max"],
      ["Splits", "10% Max"], ["Heat Damage", "0.5% Max"],
      ["Purple Mottled/Stained", "1.0% Max"], ["Aflatoxin", "20 ppb Max"],
      ["GMO Status", "Non-GMO (IP)"], ["Bulk Density", "730 kg/m3 Min"],
    ],
    spec: "ORIGIN: Brazil / India / Ukraine / Canada. PACKAGING: 50kg PP bags with inner liner or bulk vessel. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO IP declaration, Certificate of Origin, GAFTA terms, SGS inspection. QUALITY: GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-02-001", name: "Soybeans GMO", category: "agriculture",
    hs: "1201900000", price: 490, cap20: BULK.cap20, cap40: BULK.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["soybeans", "gmo", "oilseed", "commodity"],
    coa: [
      ["Moisture", "13.0% Max"], ["Protein (13% mb)", "35% Min"],
      ["Oil Content", "18% Min"], ["Foreign Material", "1.0% Max"],
      ["Splits", "10% Max"], ["Heat Damage", "0.5% Max"],
      ["Purple Mottled/Stained", "1.0% Max"], ["Aflatoxin", "20 ppb Max"],
      ["GMO Status", "GMO"], ["Bulk Density", "730 kg/m3 Min"],
    ],
    spec: "ORIGIN: Brazil / Argentina / USA. PACKAGING: Bulk vessel loading or 50kg PP bags; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, GAFTA terms, SGS inspection. QUALITY: GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-03-001", name: "Soybeans Food Grade", category: "agriculture",
    hs: "1201900000", price: 560, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["soybeans", "food-grade", "non-gmo", "premium"],
    coa: [
      ["Moisture", "12.0% Max"], ["Protein (13% mb)", "36% Min"],
      ["Oil Content", "19% Min"], ["Foreign Material", "0.5% Max"],
      ["Splits", "5% Max"], ["Heat Damage", "0.2% Max"],
      ["Purple Mottled/Stained", "0.5% Max"], ["Aflatoxin", "10 ppb Max"],
      ["GMO Status", "Non-GMO (IP)"], ["Bulk Density", "740 kg/m3 Min"],
      ["Size", "Large (5.5 mm+)"],
    ],
    spec: "ORIGIN: Canada / USA / India. PACKAGING: 25kg or 50kg PP bags with inner liner or 1MT FIBCs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO IP, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: Food-grade IP. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-04-001", name: "Sunflower Seeds Confection", category: "agriculture",
    hs: "1206009000", price: 470, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["sunflower", "confection", "oilseed", "food"],
    coa: [
      ["Moisture", "9.0% Max"], ["Oil Content", "35% Min"],
      ["Foreign Material", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Damaged", "2.0% Max"], ["Sizing (large)", "60% over 8mm"],
      ["Color", "Black stripe"], ["Aflatoxin", "10 ppb Max"],
      ["Purity", "99% Min"],
    ],
    spec: "ORIGIN: Bulgaria / Romania / Russia / Argentina. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs available. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, SGS inspection. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-05-001", name: "Sunflower Seeds Oil Type 40% Oil", category: "agriculture",
    hs: "1206009000", price: 430, cap20: BULK.cap20, cap40: BULK.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["sunflower", "oil-type", "oilseed", "crushing"],
    coa: [
      ["Moisture", "9.0% Max"], ["Oil Content", "40% Min"],
      ["Foreign Material", "2.0% Max"], ["Broken", "3.0% Max"],
      ["Damaged", "3.0% Max"], ["Free Fatty Acid (oil)", "2.0% Max"],
      ["Color", "Black"], ["Aflatoxin", "10 ppb Max"],
    ],
    spec: "ORIGIN: Ukraine / Russia / Romania. PACKAGING: Bulk vessel loading or 50kg PP bags; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, GAFTA terms. QUALITY: FOSFA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-06-001", name: "Rapeseed 00", category: "agriculture",
    hs: "1205009000", price: 490, cap20: BULK.cap20, cap40: BULK.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["rapeseed", "canola-type", "oilseed", "crushing"],
    coa: [
      ["Moisture", "9.0% Max"], ["Oil Content", "40% Min"],
      ["Foreign Material", "2.0% Max"], ["Broken", "2.0% Max"],
      ["Damaged", "2.0% Max"], ["Erucic Acid", "2.0% Max"],
      ["Glucosinolates", "30 µmol/g Max"], ["Free Fatty Acid", "2.0% Max"],
      ["Aflatoxin", "10 ppb Max"],
    ],
    spec: "ORIGIN: Ukraine / Russia / EU (France/Germany). PACKAGING: Bulk vessel loading or 50kg PP bags; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, FOSFA terms. QUALITY: FOSFA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-07-001", name: "Canola", category: "agriculture",
    hs: "1205009000", price: 510, cap20: BULK.cap20, cap40: BULK.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["canola", "rapeseed", "oilseed", "low-erucic"],
    coa: [
      ["Moisture", "9.0% Max"], ["Oil Content", "42% Min"],
      ["Foreign Material", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Damaged", "2.0% Max"], ["Erucic Acid", "2.0% Max"],
      ["Glucosinolates", "30 µmol/g Max"], ["Free Fatty Acid", "1.0% Max"],
      ["Chlorophyll", "25 mg/kg Max"], ["Aflatoxin", "10 ppb Max"],
    ],
    spec: "ORIGIN: Canada / Australia. PACKAGING: Bulk vessel loading or 50kg PP bags; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, FOSFA terms, Canadian Canola standard. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-08-001", name: "Sesame Natural 99/1", category: "agriculture",
    hs: "1207409000", price: 1150, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["sesame", "natural", "99/1", "oilseed"],
    coa: [
      ["Purity", "99.0% Min"], ["Moisture", "6.0% Max"],
      ["Oil Content", "50% Min"], ["Foreign Matter", "1.0% Max"],
      ["FFA (as oleic)", "2.0% Max"], ["Color", "Whitish"],
      ["Aflatoxin", "5 ppb Max"], ["Salmonella", "Absent/25g"],
      ["Peroxide Value", "5.0 meq/kg Max"],
    ],
    spec: "ORIGIN: India / Nigeria / Sudan / Tanzania. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: HACCP, ISO 22000. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-09-001", name: "Sesame Hulled", category: "agriculture",
    hs: "1207409000", price: 1350, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "18 months under proper storage",
    tags: ["sesame", "hulled", "premium", "food"],
    coa: [
      ["Purity", "99.5% Min"], ["Moisture", "5.0% Max"],
      ["Oil Content", "55% Min"], ["Foreign Matter", "0.5% Max"],
      ["FFA (as oleic)", "1.5% Max"], ["Color", "Pure white"],
      ["Hulling Degree", "99% Min"], ["Aflatoxin", "2 ppb Max"],
      ["Salmonella", "Absent/25g"], ["Peroxide Value", "3.0 meq/kg Max"],
    ],
    spec: "ORIGIN: India / Pakistan. PACKAGING: 25kg PP bags with inner liner or food-grade cartons; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, BRC, ISO 22000, SGS inspection. HANDLING: Store cool, dry, ventilated. Shelf life 18 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-10-001", name: "Flaxseed Brown", category: "agriculture",
    hs: "1204009000", price: 520, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "18 months under proper storage",
    tags: ["flaxseed", "linseed", "brown", "omega-3"],
    coa: [
      ["Purity", "99.0% Min"], ["Moisture", "9.0% Max"],
      ["Oil Content", "40% Min"], ["Foreign Matter", "1.0% Max"],
      ["Color", "Brown"], ["Aflatoxin", "5 ppb Max"],
      ["FFA (as oleic)", "2.0% Max"], ["Peroxide Value", "5.0 meq/kg Max"],
      ["Cadmium", "0.5 ppm Max"],
    ],
    spec: "ORIGIN: Canada / Russia / Kazakhstan. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, SGS inspection. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 18 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-11-001", name: "Safflower", category: "agriculture",
    hs: "1207709000", price: 460, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["safflower", "oilseed", "bird-seed"],
    coa: [
      ["Purity", "99.0% Min"], ["Moisture", "9.0% Max"],
      ["Oil Content", "32% Min"], ["Foreign Matter", "1.0% Max"],
      ["Color", "White"], ["Aflatoxin", "10 ppb Max"],
      ["FFA (as oleic)", "2.0% Max"], ["Damaged", "2.0% Max"],
    ],
    spec: "ORIGIN: India / USA / Mexico. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, SGS inspection. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-12-001", name: "Cottonseed Delinted", category: "agriculture",
    hs: "1207210000", price: 380, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["cottonseed", "delinted", "oilseed", "feed"],
    coa: [
      ["Moisture", "10.0% Max"], ["Oil Content", "18% Min"],
      ["Protein", "22% Min"], ["Free Gossypol", "0.5% Max"],
      ["Foreign Matter", "1.0% Max"], ["Linter Content", "1.0% Max"],
      ["Aflatoxin", "20 ppb Max"], ["Color", "Brown-black"],
    ],
    spec: "ORIGIN: India / USA / Brazil. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, SGS inspection. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-13-001", name: "Palm Kernel", category: "agriculture",
    hs: "1207609000", price: 490, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["palm-kernel", "oilseed", "tropical", "crushing"],
    coa: [
      ["Moisture", "10.0% Max"], ["Oil Content", "48% Min"],
      ["Foreign Matter", "2.0% Max"], ["Broken", "3.0% Max"],
      ["Damaged", "3.0% Max"], ["FFA (as lauric)", "5.0% Max"],
      ["Aflatoxin", "10 ppb Max"], ["Color", "Dark brown"],
    ],
    spec: "ORIGIN: Indonesia / Malaysia / Nigeria. PACKAGING: 50kg PP bags with inner liner or bulk vessel; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, RSPO (optional), Certificate of Origin, FOSFA terms. QUALITY: FOSFA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-14-001", name: "Castor Seeds", category: "agriculture",
    hs: "1207309000", price: 540, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["castor", "oilseed", "industrial", "non-edible"],
    coa: [
      ["Purity", "99.0% Min"], ["Moisture", "7.0% Max"],
      ["Oil Content", "48% Min"], ["Foreign Matter", "1.0% Max"],
      ["Broken", "2.0% Max"], ["Color", "Mottled brown"],
      ["Ricin Content (seed coat)", "present"], ["Aflatoxin", "10 ppb Max"],
    ],
    spec: "ORIGIN: India (Gujarat) / Brazil / China. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, FOSFA terms. QUALITY: Industrial non-edible grade. HANDLING: Store cool, dry, ventilated; toxic if ingested. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-OIL-15-001", name: "Hemp Seeds", category: "agriculture",
    hs: "1207990000", price: 1280, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "18 months under proper storage",
    tags: ["hemp", "seeds", "superfood", "non-gmo"],
    coa: [
      ["Purity", "99.5% Min"], ["Moisture", "9.0% Max"],
      ["Oil Content", "32% Min"], ["Foreign Matter", "0.5% Max"],
      ["THC", "0.2% Max"], ["Color", "Light grey-brown"],
      ["Aflatoxin", "2 ppb Max"], ["Salmonella", "Absent/25g"],
      ["Peroxide Value", "3.0 meq/kg Max"],
    ],
    spec: "ORIGIN: Canada / Romania / China. PACKAGING: 25kg PP bags with inner liner or food-grade cartons; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, THC compliant (<0.2%), Kosher, Halal, ISO 22000, SGS inspection. HANDLING: Store cool, dry, ventilated. Shelf life 18 months. Fumigation per ISPM-15.",
  }),

  // ============ PUL — PULSES (15) ============
  p({
    sku: "AGR-PUL-01-001", name: "Red Lentils Whole", category: "agriculture",
    hs: "0713400000", price: 720, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["lentils", "red", "whole", "pulses"],
    coa: [
      ["Moisture", "14.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Color", "Uniform red"],
      ["Size", "3-4 mm"], ["Cooking Time", "25-30 min"],
    ],
    spec: "ORIGIN: Turkey / Canada / Syria. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-02-001", name: "Red Lentils Split", category: "agriculture",
    hs: "0713400000", price: 740, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["lentils", "red", "split", "pulses"],
    coa: [
      ["Moisture", "13.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "0.5% Max"], ["Broken", "3.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Color", "Salmon red"],
      ["Size", "2-3 mm split"], ["Cooking Time", "15-20 min"],
      ["Sortex", "Yes"],
    ],
    spec: "ORIGIN: Turkey / Canada / UAE-processed. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, SGS inspection. QUALITY: Sortex-cleaned. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-03-001", name: "Green Lentils", category: "agriculture",
    hs: "0713400000", price: 680, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["lentils", "green", "whole", "pulses"],
    coa: [
      ["Moisture", "14.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Color", "Olive green"],
      ["Size", "5-7 mm"], ["Cooking Time", "30-35 min"],
    ],
    spec: "ORIGIN: Canada / Turkey / USA. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-04-001", name: "Brown Lentils", category: "agriculture",
    hs: "0713400000", price: 650, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["lentils", "brown", "whole", "pulses"],
    coa: [
      ["Moisture", "14.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Color", "Brown"],
      ["Size", "5-7 mm"], ["Cooking Time", "30-35 min"],
    ],
    spec: "ORIGIN: Turkey / Canada / USA. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: IGC/GAFTA trading rules. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-05-001", name: "French Green Lentils", category: "agriculture",
    hs: "0713400000", price: 890, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["lentils", "french-green", "puy-type", "premium"],
    coa: [
      ["Moisture", "14.0% Max"], ["Admixture", "0.5% Max"],
      ["Weevilled", "0.5% Max"], ["Broken", "1.0% Max"],
      ["Foreign Material", "0.3% Max"], ["Color", "Dark green mottled"],
      ["Size", "4-5 mm"], ["Cooking Time", "35-40 min"],
      ["Texture", "Firm, holds shape"],
    ],
    spec: "ORIGIN: France (Puy) / Canada. PACKAGING: 25kg PP bags with inner liner or food-grade cartons; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, AOP/IGP (Puy), SGS inspection. QUALITY: Premium Puy-type. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-06-001", name: "Chickpeas Kabuli 10mm", category: "agriculture",
    hs: "0713200000", price: 920, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["chickpeas", "kabuli", "garbanzo", "premium"],
    coa: [
      ["Moisture", "12.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Size", "10 mm+ (9-10 mm allowed)"],
      ["Color", "Cream"], ["Shape", "Round, ram-head"],
      ["Cooking Time", "60-90 min"], ["Sortex", "Yes"],
    ],
    spec: "ORIGIN: India / Mexico / Australia / Turkey. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: Sortex-cleaned premium. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-07-001", name: "Chickpeas Kabuli 8mm", category: "agriculture",
    hs: "0713200000", price: 820, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["chickpeas", "kabuli", "8mm", "pulses"],
    coa: [
      ["Moisture", "12.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Size", "8-9 mm"],
      ["Color", "Cream"], ["Shape", "Round, ram-head"],
      ["Cooking Time", "60-90 min"], ["Sortex", "Yes"],
    ],
    spec: "ORIGIN: India / Mexico / Australia. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: Sortex-cleaned. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-08-001", name: "Chickpeas Desi", category: "agriculture",
    hs: "0713200000", price: 720, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["chickpeas", "desi", "brown", "pulses"],
    coa: [
      ["Moisture", "12.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Size", "5-7 mm"],
      ["Color", "Dark brown"], ["Shape", "Angular"],
      ["Cooking Time", "45-60 min"],
    ],
    spec: "ORIGIN: India / Australia / Ethiopia. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: Sortex-cleaned. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-09-001", name: "Kidney Beans Red", category: "agriculture",
    hs: "0713330000", price: 950, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["beans", "kidney", "red", "pulses"],
    coa: [
      ["Moisture", "14.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Size", "180-220 pcs/100g"],
      ["Color", "Deep red"], ["Shape", "Kidney"],
      ["Cooking Time", "60-90 min"], ["Sortex", "Yes"],
    ],
    spec: "ORIGIN: China / Argentina / USA. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: Sortex-cleaned. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-10-001", name: "Black Beans", category: "agriculture",
    hs: "0713330000", price: 880, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["beans", "black", "turtle", "pulses"],
    coa: [
      ["Moisture", "14.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Size", "200-240 pcs/100g"],
      ["Color", "Glossy black"], ["Shape", "Oval"],
      ["Cooking Time", "60-90 min"], ["Sortex", "Yes"],
    ],
    spec: "ORIGIN: Argentina / Mexico / China. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: Sortex-cleaned. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-11-001", name: "Pinto Beans", category: "agriculture",
    hs: "0713330000", price: 860, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["beans", "pinto", "speckled", "pulses"],
    coa: [
      ["Moisture", "14.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Size", "180-220 pcs/100g"],
      ["Color", "Tan with brown speckles"], ["Shape", "Oval"],
      ["Cooking Time", "60-90 min"], ["Sortex", "Yes"],
    ],
    spec: "ORIGIN: USA / Mexico / Argentina. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: Sortex-cleaned. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-12-001", name: "Navy Beans", category: "agriculture",
    hs: "0713320000", price: 830, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["beans", "navy", "white", "pulses"],
    coa: [
      ["Moisture", "14.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Size", "350-450 pcs/100g"],
      ["Color", "White"], ["Shape", "Small oval"],
      ["Cooking Time", "45-60 min"], ["Sortex", "Yes"],
    ],
    spec: "ORIGIN: Canada / USA / Ethiopia. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: Sortex-cleaned. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-13-001", name: "Mung Beans Green", category: "agriculture",
    hs: "0713319000", price: 1150, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["mung-beans", "green", "sprouting", "pulses"],
    coa: [
      ["Moisture", "13.0% Max"], ["Admixture", "0.5% Max"],
      ["Weevilled", "0.5% Max"], ["Broken", "1.0% Max"],
      ["Foreign Material", "0.3% Max"], ["Size", "300-400 pcs/100g"],
      ["Color", "Bright green"], ["Shape", "Small round"],
      ["Germination", "95% Min"], ["Sortex", "Yes"],
    ],
    spec: "ORIGIN: India / China / Australia. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: Sortex-cleaned, sprouting grade. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-14-001", name: "Yellow Peas Split", category: "agriculture",
    hs: "0713100000", price: 480, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["peas", "yellow", "split", "pulses"],
    coa: [
      ["Moisture", "14.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "1.0% Max"], ["Broken", "3.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Color", "Bright yellow"],
      ["Size", "5-7 mm split"], ["Cooking Time", "30-40 min"],
      ["Sortex", "Yes"],
    ],
    spec: "ORIGIN: Canada / Russia / Ukraine. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs; private-label retail packs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: Sortex-cleaned. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-PUL-15-001", name: "Faba Beans", category: "agriculture",
    hs: "0713500000", price: 560, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["faba", "beans", "broad", "pulses"],
    coa: [
      ["Moisture", "14.0% Max"], ["Admixture", "1.0% Max"],
      ["Weevilled", "1.0% Max"], ["Broken", "2.0% Max"],
      ["Foreign Material", "0.5% Max"], ["Size", "70-90 pcs/100g"],
      ["Color", "Buff/light brown"], ["Shape", "Flat oval"],
      ["Cooking Time", "60-90 min"], ["Sortex", "Yes"],
    ],
    spec: "ORIGIN: Australia / UK / Ethiopia. PACKAGING: 25kg or 50kg PP bags with inner liner; 1MT FIBCs. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO, Kosher, Halal, Certificate of Origin, SGS inspection. QUALITY: Sortex-cleaned. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),

  // ============ NUT — NUTS (10) ============
  p({
    sku: "AGR-NUT-01-001", name: "Cashew W240", category: "agriculture",
    hs: "0801310000", price: 7800, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["cashew", "w240", "premium", "kernel"],
    coa: [
      ["Grade", "W240 (240 count/lb)"], ["Moisture", "5.0% Max"],
      ["Broken", "5% Max"], ["Admixture", "0.5% Max"],
      ["Color", "White/pale ivory"], ["Texture", "Firm, crisp"],
      ["Peroxide Value", "1.0 meq/kg Max"], ["Aflatoxin B1", "2 ppb Max"],
      ["Total Aflatoxin", "4 ppb Max"], ["Acid Value", "0.5 mg KOH/g Max"],
    ],
    spec: "ORIGIN: Vietnam / India / Ivory Coast. PACKAGING: 50lb (22.68kg) tins in cartons, vacuum-sealed; 2x10kg cartons; private-label retail packs available. CERTIFICATIONS: HACCP, BRC, Kosher, Halal, Phytosanitary Certificate, SGS inspection. QUALITY: CEPEA trading standards. HANDLING: Store cool (<10°C), dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-NUT-02-001", name: "Cashew W320", category: "agriculture",
    hs: "0801310000", price: 6800, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["cashew", "w320", "kernel", "standard"],
    coa: [
      ["Grade", "W320 (320 count/lb)"], ["Moisture", "5.0% Max"],
      ["Broken", "5% Max"], ["Admixture", "0.5% Max"],
      ["Color", "White/pale ivory"], ["Texture", "Firm, crisp"],
      ["Peroxide Value", "1.0 meq/kg Max"], ["Aflatoxin B1", "2 ppb Max"],
      ["Total Aflatoxin", "4 ppb Max"], ["Acid Value", "0.5 mg KOH/g Max"],
    ],
    spec: "ORIGIN: Vietnam / India / Ivory Coast. PACKAGING: 50lb (22.68kg) tins in cartons, vacuum-sealed; 2x10kg cartons; private-label retail packs available. CERTIFICATIONS: HACCP, BRC, Kosher, Halal, Phytosanitary Certificate, SGS inspection. QUALITY: CEPEA trading standards. HANDLING: Store cool (<10°C), dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-NUT-03-001", name: "Cashew W450", category: "agriculture",
    hs: "0801310000", price: 6200, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["cashew", "w450", "kernel", "small"],
    coa: [
      ["Grade", "W450 (450 count/lb)"], ["Moisture", "5.0% Max"],
      ["Broken", "5% Max"], ["Admixture", "0.5% Max"],
      ["Color", "White/pale ivory"], ["Texture", "Firm, crisp"],
      ["Peroxide Value", "1.0 meq/kg Max"], ["Aflatoxin B1", "2 ppb Max"],
      ["Total Aflatoxin", "4 ppb Max"], ["Acid Value", "0.5 mg KOH/g Max"],
    ],
    spec: "ORIGIN: Vietnam / India / Ivory Coast. PACKAGING: 50lb (22.68kg) tins in cartons, vacuum-sealed; 2x10kg cartons; private-label retail packs available. CERTIFICATIONS: HACCP, BRC, Kosher, Halal, Phytosanitary Certificate, SGS inspection. QUALITY: CEPEA trading standards. HANDLING: Store cool (<10°C), dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-NUT-04-001", name: "Almonds Nonpareil", category: "agriculture",
    hs: "0802110000", price: 4200, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "18 months under proper storage",
    tags: ["almonds", "nonpareil", "california", "premium"],
    coa: [
      ["Variety", "Nonpareil"], ["Size", "23/25 or 25/27"],
      ["Moisture", "5.0% Max"], ["Broken", "3% Max"],
      ["Chipped/Scratched", "5% Max"], ["Doubles", "3% Max"],
      ["Foreign Material", "0.2% Max"], ["Aflatoxin", "4 ppb Max"],
      ["Peroxide Value", "1.5 meq/kg Max"],
    ],
    spec: "ORIGIN: USA (California) / Spain / Australia. PACKAGING: 25kg cartons with vacuum-sealed liner; 50lb cartons; private-label retail packs. CERTIFICATIONS: HACCP, BRC, Kosher, Halal, Phytosanitary Certificate, SGS inspection. HANDLING: Store cool (<10°C), dry, ventilated. Shelf life 18 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-NUT-05-001", name: "Almonds Carmel", category: "agriculture",
    hs: "0802110000", price: 3900, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "18 months under proper storage",
    tags: ["almonds", "carmel", "california", "kernel"],
    coa: [
      ["Variety", "Carmel"], ["Size", "25/27 or 27/30"],
      ["Moisture", "5.0% Max"], ["Broken", "3% Max"],
      ["Chipped/Scratched", "5% Max"], ["Doubles", "5% Max"],
      ["Foreign Material", "0.2% Max"], ["Aflatoxin", "4 ppb Max"],
      ["Peroxide Value", "1.5 meq/kg Max"],
    ],
    spec: "ORIGIN: USA (California) / Spain. PACKAGING: 25kg cartons with vacuum-sealed liner; 50lb cartons; private-label retail packs. CERTIFICATIONS: HACCP, BRC, Kosher, Halal, Phytosanitary Certificate, SGS inspection. HANDLING: Store cool (<10°C), dry, ventilated. Shelf life 18 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-NUT-06-001", name: "Walnuts Light Halves", category: "agriculture",
    hs: "0802310000", price: 5200, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["walnuts", "halves", "light", "kernel"],
    coa: [
      ["Grade", "Light halves (LH)"], ["Color", "Extra light/light"],
      ["Halves", "85% Min"], ["Pieces", "10% Max"],
      ["Moisture", "5.0% Max"], ["Broken", "5% Max"],
      ["Foreign Material", "0.2% Max"], ["Aflatoxin", "4 ppb Max"],
      ["Peroxide Value", "1.5 meq/kg Max"], ["Acid Value", "0.6 mg KOH/g Max"],
    ],
    spec: "ORIGIN: USA (California) / Chile / China. PACKAGING: 25kg cartons with vacuum-sealed liner; 50lb cartons; private-label retail packs. CERTIFICATIONS: HACCP, BRC, Kosher, Halal, Phytosanitary Certificate, SGS inspection. HANDLING: Store cool (<10°C), dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-NUT-07-001", name: "Hazelnuts", category: "agriculture",
    hs: "0802210000", price: 5800, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "18 months under proper storage",
    tags: ["hazelnuts", "filberts", "kernel", "premium"],
    coa: [
      ["Variety", "Tombul/Giresun or Tonda Gentile"], ["Size", "13-15 mm"],
      ["Moisture", "5.0% Max"], ["Broken", "3% Max"],
      ["Shriveled", "2% Max"], ["Foreign Material", "0.5% Max"],
      ["Aflatoxin", "4 ppb Max"], ["Peroxide Value", "1.5 meq/kg Max"],
      ["Acid Value", "0.6 mg KOH/g Max"], ["Calibration", "11-13 mm"],
    ],
    spec: "ORIGIN: Turkey (Giresun) / Italy / USA (Oregon). PACKAGING: 25kg cartons with vacuum-sealed liner; 50lb cartons; private-label retail packs. CERTIFICATIONS: HACCP, BRC, Kosher, Halal, Phytosanitary Certificate, SGS inspection. HANDLING: Store cool (<10°C), dry, ventilated. Shelf life 18 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-NUT-08-001", name: "Pistachios Raw", category: "agriculture",
    hs: "0802510000", price: 6800, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["pistachios", "raw", "in-shell", "premium"],
    coa: [
      ["Grade", "Raw in-shell"], ["Size", "18-20/10g or 20-22/10g"],
      ["Moisture", "5.0% Max"], ["Split", "90% Min"],
      ["Closed", "2% Max"], ["Stained", "3% Max"],
      ["Foreign Material", "0.5% Max"], ["Aflatoxin", "4 ppb Max"],
      ["Peroxide Value", "2.0 meq/kg Max"],
    ],
    spec: "ORIGIN: USA (California) / Iran / Turkey. PACKAGING: 25kg or 50lb cartons with vacuum-sealed liner; private-label retail packs. CERTIFICATIONS: HACCP, BRC, Kosher, Halal, Phytosanitary Certificate, SGS inspection. QUALITY: FDA/DFA standards. HANDLING: Store cool (<10°C), dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-NUT-09-001", name: "Pecans", category: "agriculture",
    hs: "0802210000", price: 6400, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["pecans", "halves", "raw", "kernel"],
    coa: [
      ["Grade", "Mammoth Halves"], ["Color", "Light/amber"],
      ["Halves", "85% Min"], ["Pieces", "10% Max"],
      ["Moisture", "4.0% Max"], ["Broken", "5% Max"],
      ["Foreign Material", "0.5% Max"], ["Aflatoxin", "4 ppb Max"],
      ["Peroxide Value", "1.5 meq/kg Max"],
    ],
    spec: "ORIGIN: USA (Georgia/Texas) / Mexico / South Africa. PACKAGING: 25kg cartons with vacuum-sealed liner; 50lb cartons; private-label retail packs. CERTIFICATIONS: HACCP, BRC, Kosher, Halal, Phytosanitary Certificate, SGS inspection. HANDLING: Store cool (<5°C), dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-NUT-10-001", name: "Brazil Nuts", category: "agriculture",
    hs: "0801210000", price: 5500, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["brazil-nuts", "raw", "kernel", "selenium"],
    coa: [
      ["Grade", "Whole, extra large"], ["Size", "120-140 count/lb"],
      ["Moisture", "5.0% Max"], ["Broken", "3% Max"],
      ["Shriveled", "2% Max"], ["Foreign Material", "0.5% Max"],
      ["Aflatoxin", "4 ppb Max"], ["Peroxide Value", "1.5 meq/kg Max"],
      ["Selenium", "50-200 ppm"],
    ],
    spec: "ORIGIN: Brazil / Bolivia / Peru. PACKAGING: 25kg cartons with vacuum-sealed liner; 50lb cartons; private-label retail packs. CERTIFICATIONS: HACCP, BRC, Kosher, Halal, Phytosanitary Certificate, SGS inspection. HANDLING: Store cool (<10°C), dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),

  // ============ FED — ANIMAL FEED (10) ============
  p({
    sku: "AGR-FED-01-001", name: "Soybean Meal 46% Protein", category: "agriculture",
    hs: "2304000000", price: 460, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["soybean-meal", "feed", "protein", "dehulled"],
    coa: [
      ["Protein (as is)", "46.0% Min"], ["Moisture", "12.0% Max"],
      ["Fat", "1.0% Min"], ["Fiber", "3.5% Max"],
      ["Ash", "6.5% Max"], ["Urease Activity", "0.05-0.20 pH rise"],
      ["Protein Solubility (KOH)", "75-85%"], ["Trypsin Inhibitor", "5 mg/g Max"],
      ["Aflatoxin", "20 ppb Max"], ["Bulk Density", "600 kg/m3 Min"],
    ],
    spec: "ORIGIN: Brazil / Argentina / USA / India. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk vessel loading. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO/GMO declaration, Certificate of Origin, FOSFA/GAFTA terms, SGS inspection. QUALITY: Feed-grade, solvent-extracted. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-FED-02-001", name: "Corn Gluten Meal 60%", category: "agriculture",
    hs: "2303100000", price: 440, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["corn-gluten-meal", "feed", "high-protein", "energy"],
    coa: [
      ["Protein (dry basis)", "60.0% Min"], ["Moisture", "10.0% Max"],
      ["Fat", "1.5% Min"], ["Fiber", "3.0% Max"],
      ["Ash", "3.0% Max"], ["Xanthophylls", "200 ppm Min"],
      ["Aflatoxin", "20 ppb Max"], ["Color", "Yellow/golden"],
    ],
    spec: "ORIGIN: China / USA / Brazil. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO/GMO declaration, Certificate of Origin, SGS inspection. QUALITY: Feed-grade, wet-milling byproduct. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-FED-03-001", name: "DDGS", category: "agriculture",
    hs: "2303300000", price: 275, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["ddgs", "distillers-grains", "feed", "ethanol-byproduct"],
    coa: [
      ["Protein (dry basis)", "27.0% Min"], ["Moisture", "12.0% Max"],
      ["Fat", "8.0% Min"], ["Fiber", "9.0% Max"],
      ["Ash", "5.0% Max"], ["Sulfur", "0.5% Max"],
      ["Aflatoxin", "20 ppb Max"], ["Color", "Golden"],
      ["Bulk Density", "450-550 kg/m3"],
    ],
    spec: "ORIGIN: USA / China / Brazil. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk vessel loading. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO/GMO declaration, Certificate of Origin, SGS inspection. QUALITY: Feed-grade, dried distillers grains with solubles. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-FED-04-001", name: "Alfalfa Hay Cubed", category: "agriculture",
    hs: "1214100000", price: 265, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["alfalfa", "hay", "cubes", "forage"],
    coa: [
      ["Protein (dry basis)", "17.0% Min"], ["Moisture", "12.0% Max"],
      ["Fiber (ADF)", "30.0% Max"], ["Fiber (NDF)", "40.0% Max"],
      ["TDN", "55% Min"], ["RFV (Relative Feed Value)", "125 Min"],
      ["Ash", "12.0% Max"], ["Cube Size", "3.2 cm"],
    ],
    spec: "ORIGIN: USA / Canada / Spain. PACKAGING: 50kg PP bags; 1MT FIBCs; bulk in containers; compressed bales available. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, SGS inspection. QUALITY: Feed-grade forage. HANDLING: Store dry, ventilated; protect from moisture. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-FED-05-001", name: "Wheat Bran", category: "agriculture",
    hs: "2302300000", price: 190, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "9 months under proper storage",
    tags: ["wheat-bran", "feed", "fiber", "milling-byproduct"],
    coa: [
      ["Protein (dry basis)", "14.0% Min"], ["Moisture", "13.0% Max"],
      ["Fiber", "9.0% Max"], ["Ash", "6.0% Max"],
      ["Fat", "4.0% Min"], ["Starch", "20.0% Max"],
      ["Aflatoxin", "20 ppb Max"], ["Bulk Density", "300 kg/m3 Min"],
    ],
    spec: "ORIGIN: Russia / Ukraine / India / Turkey. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, SGS inspection. QUALITY: Feed-grade milling byproduct. HANDLING: Store cool, dry, ventilated. Shelf life 9 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-FED-06-001", name: "Rice Bran", category: "agriculture",
    hs: "2302200000", price: 180, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "6 months under proper storage",
    tags: ["rice-bran", "feed", "fiber", "milling-byproduct"],
    coa: [
      ["Protein (dry basis)", "12.0% Min"], ["Moisture", "12.0% Max"],
      ["Oil Content", "12.0% Min"], ["Fiber", "12.0% Max"],
      ["Ash", "10.0% Max"], ["FFA (as oleic)", "10.0% Max"],
      ["Aflatoxin", "20 ppb Max"], ["Bulk Density", "350 kg/m3 Min"],
    ],
    spec: "ORIGIN: India / Thailand / Vietnam. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, SGS inspection. QUALITY: Feed-grade, raw stabilized bran. HANDLING: Store cool, dry, ventilated; FFA increases rapidly. Shelf life 6 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-FED-07-001", name: "Cottonseed Meal 41%", category: "agriculture",
    hs: "2306100000", price: 320, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["cottonseed-meal", "feed", "protein", "byproduct"],
    coa: [
      ["Protein (dry basis)", "41.0% Min"], ["Moisture", "12.0% Max"],
      ["Fat", "1.5% Min"], ["Fiber", "14.0% Max"],
      ["Ash", "7.0% Max"], ["Free Gossypol", "0.12% Max"],
      ["Aflatoxin", "20 ppb Max"], ["Bulk Density", "550 kg/m3 Min"],
    ],
    spec: "ORIGIN: India / China / USA / Brazil. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, FOSFA terms, SGS inspection. QUALITY: Feed-grade, solvent-extracted. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-FED-08-001", name: "Sunflower Meal 32%", category: "agriculture",
    hs: "2306300000", price: 215, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["sunflower-meal", "feed", "protein", "byproduct"],
    coa: [
      ["Protein (dry basis)", "32.0% Min"], ["Moisture", "11.0% Max"],
      ["Fat", "2.0% Min"], ["Fiber", "22.0% Max"],
      ["Ash", "7.0% Max"], ["Aflatoxin", "20 ppb Max"],
      ["Bulk Density", "500 kg/m3 Min"], ["Color", "Grey-brown"],
    ],
    spec: "ORIGIN: Ukraine / Russia / Argentina. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, FOSFA terms, SGS inspection. QUALITY: Feed-grade, solvent-extracted. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-FED-09-001", name: "Rapeseed Meal", category: "agriculture",
    hs: "2306400000", price: 245, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["rapeseed-meal", "canola-meal", "feed", "protein"],
    coa: [
      ["Protein (dry basis)", "35.0% Min"], ["Moisture", "12.0% Max"],
      ["Fat", "2.0% Min"], ["Fiber", "12.0% Max"],
      ["Ash", "7.5% Max"], ["Glucosinolates", "30 µmol/g Max"],
      ["Aflatoxin", "20 ppb Max"], ["Bulk Density", "550 kg/m3 Min"],
    ],
    spec: "ORIGIN: Germany / Canada / France. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, FOSFA terms, SGS inspection. QUALITY: Feed-grade, solvent-extracted. HANDLING: Store cool, dry, ventilated. Shelf life 12 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-FED-10-001", name: "Fish Meal 65%", category: "agriculture",
    hs: "2301200000", price: 1500, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "12 months under proper storage",
    tags: ["fish-meal", "feed", "high-protein", "aquaculture"],
    coa: [
      ["Protein (dry basis)", "65.0% Min"], ["Moisture", "10.0% Max"],
      ["Fat", "10.0% Max"], ["Ash", "16.0% Max"],
      ["Salt & Sand", "5.0% Max"], ["Histamine", "500 ppm Max"],
      ["Aflatoxin", "10 ppb Max"], ["TVN (Total Volatile Nitrogen)", "100 mg/100g Max"],
      ["Antioxidant (Ethoxyquin/BHT)", "200 ppm"],
    ],
    spec: "ORIGIN: Peru / Chile / Vietnam. PACKAGING: 50kg PP bags with inner liner, antioxidant-treated; 1MT FIBCs; bulk in containers. CERTIFICATIONS: Phytosanitary, Health Certificate, Certificate of Origin, SGS, IFFO RS. QUALITY: Aquaculture-grade, steam-dried. HANDLING: Store cool, dry, ventilated; stabilize with antioxidant. Shelf life 12 months. Fumigation per ISPM-15.",
  }),

  // ============ CRP — OTHER CROPS (10) ============
  p({
    sku: "AGR-CRP-01-001", name: "Cotton Lint", category: "agriculture",
    hs: "5201000000", price: 1650, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["cotton", "lint", "raw", "textile"],
    coa: [
      ["Grade", "Middling (31-3-36)"], ["Staple Length", "1.1/8 in Min"],
      ["Micronaire", "3.5-4.9"], ["Strength (g/tex)", "26 Min"],
      ["Uniformity Index", "82% Min"], ["Color", "White"],
      ["Trash Content", "2.0% Max"], ["Moisture", "7.0% Max"],
      ["Elongation", "6.5% Min"], ["Short Fiber Index", "10% Max"],
    ],
    spec: "ORIGIN: USA / India / Brazil / Uzbekistan. PACKAGING: Universal 500lb (227kg) bales, poly-wrapped; compressed bales 180 kg/m3. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, SGS inspection, HVI test report. QUALITY: USDA classing, ICA Bremen rules. HANDLING: Store dry, ventilated; protect from moisture, contamination. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-CRP-02-001", name: "Raw Sugar ICUMSA 45", category: "agriculture",
    hs: "1701140000", price: 520, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["sugar", "raw", "icumsa-45", "refining"],
    coa: [
      ["ICUMSA (color)", "45 IU Max"], ["Polarization", "99.5° Min"],
      ["Moisture", "0.10% Max"], ["Ash", "0.04% Max"],
      ["Sulfated Ash", "0.04% Max"], ["Reducing Sugars", "0.05% Max"],
      ["Solubility", "100%"], ["Granulation (fine)", "100% through 0.8 mm"],
      ["Arsenic", "1 ppm Max"], ["Lead", "1 ppm Max"],
    ],
    spec: "ORIGIN: Brazil / India / Thailand. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk vessel loading. CERTIFICATIONS: Phytosanitary Certificate, Health Certificate, Certificate of Origin, SGS inspection. QUALITY: VHP raw sugar refining standard. HANDLING: Store cool, dry, ventilated; protect from moisture and contamination. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-CRP-03-001", name: "Raw Sugar ICUMSA 600", category: "agriculture",
    hs: "1701140000", price: 460, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["sugar", "raw", "icumsa-600", "vhp"],
    coa: [
      ["ICUMSA (color)", "600 IU Max"], ["Polarization", "99.0° Min"],
      ["Moisture", "0.15% Max"], ["Ash", "0.20% Max"],
      ["Reducing Sugars", "0.10% Max"], ["Color", "Brown"],
      ["Granulation", "Free-flowing crystals"], ["Foreign Matter", "0.1% Max"],
    ],
    spec: "ORIGIN: Brazil / India / Thailand / Cuba. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk vessel loading. CERTIFICATIONS: Phytosanitary Certificate, Health Certificate, Certificate of Origin, SGS inspection. QUALITY: VHP raw sugar for refining. HANDLING: Store cool, dry, ventilated; protect from moisture. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-CRP-04-001", name: "Raw Sugar ICUMSA 1200", category: "agriculture",
    hs: "1701140000", price: 440, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["sugar", "raw", "icumssa-1200", "vhp"],
    coa: [
      ["ICUMSA (color)", "1200 IU Max"], ["Polarization", "97.5° Min"],
      ["Moisture", "0.20% Max"], ["Ash", "0.30% Max"],
      ["Reducing Sugars", "0.15% Max"], ["Color", "Dark brown"],
      ["Granulation", "Free-flowing crystals"], ["Foreign Matter", "0.1% Max"],
    ],
    spec: "ORIGIN: Brazil / India / Thailand. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk vessel loading. CERTIFICATIONS: Phytosanitary Certificate, Health Certificate, Certificate of Origin, SGS inspection. QUALITY: VHP raw sugar for refining. HANDLING: Store cool, dry, ventilated; protect from moisture. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-CRP-05-001", name: "Refined Sugar ICUMSA 45", category: "agriculture",
    hs: "1701991000", price: 540, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["sugar", "refined", "icumsa-45", "food-grade"],
    coa: [
      ["ICUMSA (color)", "45 IU Max"], ["Polarization", "99.80° Min"],
      ["Moisture", "0.04% Max"], ["Ash", "0.04% Max"],
      ["Sulfited Ash", "0.04% Max"], ["Reducing Sugars", "0.04% Max"],
      ["Sulfur Dioxide (SO2)", "15 ppm Max"], ["Solubility", "100%"],
      ["Arsenic", "1 ppm Max"], ["Lead", "1 ppm Max"], ["Granulation", "Fine"],
    ],
    spec: "ORIGIN: Brazil / India / UAE-processed. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; 1kg/2kg/5kg retail packs; bulk vessel loading. CERTIFICATIONS: Phytosanitary, Health, Kosher, Halal, ISO 22000, FSSC 22000, Certificate of Origin, SGS. QUALITY: Food-grade EC2 refined. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-CRP-06-001", name: "Cocoa Beans Grade 1", category: "agriculture",
    hs: "1801000000", price: 8200, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["cocoa", "beans", "grade-1", "chocolate"],
    coa: [
      ["Grade", "Grade 1 (main crop)"], ["Bean Count", "100 g/100 beans Max"],
      ["Moisture", "7.5% Max"], ["Foreign Matter", "1.0% Max"],
      ["Slatty Beans", "5.0% Max"], ["Moldy Beans", "4.0% Max"],
      ["Insect Damaged", "4.0% Max"], ["Defects", "5% Max"],
      ["Cut Test", "Cocoa solids 50% Min"], ["Fermentation", "Properly fermented"],
    ],
    spec: "ORIGIN: Ivory Coast / Ghana / Cameroon. PACKAGING: 60-65kg natural jute bags; 1MT FIBCs available. CERTIFICATIONS: Phytosanitary, Fairtrade/RA (optional), Certificate of Origin, SGS, FCC. QUALITY: ISO 2451 cocoa bean standard. HANDLING: Store cool, dry, ventilated; protect from moisture, off-odors, pests. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-CRP-07-001", name: "Tobacco FC Virginia", category: "agriculture",
    hs: "2401201000", price: 4900, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["tobacco", "virginia", "flue-cured", "fc"],
    coa: [
      ["Grade", "FC Virginia - B3F / B2F"], ["Moisture", "12.0% Max"],
      ["Nicotine", "2.5-3.5%"], ["Reducing Sugars", "18-22%"],
      ["Chloride", "0.6% Max"], ["Filling Value", "3.5 cm3/g Min"],
      ["Stem Content", "5.0% Max"], ["Color", "Lemon-orange"],
      ["Length", "40-60 cm"], ["Aroma", "Characteristic"],
    ],
    spec: "ORIGIN: Brazil / India / Zimbabwe / USA. PACKAGING: 200kg C-48 cardboard cartons, lined; 100kg farm bales. CERTIFICATIONS: Phytosanitary Certificate, Certificate of Origin, CORESTA rules, SGS inspection. QUALITY: ISO 4874 sampling. HANDLING: Store cool (18-22°C), humidity 60-65%; protect from moisture and pests. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-CRP-08-001", name: "Natural Rubber TSR20", category: "agriculture",
    hs: "4001220000", price: 1550, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["rubber", "tsr20", "natural", "industrial"],
    coa: [
      ["Grade", "TSR 20 (SMR 20 equivalent)"], ["Dirt Content", "0.20% Max"],
      ["Ash Content", "0.60% Max"], ["Volatile Matter", "0.80% Max"],
      ["Nitrogen Content", "0.60% Max"], ["Initial Plasticity (P0)", "30 Min"],
      ["Plasticity Retention Index (PRI)", "40 Min"],
      ["Moisture", "0.50% Max"], ["Color", "Brown block"],
    ],
    spec: "ORIGIN: Thailand / Indonesia / Vietnam / Malaysia. PACKAGING: 33.3 kg or 35 kg bales in wooden pallets (1MT/pallet); shrink-wrapped. CERTIFICATIONS: ISO 9000, Certificate of Origin, SGS inspection, GREENBOOK compliance. QUALITY: ISO 2000 spec for TSR20. HANDLING: Store cool (<30°C), dry, ventilated, away from sunlight; protect from contamination. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-CRP-09-001", name: "Natural Rubber RSS3", category: "agriculture",
    hs: "4001210000", price: 1650, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["rubber", "rss3", "ribbed-smoke-sheet", "natural"],
    coa: [
      ["Grade", "RSS 3 (Ribbed Smoked Sheet)"], ["Dirt Content", "0.05% Max"],
      ["Ash Content", "0.50% Max"], ["Volatile Matter", "0.80% Max"],
      ["Nitrogen Content", "0.60% Max"], ["Initial Plasticity (P0)", "30 Min"],
      ["Plasticity Retention Index (PRI)", "60 Min"],
      ["Color", "Light brown, uniform"], ["Visual Grade", "RSS 3 per GREENBOOK"],
    ],
    spec: "ORIGIN: Thailand / Indonesia / Sri Lanka. PACKAGING: 111.11 kg bales (9 bales/MT) in wooden pallets; shrink-wrapped. CERTIFICATIONS: GREENBOOK compliance, ISO 1400 sampling, Certificate of Origin, SGS inspection. QUALITY: ISO 2000 RSS standard. HANDLING: Store cool (<30°C), dry, ventilated, away from sunlight; protect from contamination. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
  p({
    sku: "AGR-CRP-10-001", name: "Guar Seeds", category: "agriculture",
    hs: "1207290000", price: 780, cap20: BAG50.cap20, cap40: BAG50.cap40,
    shelfLife: "24 months under proper storage",
    tags: ["guar", "seeds", "industrial", "gum"],
    coa: [
      ["Purity", "99.0% Min"], ["Moisture", "10.0% Max"],
      ["Endosperm (Gum)", "32% Min"], ["Foreign Matter", "1.0% Max"],
      ["Broken", "2.0% Max"], ["Color", "Off-white to dull white"],
      ["Aflatoxin", "10 ppb Max"], ["Germ", "43% Min"],
    ],
    spec: "ORIGIN: India (Rajasthan) / Pakistan. PACKAGING: 50kg PP bags with inner liner; 1MT FIBCs; bulk in containers. CERTIFICATIONS: Phytosanitary Certificate, Non-GMO declaration, Certificate of Origin, SGS inspection. QUALITY: IGC/GAFTA trading rules; suitable for guar gum splitting. HANDLING: Store cool, dry, ventilated. Shelf life 24 months. Fumigation per ISPM-15.",
  }),
];
